package uk.gov.hmcts.reform.fpl.ccd.event.page;

import uk.gov.hmcts.ccd.sdk.api.Event;
import uk.gov.hmcts.ccd.sdk.api.FieldCollection;
import uk.gov.hmcts.reform.fpl.enums.State;
import uk.gov.hmcts.reform.fpl.model.CaseData;
import uk.gov.hmcts.reform.fpl.model.UserRole;
import uk.gov.hmcts.reform.fpl.model.event.GatekeepingOrderEventData;

/**
 * Generated by ccd-definition-converter from CARE_SUPERVISION_EPO on migration; owned by this service team.
 *
 * <p>Wizard page {@code SelectStandardDirections} of event {@code addGatekeepingOrder}.
 */
public final class AddGatekeepingOrderSelectStandardDirectionsPage {
    private AddGatekeepingOrderSelectStandardDirectionsPage() {
    }

    /**
     * Applies this page's fields to the event.
     *
     * @param fields the event's field-collection builder
     */
    public static void apply(
            FieldCollection.FieldCollectionBuilder<CaseData, State, Event.EventBuilder<CaseData, UserRole, State>> fields) {
        fields.page("SelectStandardDirections");
        fields.showCondition("gatekeepingOrderRouter=\"SERVICE\" OR useServiceRoute=\"YES\"");
        fields.readonly(CaseData::getSelectDirectionsLabel);
        fields.readonly(CaseData::getDirectionsForAllPartiesLabelSmall);
        fields.complex(CaseData::getGatekeepingOrderEventData)
                    .optional(GatekeepingOrderEventData::getDirectionsForAllParties).done();
        fields.readonly(CaseData::getDirectionsForLocalAuthorityLabelSmall);
        fields.complex(CaseData::getGatekeepingOrderEventData)
                    .optional(GatekeepingOrderEventData::getDirectionsForLocalAuthority).done();
        fields.readonly(CaseData::getDirectionsForRespondentsLabelSmall);
        fields.complex(CaseData::getGatekeepingOrderEventData)
                    .optional(GatekeepingOrderEventData::getDirectionsForRespondents).done();
        fields.readonly(CaseData::getDirectionsForCafcassLabelSmall);
        fields.complex(CaseData::getGatekeepingOrderEventData)
                    .optional(GatekeepingOrderEventData::getDirectionsForCafcassUpdated).done();
        fields.readonly(CaseData::getDirectionsForOthersLabelSmall);
        fields.complex(CaseData::getGatekeepingOrderEventData)
                    .optional(GatekeepingOrderEventData::getDirectionsForOthers).done();
        fields.readonly(CaseData::getDirectionsForCourtLabelSmall);
        fields.complex(CaseData::getGatekeepingOrderEventData)
                    .optional(GatekeepingOrderEventData::getDirectionsForCourtUpdated).done();
    }
}
