package uk.gov.hmcts.reform.fpl.ccd.event.page;

import uk.gov.hmcts.ccd.sdk.api.Event;
import uk.gov.hmcts.ccd.sdk.api.FieldCollection;
import uk.gov.hmcts.reform.fpl.enums.State;
import uk.gov.hmcts.reform.fpl.model.CaseData;
import uk.gov.hmcts.reform.fpl.model.EditableStandardDirection;
import uk.gov.hmcts.reform.fpl.model.ImmediateStandardDirection;
import uk.gov.hmcts.reform.fpl.model.UserRole;

/**
 * Generated by ccd-definition-converter from CARE_SUPERVISION_EPO on migration; owned by this service team.
 *
 * <p>Wizard page {@code ConfirmStandardDirections} of event {@code addUrgentDirections}.
 */
public final class AddUrgentDirectionsConfirmStandardDirectionsPage {
    private AddUrgentDirectionsConfirmStandardDirectionsPage() {
    }

    /**
     * Applies this page's fields to the event.
     *
     * @param fields the event's field-collection builder
     */
    public static void apply(
            FieldCollection.FieldCollectionBuilder<CaseData, State, Event.EventBuilder<CaseData, UserRole, State>> fields) {
        fields.page("ConfirmStandardDirections");
        fields.showCondition("urgentDirectionsRouter=\"SERVICE\" OR useServiceRoute=\"YES\"");
        fields.readonly(CaseData::getGatekeepingOrderHasHearing1)
                    .fieldShowCondition("directionsForAllPartiesLabel=\"DO_NOT_SHOW\"");
        fields.readonly(CaseData::getEditDirectionsLabel);
        fields.readonly(CaseData::getDirectionsForAllPartiesLabel)
                    .fieldShowCondition("urgentDirectionsForAllParties !=\"\"");
        fields.complex(CaseData::getDirection_ATTEND_HEARING)
                    .readonly(EditableStandardDirection::getTitle)
                    .noHintText()
                    .optional(EditableStandardDirection::getDescription)
                    .readonly(EditableStandardDirection::getAssignee)
                    .noHintText()
                    .mandatory(EditableStandardDirection::getDueDateType)
                    .mandatory(EditableStandardDirection::getDateToBeCompletedBy)
                    .fieldShowCondition("direction-ATTEND_HEARING.dueDateType=\"DATE\"")
                    .noHintText()
                    .mandatory(EditableStandardDirection::getDaysBeforeHearing)
                    .fieldShowCondition("direction-ATTEND_HEARING.dueDateType=\"DAYS\"").done()
                    .fieldShowCondition("urgentDirectionsForAllParties CONTAINS \"ATTEND_HEARING\"");
        fields.readonly(CaseData::getDirectionsForLocalAuthorityLabel)
                    .fieldShowCondition("urgentDirectionsForLocalAuthority !=\"\"");
        fields.mandatory(CaseData::getDirection_LODGE_BUNDLE)
                    .fieldShowCondition("urgentDirectionsForLocalAuthority CONTAINS \"LODGE_BUNDLE\"");
        fields.mandatory(CaseData::getDirection_REDUCE_TIME_FOR_SERVICE)
                    .fieldShowCondition("urgentDirectionsForLocalAuthority CONTAINS \"REDUCE_TIME_FOR_SERVICE\"");
        fields.readonly(CaseData::getDirectionsForCafcassLabel)
                    .fieldShowCondition("urgentDirectionsForCafcass !=\"\"");
        fields.complex(CaseData::getDirection_APPOINT_CHILDREN_GUARDIAN_IMMEDIATE)
                    .readonly(ImmediateStandardDirection::getTitle)
                    .noHintText()
                    .optional(ImmediateStandardDirection::getDescription)
                    .readonly(ImmediateStandardDirection::getAssignee)
                    .noHintText().done()
                    .fieldShowCondition("urgentDirectionsForCafcass CONTAINS \"APPOINT_CHILDREN_GUARDIAN\"");
        fields.complex(CaseData::getDirection_APPOINT_CHILDREN_GUARDIAN)
                    .readonly(EditableStandardDirection::getTitle)
                    .noHintText()
                    .optional(EditableStandardDirection::getDescription)
                    .readonly(EditableStandardDirection::getAssignee)
                    .noHintText()
                    .mandatory(EditableStandardDirection::getDueDateType)
                    .mandatory(EditableStandardDirection::getDateToBeCompletedBy)
                    .fieldShowCondition("direction-APPOINT_CHILDREN_GUARDIAN.dueDateType=\"DATE\"")
                    .noHintText()
                    .mandatory(EditableStandardDirection::getDaysBeforeHearing)
                    .fieldShowCondition("direction-APPOINT_CHILDREN_GUARDIAN.dueDateType=\"DAYS\"").done()
                    .fieldShowCondition("directionsForCafcassLabel=\"DO_NOT_SHOW\"");
        fields.readonly(CaseData::getDirectionsForCourtLabel)
                    .fieldShowCondition("directionsForCourtUpdated CONTAINS \"ARRANGE_INTERPRETERS\"");
        fields.complex(CaseData::getDirection_ARRANGE_INTERPRETERS)
                    .readonly(EditableStandardDirection::getTitle)
                    .noHintText()
                    .optional(EditableStandardDirection::getDescription)
                    .readonly(EditableStandardDirection::getAssignee)
                    .noHintText()
                    .mandatory(EditableStandardDirection::getDueDateType)
                    .mandatory(EditableStandardDirection::getDateToBeCompletedBy)
                    .fieldShowCondition("direction-ARRANGE_INTERPRETERS.dueDateType=\"DATE\"")
                    .noHintText()
                    .mandatory(EditableStandardDirection::getDaysBeforeHearing)
                    .fieldShowCondition("direction-ARRANGE_INTERPRETERS.dueDateType=\"DAYS\"").done()
                    .fieldShowCondition("directionsForCourtLabel=\"DO_NOT_SHOW\"");
        fields.complex(CaseData::getDirection_ARRANGE_INTERPRETERS_IMMEDIATE)
                    .readonly(ImmediateStandardDirection::getTitle)
                    .noHintText()
                    .optional(ImmediateStandardDirection::getDescription)
                    .readonly(ImmediateStandardDirection::getAssignee)
                    .noHintText().done()
                    .fieldShowCondition("directionsForCourtUpdated CONTAINS \"ARRANGE_INTERPRETERS\"");
    }
}
