package uk.gov.hmcts.reform.fpl.ccd.event.page;

import uk.gov.hmcts.ccd.sdk.api.Event;
import uk.gov.hmcts.ccd.sdk.api.FieldCollection;
import uk.gov.hmcts.reform.fpl.enums.State;
import uk.gov.hmcts.reform.fpl.model.CaseData;
import uk.gov.hmcts.reform.fpl.model.UserRole;

/**
 * Generated by ccd-definition-converter from CARE_SUPERVISION_EPO on migration; owned by this service team.
 *
 * <p>Wizard page {@code additionRepresentation} of event {@code amendChildren}.
 */
public final class AmendChildrenAdditionRepresentationPage {
    private AmendChildrenAdditionRepresentationPage() {
    }

    /**
     * Applies this page's fields to the event.
     *
     * @param fields the event's field-collection builder
     */
    public static void apply(
            FieldCollection.FieldCollectionBuilder<CaseData, State, Event.EventBuilder<CaseData, UserRole, State>> fields) {
        fields.page("additionRepresentation");
        fields.showCondition("childrenHaveRepresentation = \"Yes\" AND optionCount!=\"0\"");
        AmendChildrenAdditionRepresentationPageFields1.apply(fields);
        AmendChildrenAdditionRepresentationPageFields2.apply(fields);
        AmendChildrenAdditionRepresentationPageFields3.apply(fields);
        AmendChildrenAdditionRepresentationPageFields4.apply(fields);
    }
}
