package uk.gov.hmcts.reform.fpl.ccd.event.page;

import uk.gov.hmcts.ccd.sdk.api.Event;
import uk.gov.hmcts.ccd.sdk.api.FieldCollection;
import uk.gov.hmcts.reform.fpl.model.Address;
import uk.gov.hmcts.reform.fpl.enums.State;
import uk.gov.hmcts.reform.fpl.model.CaseData;
import uk.gov.hmcts.reform.fpl.model.ChildParty;
import uk.gov.hmcts.reform.fpl.model.ChildrenNew;
import uk.gov.hmcts.reform.fpl.model.common.Telephone;
import uk.gov.hmcts.reform.fpl.model.UserRole;

/**
 * Generated by ccd-definition-converter from CARE_SUPERVISION_EPO on migration; owned by this service team.
 *
 * <p>Wizard page {@code childrenDetails} of event {@code amendChildren}.
 */
public final class AmendChildrenChildrenDetailsPage {
    private AmendChildrenChildrenDetailsPage() {
    }

    /**
     * Applies this page's fields to the event.
     *
     * @param fields the event's field-collection builder
     */
    public static void apply(
            FieldCollection.FieldCollectionBuilder<CaseData, State, Event.EventBuilder<CaseData, UserRole, State>> fields) {
        fields.page("childrenDetails");
        fields.complex(CaseData::getChildren1).done();
        fields.complex(CaseData::getChildren1, ChildrenNew.class)
                    .complex(ChildrenNew::getParty)
                    .mandatory(ChildParty::getFirstName)
                    .noHintText().done()
                    .complex(ChildrenNew::getParty)
                    .mandatory(ChildParty::getLastName)
                    .noHintText().done()
                    .complex(ChildrenNew::getParty)
                    .mandatory(ChildParty::getDateOfBirth)
                    .noHintText().done()
                    .complex(ChildrenNew::getParty)
                    .mandatory(ChildParty::getGender).done()
                    .complex(ChildrenNew::getParty)
                    .optional(ChildParty::getGenderIdentification).done()
                    .complex(ChildrenNew::getParty)
                    .mandatory(ChildParty::getLivingSituation).done()
                    .complex(ChildrenNew::getParty)
                    .optional(ChildParty::getAddressAutoConfidentialLabel).done()
                    .complex(ChildrenNew::getParty)
                    .optional(ChildParty::getAddress).done()
                    .complex(ChildrenNew::getParty)
                    .complex(ChildParty::getAddress)
                    .optional(Address::getAddressLine1).done().done()
                    .complex(ChildrenNew::getParty)
                    .complex(ChildParty::getAddress)
                    .optional(Address::getAddressLine2).done().done()
                    .complex(ChildrenNew::getParty)
                    .complex(ChildParty::getAddress)
                    .optional(Address::getAddressLine3).done().done()
                    .complex(ChildrenNew::getParty)
                    .complex(ChildParty::getAddress)
                    .optional(Address::getPostTown).done().done()
                    .complex(ChildrenNew::getParty)
                    .complex(ChildParty::getAddress)
                    .optional(Address::getCounty).done().done()
                    .complex(ChildrenNew::getParty)
                    .complex(ChildParty::getAddress)
                    .optional(Address::getPostcode).done().done()
                    .complex(ChildrenNew::getParty)
                    .complex(ChildParty::getAddress)
                    .optional(Address::getCountry).done().done()
                    .complex(ChildrenNew::getParty)
                    .optional(ChildParty::getIsAddressConfidential).done()
                    .complex(ChildrenNew::getParty)
                    .optional(ChildParty::getLivingSituationDetails).done()
                    .complex(ChildrenNew::getParty)
                    .mandatory(ChildParty::getLivingWithDetails)
                    .noHintText().done()
                    .complex(ChildrenNew::getParty)
                    .optional(ChildParty::getAddressChangeDate)
                    .eventLabel(" ")
                    .noHintText().done()
                    .complex(ChildrenNew::getParty)
                    .optional(ChildParty::getDatePowersEnd)
                    .noHintText().done()
                    .complex(ChildrenNew::getParty)
                    .optional(ChildParty::getCareStartDate)
                    .noHintText().done()
                    .complex(ChildrenNew::getParty)
                    .optional(ChildParty::getDischargeDate)
                    .noHintText().done()
                    .complex(ChildrenNew::getParty)
                    .optional(ChildParty::getDetailsHidden)
                    .fieldShowCondition("party=\"DO_NOT_SHOW\"").done()
                    .complex(ChildrenNew::getParty)
                    .optional(ChildParty::getDetailsHiddenReason)
                    .fieldShowCondition("party=\"DO_NOT_SHOW\"").done()
                    .complex(ChildrenNew::getParty)
                    .optional(ChildParty::getCareAndContactPlan)
                    .noHintText().done()
                    .complex(ChildrenNew::getParty)
                    .optional(ChildParty::getKeyDates)
                    .noHintText().done()
                    .complex(ChildrenNew::getParty)
                    .optional(ChildParty::getAdditionalNeeds)
                    .noHintText().done()
                    .complex(ChildrenNew::getParty)
                    .optional(ChildParty::getAdditionalNeedsDetails).done()
                    .complex(ChildrenNew::getParty)
                    .optional(ChildParty::getMothersName).done()
                    .complex(ChildrenNew::getParty)
                    .optional(ChildParty::getFathersName).done()
                    .complex(ChildrenNew::getParty)
                    .optional(ChildParty::getAdoption).done()
                    .complex(ChildrenNew::getParty)
                    .optional(ChildParty::getPlacementOrderApplication).done()
                    .complex(ChildrenNew::getParty)
                    .optional(ChildParty::getPlacementCourt)
                    .eventLabel(" ").done()
                    .complex(ChildrenNew::getParty)
                    .optional(ChildParty::getSocialWorkerName).done()
                    .complex(ChildrenNew::getParty)
                    .optional(ChildParty::getSocialWorkerTelephoneNumber).done()
                    .complex(ChildrenNew::getParty)
                    .complex(ChildParty::getSocialWorkerTelephoneNumber)
                    .optional(Telephone::getTelephoneNumber)
                    .eventLabel("Social worker's phone number")
                    .noHintText().done().done()
                    .complex(ChildrenNew::getParty)
                    .complex(ChildParty::getSocialWorkerTelephoneNumber)
                    .optional(Telephone::getContactDirection)
                    .fieldShowCondition("party=\"DO_NOT_SHOW\"").done().done()
                    .complex(ChildrenNew::getParty)
                    .optional(ChildParty::getSocialWorkerEmail).done()
                    .complex(ChildrenNew::getParty)
                    .optional(ChildParty::getSocialWorkerDetailsHidden).done()
                    .complex(ChildrenNew::getParty)
                    .optional(ChildParty::getSocialWorkerDetailsHiddenReason).done()
                    .readonly(ChildrenNew::getRepresentative)
                    .fieldShowCondition("party=\"DO_NOT_SHOW\"")
                    .readonly(ChildrenNew::getSolicitor)
                    .fieldShowCondition("party=\"DO_NOT_SHOW\"")
                    .readonly(ChildrenNew::getLegalCounsellors)
                    .fieldShowCondition("party=\"DO_NOT_SHOW\"").done();
    }
}
