package uk.gov.hmcts.reform.fpl.ccd.event.page;

import uk.gov.hmcts.ccd.sdk.api.Event;
import uk.gov.hmcts.ccd.sdk.api.FieldCollection;
import uk.gov.hmcts.reform.fpl.enums.State;
import uk.gov.hmcts.reform.fpl.model.CaseData;
import uk.gov.hmcts.reform.fpl.model.UserRole;
import uk.gov.hmcts.reform.fpl.model.event.ChildrenEventData;

/**
 * Generated by ccd-definition-converter from CARE_SUPERVISION_EPO on migration; owned by this service team.
 *
 * <p>Field placements for page {@code additionRepresentation} of event {@code amendChildren} (part 4 of 4).
 */
public final class AmendChildrenAdditionRepresentationPageFields4 {
    private AmendChildrenAdditionRepresentationPageFields4() {
    }

    /**
     * @param fields the event's field-collection builder
     */
    public static void apply(
            FieldCollection.FieldCollectionBuilder<CaseData, State, Event.EventBuilder<CaseData, UserRole, State>> fields) {
        fields.complex(CaseData::getChildrenEventData)
                    .optional(ChildrenEventData::getChildRepresentationDetails12)
                    .fieldShowCondition("childrenHaveSameRepresentation = \"No\" AND optionCount=\"0123456789101112*\"")
                    .optional(ChildrenEventData::getChildRepresentationDetails13)
                    .fieldShowCondition("childrenHaveSameRepresentation = \"No\" AND optionCount=\"012345678910111213*\"")
                    .optional(ChildrenEventData::getChildRepresentationDetails14)
                    .fieldShowCondition("childrenHaveSameRepresentation = \"No\" AND optionCount=\"01234567891011121314*\"").done();
    }
}
