package uk.gov.hmcts.reform.fpl.ccd.event.page;

import uk.gov.hmcts.ccd.sdk.api.Event;
import uk.gov.hmcts.ccd.sdk.api.FieldCollection;
import uk.gov.hmcts.reform.fpl.enums.State;
import uk.gov.hmcts.reform.fpl.model.CaseData;
import uk.gov.hmcts.reform.fpl.model.UserRole;
import uk.gov.hmcts.reform.fpl.model.event.ChildrenEventData;

/**
 * Generated by ccd-definition-converter from CARE_SUPERVISION_EPO on migration; owned by this service team.
 *
 * <p>Field placements for page {@code additionRepresentation} of event {@code amendChildren} (part 1 of 4).
 */
public final class AmendChildrenAdditionRepresentationPageFields1 {
    private AmendChildrenAdditionRepresentationPageFields1() {
    }

    /**
     * @param fields the event's field-collection builder
     */
    public static void apply(
            FieldCollection.FieldCollectionBuilder<CaseData, State, Event.EventBuilder<CaseData, UserRole, State>> fields) {
        fields.readonly(CaseData::getOptionCount)
                    .fieldShowCondition("childrenHaveRepresentation = \"DO_NOT_SHOW\"");
        fields.readonly(CaseData::getChildrenMainRepresentativeName);
        fields.complex(CaseData::getChildrenEventData)
                    .mandatory(ChildrenEventData::getChildrenHaveSameRepresentation)
                    .optional(ChildrenEventData::getChildRepresentationDetails0)
                    .fieldShowCondition("childrenHaveSameRepresentation = \"No\" AND optionCount=\"0*\"")
                    .optional(ChildrenEventData::getChildRepresentationDetails1)
                    .fieldShowCondition("childrenHaveSameRepresentation = \"No\" AND optionCount=\"01*\"")
                    .optional(ChildrenEventData::getChildRepresentationDetails2)
                    .fieldShowCondition("childrenHaveSameRepresentation = \"No\" AND optionCount=\"012*\"")
                    .optional(ChildrenEventData::getChildRepresentationDetails3)
                    .fieldShowCondition("childrenHaveSameRepresentation = \"No\" AND optionCount=\"0123*\"").done();
    }
}
