package uk.gov.hmcts.reform.fpl.ccd.event.page;

import uk.gov.hmcts.ccd.sdk.api.Event;
import uk.gov.hmcts.ccd.sdk.api.FieldCollection;
import uk.gov.hmcts.reform.fpl.enums.State;
import uk.gov.hmcts.reform.fpl.model.CaseData;
import uk.gov.hmcts.reform.fpl.model.Direction;
import uk.gov.hmcts.reform.fpl.model.UserRole;

/**
 * Generated by ccd-definition-converter from CARE_SUPERVISION_EPO on migration; owned by this service team.
 *
 * <p>Wizard page {@code localAuthorityDirections} of event {@code draftSDO}.
 */
public final class DraftSDOLocalAuthorityDirectionsPage {
    private DraftSDOLocalAuthorityDirectionsPage() {
    }

    /**
     * Applies this page's fields to the event.
     *
     * @param fields the event's field-collection builder
     */
    public static void apply(
            FieldCollection.FieldCollectionBuilder<CaseData, State, Event.EventBuilder<CaseData, UserRole, State>> fields) {
        fields.page("localAuthorityDirections");
        fields.showCondition("sdoRouter=\"SERVICE\" OR useServiceRoute=\"YES\"");
        fields.readonlyNoSummary(CaseData::getLocalAuthorityDirectionsHearingDate);
        fields.complex(CaseData::getLocalAuthorityDirections, false).done();
        fields.complex(CaseData::getLocalAuthorityDirections, Direction.class)
                    .readonly(Direction::getReadOnly)
                    .eventLabel(" ")
                    .readonly(Direction::getDirectionRemovable)
                    .eventLabel(" ")
                    .readonly(Direction::getDirectionType)
                    .eventLabel(" ")
                    .mandatory(Direction::getDirectionNeeded)
                    .fieldShowCondition("localAuthorityDirections.directionRemovable=\"Yes\"")
                    .eventLabel(" ")
                    .optional(Direction::getDirectionText)
                    .fieldShowCondition("localAuthorityDirections.readOnly!=\"Yes\" AND localAuthorityDirections.directionNeeded!=\"No\"")
                    .optional(Direction::getDateToBeCompletedBy).done();
        fields.complex(CaseData::getLocalAuthorityDirectionsCustom, false).done();
        fields.complex(CaseData::getLocalAuthorityDirectionsCustom, Direction.class)
                    .mandatory(Direction::getDirectionType)
                    .eventLabel(" ")
                    .optional(Direction::getDirectionText)
                    .optional(Direction::getDateToBeCompletedBy).done();
    }
}
