package uk.gov.hmcts.reform.fpl.ccd.event.page;

import uk.gov.hmcts.ccd.sdk.api.Event;
import uk.gov.hmcts.ccd.sdk.api.FieldCollection;
import uk.gov.hmcts.reform.fpl.enums.State;
import uk.gov.hmcts.reform.fpl.model.CaseData;
import uk.gov.hmcts.reform.fpl.model.UserRole;
import uk.gov.hmcts.reform.fpl.model.common.JudgeAndLegalAdvisor;

/**
 * Generated by ccd-definition-converter from CARE_SUPERVISION_EPO on migration; owned by this service team.
 *
 * <p>Wizard page {@code judgeAndLegalAdvisor} of event {@code draftSDO}.
 */
public final class DraftSDOJudgeAndLegalAdvisorPage {
    private DraftSDOJudgeAndLegalAdvisorPage() {
    }

    /**
     * Applies this page's fields to the event.
     *
     * @param fields the event's field-collection builder
     */
    public static void apply(
            FieldCollection.FieldCollectionBuilder<CaseData, State, Event.EventBuilder<CaseData, UserRole, State>> fields) {
        fields.page("judgeAndLegalAdvisor");
        fields.showCondition("sdoRouter!=\"URGENT\"");
        fields.complex(CaseData::getJudgeAndLegalAdvisor, false)
                    .readonly(JudgeAndLegalAdvisor::getAllocatedJudgeLabel)
                    .eventLabel(" ")
                    .mandatory(JudgeAndLegalAdvisor::getUseAllocatedJudge)
                    .eventLabel("Is this judge issuing the order?")
                    .mandatory(JudgeAndLegalAdvisor::getJudgeSubHeading)
                    .eventLabel("Who is issuing the order?")
                    .mandatory(JudgeAndLegalAdvisor::getJudgeTitle)
                    .eventLabel("Judge or Magistrate's title")
                    .mandatory(JudgeAndLegalAdvisor::getOtherTitle)
                    .eventLabel("Title")
                    .mandatory(JudgeAndLegalAdvisor::getJudgeLastName)
                    .eventLabel("Last name")
                    .mandatory(JudgeAndLegalAdvisor::getJudgeFullName)
                    .eventLabel("Full name")
                    .mandatory(JudgeAndLegalAdvisor::getJudgeEmailAddress)
                    .eventLabel("Email Address")
                    .optional(JudgeAndLegalAdvisor::getLegalAdvisorName)
                    .eventLabel("Justices' Legal Adviser's full name").done();
    }
}
