package uk.gov.hmcts.reform.fpl.ccd.event.page;

import uk.gov.hmcts.ccd.sdk.api.Event;
import uk.gov.hmcts.ccd.sdk.api.FieldCollection;
import uk.gov.hmcts.reform.fpl.enums.State;
import uk.gov.hmcts.reform.fpl.model.CaseData;
import uk.gov.hmcts.reform.fpl.model.StandardDirectionOrder;
import uk.gov.hmcts.reform.fpl.model.UserRole;

/**
 * Generated by ccd-definition-converter from CARE_SUPERVISION_EPO on migration; owned by this service team.
 *
 * <p>Wizard page {@code documentReview} of event {@code draftSDO}.
 */
public final class DraftSDODocumentReviewPage {
    private DraftSDODocumentReviewPage() {
    }

    /**
     * Applies this page's fields to the event.
     *
     * @param fields the event's field-collection builder
     */
    public static void apply(
            FieldCollection.FieldCollectionBuilder<CaseData, State, Event.EventBuilder<CaseData, UserRole, State>> fields) {
        fields.page("documentReview");
        fields.showCondition("sdoRouter!=\"URGENT\"");
        fields.complex(CaseData::getStandardDirectionOrder, false)
                    .readonly(StandardDirectionOrder::getOrderDoc)
                    .eventLabel("Check the order")
                    .mandatory(StandardDirectionOrder::getOrderStatus)
                    .fieldShowCondition("standardDirectionOrder.orderDoc!=\"SHOW ME\"").done()
                    .caseEventFieldLabel(" ");
    }
}
