package uk.gov.hmcts.reform.fpl.ccd.event.page;

import uk.gov.hmcts.ccd.sdk.api.Event;
import uk.gov.hmcts.ccd.sdk.api.FieldCollection;
import uk.gov.hmcts.reform.fpl.enums.State;
import uk.gov.hmcts.reform.fpl.model.CaseData;
import uk.gov.hmcts.reform.fpl.model.UserRole;
import uk.gov.hmcts.reform.fpl.model.event.LocalAuthorityEventData;

/**
 * Generated by ccd-definition-converter from CARE_SUPERVISION_EPO on migration; owned by this service team.
 *
 * <p>Wizard page {@code ApplicantDetails} of event {@code enterApplicantDetailsLA}.
 */
public final class EnterApplicantDetailsLAApplicantDetailsPage {
    private EnterApplicantDetailsLAApplicantDetailsPage() {
    }

    /**
     * Applies this page's fields to the event.
     *
     * @param fields the event's field-collection builder
     */
    public static void apply(
            FieldCollection.FieldCollectionBuilder<CaseData, State, Event.EventBuilder<CaseData, UserRole, State>> fields) {
        fields.page("ApplicantDetails");
        fields.complex(CaseData::getLocalAuthorityEventData)
                    .optional(LocalAuthorityEventData::getLocalAuthority).done();
        fields.readonly(CaseData::getIsCTSCUser)
                    .fieldShowCondition("localAuthority=\"DO_NOT_SHOW\"")
                    .retainHiddenValue();
    }
}
