package uk.gov.hmcts.reform.fpl.ccd.event.page;

import uk.gov.hmcts.ccd.sdk.api.Event;
import uk.gov.hmcts.ccd.sdk.api.FieldCollection;
import uk.gov.hmcts.reform.fpl.enums.State;
import uk.gov.hmcts.reform.fpl.model.CaseData;
import uk.gov.hmcts.reform.fpl.model.UserRole;
import uk.gov.hmcts.reform.fpl.model.event.LocalAuthorityEventData;

/**
 * Generated by ccd-definition-converter from CARE_SUPERVISION_EPO on migration; owned by this service team.
 *
 * <p>Wizard page {@code ApplicantContact} of event {@code enterApplicantDetailsLA}.
 */
public final class EnterApplicantDetailsLAApplicantContactPage {
    private EnterApplicantDetailsLAApplicantContactPage() {
    }

    /**
     * Applies this page's fields to the event.
     *
     * @param fields the event's field-collection builder
     */
    public static void apply(
            FieldCollection.FieldCollectionBuilder<CaseData, State, Event.EventBuilder<CaseData, UserRole, State>> fields) {
        fields.page("ApplicantContact");
        fields.readonly(CaseData::getApplicantContactLabel)
                    .caseEventFieldLabel("<h2>People within your organization who need notifications</h2><br/><h2>Main contact</h2><span class=\"form-hint\">HMCTS will contact this person if they have any questions</span>");
        fields.complex(CaseData::getLocalAuthorityEventData)
                    .optional(LocalAuthorityEventData::getApplicantContact)
                    .caseEventFieldLabel(" ").done();
        fields.readonly(CaseData::getApplicantOtherContactLabel)
                    .caseEventFieldLabel("<h2>Others within your organisation who need notifications</h2><span class=\"form-hint\">Only people with myHMCTS login can receive notifications</span>");
        fields.complex(CaseData::getLocalAuthorityEventData)
                    .optional(LocalAuthorityEventData::getApplicantContactOthers).done();
    }
}
