package uk.gov.hmcts.reform.fpl.ccd.event.page;

import uk.gov.hmcts.ccd.sdk.api.Event;
import uk.gov.hmcts.ccd.sdk.api.FieldCollection;
import uk.gov.hmcts.reform.fpl.enums.State;
import uk.gov.hmcts.reform.fpl.model.CaseData;
import uk.gov.hmcts.reform.fpl.model.Colleague;
import uk.gov.hmcts.reform.fpl.model.UserRole;

/**
 * Generated by ccd-definition-converter from CARE_SUPERVISION_EPO on migration; owned by this service team.
 *
 * <p>Wizard page {@code Colleagues} of event {@code enterLocalAuthorityAfterSubmission}.
 */
public final class EnterLocalAuthorityAfterSubmissionColleaguesPage {
    private EnterLocalAuthorityAfterSubmissionColleaguesPage() {
    }

    /**
     * Applies this page's fields to the event.
     *
     * @param fields the event's field-collection builder
     */
    public static void apply(
            FieldCollection.FieldCollectionBuilder<CaseData, State, Event.EventBuilder<CaseData, UserRole, State>> fields) {
        fields.page("Colleagues");
        fields.complex(CaseData::getLocalAuthorityColleagues).done();
        fields.complex(CaseData::getLocalAuthorityColleagues, Colleague.class)
                    .mandatory(Colleague::getRole)
                    .eventLabel("Select their role")
                    .mandatory(Colleague::getTitle)
                    .eventLabel("Add job title")
                    .optional(Colleague::getDx)
                    .optional(Colleague::getReference)
                    .mandatory(Colleague::getFullName)
                    .eventLabel("Full name")
                    .mandatory(Colleague::getEmail)
                    .eventLabel("Email")
                    .optional(Colleague::getPhone)
                    .mandatory(Colleague::getNotificationRecipient)
                    .eventLabel("Send them case update notifications?")
                    .readonly(Colleague::getMainContact)
                    .fieldShowCondition("role=\"DO NOT SHOW\"").done();
    }
}
