package uk.gov.hmcts.reform.fpl.ccd.event.page;

import uk.gov.hmcts.ccd.sdk.api.Event;
import uk.gov.hmcts.ccd.sdk.api.FieldCollection;
import uk.gov.hmcts.reform.fpl.enums.State;
import uk.gov.hmcts.reform.fpl.model.CaseData;
import uk.gov.hmcts.reform.fpl.model.UserRole;
import uk.gov.hmcts.reform.fpl.model.event.ChildExtensionEventData;

/**
 * Generated by ccd-definition-converter from CARE_SUPERVISION_EPO on migration; owned by this service team.
 *
 * <p>Field placements for page {@code extend26WeekTimelineSelectExtension} of event {@code extend26WeekTimeline} (part 2 of 2).
 */
public final class Extend26WeekTimelineExtend26WeekTimelineSelectExtensionPageFields2 {
    private Extend26WeekTimelineExtend26WeekTimelineSelectExtensionPageFields2() {
    }

    /**
     * @param fields the event's field-collection builder
     */
    public static void apply(
            FieldCollection.FieldCollectionBuilder<CaseData, State, Event.EventBuilder<CaseData, UserRole, State>> fields) {
        fields.complex(CaseData::getChildExtensionEventData)
                    .optional(ChildExtensionEventData::getChildExtension13)
                    .fieldShowCondition("childSelected13=\"Yes\" AND sameExtensionForAllChildren=\"No\"")
                    .optional(ChildExtensionEventData::getChildExtension14)
                    .fieldShowCondition("childSelected14=\"Yes\" AND sameExtensionForAllChildren=\"No\"").done();
    }
}
