package uk.gov.hmcts.reform.fpl.ccd.event.page;

import uk.gov.hmcts.ccd.sdk.api.Event;
import uk.gov.hmcts.ccd.sdk.api.FieldCollection;
import uk.gov.hmcts.reform.fpl.enums.State;
import uk.gov.hmcts.reform.fpl.model.CaseData;
import uk.gov.hmcts.reform.fpl.model.UserRole;

/**
 * Generated by ccd-definition-converter from CARE_SUPERVISION_EPO on migration; owned by this service team.
 *
 * <p>Wizard page {@code ConfirmHearingDetails} of event {@code manageHearings}.
 */
public final class ManageHearingsConfirmHearingDetailsPage {
    private ManageHearingsConfirmHearingDetailsPage() {
    }

    /**
     * Applies this page's fields to the event.
     *
     * @param fields the event's field-collection builder
     */
    public static void apply(
            FieldCollection.FieldCollectionBuilder<CaseData, State, Event.EventBuilder<CaseData, UserRole, State>> fields) {
        fields.page("ConfirmHearingDetails");
        fields.showCondition("showConfirmPastHearingDatesPage=\"Yes\"");
        fields.readonlyNoSummary(CaseData::getConfirmHearingDateLabel)
                    .publish(false);
        fields.readonlyNoSummary(CaseData::getHearingStartDateLabel)
                    .fieldShowCondition("startDateFlag=\"Yes\"")
                    .publish(false);
        fields.readonlyNoSummary(CaseData::getHearingDurationLabel)
                    .fieldShowCondition("endDateFlag=\"Yes\"")
                    .publish(false);
        fields.mandatoryNoSummary(CaseData::getConfirmHearingDate)
                    .publish(false);
        fields.mandatoryNoSummary(CaseData::getHearingEndDateConfirmation)
                    .fieldShowCondition("confirmHearingDate = \"No\" AND endDateFlag=\"Yes\"")
                    .publish(false);
        fields.mandatoryNoSummary(CaseData::getHearingStartDateConfirmation)
                    .fieldShowCondition("confirmHearingDate = \"No\" AND startDateFlag=\"Yes\"")
                    .publish(false);
    }
}
