package uk.gov.hmcts.reform.fpl.ccd.event.page;

import uk.gov.hmcts.ccd.sdk.api.Event;
import uk.gov.hmcts.ccd.sdk.api.FieldCollection;
import uk.gov.hmcts.reform.fpl.enums.State;
import uk.gov.hmcts.reform.fpl.model.CaseData;
import uk.gov.hmcts.reform.fpl.model.common.JudgeAndLegalAdvisor;
import uk.gov.hmcts.reform.fpl.model.UserRole;
import uk.gov.hmcts.reform.fpl.model.event.ManageOrdersEventData;

/**
 * Generated by ccd-definition-converter from CARE_SUPERVISION_EPO on migration; owned by this service team.
 *
 * <p>Wizard page {@code IssuingDetails} of event {@code manageOrders}.
 */
public final class ManageOrdersIssuingDetailsPage {
    private ManageOrdersIssuingDetailsPage() {
    }

    /**
     * Applies this page's fields to the event.
     *
     * @param fields the event's field-collection builder
     */
    public static void apply(
            FieldCollection.FieldCollectionBuilder<CaseData, State, Event.EventBuilder<CaseData, UserRole, State>> fields) {
        fields.page("IssuingDetails");
        fields.showCondition("orderTempQuestions.approver=\"YES\" OR orderTempQuestions.approvalDate=\"YES\" OR orderTempQuestions.approvalDateTime=\"YES\"");
        fields.readonlyNoSummary(CaseData::getIssuingDetailsSectionHeader);
        fields.readonlyNoSummary(CaseData::getIssuingDetailsSectionSubHeader);
        fields.complex(CaseData::getManageOrdersEventData)
                    .mandatory(ManageOrdersEventData::getManageOrdersChildPlacementApplication)
                    .fieldShowCondition("orderTempQuestions.childPlacementApplications=\"YES\"")
                    .caseEventFieldLabel("Child placement application").done();
        fields.complex(CaseData::getJudgeAndLegalAdvisor)
                    .readonly(JudgeAndLegalAdvisor::getAllocatedJudgeLabel)
                    .eventLabel(" ")
                    .mandatory(JudgeAndLegalAdvisor::getUseAllocatedJudge)
                    .eventLabel("Is this judge issuing the order?")
                    .readonly(JudgeAndLegalAdvisor::getJudgeSubHeading)
                    .mandatory(JudgeAndLegalAdvisor::getJudgeTitle)
                    .eventLabel("Judge or Magistrate's title")
                    .mandatory(JudgeAndLegalAdvisor::getOtherTitle)
                    .eventLabel("Title")
                    .mandatory(JudgeAndLegalAdvisor::getJudgeLastName)
                    .eventLabel("Last name")
                    .mandatory(JudgeAndLegalAdvisor::getJudgeFullName)
                    .eventLabel("Full name")
                    .mandatory(JudgeAndLegalAdvisor::getJudgeEmailAddress)
                    .eventLabel("Email Address")
                    .optional(JudgeAndLegalAdvisor::getLegalAdvisorName)
                    .eventLabel("Justices' Legal Adviser's full name").done()
                    .fieldShowCondition("orderTempQuestions.approver=\"YES\"")
                    .caseEventFieldLabel(" ");
        fields.complex(CaseData::getManageOrdersEventData)
                    .mandatory(ManageOrdersEventData::getManageOrdersApprovalDate)
                    .fieldShowCondition("orderTempQuestions.approvalDate=\"YES\"")
                    .mandatory(ManageOrdersEventData::getManageOrdersApprovalDateTime)
                    .fieldShowCondition("orderTempQuestions.approvalDateTime=\"YES\"").done();
    }
}
