package uk.gov.hmcts.reform.fpl.ccd.event.page;

import uk.gov.hmcts.ccd.sdk.api.Event;
import uk.gov.hmcts.ccd.sdk.api.FieldCollection;
import uk.gov.hmcts.reform.fpl.enums.State;
import uk.gov.hmcts.reform.fpl.model.CaseData;
import uk.gov.hmcts.reform.fpl.model.UserRole;
import uk.gov.hmcts.reform.fpl.model.event.ManageOrdersEventData;

/**
 * Generated by ccd-definition-converter from CARE_SUPERVISION_EPO on migration; owned by this service team.
 *
 * <p>Wizard page {@code HearingDetails} of event {@code manageOrders}.
 */
public final class ManageOrdersHearingDetailsPage {
    private ManageOrdersHearingDetailsPage() {
    }

    /**
     * Applies this page's fields to the event.
     *
     * @param fields the event's field-collection builder
     */
    public static void apply(
            FieldCollection.FieldCollectionBuilder<CaseData, State, Event.EventBuilder<CaseData, UserRole, State>> fields) {
        fields.page("HearingDetails");
        fields.showCondition("orderTempQuestions.hearingDetails=\"YES\"");
        fields.readonlyNoSummary(CaseData::getHearingDetailsSectionHeader);
        fields.readonlyNoSummary(CaseData::getHearingDetailsSectionSubHeader);
        fields.mandatory(CaseData::getManageOrdersApprovedAtHearing)
                    .fieldShowCondition("orderTempQuestions.hearingDetails=\"YES\"");
        fields.complex(CaseData::getManageOrdersEventData)
                    .mandatory(ManageOrdersEventData::getManageOrdersApprovedAtHearingList)
                    .fieldShowCondition("orderTempQuestions.hearingDetails=\"YES\" AND manageOrdersApprovedAtHearing=\"Yes\"").done();
        fields.mandatory(CaseData::getManageOrdersShouldLinkApplication)
                    .fieldShowCondition("orderTempQuestions.linkApplication=\"YES\"");
        fields.complex(CaseData::getManageOrdersEventData)
                    .mandatory(ManageOrdersEventData::getManageOrdersLinkedApplication)
                    .fieldShowCondition("manageOrdersShouldLinkApplication=\"Yes\"").done();
    }
}
