package uk.gov.hmcts.reform.fpl.ccd.event.page;

import uk.gov.hmcts.ccd.sdk.api.Event;
import uk.gov.hmcts.ccd.sdk.api.FieldCollection;
import uk.gov.hmcts.reform.fpl.enums.State;
import uk.gov.hmcts.reform.fpl.model.CaseData;
import uk.gov.hmcts.reform.fpl.model.UserRole;
import uk.gov.hmcts.reform.fpl.model.event.ManageOrdersEventData;

/**
 * Generated by ccd-definition-converter from CARE_SUPERVISION_EPO on migration; owned by this service team.
 *
 * <p>Wizard page {@code review} of event {@code manageOrders}.
 */
public final class ManageOrdersReviewPage {
    private ManageOrdersReviewPage() {
    }

    /**
     * Applies this page's fields to the event.
     *
     * @param fields the event's field-collection builder
     */
    public static void apply(
            FieldCollection.FieldCollectionBuilder<CaseData, State, Event.EventBuilder<CaseData, UserRole, State>> fields) {
        fields.page("review");
        fields.showCondition("orderTempQuestions.previewOrder=\"YES\"");
        fields.readonlyNoSummary(CaseData::getOrderPreviewSectionHeader);
        fields.readonlyNoSummary(CaseData::getOrderPreview);
        fields.complex(CaseData::getManageOrdersEventData)
                    .mandatory(ManageOrdersEventData::getManageOrdersCloseCase)
                    .fieldShowCondition("orderTempQuestions.closeCase=\"YES\"").done();
        fields.readonly(CaseData::getManageOrdersCloseCaseWarning)
                    .fieldShowCondition("orderTempQuestions.closeCase=\"YES\" AND manageOrdersCloseCase=\"Yes\"");
    }
}
