package uk.gov.hmcts.reform.fpl.ccd.event.page;

import uk.gov.hmcts.ccd.sdk.api.Event;
import uk.gov.hmcts.ccd.sdk.api.FieldCollection;
import uk.gov.hmcts.reform.fpl.enums.State;
import uk.gov.hmcts.reform.fpl.model.CaseData;
import uk.gov.hmcts.reform.fpl.model.UserRole;

/**
 * Generated by ccd-definition-converter from CARE_SUPERVISION_EPO on migration; owned by this service team.
 *
 * <p>Wizard page {@code SelectHearingOption} of event {@code manageHearings}.
 */
public final class ManageHearingsSelectHearingOptionPage {
    private ManageHearingsSelectHearingOptionPage() {
    }

    /**
     * Applies this page's fields to the event.
     *
     * @param fields the event's field-collection builder
     */
    public static void apply(
            FieldCollection.FieldCollectionBuilder<CaseData, State, Event.EventBuilder<CaseData, UserRole, State>> fields) {
        fields.page("SelectHearingOption");
        fields.showCondition("hasExistingHearings=\"Yes\"");
        fields.readonly(CaseData::getHasExistingHearings)
                    .fieldShowCondition("hearingOption=\"DO_NOT_SHOW\"")
                    .publish(false);
        fields.readonly(CaseData::getFirstHearingFlag)
                    .fieldShowCondition("hearingOption=\"DO_NOT_SHOW\"")
                    .publish(false);
        fields.readonly(CaseData::getHasPreviousHearingVenue)
                    .fieldShowCondition("hearingOption=\"DO_NOT_SHOW\"")
                    .publish(false);
        fields.readonly(CaseData::getHasHearingsToAdjourn)
                    .fieldShowCondition("hearingOption=\"DO_NOT_SHOW\"")
                    .publish(false);
        fields.readonly(CaseData::getHasPastHearings)
                    .fieldShowCondition("hearingOption=\"DO_NOT_SHOW\"")
                    .publish(false);
        fields.readonly(CaseData::getHasFutureHearings)
                    .fieldShowCondition("hearingOption=\"DO_NOT_SHOW\"")
                    .publish(false);
        fields.readonly(CaseData::getHasHearingsToVacate)
                    .fieldShowCondition("hearingOption=\"DO_NOT_SHOW\"")
                    .publish(false);
        fields.readonly(CaseData::getHasHearingsToReList)
                    .fieldShowCondition("hearingOption=\"DO_NOT_SHOW\"")
                    .publish(false);
        fields.readonly(CaseData::getHasOthers)
                    .fieldShowCondition("hearingOption=\"DO_NOT_SHOW\"")
                    .publish(false);
        fields.readonlyNoSummary(CaseData::getToReListHearingsLabel)
                    .fieldShowCondition("hasHearingsToReList=\"Yes\"")
                    .publish(false);
        fields.mandatoryNoSummary(CaseData::getHearingOption)
                    .publish(false);
        fields.mandatory(CaseData::getPastHearingDateList)
                    .fieldShowCondition("hearingOption=\"EDIT_PAST_HEARING\" AND hasPastHearings=\"Yes\"")
                    .publish(false);
        fields.readonly(CaseData::getNoPastHearingsToEditLabel)
                    .fieldShowCondition("hearingOption=\"EDIT_PAST_HEARING\" AND hasPastHearings=\"\"")
                    .publish(false);
        fields.readonly(CaseData::getNoFutureHearingsToEditLabel)
                    .fieldShowCondition("hearingOption=\"EDIT_FUTURE_HEARING\" AND hasFutureHearings=\"\"")
                    .publish(false);
        fields.readonly(CaseData::getNoHearingsToAdjournLabel)
                    .fieldShowCondition("hearingOption=\"ADJOURN_HEARING\" AND hasHearingsToAdjourn=\"\"")
                    .publish(false);
        fields.mandatory(CaseData::getPastAndTodayHearingDateList)
                    .fieldShowCondition("hearingOption=\"ADJOURN_HEARING\" AND hasHearingsToAdjourn=\"Yes\"")
                    .publish(false);
        fields.mandatory(CaseData::getFutureHearingDateList)
                    .fieldShowCondition("hearingOption=\"EDIT_FUTURE_HEARING\" AND hasFutureHearings=\"Yes\"")
                    .publish(false);
        fields.readonly(CaseData::getNoHearingsToVacateLabel)
                    .fieldShowCondition("hearingOption=\"VACATE_HEARING\" AND hasHearingsToVacate=\"\"")
                    .publish(false);
        fields.readonly(CaseData::getNoHearingsToReListLabel)
                    .fieldShowCondition("hearingOption=\"RE_LIST_HEARING\" AND hasHearingsToReList=\"\"")
                    .publish(false);
        fields.mandatory(CaseData::getToReListHearingDateList)
                    .fieldShowCondition("hearingOption=\"RE_LIST_HEARING\" AND hasHearingsToReList=\"Yes\"")
                    .publish(false);
        fields.mandatory(CaseData::getVacateHearingDateList)
                    .fieldShowCondition("hearingOption=\"VACATE_HEARING\" AND hasHearingsToVacate=\"Yes\"")
                    .publish(false);
        fields.mandatory(CaseData::getVacatedHearingDate)
                    .fieldShowCondition("hearingOption=\"VACATE_HEARING\" AND hasHearingsToVacate=\"Yes\"")
                    .publish(false);
    }
}
