package uk.gov.hmcts.reform.fpl.ccd.event.page;

import uk.gov.hmcts.ccd.sdk.api.Event;
import uk.gov.hmcts.ccd.sdk.api.FieldCollection;
import uk.gov.hmcts.reform.fpl.enums.State;
import uk.gov.hmcts.reform.fpl.model.CaseData;
import uk.gov.hmcts.reform.fpl.model.ManageHearingHousekeepEventData;
import uk.gov.hmcts.reform.fpl.model.UserRole;

/**
 * Generated by ccd-definition-converter from CARE_SUPERVISION_EPO on migration; owned by this service team.
 *
 * <p>Wizard page {@code SelectReListOption} of event {@code manageHearings}.
 */
public final class ManageHearingsSelectReListOptionPage {
    private ManageHearingsSelectReListOptionPage() {
    }

    /**
     * Applies this page's fields to the event.
     *
     * @param fields the event's field-collection builder
     */
    public static void apply(
            FieldCollection.FieldCollectionBuilder<CaseData, State, Event.EventBuilder<CaseData, UserRole, State>> fields) {
        fields.page("SelectReListOption");
        fields.showCondition("hearingOption=\"ADJOURN_HEARING\" OR hearingOption=\"VACATE_HEARING\"");
        fields.readonly(CaseData::getShowVacatePastHearingWarning)
                    .fieldShowCondition("vacatePastHearingWarning=\"DO_NOT_SHOW\"")
                    .publish(false);
        fields.readonly(CaseData::getVacatePastHearingWarning)
                    .fieldShowCondition("showVacatePastHearingWarning=\"Yes\"")
                    .publish(false);
        fields.mandatory(CaseData::getHearingReListOption)
                    .publish(false);
        fields.complex(CaseData::getManageHearingHousekeepEventData)
                    .mandatory(ManageHearingHousekeepEventData::getHearingHousekeepOption)
                    .fieldShowCondition("hearingReListOption=\"NONE\"")
                    .publish(false)
                    .mandatory(ManageHearingHousekeepEventData::getHearingHousekeepReason)
                    .fieldShowCondition("hearingHousekeepOption=\"YES\"")
                    .publish(false)
                    .mandatory(ManageHearingHousekeepEventData::getHearingHousekeepReasonOther)
                    .fieldShowCondition("hearingHousekeepOption=\"YES\" AND hearingHousekeepReason=\"OTHER\"")
                    .publish(false).done();
    }
}
