package uk.gov.hmcts.reform.fpl.ccd.event.page;

import uk.gov.hmcts.ccd.sdk.api.Event;
import uk.gov.hmcts.ccd.sdk.api.FieldCollection;
import uk.gov.hmcts.reform.fpl.enums.State;
import uk.gov.hmcts.reform.fpl.model.CaseData;
import uk.gov.hmcts.reform.fpl.model.UserRole;
import uk.gov.hmcts.reform.fpl.model.event.ManageOrdersEventData;

/**
 * Generated by ccd-definition-converter from CARE_SUPERVISION_EPO on migration; owned by this service team.
 *
 * <p>Field placements for page {@code OrderDetails} of event {@code manageOrders} (part 2 of 2).
 */
public final class ManageOrdersOrderDetailsPageFields2 {
    private ManageOrdersOrderDetailsPageFields2() {
    }

    /**
     * @param fields the event's field-collection builder
     */
    public static void apply(
            FieldCollection.FieldCollectionBuilder<CaseData, State, Event.EventBuilder<CaseData, UserRole, State>> fields) {
        fields.readonlyNoSummary(CaseData::getManageOrdersTransparencyOrderPublishIdentityLabel)
                    .fieldShowCondition("orderTempQuestions.manageOrdersTransparencyOrder=\"YES\"");
        fields.complex(CaseData::getManageOrdersEventData)
                    .optional(ManageOrdersEventData::getManageOrdersTransparencyOrderPublishIdentityDetails)
                    .fieldShowCondition("orderTempQuestions.manageOrdersTransparencyOrder=\"YES\"").done();
        fields.readonlyNoSummary(CaseData::getManageOrdersTransparencyOrderPublishDocumentsLabel)
                    .fieldShowCondition("orderTempQuestions.manageOrdersTransparencyOrder=\"YES\"");
        fields.complex(CaseData::getManageOrdersEventData)
                    .optional(ManageOrdersEventData::getManageOrdersTransparencyOrderPublishDocumentsDetails)
                    .fieldShowCondition("orderTempQuestions.manageOrdersTransparencyOrder=\"YES\"")
                    .mandatory(ManageOrdersEventData::getManageOrdersTransparencyOrderPermissionToReportEffectiveDate)
                    .fieldShowCondition("orderTempQuestions.manageOrdersTransparencyOrder=\"YES\"")
                    .mandatory(ManageOrdersEventData::getManageOrdersNonMolestationOrderApplicant)
                    .fieldShowCondition("orderTempQuestions.nonMolestationOrder=\"YES\"")
                    .mandatory(ManageOrdersEventData::getManageOrdersNonMolestationOrderRespondent)
                    .fieldShowCondition("orderTempQuestions.nonMolestationOrder=\"YES\"")
                    .optional(ManageOrdersEventData::getManageOrdersRecitalsAndPreamblesOptional)
                    .fieldShowCondition("orderTempQuestions.nonMolestationOrder=\"YES\"")
                    .mandatory(ManageOrdersEventData::getManageOrdersNonMolestationOrder)
                    .fieldShowCondition("orderTempQuestions.nonMolestationOrder=\"YES\"").done();
    }
}
