package uk.gov.hmcts.reform.fpl.ccd.event.page;

import uk.gov.hmcts.ccd.sdk.api.Event;
import uk.gov.hmcts.ccd.sdk.api.FieldCollection;
import uk.gov.hmcts.reform.fpl.enums.State;
import uk.gov.hmcts.reform.fpl.model.CaseData;
import uk.gov.hmcts.reform.fpl.model.UserRole;
import uk.gov.hmcts.reform.fpl.model.event.ManageDocumentEventData;

/**
 * Generated by ccd-definition-converter from CARE_SUPERVISION_EPO on migration; owned by this service team.
 *
 * <p>Wizard page {@code UploadNewDocuments} of event {@code manageDocumentsV2}.
 */
public final class ManageDocumentsV2UploadNewDocumentsPage {
    private ManageDocumentsV2UploadNewDocumentsPage() {
    }

    /**
     * Applies this page's fields to the event.
     *
     * @param fields the event's field-collection builder
     */
    public static void apply(
            FieldCollection.FieldCollectionBuilder<CaseData, State, Event.EventBuilder<CaseData, UserRole, State>> fields) {
        fields.page("UploadNewDocuments");
        fields.pageLabel("Upload new documents");
        fields.showCondition("manageDocumentAction=\"UPLOAD_DOCUMENTS\"");
        fields.readonly(CaseData::getManageDocumentUploadNewDocInstructionLabel);
        fields.readonly(CaseData::getManageDocumentRequirementLabel);
        fields.complex(CaseData::getManageDocumentEventData)
                    .optional(ManageDocumentEventData::getUploadableDocumentBundle)
                    .mandatory(ManageDocumentEventData::getDocumentAcknowledge).done();
        fields.readonlyNoSummary(CaseData::getCaseName)
                    .fieldShowCondition("documentAcknowledge=\"DO_NOT_SHOW\"");
        fields.complex(CaseData::getManageDocumentEventData)
                    .readonlyNoSummary(ManageDocumentEventData::getHasConfidentialParty)
                    .fieldShowCondition("documentAcknowledge=\"DO_NOT_SHOW\"").done();
        fields.readonlyNoSummary(CaseData::getLanguageRequirement)
                    .fieldShowCondition("documentAcknowledge=\"DO_NOT_SHOW\"");
        fields.complex(CaseData::getManageDocumentEventData)
                    .readonlyNoSummary(ManageDocumentEventData::getAskForPlacementNoticeRecipientType)
                    .fieldShowCondition("documentAcknowledge=\"DO_NOT_SHOW\"")
                    .readonlyNoSummary(ManageDocumentEventData::getAllowMarkDocumentConfidential)
                    .fieldShowCondition("documentAcknowledge=\"DO_NOT_SHOW\"").done();
    }
}
