package uk.gov.hmcts.reform.fpl.ccd.event.page;

import uk.gov.hmcts.ccd.sdk.api.Event;
import uk.gov.hmcts.ccd.sdk.api.FieldCollection;
import uk.gov.hmcts.reform.fpl.enums.State;
import uk.gov.hmcts.reform.fpl.model.CaseData;
import uk.gov.hmcts.reform.fpl.model.UserRole;
import uk.gov.hmcts.reform.fpl.model.event.LocalAuthoritiesEventData;

/**
 * Generated by ccd-definition-converter from CARE_SUPERVISION_EPO on migration; owned by this service team.
 *
 * <p>Wizard page {@code Action} of event {@code manageLocalAuthorities}.
 */
public final class ManageLocalAuthoritiesActionPage {
    private ManageLocalAuthoritiesActionPage() {
    }

    /**
     * Applies this page's fields to the event.
     *
     * @param fields the event's field-collection builder
     */
    public static void apply(
            FieldCollection.FieldCollectionBuilder<CaseData, State, Event.EventBuilder<CaseData, UserRole, State>> fields) {
        fields.page("Action");
        fields.complex(CaseData::getLocalAuthoritiesEventData)
                    .readonly(LocalAuthoritiesEventData::getIsLaSolicitor)
                    .fieldShowCondition("localAuthorityActionLabel=\"DO NOT SHOW\"")
                    .publish(false).done();
        fields.readonly(CaseData::getLocalAuthorityActionLabel)
                    .fieldShowCondition("isLaSolicitor!=\"YES\"")
                    .publish(false);
        fields.readonly(CaseData::getLocalAuthorityActionLabelLA)
                    .fieldShowCondition("isLaSolicitor=\"YES\"")
                    .publish(false);
        fields.complex(CaseData::getLocalAuthoritiesEventData)
                    .mandatory(LocalAuthoritiesEventData::getLocalAuthorityAction)
                    .fieldShowCondition("isLaSolicitor!=\"YES\"")
                    .publish(false)
                    .mandatory(LocalAuthoritiesEventData::getLocalAuthorityActionLA)
                    .fieldShowCondition("isLaSolicitor=\"YES\"")
                    .publish(false)
                    .mandatory(LocalAuthoritiesEventData::getLocalAuthoritiesToShare)
                    .fieldShowCondition("localAuthorityAction=\"ADD\" OR localAuthorityActionLA=\"ADD\"")
                    .publish(false).done();
    }
}
