package uk.gov.hmcts.reform.fpl.ccd.event.page;

import uk.gov.hmcts.ccd.sdk.api.Event;
import uk.gov.hmcts.ccd.sdk.api.FieldCollection;
import uk.gov.hmcts.reform.fpl.enums.State;
import uk.gov.hmcts.reform.fpl.model.CaseData;
import uk.gov.hmcts.reform.fpl.model.UserRole;
import uk.gov.hmcts.reform.fpl.model.event.MessageJudgeEventData;

/**
 * Generated by ccd-definition-converter from CARE_SUPERVISION_EPO on migration; owned by this service team.
 *
 * <p>Wizard page {@code NewMessageMetaData} of event {@code messageJudgeOrLegalAdviser}.
 */
public final class MessageJudgeOrLegalAdviserNewMessageMetaDataPage {
    private MessageJudgeOrLegalAdviserNewMessageMetaDataPage() {
    }

    /**
     * Applies this page's fields to the event.
     *
     * @param fields the event's field-collection builder
     */
    public static void apply(
            FieldCollection.FieldCollectionBuilder<CaseData, State, Event.EventBuilder<CaseData, UserRole, State>> fields) {
        fields.page("NewMessageMetaData");
        fields.complex(CaseData::getMessageJudgeEventData)
                    .readonlyNoSummary(MessageJudgeEventData::getRelatedDocumentsLabel)
                    .fieldShowCondition("isMessageRegardingDocuments=\"DOCUMENT\" OR isMessageRegardingDocuments=\"APPLICATION\"")
                    .publish(false).done();
        fields.readonlyNoSummary(CaseData::getNextHearingLabel)
                    .publish(false);
        fields.complex(CaseData::getMessageJudgeEventData)
                    .optional(MessageJudgeEventData::getJudicialMessageMetaData)
                    .publish(false)
                    .readonlyNoSummary(MessageJudgeEventData::getIsJudiciary)
                    .fieldShowCondition("hasAdditionalApplications=\"DO NOT SHOW\"")
                    .publish(false)
                    .mandatory(MessageJudgeEventData::getJudicialMessageNote)
                    .publish(false).done();
        fields.mandatoryNoSummary(CaseData::getLatestRoleSent)
                    .fieldShowCondition("isMessageRegardingDocuments=\"DO_NOT_SHOW\"");
        fields.readonly(CaseData::getCourt)
                    .fieldShowCondition("isMessageRegardingDocuments=\"DO_NOT_SHOW\"");
    }
}
