package uk.gov.hmcts.reform.fpl.ccd.event.page;

import uk.gov.hmcts.ccd.sdk.api.Event;
import uk.gov.hmcts.ccd.sdk.api.FieldCollection;
import uk.gov.hmcts.reform.fpl.enums.State;
import uk.gov.hmcts.reform.fpl.model.CaseData;
import uk.gov.hmcts.reform.fpl.model.UserRole;

/**
 * Generated by ccd-definition-converter from CARE_SUPERVISION_EPO on migration; owned by this service team.
 *
 * <p>Wizard page {@code selectOutsourcingLA} of event {@code openCase}.
 */
public final class OpenCaseSelectOutsourcingLAPage {
    private OpenCaseSelectOutsourcingLAPage() {
    }

    /**
     * Applies this page's fields to the event.
     *
     * @param fields the event's field-collection builder
     */
    public static void apply(
            FieldCollection.FieldCollectionBuilder<CaseData, State, Event.EventBuilder<CaseData, UserRole, State>> fields) {
        fields.page("selectOutsourcingLA");
        fields.showCondition("isLocalAuthority=\"NO\" OR outsourcingType != \"\"");
        fields.readonly(CaseData::getOutsourcingType)
                    .fieldShowCondition("outsourcingLAs = \"DO_NOT_SHOW\"");
        fields.readonly(CaseData::getIsLocalAuthority)
                    .fieldShowCondition("outsourcingLAs = \"DO_NOT_SHOW\"");
        fields.mandatory(CaseData::getRepresentativeType)
                    .fieldShowCondition("outsourcingType != \"MLA\"");
        fields.mandatory(CaseData::getOutsourcingLAs)
                    .fieldShowCondition("outsourcingType = \"MLA\" OR representativeType=\"LOCAL_AUTHORITY\"");
        fields.mandatory(CaseData::getRelatingLA)
                    .fieldShowCondition("representativeType=\"RESPONDENT_SOLICITOR\" OR representativeType=\"CHILD_SOLICITOR\"");
    }
}
