package uk.gov.hmcts.reform.fpl.ccd.event.page;

import uk.gov.hmcts.ccd.sdk.api.Event;
import uk.gov.hmcts.ccd.sdk.api.FieldCollection;
import uk.gov.hmcts.reform.fpl.enums.State;
import uk.gov.hmcts.reform.fpl.model.CaseData;
import uk.gov.hmcts.reform.fpl.model.UserRole;
import uk.gov.hmcts.reform.fpl.model.event.PlacementEventData;

/**
 * Generated by ccd-definition-converter from CARE_SUPERVISION_EPO on migration; owned by this service team.
 *
 * <p>Wizard page {@code noticeDetails} of event {@code placementNotice}.
 */
public final class PlacementNoticeNoticeDetailsPage {
    private PlacementNoticeNoticeDetailsPage() {
    }

    /**
     * Applies this page's fields to the event.
     *
     * @param fields the event's field-collection builder
     */
    public static void apply(
            FieldCollection.FieldCollectionBuilder<CaseData, State, Event.EventBuilder<CaseData, UserRole, State>> fields) {
        fields.page("noticeDetails");
        fields.pageLabel("Notice of hearing details");
        fields.readonly(CaseData::getPlacementChildNameLabel);
        fields.complex(CaseData::getPlacementEventData)
                    .readonlyNoSummary(PlacementEventData::getPlacement)
                    .fieldShowCondition("placementChildNameLabel = \"DO_NOT_SHOW\"")
                    .mandatory(PlacementEventData::getPlacementNoticeDateTime)
                    .mandatory(PlacementEventData::getPlacementNoticeDuration)
                    .mandatory(PlacementEventData::getPlacementNoticeVenue).done();
    }
}
