package uk.gov.hmcts.reform.fpl.ccd.event.page;

import uk.gov.hmcts.ccd.sdk.api.Event;
import uk.gov.hmcts.ccd.sdk.api.FieldCollection;
import uk.gov.hmcts.reform.fpl.enums.State;
import uk.gov.hmcts.reform.fpl.model.CaseData;
import uk.gov.hmcts.reform.fpl.model.UserRole;
import uk.gov.hmcts.reform.fpl.model.event.PlacementEventData;

/**
 * Generated by ccd-definition-converter from CARE_SUPERVISION_EPO on migration; owned by this service team.
 *
 * <p>Wizard page {@code placementList} of event {@code placementNotice}.
 */
public final class PlacementNoticePlacementListPage {
    private PlacementNoticePlacementListPage() {
    }

    /**
     * Applies this page's fields to the event.
     *
     * @param fields the event's field-collection builder
     */
    public static void apply(
            FieldCollection.FieldCollectionBuilder<CaseData, State, Event.EventBuilder<CaseData, UserRole, State>> fields) {
        fields.page("placementList");
        fields.complex(CaseData::getPlacementEventData)
                    .readonly(PlacementEventData::getHasExistingPlacements)
                    .fieldShowCondition("noPlacementApplicationsLabel = \"DO_NOT_SHOW\"")
                    .readonly(PlacementEventData::getPlacementChildName)
                    .fieldShowCondition("placementChildNameLabel2=\"DO NOT SHOW\"").done();
        fields.mandatory(CaseData::getPlacementList)
                    .fieldShowCondition("hasExistingPlacements = \"YES\"");
        fields.readonly(CaseData::getNoPlacementApplicationsLabel)
                    .fieldShowCondition("hasExistingPlacements = \"NO\"");
    }
}
