package uk.gov.hmcts.reform.fpl.ccd.event.page;

import uk.gov.hmcts.ccd.sdk.api.Event;
import uk.gov.hmcts.ccd.sdk.api.FieldCollection;
import uk.gov.hmcts.reform.fpl.enums.State;
import uk.gov.hmcts.reform.fpl.model.CaseData;
import uk.gov.hmcts.reform.fpl.model.UserRole;
import uk.gov.hmcts.reform.fpl.model.event.RecordChildrenFinalDecisionsEventData;

/**
 * Generated by ccd-definition-converter from CARE_SUPERVISION_EPO on migration; owned by this service team.
 *
 * <p>Wizard page {@code 2} of event {@code recordFinalDecisions}.
 */
public final class RecordFinalDecisionsPage2 {
    private RecordFinalDecisionsPage2() {
    }

    /**
     * Applies this page's fields to the event.
     *
     * @param fields the event's field-collection builder
     */
    public static void apply(
            FieldCollection.FieldCollectionBuilder<CaseData, State, Event.EventBuilder<CaseData, UserRole, State>> fields) {
        fields.page("2");
        fields.readonlyNoSummary(CaseData::getCloseCaseDetailsHeadingLabel);
        fields.complex(CaseData::getRecordChildrenFinalDecisionsEventData)
                    .mandatoryNoSummary(RecordChildrenFinalDecisionsEventData::getFinalDecisionDate)
                    .caseEventFieldLabel("Date final decision was made")
                    .optionalNoSummary(RecordChildrenFinalDecisionsEventData::getChildFinalDecisionDetails00)
                    .fieldShowCondition("childSelector.option0 CONTAINS \"SELECTED\" OR optionCount=\"0*\"")
                    .optionalNoSummary(RecordChildrenFinalDecisionsEventData::getChildFinalDecisionDetails01)
                    .fieldShowCondition("childSelector.option1 CONTAINS \"SELECTED\" OR optionCount=\"01*\"")
                    .optionalNoSummary(RecordChildrenFinalDecisionsEventData::getChildFinalDecisionDetails02)
                    .fieldShowCondition("childSelector.option2 CONTAINS \"SELECTED\" OR optionCount=\"012*\"")
                    .optionalNoSummary(RecordChildrenFinalDecisionsEventData::getChildFinalDecisionDetails03)
                    .fieldShowCondition("childSelector.option3 CONTAINS \"SELECTED\" OR optionCount=\"0123*\"")
                    .optionalNoSummary(RecordChildrenFinalDecisionsEventData::getChildFinalDecisionDetails04)
                    .fieldShowCondition("childSelector.option4 CONTAINS \"SELECTED\" OR optionCount=\"01234*\"")
                    .optionalNoSummary(RecordChildrenFinalDecisionsEventData::getChildFinalDecisionDetails05)
                    .fieldShowCondition("childSelector.option5 CONTAINS \"SELECTED\" OR optionCount=\"012345*\"")
                    .optionalNoSummary(RecordChildrenFinalDecisionsEventData::getChildFinalDecisionDetails06)
                    .fieldShowCondition("childSelector.option6 CONTAINS \"SELECTED\" OR optionCount=\"0123456*\"")
                    .optionalNoSummary(RecordChildrenFinalDecisionsEventData::getChildFinalDecisionDetails07)
                    .fieldShowCondition("childSelector.option7 CONTAINS \"SELECTED\" OR optionCount=\"01234567*\"")
                    .optionalNoSummary(RecordChildrenFinalDecisionsEventData::getChildFinalDecisionDetails08)
                    .fieldShowCondition("childSelector.option8 CONTAINS \"SELECTED\" OR optionCount=\"012345678*\"")
                    .optionalNoSummary(RecordChildrenFinalDecisionsEventData::getChildFinalDecisionDetails09)
                    .fieldShowCondition("childSelector.option9 CONTAINS \"SELECTED\" OR optionCount=\"0123456789*\"")
                    .optionalNoSummary(RecordChildrenFinalDecisionsEventData::getChildFinalDecisionDetails10)
                    .fieldShowCondition("childSelector.option10 CONTAINS \"SELECTED\" OR optionCount=\"012345678910*\"")
                    .optionalNoSummary(RecordChildrenFinalDecisionsEventData::getChildFinalDecisionDetails11)
                    .fieldShowCondition("childSelector.option11 CONTAINS \"SELECTED\" OR optionCount=\"01234567891011*\"")
                    .optionalNoSummary(RecordChildrenFinalDecisionsEventData::getChildFinalDecisionDetails12)
                    .fieldShowCondition("childSelector.option12 CONTAINS \"SELECTED\" OR optionCount=\"0123456789101112*\"")
                    .optionalNoSummary(RecordChildrenFinalDecisionsEventData::getChildFinalDecisionDetails13)
                    .fieldShowCondition("childSelector.option13 CONTAINS \"SELECTED\" OR optionCount=\"012345678910111213*\"")
                    .optionalNoSummary(RecordChildrenFinalDecisionsEventData::getChildFinalDecisionDetails14)
                    .fieldShowCondition("childSelector.option14 CONTAINS \"SELECTED\" OR optionCount=\"01234567891011121314*\"").done();
    }
}
