package uk.gov.hmcts.reform.fpl.ccd.event.page;

import uk.gov.hmcts.ccd.sdk.api.Event;
import uk.gov.hmcts.ccd.sdk.api.FieldCollection;
import uk.gov.hmcts.reform.fpl.enums.State;
import uk.gov.hmcts.reform.fpl.model.CaseData;
import uk.gov.hmcts.reform.fpl.model.UserRole;
import uk.gov.hmcts.reform.fpl.model.event.MessageJudgeEventData;

/**
 * Generated by ccd-definition-converter from CARE_SUPERVISION_EPO on migration; owned by this service team.
 *
 * <p>Wizard page {@code SelectMessage} of event {@code replyToMessageJudgeOrLegalAdviser}.
 */
public final class ReplyToMessageJudgeOrLegalAdviserSelectMessagePage {
    private ReplyToMessageJudgeOrLegalAdviserSelectMessagePage() {
    }

    /**
     * Applies this page's fields to the event.
     *
     * @param fields the event's field-collection builder
     */
    public static void apply(
            FieldCollection.FieldCollectionBuilder<CaseData, State, Event.EventBuilder<CaseData, UserRole, State>> fields) {
        fields.page("SelectMessage");
        fields.readonlyNoSummary(CaseData::getHasJudicialMessages)
                    .fieldShowCondition("judicialMessageDynamicList=\"DO_NOT_SHOW\"")
                    .publish(false);
        fields.complex(CaseData::getMessageJudgeEventData)
                    .readonlyNoSummary(MessageJudgeEventData::getIsSendingEmailsInCourt)
                    .fieldShowCondition("judicialMessageDynamicList=\"DO_NOT_SHOW\"")
                    .retainHiddenValue()
                    .publish(false).done();
        fields.readonly(CaseData::getCourt)
                    .fieldShowCondition("judicialMessageReply=\"DO_NOT_SHOW\"");
        fields.complex(CaseData::getMessageJudgeEventData)
                    .mandatoryNoSummary(MessageJudgeEventData::getJudicialMessageDynamicList)
                    .fieldShowCondition("hasJudicialMessages=\"YES\"")
                    .publish(false).done();
        fields.readonlyNoSummary(CaseData::getNoJudicialMessageLabel)
                    .fieldShowCondition("hasJudicialMessages=\"NO\"")
                    .publish(false);
    }
}
