package uk.gov.hmcts.reform.fpl.ccd.event.page;

import uk.gov.hmcts.ccd.sdk.api.Event;
import uk.gov.hmcts.ccd.sdk.api.FieldCollection;
import uk.gov.hmcts.reform.fpl.enums.State;
import uk.gov.hmcts.reform.fpl.model.CaseData;
import uk.gov.hmcts.reform.fpl.model.Supplement;
import uk.gov.hmcts.reform.fpl.model.SupportingEvidenceBundle;
import uk.gov.hmcts.reform.fpl.model.UserRole;
import uk.gov.hmcts.reform.fpl.model.common.C2DocumentBundle;
import uk.gov.hmcts.reform.fpl.model.order.DraftOrder;

/**
 * Generated by ccd-definition-converter from CARE_SUPERVISION_EPO on migration; owned by this service team.
 *
 * <p>Wizard page {@code 2} of event {@code uploadAdditionalApplications}.
 */
public final class UploadAdditionalApplicationsPage2 {
    private UploadAdditionalApplicationsPage2() {
    }

    /**
     * Applies this page's fields to the event.
     *
     * @param fields the event's field-collection builder
     */
    public static void apply(
            FieldCollection.FieldCollectionBuilder<CaseData, State, Event.EventBuilder<CaseData, UserRole, State>> fields) {
        fields.page("2");
        fields.showCondition("additionalApplicationType CONTAINS \"C2_ORDER\"");
        fields.complex(CaseData::getTemporaryC2Document)
                    .mandatory(C2DocumentBundle::getDocument)
                    .eventLabel("Upload C2 application")
                    .readonly(C2DocumentBundle::getDocumentAcknowledgeLabel)
                    .fieldShowCondition("documentAcknowledge!=\"ACK_RELATED_TO_CASE\"")
                    .eventLabel("<br /><div class='govuk-warning-text'><span class='govuk-warning-text__icon' aria-hidden='true'>!</span><strong class='govuk-warning-text__text'>Check if this document is related to ${caseName}</strong></div><br>")
                    .readonly(C2DocumentBundle::getDocumentAcknowledgeLabelForCYA)
                    .fieldShowCondition("documentAcknowledge=\"ACK_RELATED_TO_CASE\"")
                    .eventLabel("<br /><div class='govuk-warning-text'><span class='govuk-warning-text__icon' aria-hidden='true'>!</span><strong class='govuk-warning-text__text'>Check if this document is related to this case</strong></div><br>")
                    .mandatory(C2DocumentBundle::getDocumentAcknowledge)
                    .eventLabel("Tick to confirm this document is related to this case")
                    .optional(C2DocumentBundle::getC2AdditionalOrdersRequested)
                    .eventLabel("Are you using the C2 to apply for any of the below?")
                    .mandatory(C2DocumentBundle::getParentalResponsibilityType)
                    .fieldShowCondition("temporaryC2Document.c2AdditionalOrdersRequested CONTAINS \"PARENTAL_RESPONSIBILITY\"")
                    .eventLabel("Who's seeking parental responsibility?")
                    .mandatory(C2DocumentBundle::getHearingList)
                    .fieldShowCondition("temporaryC2Document.c2AdditionalOrdersRequested CONTAINS \"REQUESTING_ADJOURNMENT\"")
                    .eventLabel("Which hearing are you requesting to be adjourned?")
                    .mandatory(C2DocumentBundle::getRequestedHearingToAdjourn)
                    .fieldShowCondition("temporaryC2Document=\"DO NOT SHOW\"")
                    .eventLabel("Hearing requested to adjourn")
                    .optional(C2DocumentBundle::getUrgencyTimeFrameType)
                    .eventLabel("Please state how soon you want the judge to consider your application?")
                    .optional(C2DocumentBundle::getSupplementsBundle)
                    .eventLabel("Supplements")
                    .complex(C2DocumentBundle::getSupplementsBundle, Supplement.class)
                    .mandatory(Supplement::getName)
                    .eventLabel("Select supplement").done()
                    .complex(C2DocumentBundle::getSupplementsBundle, Supplement.class)
                    .mandatory(Supplement::getSecureAccommodationType)
                    .fieldShowCondition("temporaryC2Document.supplementsBundle.name=\"C20_SECURE_ACCOMMODATION\"")
                    .eventLabel("Which jurisdiction?").done()
                    .complex(C2DocumentBundle::getSupplementsBundle, Supplement.class)
                    .optional(Supplement::getNotes).done()
                    .complex(C2DocumentBundle::getSupplementsBundle, Supplement.class)
                    .mandatory(Supplement::getDocument)
                    .eventLabel("Upload document").done()
                    .complex(C2DocumentBundle::getSupplementsBundle, Supplement.class)
                    .mandatory(Supplement::getDocumentAcknowledge)
                    .eventLabel("Tick to confirm this document is related to this case").done()
                    .optional(C2DocumentBundle::getDraftOrdersBundle)
                    .eventLabel("Draft Orders")
                    .complex(C2DocumentBundle::getDraftOrdersBundle, DraftOrder.class)
                    .mandatory(DraftOrder::getTitle)
                    .eventLabel("File name").done()
                    .complex(C2DocumentBundle::getDraftOrdersBundle, DraftOrder.class)
                    .mandatory(DraftOrder::getDocument)
                    .eventLabel("Upload document").done()
                    .complex(C2DocumentBundle::getDraftOrdersBundle, DraftOrder.class)
                    .readonly(DraftOrder::getDocumentAcknowledgeLabel)
                    .fieldShowCondition("documentAcknowledge!=\"ACK_RELATED_TO_CASE\"")
                    .eventLabel("<br /><div class='govuk-warning-text'><span class='govuk-warning-text__icon' aria-hidden='true'>!</span><strong class='govuk-warning-text__text'>Check if this document is related to ${caseName}</strong></div><br>").done()
                    .complex(C2DocumentBundle::getDraftOrdersBundle, DraftOrder.class)
                    .readonly(DraftOrder::getDocumentAcknowledgeLabelForCYA)
                    .fieldShowCondition("documentAcknowledge=\"ACK_RELATED_TO_CASE\"")
                    .eventLabel("<br /><div class='govuk-warning-text'><span class='govuk-warning-text__icon' aria-hidden='true'>!</span><strong class='govuk-warning-text__text'>Check if this document is related to this case</strong></div><br>").done()
                    .complex(C2DocumentBundle::getDraftOrdersBundle, DraftOrder.class)
                    .mandatory(DraftOrder::getDocumentAcknowledge)
                    .eventLabel("Tick to confirm this document is related to this case").done()
                    .optional(C2DocumentBundle::getSupportingEvidenceBundle)
                    .eventLabel("Supporting Documents")
                    .complex(C2DocumentBundle::getSupportingEvidenceBundle, SupportingEvidenceBundle.class)
                    .mandatory(SupportingEvidenceBundle::getName)
                    .eventLabel("File name").done()
                    .complex(C2DocumentBundle::getSupportingEvidenceBundle, SupportingEvidenceBundle.class)
                    .optional(SupportingEvidenceBundle::getNotes).done()
                    .complex(C2DocumentBundle::getSupportingEvidenceBundle, SupportingEvidenceBundle.class)
                    .optional(SupportingEvidenceBundle::getDateTimeReceived)
                    .fieldShowCondition("temporaryC2Document=\"DO NOT SHOW\"").done()
                    .complex(C2DocumentBundle::getSupportingEvidenceBundle, SupportingEvidenceBundle.class)
                    .mandatory(SupportingEvidenceBundle::getDocument)
                    .eventLabel("Upload document").done()
                    .complex(C2DocumentBundle::getSupportingEvidenceBundle, SupportingEvidenceBundle.class)
                    .readonly(SupportingEvidenceBundle::getDocumentAcknowledgeLabel)
                    .fieldShowCondition("documentAcknowledge!=\"ACK_RELATED_TO_CASE\"")
                    .eventLabel("<br /><div class='govuk-warning-text'><span class='govuk-warning-text__icon' aria-hidden='true'>!</span><strong class='govuk-warning-text__text'>Check if this document is related to ${caseName}</strong></div><br>").done()
                    .complex(C2DocumentBundle::getSupportingEvidenceBundle, SupportingEvidenceBundle.class)
                    .readonly(SupportingEvidenceBundle::getDocumentAcknowledgeLabelForCYA)
                    .fieldShowCondition("documentAcknowledge=\"ACK_RELATED_TO_CASE\"")
                    .eventLabel("<br /><div class='govuk-warning-text'><span class='govuk-warning-text__icon' aria-hidden='true'>!</span><strong class='govuk-warning-text__text'>Check if this document is related to this case</strong></div><br>").done()
                    .complex(C2DocumentBundle::getSupportingEvidenceBundle, SupportingEvidenceBundle.class)
                    .mandatory(SupportingEvidenceBundle::getDocumentAcknowledge)
                    .eventLabel("Tick to confirm this document is related to this case").done().done();
        fields.readonly(CaseData::getSkipPaymentPage)
                    .fieldShowCondition("additionalApplicationType=\"DO_NOT_SHOW\"")
                    .publish(false);
    }
}
