package uk.gov.hmcts.reform.fpl.ccd.event.page;

import uk.gov.hmcts.ccd.sdk.api.Event;
import uk.gov.hmcts.ccd.sdk.api.FieldCollection;
import uk.gov.hmcts.reform.fpl.enums.State;
import uk.gov.hmcts.reform.fpl.model.CaseData;
import uk.gov.hmcts.reform.fpl.model.UserRole;
import uk.gov.hmcts.reform.fpl.model.event.UploadDraftOrdersData;

/**
 * Generated by ccd-definition-converter from CARE_SUPERVISION_EPO on migration; owned by this service team.
 *
 * <p>Wizard page {@code CMOChoice} of event {@code uploadCMO}.
 */
public final class UploadCMOCMOChoicePage {
    private UploadCMOCMOChoicePage() {
    }

    /**
     * Applies this page's fields to the event.
     *
     * @param fields the event's field-collection builder
     */
    public static void apply(
            FieldCollection.FieldCollectionBuilder<CaseData, State, Event.EventBuilder<CaseData, UserRole, State>> fields) {
        fields.page("CMOChoice");
        fields.showCondition("hearingOrderDraftKind CONTAINS \"CMO\"");
        fields.complex(CaseData::getUploadDraftOrdersEventData)
                    .readonlyNoSummary(UploadDraftOrdersData::getShowCMOsSentToJudge)
                    .fieldShowCondition("cmosSentToJudge = \"DO_NOT_SHOW\"")
                    .publish(false)
                    .readonlyNoSummary(UploadDraftOrdersData::getCmosSentToJudge)
                    .fieldShowCondition("showCMOsSentToJudge = \"YES\"")
                    .publish(false)
                    .mandatory(UploadDraftOrdersData::getCmoUploadType)
                    .publish(false)
                    .mandatory(UploadDraftOrdersData::getPastHearingsForCMO)
                    .fieldShowCondition("cmoUploadType=\"AGREED\"")
                    .publish(false)
                    .mandatory(UploadDraftOrdersData::getFutureHearingsForCMO)
                    .fieldShowCondition("cmoUploadType=\"DRAFT\"")
                    .publish(false).done();
    }
}
