version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: codeceptjs
    versions:
    - "> 2.6.8, < 2.7"
  - dependency-name: husky
    versions:
    - ">= 4.0.a, < 4.1"
  - dependency-name: husky
    versions:
    - ">= 4.1.a, < 4.2"
  - dependency-name: husky
    versions:
    - ">= 4.2.a, < 4.3"
  - dependency-name: husky
    versions:
    - ">= 5.a, < 6"
  - dependency-name: webdriverio
    versions:
    - 7.1.0
    - 7.2.0
    - 7.2.1
    - 7.2.2
    - 7.5.1
  - dependency-name: y18n
    versions:
    - 4.0.1
  - dependency-name: puppeteer
    versions:
    - 7.0.0
- package-ecosystem: docker
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
- package-ecosystem: gitsubmodule
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
- package-ecosystem: gradle
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: com.github.ben-manes.versions
    versions:
    - ">= 0.38.a, < 0.39"
  - dependency-name: com.launchdarkly:okhttp-eventsource
    versions:
    - ">= 2.0.a, < 2.1"
  - dependency-name: io.gatling:gatling-core
    versions:
    - "> 3.1.1, < 4"
  - dependency-name: io.gatling:gatling-core
    versions:
    - ">= 3.3.a, < 3.4"
  - dependency-name: io.gatling:gatling-http
    versions:
    - "> 3.1.1, < 4"
  - dependency-name: io.gatling:gatling-http
    versions:
    - ">= 3.3.a, < 3.4"
  - dependency-name: io.github.openfeign:feign-core
    versions:
    - "> 10.9, < 11"
  - dependency-name: io.github.openfeign:feign-core
    versions:
    - ">= 11.0.a, < 11.1"
  - dependency-name: io.github.openfeign:feign-core
    versions:
    - ">= 11.1.a, < 11.2"
  - dependency-name: net.serenity-bdd:serenity-gradle-plugin
    versions:
    - "> 2.3.13, < 2.4"
  - dependency-name: org.flywaydb:flyway-core
    versions:
    - ">= 7.0.a, < 7.1"
  - dependency-name: uk.gov.hmcts.reform:send-letter-client
    versions:
    - ">= 2.6.a, < 2.7"
  - dependency-name: org.springframework.cloud:spring-cloud-netflix-ribbon
    versions:
    - 2.2.8.RELEASE
  - dependency-name: org.flywaydb:flyway-core
    versions:
    - 7.7.3
    - 7.8.0
  - dependency-name: net.serenity-bdd:serenity-gradle-plugin
    versions:
    - 2.4.4
  - dependency-name: com.fasterxml.jackson.core:jackson-databind
    versions:
    - 2.12.2
    - 2.12.3
  - dependency-name: au.com.dius.pact
    versions:
    - 4.2.4
  - dependency-name: org.springframework.cloud:spring-cloud-starter-openfeign
    versions:
    - 3.0.2
  - dependency-name: org.owasp.dependencycheck
    versions:
    - 6.1.3
    - 6.1.4
  - dependency-name: com.google.guava:guava
    versions:
    - 30.1.1-jre
  - dependency-name: org.springframework.cloud:spring-cloud-dependencies
    versions:
    - 2020.0.2
