#!/bin/bash

(ccd-docker/bin/idam-create-caseworker.sh caseworker,caseworker-publiclaw,caseworker-publiclaw-localAuthority peter_la_portsmouth@yahoo.com password FR LocalAuthority)
(ccd-docker/bin/idam-create-caseworker.sh caseworker,caseworker-publiclaw,caseworker-publiclaw-localAuthority helen_la_hampshire@yahoo.com)
(ccd-docker/bin/idam-create-caseworker.sh caseworker,caseworker-publiclaw,caseworker-publiclaw-courtadmin craig_ca_court@yahoo.com)
(ccd-docker/bin/idam-create-caseworker.sh caseworker,caseworker-publiclaw,caseworker-publiclaw-cafcass claire_cg_guardian@yahoo.com)
(ccd-docker/bin/idam-create-caseworker.sh caseworker,caseworker-publiclaw,caseworker-publiclaw-localAuthority eric.la.cooper@gmail.com)
(ccd-docker/bin/idam-create-caseworker.sh caseworker,caseworker-publiclaw,caseworker-publiclaw-cafcass helen.gu.webster@gmail.com)
(ccd-docker/bin/idam-create-caseworker.sh caseworker,caseworker-publiclaw,caseworker-publiclaw-cafcass colin.ca.bradley@gmail.com)
(ccd-docker/bin/idam-create-caseworker.sh caseworker,caseworker-publiclaw,caseworker-test henry.so.grabit@gmail.com)
(ccd-docker/bin/idam-create-caseworker.sh caseworker,caseworker-publiclaw,caseworker-publiclaw-judiciary judge.ju.dread@gmail.com)
(ccd-docker/bin/idam-create-caseworker.sh caseworker,caseworker-publiclaw,caseworker-publiclaw Hayley.Foulkes@justice.gov.uk)
(ccd-docker/bin/idam-create-caseworker.sh caseworker,caseworker-publiclaw,caseworker-publiclaw Jason.llewelyn@justice.gov.uk)
(ccd-docker/bin/idam-create-caseworker.sh caseworker,caseworker-publiclaw,caseworker-publiclaw-localAuthority Lisa.Thomas@swansea.gov.uk)
(ccd-docker/bin/idam-create-caseworker.sh caseworker,caseworker-publiclaw,caseworker-publiclaw Laurie.taylor@justice.gov.uk)
(ccd-docker/bin/idam-create-caseworker.sh caseworker,caseworker-publiclaw,caseworker-publiclaw-localAuthority Richard.Hooper@swansea.gov.uk)
(ccd-docker/bin/idam-create-caseworker.sh caseworker,caseworker-publiclaw,caseworker-publiclaw-localAuthority Kate.Edwards@swansea.gov.uk)
(ccd-docker/bin/ccd-add-role.sh caseworker-test)
(ccd-docker/bin/ccd-add-role.sh caseworker-publiclaw-localAuthority)
(ccd-docker/bin/ccd-add-role.sh caseworker-publiclaw-cafcass)
(ccd-docker/bin/ccd-add-role.sh caseworker-publiclaw)
(ccd-docker/bin/ccd-add-role.sh caseworker-publiclaw-judiciary)
(ccd-docker/bin/ccd-add-role.sh caseworker-publiclaw-courtadmin)
