package uk.gov.hmcts.reform.fpl.enums;

public enum C2AdditionalOrdersRequested {
    CHANGE_SURNAME_OR_REMOVE_JURISDICTION, APPOINTMENT_OF_GUARDIAN, TERMINATION_OF_APPOINTMENT_OF_GUARDIAN,
    PARENTAL_RESPONSIBILITY
}
