package uk.gov.hmcts.reform.fpl.enums;

public enum OtherApplicationType {
    C1_CHANGE_SURNAME_OR_REMOVE_FROM_JURISDICTION,
    C1_APPOINTMENT_OF_A_GUARDIAN,
    C1_TERMINATION_OF_APPOINTMENT_OF_A_GUARDIAN,
    C1_PARENTAL_RESPONSIBILITY,
    C1_WITH_SUPPLEMENT,
    C3_SEARCH_TAKE_CHARGE_AND_DELIVERY_OF_A_CHILD,
    C4_WHEREABOUTS_OF_A_MISSING_CHILD,
    C12_WARRANT_TO_ASSIST_PERSON,
    C17_EDUCATION_SUPERVISION_ORDER,
    C17A_EXTENSION_OF_ESO,
    C19_WARRANT_TO_ASSISTANCE,
    C100_CHILD_ARRANGEMENTS,
    C63_DECLARATION_OF_PARENTAGE
}
