apiVersion: v1
kind: ConfigMap
metadata:
  name: prd-mappings
data:
  mockUser1.json: |
    {
      "request": {
        "method": "GET",
        "urlPath": "/refdata/external/v1/organisations/users",
        "queryParameters": {
          "email": {
            "equalTo": "{{ .Values.users[0].email }}"
          }
        }
      },
      "response": {
        "status": 200,
        "headers": {
          "Content-Type": "application/json"
        },
        "body": "{ \"userIdentifier\": \"{{ .Values.users[0].identifier }}\"}"
      }
    }
  mockUser2.json: |
    {
      "request": {
        "method": "GET",
        "urlPath": "/refdata/external/v1/organisations/users",
        "queryParameters": {
          "email": {
            "equalTo": "{{ .Values.users[1].email }}"
          }
        }
      },
      "response": {
        "status": 200,
        "headers": {
          "Content-Type": "application/json"
        },
        "body": "{ \"userIdentifier\": \"{{ .Values.users[1].identifier }}\"}"
      }
    }
  passThrough.json: |
    {
        "request": {
            "urlPattern": "/refdata/external/.*"
        },
        "response": {
            "proxyBaseUrl" : {{ .Values.prd.url }}
        }
    }
