/*global process*/

module.exports = {
  localAuthorityEmail: 'local-authority@example.com',
  localAuthorityPassword: process.env.LA_USER_PASSWORD || 'Password12',
  hmctsAdminEmail: 'hmcts-admin@example.com',
  hmctsAdminPassword: process.env.CA_USER_PASSWORD || 'Password12',
  eventSummary: '',
  eventDescription: '',
  applicationActions: {
    selectOrders: 'Orders and directions needed',
    selectHearing: 'Hearing needed',
    enterChildren: 'Children',
    enterRespondents: 'Respondents',
    enterApplicants: 'Applicant',
    enterOthers: 'Others to be given notice',
    enterGrounds: 'Grounds for the application',
    enterRisk: 'Risk and harm to children',
    enterFactorsAffectingParenting: 'Factors affecting parenting',
    enterInternationalElement: 'International element',
    enterOtherProceedings: 'Other proceedings',
    enterAllocationProposal: 'Allocation proposal',
    attendingHearing: 'Attending the hearing',
    uploadDocuments: 'Documents',
    submitCase: 'Submit application',
  },
  addFamilyManCaseNumber: 'Add case number',
  testFile: './e2e/fixtures/mockFile.txt',
  presidentsGuidanceUrl: 'https://www.judiciary.uk/wp-content/uploads/2013/03/President%E2%80%99s-Guidance-on-Allocation-and-Gatekeeping.pdf',
  scheduleUrl: 'https://www.judiciary.uk/wp-content/uploads/2013/03/Schedule-to-the-President%E2%80%99s-Guidance-on-Allocation-and-Gatekeeping.pdf',
  otherProposalUrl: '/otherProposal/otherProposal1',
};
