const defaultPassword = 'Password12';
const e2ePw = process.env.E2E_TEST_PASSWORD;

module.exports = {
  newSwanseaLocalAuthorityUserOne: {
    email: 'local-authority-swansea-0001@maildrop.cc',

    password:  e2ePw,
    forename: 'Local',
    surname: 'Authority',
  },

  swanseaLocalAuthorityUserOne: {
    email: 'kurt@swansea.gov.uk',
    password: process.env.LA_USER_PASSWORD || defaultPassword,
    forename: 'kurt@swansea.gov.uk',
    surname: '(local-authority)',
  },
  newSwanseaLocalAuthorityUserTwo: {
    email: 'Local-Authority-Swansea-0002@AAT.com',
    password:  e2ePw,
  },
  swanseaLocalAuthorityUserTwo: {
    email: 'damian@swansea.gov.uk',
    password: process.env.LA_USER_PASSWORD || defaultPassword,
    forename: 'damian@swansea.gov.uk',
    surname: '(local-authority)',
  },
  newHillingdonLocalAuthorityUserOne: {
    email: 'Local-Authority-Hillingdon-0001@AAT.com',
    password:  e2ePw,
  },
  hillingdonLocalAuthorityUserOne: {
    email: 'sam@hillingdon.gov.uk',
    password: process.env.LA_USER_PASSWORD || defaultPassword,
    forename: 'sam@hillingdon.gov.uk',
    surname: '(local-authority)',
  },
  hillingdonLocalAuthorityUserTwo: {
    email: 'siva@hillingdon.gov.uk',
    password: process.env.LA_USER_PASSWORD || defaultPassword,
    forename: 'siva@hillingdon.gov.uk',
    surname: '(local-authority)',
  },
  wiltshireLocalAuthorityUserOne: {
    email: 'raghu@wiltshire.gov.uk',
    password: process.env.LA_USER_PASSWORD || defaultPassword,
    forename: 'raghu@wiltshire.gov.uk',
    surname: '(local-authority)',
  },
  wiltshireLocalAuthorityUserTwo: {
    email: 'sam@wiltshire.gov.uk',
    password: process.env.LA_USER_PASSWORD || defaultPassword,
    forename: 'sam@wiltshire.gov.uk',
    surname: '(local-authority)',
  },
  localAuthorityBarristerUserOne: {
    email: 'la-barrister@mailnesia.com',
    password: process.env.LA_BARRISTER_USER_PASSWORD || defaultPassword,
    forename: 'la-barrister@mailnesia.com',
    surname: '(local-authority-barrister)',
  },
  hmctsAdminUser: {
    email: 'fpl-ctsc-admin@justice.gov.uk',
    password: process.env.CA_USER_PASSWORD || defaultPassword,
  },
  hmctsSuperUser: {
    email: 'fpl-ctsc-team-leader@justice.gov.uk',
    password: process.env.SUPER_USER_PASSWORD || defaultPassword,
  },
  cafcassUser: {
    email: 'cafcass@example.com',
    password: process.env.CAFCASS_USER_PASSWORD || defaultPassword,
  },
  gateKeeperUser: {
    email: 'gatekeeper-only@mailnesia.com',
    password: process.env.GATEKEEPER_USER_PASSWORD || defaultPassword,
  },
  judicaryUser: {
    email: 'judiciary-only@mailnesia.com',
    password: process.env.JUDICIARY_USER_PASSWORD || defaultPassword,
  },
  magistrateUser: {
    email: 'magistrate@mailnesia.com',
    password: process.env.MAGISTRATE_USER_PASSWORD || defaultPassword,
  },
  systemUpdateUser: {
    email: process.env.SYSTEM_UPDATE_USER_USERNAME || 'fpl-system-update@mailnesia.com',
    password: process.env.SYSTEM_UPDATE_USER_PASSWORD || defaultPassword,
  },
  smokeTestUser: {
    email: process.env.SMOKE_TEST_LA_USER_USERNAME || 'james@swansea.gov.uk',
    password: process.env.SMOKE_TEST_LA_USER_PASSWORD || defaultPassword,
  },
  hmctsUser: {
    email: process.env.HMCTS_USER_USERNAME || 'kurt@swansea.gov.uk',
    password: process.env.HMCTS_USER_PASSWORD || defaultPassword,
  },
  privateSolicitorOne: {
    email: 'solicitor1@solicitors.uk',
    password: process.env.LA_USER_PASSWORD || defaultPassword,
  },
  privateSolicitorTwo: {
    email: 'solicitor2@solicitors.uk',
    password: process.env.LA_USER_PASSWORD || defaultPassword,
  },
  localAuthorityPassword: process.env.LA_USER_PASSWORD || defaultPassword,
  baseUrl: process.env.URL || 'https://manage-case.aat.platform.hmcts.net',
  fplServiceUrl: process.env.CASE_SERVICE_URL || 'http://fpl-case-service-aat.service.core-compute-aat.internal',
  idamApiUrl: 'https://idam-api.aat.platform.hmcts.net',
  swanseaOrgId: process.env.SWANSEA_ORG_ID || 'ORGSA',
  mockedPayment: (process.env.MOCKED_PAYMENTS || 'true').toLowerCase() === 'true',
  ctscEmail: process.env.CTSC_EMAIL || 'FamilyPublicLaw+ctsc@gmail.com',
  TestOutputDir: process.env.E2E_OUTPUT_DIR || './output',
  TestForAccessibility: process.env.TESTS_FOR_ACCESSIBILITY === 'true',
  definition: {
    jurisdiction: 'PUBLICLAW',
    jurisdictionFullDesc: 'Public Law',
    caseType: 'CARE_SUPERVISION_EPO',
    caseTypeFullDesc: 'Public Law Applications',
  },
  // actions
  applicationActions: {
    enterOrdersAndDirectionsNeeded: 'Orders and directions sought',
    enterHearingNeeded: 'Hearing urgency',
    enterChildren: 'Child\'s details',
    enterRespondents: 'Respondents\' details',
    enterApplicant: 'Applicant\'s details',
    enterLocalAuthority: 'Local authority\'s details',
    enterOthers: 'Other people in the case',
    enterGrounds: 'Grounds for the application',
    enterRiskAndHarmToChildren: 'Risk and harm to children',
    enterFactorsAffectingParenting: 'Factors affecting parenting',
    enterInternationalElement: 'International element',
    enterOtherProceedings: 'Other proceedings',
    enterAllocationProposal: 'Allocation proposal',
    enterAllocationDecision: 'Judicial Gatekeeping',
    enterAttendingHearing: 'Court services',
    uploadDocuments: 'Upload documents',
    changeCaseName: 'Change draft case name',
    submitCase: 'Submit application',
    deleteApplication: 'Delete an application',
    uploadCMO: 'Upload draft orders',
    approveOrders: 'Approve orders',
    allocatedJudge: 'Allocated Judge',
    extend26WeekTimeline: 'Extend 26-week timeline',
    manageLegalRepresentatives: 'Add counsel/external solicitor',
    addApplicationDocuments: 'Application documents',
    manageDocumentsLA: 'Manage documents',
    messageJudge: 'Send messages',
    replyMessage: 'Reply to messages',
    removeManagingOrganisation: 'Remove managing organisation',
    languageRequirement: 'Welsh language requirements',
    selectCourt: 'Select court to issue',
    addOrRemoveLegalCounsel: 'Add or remove legal counsel',
  },
  administrationActions: {
    addCaseFlag: 'Add case flag',
    addFamilyManCaseNumber: 'Add case number',
    changeCaseName: 'Change draft case name',
    sendToGatekeeper: 'Send to gatekeeper',
    notifyGatekeeper: 'Notify gatekeeper',
    amendChildren: 'Children',
    amendRespondents: 'Respondents',
    amendOther: 'Others to be given notice',
    amendInternationalElement: 'International element',
    amendOtherProceedings: 'Other proceedings',
    amendAttendingHearing: 'Attending the hearing',
    amendRepresentatives: 'Manage representatives',
    manageHearings: 'Manage hearings',
    createNoticeOfProceedings: 'Create notice of proceedings',
    addStatementOfService: 'Add statement of service (c9)',
    uploadC2Documents: 'Upload a C2',
    addGatekeepingOrder: 'Judicial Gatekeeping',
    createOrder: 'Create or upload an order',
    placement: 'Placement',
    placementHearing: 'Notice of Placement - Hearing',
    handleSupplementaryEvidence: 'Handle supplementary evidence',
    bulkScan: 'Attach scanned docs',
    addNote: 'Add a case note',
    addExpertReportLog: 'Log expert report',
    recordFinalDecisions: 'Record final decisions',
    returnApplication: 'Return application',
    manageDocuments: 'Manage documents',
    uploadAdditionalApplications: 'Upload additional applications',
    manageOrders: 'Manage orders',
    uploadWelshTranslations: 'Upload translated documents',
    languageRequirement: 'Welsh language requirements',
    manageLocalAuthorities: 'Manage LAs / Transfer to court',
  },
  superUserActions: {
    removeOrdersAndApplications: 'Removal Tool',
    changeCaseState: 'Change case state',
  },
  internalActions: {
    updateCase: 'internal-change-UPDATE_CASE',
  },
  // files
  testFile: './e2e/fixtures/testFiles/mockFile.txt',
  testFile2: './e2e/fixtures/testFiles/mockFile2.txt',
  testFile3: './e2e/fixtures/testFiles/mockFile3.txt',
  testFile4: './e2e/fixtures/testFiles/mockFile4.txt',
  testFile5: './e2e/fixtures/testFiles/mockFile5.txt',
  testFile6: './e2e/fixtures/testFiles/mockFile6.txt',
  testFile7: './e2e/fixtures/testFiles/mockFile7.txt',
  testFile8: './e2e/fixtures/testFiles/mockFile8.txt',
  testFile9: './e2e/fixtures/testFiles/mockFile9.txt',
  testFile10: './e2e/fixtures/testFiles/mockFile10.txt',
  testFile11: './e2e/fixtures/testFiles/mockFile11.txt',
  testFile12: './e2e/fixtures/testFiles/mockFile12.txt',
  testFile13: './e2e/fixtures/testFiles/mockFile13.txt',
  testFile14: './e2e/fixtures/testFiles/mockFile14.txt',
  testFile15: './e2e/fixtures/testFiles/mockFile15.txt',
  testFile16: './e2e/fixtures/testFiles/mockFile16.txt',
  testPdfFile: './e2e/fixtures/testFiles/mockFile.pdf',
  testWordFile: './e2e/fixtures/testFiles/mockFile.docx',
  testWordFileSdo: './e2e/fixtures/testFiles/sdo.docx',
  testPdfFileUho: './e2e/fixtures/testFiles/uho.pdf',
  // urls
  presidentsGuidanceUrl: 'https://www.judiciary.uk/wp-content/uploads/2013/03/President%E2%80%99s-Guidance-on-Allocation-and-Gatekeeping.pdf',
  scheduleUrl: 'https://www.judiciary.uk/wp-content/uploads/2013/03/Schedule-to-the-President%E2%80%99s-Guidance-on-Allocation-and-Gatekeeping.pdf',
  otherProposalUrl: '/otherProposal/otherProposal1',
};
