package uk.gov.hmcts.reform.fpl.model;

import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;
import uk.gov.hmcts.ccd.sdk.api.CCD;
import uk.gov.hmcts.ccd.sdk.api.ComplexType;
import uk.gov.hmcts.ccd.sdk.type.FieldType;

/**
 * Generated by ccd-definition-converter from CARE_SUPERVISION_EPO on migration; owned by this service team.
 */
@Data
@Builder
@NoArgsConstructor
@AllArgsConstructor
@ComplexType(
        generate = true
)
public class AllocationProposal {
    @CCD(
            label = "Which level of judge do you recommend for this case?",
            showCondition = "proposalV2!=\"*\""
    )
    private AllocationProposalList proposal;

    @CCD(
            label = "Which level of judge do you recommend for this case?"
    )
    private AllocationProposalListV2 proposalV2;

    @CCD(
            label = " ",
            typeOverride = FieldType.Label
    )
    private String reasonLabel1;

    @CCD(
            label = "Reasons for recommendation",
            typeOverride = FieldType.TextArea
    )
    private String proposalReason;
}
