package uk.gov.hmcts.reform.fpl.model;

import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;
import uk.gov.hmcts.ccd.sdk.api.CCD;
import uk.gov.hmcts.ccd.sdk.api.ComplexType;
import uk.gov.hmcts.ccd.sdk.type.FieldType;
import uk.gov.hmcts.ccd.sdk.type.YesOrNo;

/**
 * Generated by ccd-definition-converter from CARE_SUPERVISION_EPO on migration; owned by this service team.
 */
@Data
@Builder
@NoArgsConstructor
@AllArgsConstructor
@ComplexType(
        generate = true
)
public class AllocationDecision {
    @CCD(
            label = "The proposed allocation is ${allocationProposal.proposalV2}.",
            showCondition = "allocationProposalPresent=\"DO_NOT_SHOW\"",
            typeOverride = FieldType.Label
    )
    private String allocationDecision_Label;

    @CCD(
            label = "${allocationProposal.proposalReason}",
            showCondition = "allocationProposalPresent=\"DO_NOT_SHOW\"",
            typeOverride = FieldType.Label
    )
    private String allocationDecision_LabelReason;

    @CCD(
            label = "The local authority has not made an allocation proposal.",
            showCondition = "allocationProposalPresent=\"DO_NOT_SHOW\"",
            typeOverride = FieldType.Label
    )
    private String missingAllocationDecision_Label;

    @CCD(
            label = "Is this the right level of judge?",
            showCondition = "allocationProposalPresent=\"DO_NOT_SHOW\""
    )
    private YesOrNo judgeLevelRadio;

    @CCD(
            label = "Which level of judge is needed for this case?"
    )
    private AllocationProposalList proposal;

    @CCD(
            label = "Which level of judge is needed for this case?"
    )
    private AllocationProposalListV2 proposalV2;

    @CCD(
            label = "Give reason",
            typeOverride = FieldType.TextArea
    )
    private String proposalReason;

    @CCD(
            label = "Is allocation proposal present?",
            showCondition = "allocationProposalPresent=\"DO_NOT_SHOW\""
    )
    private YesOrNo allocationProposalPresent;
}
