package uk.gov.hmcts.reform.fpl.model;

import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;
import uk.gov.hmcts.ccd.sdk.api.CCD;
import uk.gov.hmcts.ccd.sdk.api.ComplexType;
import uk.gov.hmcts.ccd.sdk.type.FieldType;
import uk.gov.hmcts.ccd.sdk.type.YesOrNo;

/**
 * Generated by ccd-definition-converter from CARE_SUPERVISION_EPO on migration; owned by this service team.
 */
@Data
@Builder
@NoArgsConstructor
@AllArgsConstructor
@ComplexType(
        generate = true
)
public class ApplicantContactOther {
    @CCD(
            label = "First name"
    )
    private String firstName;

    @CCD(
            label = "Last name"
    )
    private String lastName;

    @CCD(
            label = "Email address",
            typeOverride = FieldType.Email
    )
    private String email;

    @CCD(
            label = "Role"
    )
    private ApplicantContactRoleFixedList role;

    @CCD(
            label = "Enter their role",
            showCondition = "role=\"OTHER\""
    )
    private String title;

    @CCD(
            label = "Main contact",
            showCondition = "role=\"DO_NOT_SHOW\""
    )
    private YesOrNo mainContact;
}
