package uk.gov.hmcts.reform.fpl.model;

import com.fasterxml.jackson.annotation.JsonValue;
import lombok.AllArgsConstructor;
import lombok.Getter;
import uk.gov.hmcts.ccd.sdk.api.ComplexType;
import uk.gov.hmcts.ccd.sdk.api.HasLabel;

/**
 * Generated by ccd-definition-converter from CARE_SUPERVISION_EPO on migration; owned by this service team.
 */
@ComplexType(
        name = "attachedToFollowOption",
        generate = true
)
@Getter
@AllArgsConstructor
public enum AttachedToFollowOption implements HasLabel {
    ATTACHED("Attached", "Attached"),

    INCLUDED_IN_SOCIAL_WORK_EVIDENCE_TEMPLATE_SWET("Included in social work evidence template (SWET)", "Included in social work evidence template (SWET)"),

    TO_FOLLOW("To follow", "To follow");

    private final String label;

    @JsonValue
    private final String code;
}
