package uk.gov.hmcts.reform.fpl.model;

import lombok.Getter;
import lombok.RequiredArgsConstructor;
import uk.gov.hmcts.ccd.sdk.api.HasLabel;

/**
 * Generated by ccd-definition-converter from CARE_SUPERVISION_EPO on migration; owned by this service team.
 */
@RequiredArgsConstructor
@Getter
public enum C36SupervisionOrderType implements HasLabel {
    VARIATION_OF_SUPERVISION_ORDER("Variation of supervision order"),

    EXTENSION_OF_SUPERVISION_ORDER("Extension of supervision order");

    private final String label;
}
