package uk.gov.hmcts.reform.fpl.model;

import lombok.Getter;
import lombok.RequiredArgsConstructor;
import uk.gov.hmcts.ccd.sdk.api.HasLabel;

/**
 * Generated by ccd-definition-converter from CARE_SUPERVISION_EPO on migration; owned by this service team.
 */
@RequiredArgsConstructor
@Getter
public enum CafcassWalesOffices implements HasLabel {
    ABERYSTWYTH("Aberystwyth"),

    CAERNARFON("Caernarfon"),

    CARDIFF("Cardiff"),

    CARMARTHEN("Carmarthen"),

    LLANDRINDOD_WELLS("Llandrindod Wells"),

    LLANDUDNO_JUNCTION("Llandudno Junction"),

    MERTHYR_TYDFIL("Merthyr Tydfil"),

    NEWPORT("Newport"),

    NEWTON("Newton"),

    SWANSEA("Swansea"),

    WREXHAM("Wrexham");

    private final String label;
}
