package uk.gov.hmcts.reform.fpl.model;
import uk.gov.hmcts.reform.fpl.enums.CMOStatus;

import java.util.List;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;
import uk.gov.hmcts.ccd.sdk.api.CCD;
import uk.gov.hmcts.ccd.sdk.api.ComplexType;
import uk.gov.hmcts.ccd.sdk.type.Document;
import uk.gov.hmcts.ccd.sdk.type.ListValue;

/**
 * Generated by ccd-definition-converter from CARE_SUPERVISION_EPO on migration; owned by this service team.
 */
@Data
@Builder
@NoArgsConstructor
@AllArgsConstructor
@ComplexType(
        generate = true
)
public class CaseManagementOrder {
    @CCD(
            label = "Order actions"
    )
    private OrderAction action;

    @CCD(
            label = "File"
    )
    private Document orderDoc;

    @CCD(
            label = "Date of issue"
    )
    private String dateOfIssue;

    @CCD(
            label = "Which hearing is this order for?"
    )
    private String hearingDate;

    @CCD(
            label = "id",
            showCondition = "hearingDate=\"DO_NOT_SHOW\""
    )
    private String id;

    @CCD(
            label = "Directions"
    )
    private List<ListValue<Direction>> directions;

    @CCD(
            label = "Schedule"
    )
    private Schedule schedule;

    @CCD(
            label = "Recitals"
    )
    private List<ListValue<Recitals>> recitals;

    @CCD(
            label = "Is this ready to be sent to the judge?"
    )
    private CMOStatus status;

    @CCD(
            label = "Next Hearing"
    )
    private NextHearing nextHearing;
}
