package uk.gov.hmcts.reform.fpl.model;

import com.fasterxml.jackson.annotation.JsonValue;
import lombok.AllArgsConstructor;
import lombok.Getter;
import uk.gov.hmcts.ccd.sdk.api.HasLabel;

/**
 * Generated by ccd-definition-converter from CARE_SUPERVISION_EPO on migration; owned by this service team.
 */
@Getter
@AllArgsConstructor
public enum CaseExtensionTimeList implements HasLabel {
    EIGHT_WEEK_EXTENSION("Extend by 8 Weeks", "EightWeekExtension"),

    OTHER_EXTENSION("Enter a different date", "OtherExtension");

    private final String label;

    @JsonValue
    private final String code;
}
