package uk.gov.hmcts.reform.fpl.model;

import lombok.Getter;
import lombok.RequiredArgsConstructor;
import uk.gov.hmcts.ccd.sdk.api.HasLabel;

/**
 * Generated by ccd-definition-converter from CARE_SUPERVISION_EPO on migration; owned by this service team.
 */
@RequiredArgsConstructor
@Getter
public enum CMOActionType implements HasLabel {
    SEND_TO_ALL_PARTIES("Yes, send this to all parties"),

    JUDGE_REQUESTED_CHANGE("No, the applicant needs to make changes"),

    SELF_REVIEW("No, I need to make changes");

    private final String label;
}
