package uk.gov.hmcts.reform.fpl.model;

import lombok.Getter;
import lombok.RequiredArgsConstructor;
import uk.gov.hmcts.ccd.sdk.api.HasLabel;

/**
 * Generated by ccd-definition-converter from CARE_SUPERVISION_EPO on migration; owned by this service team.
 */
@RequiredArgsConstructor
@Getter
public enum CMONextHearingType implements HasLabel {
    FURTHER_CASE_MGMT_HEARING("Further case management hearing"),

    ISSUES_RESOLUTION_HEARING("Issues resolution hearing"),

    FINAL_HEARING("Final hearing");

    private final String label;
}
