package uk.gov.hmcts.reform.fpl.model;

import com.fasterxml.jackson.annotation.JsonValue;
import lombok.AllArgsConstructor;
import lombok.Getter;
import uk.gov.hmcts.ccd.sdk.api.HasLabel;

/**
 * Generated by ccd-definition-converter from CARE_SUPERVISION_EPO on migration; owned by this service team.
 */
@Getter
@AllArgsConstructor
public enum ConfirmPR implements HasLabel {
    CONFIRM("I confirm that each person added as a respondent has parental responsibility for one or more children in the application. Any person in the case who does not have parental responsibility will be added to 'Other people in the case'.", "confirm");

    private final String label;

    @JsonValue
    private final String code;
}
