package uk.gov.hmcts.reform.fpl.model;

import lombok.Getter;
import lombok.RequiredArgsConstructor;
import uk.gov.hmcts.ccd.sdk.api.HasLabel;

/**
 * Generated by ccd-definition-converter from CARE_SUPERVISION_EPO on migration; owned by this service team.
 */
@RequiredArgsConstructor
@Getter
public enum DirectionTypesForAllParties implements HasLabel {
    REQUEST_PERMISSION_FOR_EXPERT_EVIDENCE("Request permission for expert evidence"),

    REQUEST_HELP_TO_TAKE_PART_IN_PROCEEDINGS("Request help to take part in proceedings"),

    ASK_FOR_DISCLOSURE("Ask for disclosure"),

    ATTEND_HEARING("Attend the pre-hearing and hearing"),

    CONTACT_ALTERNATIVE_CARERS("Contact alternative carers");

    private final String label;
}
