package uk.gov.hmcts.reform.fpl.model;

import lombok.Getter;
import lombok.RequiredArgsConstructor;
import uk.gov.hmcts.ccd.sdk.api.HasLabel;

/**
 * Generated by ccd-definition-converter from CARE_SUPERVISION_EPO on migration; owned by this service team.
 */
@RequiredArgsConstructor
@Getter
public enum DirectionTypesForCafcass implements HasLabel {
    APPOINT_CHILDREN_GUARDIAN("Appoint a children's guardian"),

    ARRANGE_ADVOCATES_MEETING("Arrange an advocates' meeting"),

    SEND_GUARDIANS_ANALYSIS("Send the guardian's analysis to all parties");

    private final String label;
}
