package uk.gov.hmcts.reform.fpl.model;

import lombok.Getter;
import lombok.RequiredArgsConstructor;
import uk.gov.hmcts.ccd.sdk.api.HasLabel;

/**
 * Generated by ccd-definition-converter from CARE_SUPERVISION_EPO on migration; owned by this service team.
 */
@RequiredArgsConstructor
@Getter
public enum DraftOrderType implements HasLabel {
    AGREED_CMO("Agreed CMO discussed at hearing"),

    DRAFT_CMO("Draft CMO from advocates' meeting"),

    C21("Draft order");

    private final String label;
}
