package uk.gov.hmcts.reform.fpl.model;
import uk.gov.hmcts.reform.fpl.enums.DirectionDueDateType;

import java.time.LocalDateTime;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;
import uk.gov.hmcts.ccd.sdk.api.CCD;
import uk.gov.hmcts.ccd.sdk.api.ComplexType;
import uk.gov.hmcts.ccd.sdk.type.FieldType;

/**
 * Generated by ccd-definition-converter from CARE_SUPERVISION_EPO on migration; owned by this service team.
 */
@Data
@Builder
@NoArgsConstructor
@AllArgsConstructor
@ComplexType(
        generate = true
)
public class EditableStandardDirection {
    @CCD(
            label = "Type",
            hint = "You must include a brief direction summary",
            showCondition = "dueDateType = \"DO NOT SHOW\""
    )
    private String title;

    @CCD(
            label = "Description",
            typeOverride = FieldType.TextArea
    )
    private String description;

    @CCD(
            label = "Type",
            showCondition = "dueDateType = \"DO NOT SHOW\""
    )
    private String type;

    @CCD(
            label = "Type",
            hint = "You must include a brief direction summary",
            showCondition = "dueDateType = \"DO NOT SHOW\""
    )
    private String assignee;

    @CCD(
            label = "Due date"
    )
    private DirectionDueDateType dueDateType;

    @CCD(
            label = "Date and time",
            hint = "Use 24h format",
            showCondition = "dueDateType=\"DATE\""
    )
    private LocalDateTime dateToBeCompletedBy;

    @CCD(
            label = "Number of days",
            showCondition = "dueDateType=\"DAYS\"",
            min = 0,
            max = 365
    )
    private Integer daysBeforeHearing;
}
