package uk.gov.hmcts.reform.fpl.model;

/**
 * Generated by ccd-definition-converter — do not edit by hand.
 *
 * <p>Runtime environment-flag checks used to guard overlay event registrations.
 */
public final class EnvironmentFlags {
    /**
     * Utility class — do not instantiate.
     */
    private EnvironmentFlags() {
    }

    /**
     * Evaluates a named environment predicate.
     *
     * @param name the system-property or environment-variable name to check
     * @param expected the value required for the predicate to hold
     * @return {@code true} when the resolved value equals {@code expected}, case-insensitively
     */
    public static boolean flag(String name, String expected) {
        String value = System.getProperty(name, System.getenv().getOrDefault(name, ""));
        return expected.equalsIgnoreCase(value);
    }
}
