package uk.gov.hmcts.reform.fpl.model;

import lombok.Getter;
import lombok.RequiredArgsConstructor;
import uk.gov.hmcts.ccd.sdk.api.HasLabel;

/**
 * Generated by ccd-definition-converter from CARE_SUPERVISION_EPO on migration; owned by this service team.
 */
@RequiredArgsConstructor
@Getter
public enum EPOExclusionRequirementTypes implements HasLabel {
    NO_TO_EXCLUSION("No"),

    STARTING_ON_SAME_DATE("Yes, starting on the date on the order"),

    STARTING_ON_DIFFERENT_DATE("Yes, starting on a different date");

    private final String label;
}
