package uk.gov.hmcts.reform.fpl.model;

import lombok.Getter;
import lombok.RequiredArgsConstructor;
import uk.gov.hmcts.ccd.sdk.api.HasLabel;

/**
 * Generated by ccd-definition-converter from CARE_SUPERVISION_EPO on migration; owned by this service team.
 */
@RequiredArgsConstructor
@Getter
public enum EPOReasons implements HasLabel {
    URGENT_ACCESS_TO_CHILD_IS_OBSTRUCTED("You're making enquiries and need urgent access to the child to find out about their welfare, and access is being unreasonably refused"),

    HARM_IF_KEPT_IN_CURRENT_ACCOMMODATION("There's reasonable cause to believe the child is likely to suffer significant harm if they don't stay in their current accommodation"),

    HARM_IF_NOT_MOVED_TO_NEW_ACCOMMODATION("There's reasonable cause to believe the child is likely to suffer significant harm if they're not moved to accommodation provided by you, or on your behalf");

    private final String label;
}
