package uk.gov.hmcts.reform.fpl.model;

import com.fasterxml.jackson.annotation.JsonValue;
import lombok.AllArgsConstructor;
import lombok.Getter;
import uk.gov.hmcts.ccd.sdk.api.HasLabel;

/**
 * Generated by ccd-definition-converter from CARE_SUPERVISION_EPO on migration; owned by this service team.
 */
@Getter
@AllArgsConstructor
public enum EssexAndSuffolkDFJCourts implements HasLabel {
    _167("Chelmsford", "167");

    private final String label;

    @JsonValue
    private final String code;
}
