package uk.gov.hmcts.reform.fpl.model;

import lombok.Getter;
import lombok.RequiredArgsConstructor;
import uk.gov.hmcts.ccd.sdk.api.HasLabel;

/**
 * Generated by ccd-definition-converter from CARE_SUPERVISION_EPO on migration; owned by this service team.
 */
@RequiredArgsConstructor
@Getter
public enum FactorsAffectingParentingList implements HasLabel {
    ALCOHOL_DRUG_ABUSE("Alcohol or drug abuse"),

    DOMESTIC_ABUSE("Domestic abuse"),

    ANYTHING_ELSE("Anything else");

    private final String label;
}
