package uk.gov.hmcts.reform.fpl.model;

import lombok.Getter;
import lombok.RequiredArgsConstructor;
import uk.gov.hmcts.ccd.sdk.api.HasLabel;

/**
 * Generated by ccd-definition-converter from CARE_SUPERVISION_EPO on migration; owned by this service team.
 */
@RequiredArgsConstructor
@Getter
public enum GatekeepingOrderRoutes implements HasLabel {
    SERVICE("Create the gatekeeping order"),

    UPLOAD("Upload a prepared gatekeeping order");

    private final String label;
}
