package uk.gov.hmcts.reform.fpl.model;

import com.fasterxml.jackson.annotation.JsonValue;
import lombok.AllArgsConstructor;
import lombok.Getter;
import uk.gov.hmcts.ccd.sdk.api.HasLabel;

/**
 * Generated by ccd-definition-converter from CARE_SUPERVISION_EPO on migration; owned by this service team.
 */
@Getter
@AllArgsConstructor
public enum GroundsList implements HasLabel {
    BEYOND_CONTROL("Child is beyond parental control", "beyondControl"),

    NO_CARE("The care given to the child not being what it would be reasonable to expect a parent to give", "noCare");

    private final String label;

    @JsonValue
    private final String code;
}
