package uk.gov.hmcts.reform.fpl.model;

import com.fasterxml.jackson.annotation.JsonValue;
import lombok.AllArgsConstructor;
import lombok.Getter;
import uk.gov.hmcts.ccd.sdk.api.HasLabel;

/**
 * Generated by ccd-definition-converter from CARE_SUPERVISION_EPO on migration; owned by this service team.
 */
@Getter
@AllArgsConstructor
public enum HearingTypeFixedList implements HasLabel {
    STANDARD_CASE_MANAGEMENT_HEARING("Standard case management hearing", "Standard case management hearing"),

    URGENT_PRELIMINARY_CASE_MANAGEMENT_HEARI("Urgent preliminary case management hearing", "Urgent preliminary case management heari"),

    CONTESTED_INTERIM_CARE_ORDER("Contested interim care order", "Contested interim care order"),

    ACCELERATED_DISCHARGE_OF_CARE("Accelerated discharge of care", "Accelerated discharge of care"),

    OTHER("Other", "Other");

    private final String label;

    @JsonValue
    private final String code;
}
