package uk.gov.hmcts.reform.fpl.model;

import lombok.Getter;
import lombok.RequiredArgsConstructor;
import uk.gov.hmcts.ccd.sdk.api.ComplexType;
import uk.gov.hmcts.ccd.sdk.api.HasLabel;

/**
 * Generated by ccd-definition-converter from CARE_SUPERVISION_EPO on migration; owned by this service team.
 */
@ComplexType(
        name = "HearingCancellationReasons-HMCTS",
        generate = true
)
@RequiredArgsConstructor
@Getter
public enum HearingCancellationReasonsHMCTS implements HasLabel {
    HM1("No courtroom available"),

    HM2("No special measures"),

    HM3("Interpreter not available"),

    JU1("Lack of judicial continuity"),

    JU2("Insufficient time listed or to complete hearing"),

    JU3("No Judge available");

    private final String label;
}
