package uk.gov.hmcts.reform.fpl.model;

import java.util.Set;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;
import uk.gov.hmcts.ccd.sdk.api.CCD;
import uk.gov.hmcts.ccd.sdk.api.ComplexType;
import uk.gov.hmcts.ccd.sdk.type.YesOrNo;

/**
 * Generated by ccd-definition-converter from CARE_SUPERVISION_EPO on migration; owned by this service team.
 */
@Data
@Builder
@NoArgsConstructor
@AllArgsConstructor
@ComplexType(
        generate = true
)
public class HearingSelector {
    @CCD(
            label = "placeholder",
            showCondition = "optionCount=\"DO NOT SHOW\""
    )
    private String optionCount;

    @CCD(
            label = "HHearing 1",
            showCondition = "optionCount=\"HIDDEN FIELD FOR SHOW HIDE\""
    )
    private YesOrNo option0Hidden;

    @CCD(
            label = "HHearing 2",
            showCondition = "optionCount=\"HIDDEN FIELD FOR SHOW HIDE\""
    )
    private YesOrNo option1Hidden;

    @CCD(
            label = "HHearing 3",
            showCondition = "optionCount=\"HIDDEN FIELD FOR SHOW HIDE\""
    )
    private YesOrNo option2Hidden;

    @CCD(
            label = "HHearing 4",
            showCondition = "optionCount=\"HIDDEN FIELD FOR SHOW HIDE\""
    )
    private YesOrNo option3Hidden;

    @CCD(
            label = "HHearing 5",
            showCondition = "optionCount=\"HIDDEN FIELD FOR SHOW HIDE\""
    )
    private YesOrNo option4Hidden;

    @CCD(
            label = " ",
            showCondition = "optionCount=\"1*\" AND option0Hidden!=\"Yes\""
    )
    private Set<HearingSelector0> option0;

    @CCD(
            label = " ",
            showCondition = "optionCount=\"12*\" AND option1Hidden!=\"Yes\""
    )
    private Set<HearingSelector1> option1;

    @CCD(
            label = " ",
            showCondition = "optionCount=\"123*\" AND option2Hidden!=\"Yes\""
    )
    private Set<HearingSelector2> option2;

    @CCD(
            label = " ",
            showCondition = "optionCount=\"1234*\" AND option3Hidden!=\"Yes\""
    )
    private Set<HearingSelector3> option3;

    @CCD(
            label = " ",
            showCondition = "optionCount=\"12345*\" AND option4Hidden!=\"Yes\""
    )
    private Set<HearingSelector4> option4;
}
