package uk.gov.hmcts.reform.fpl.model;

import lombok.Getter;
import lombok.RequiredArgsConstructor;
import uk.gov.hmcts.ccd.sdk.api.HasLabel;

/**
 * Generated by ccd-definition-converter from CARE_SUPERVISION_EPO on migration; owned by this service team.
 */
@RequiredArgsConstructor
@Getter
public enum HearingHousekeepReasons implements HasLabel {
    LIST_IN_ERROR("Listed in error"),

    DUPLICATE("Duplicate hearing event"),

    OTHER("Other");

    private final String label;
}
