package uk.gov.hmcts.reform.fpl.model;

import java.util.List;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;
import uk.gov.hmcts.ccd.sdk.api.CCD;
import uk.gov.hmcts.ccd.sdk.api.ComplexType;
import uk.gov.hmcts.ccd.sdk.type.ListValue;
import uk.gov.hmcts.ccd.sdk.type.YesOrNo;

/**
 * Generated by ccd-definition-converter from CARE_SUPERVISION_EPO on migration; owned by this service team.
 */
@Data
@Builder
@NoArgsConstructor
@AllArgsConstructor
@ComplexType(
        generate = true
)
public class HearingFurtherEvidenceBundle {
    @CCD(
            label = "Hearing"
    )
    private String hearingName;

    @CCD(
            label = "Documents"
    )
    private List<ListValue<SupportingEvidenceBundle>> supportingEvidenceBundle;

    @CCD(
            label = "Documents",
            searchable = false
    )
    private List<ListValue<SupportingEvidenceBundle>> supportingEvidenceLA;

    @CCD(
            label = "Documents",
            searchable = false
    )
    private List<ListValue<SupportingEvidenceBundle>> supportingEvidenceNC;

    @CCD(
            label = "Is confidential?"
    )
    private YesOrNo markAsConfidential;
}
