package uk.gov.hmcts.reform.fpl.model;

import com.fasterxml.jackson.annotation.JsonValue;
import lombok.AllArgsConstructor;
import lombok.Getter;
import uk.gov.hmcts.ccd.sdk.api.HasLabel;

/**
 * Generated by ccd-definition-converter from CARE_SUPERVISION_EPO on migration; owned by this service team.
 */
@Getter
@AllArgsConstructor
public enum IsAddressKnowList implements HasLabel {
    YES("Yes", "Yes"),

    NO("No", "No"),

    LIVE_IN_REFUGE("They are living in a refuge", "LIVE_IN_REFUGE");

    private final String label;

    @JsonValue
    private final String code;
}
