package uk.gov.hmcts.reform.fpl.model;

import lombok.Getter;
import lombok.RequiredArgsConstructor;
import uk.gov.hmcts.ccd.sdk.api.HasLabel;

/**
 * Generated by ccd-definition-converter from CARE_SUPERVISION_EPO on migration; owned by this service team.
 */
@RequiredArgsConstructor
@Getter
public enum JudicialMessageSenderRoleTypes implements HasLabel {
    CTSC("CTSC"),

    LOCAL_COURT_ADMIN("Local Court Admin"),

    OTHER("Legal Adviser"),

    HEARING_JUDGE("Hearing Judge");

    private final String label;
}
