package uk.gov.hmcts.reform.fpl.model;

import com.fasterxml.jackson.annotation.JsonValue;
import lombok.AllArgsConstructor;
import lombok.Getter;
import uk.gov.hmcts.ccd.sdk.api.HasLabel;

/**
 * Generated by ccd-definition-converter from CARE_SUPERVISION_EPO on migration; owned by this service team.
 */
@Getter
@AllArgsConstructor
public enum LiverpoolDFJCourts implements HasLabel {
    _170("Chester", "170"),

    _181("Crewe", "181"),

    _251("Liverpool", "251");

    private final String label;

    @JsonValue
    private final String code;
}
