package uk.gov.hmcts.reform.fpl.model;

import lombok.Getter;
import lombok.RequiredArgsConstructor;
import uk.gov.hmcts.ccd.sdk.api.HasLabel;

/**
 * Generated by ccd-definition-converter from CARE_SUPERVISION_EPO on migration; owned by this service team.
 */
@RequiredArgsConstructor
@Getter
public enum ManageDocumentSubtypeList implements HasLabel {
    RESPONDENT_STATEMENT("Respondent statement"),

    OTHER("Any other document");

    private final String label;
}
