package uk.gov.hmcts.reform.fpl.model;

import com.fasterxml.jackson.annotation.JsonValue;
import lombok.AllArgsConstructor;
import lombok.Getter;
import uk.gov.hmcts.ccd.sdk.api.HasLabel;

/**
 * Generated by ccd-definition-converter from CARE_SUPERVISION_EPO on migration; owned by this service team.
 */
@Getter
@AllArgsConstructor
public enum NorthWalesDFJCourts implements HasLabel {
    _159("Caernarfon", "159"),

    _308("Prestatyn (Rhyl)", "308"),

    _384("Wrexham", "384");

    private final String label;

    @JsonValue
    private final String code;
}
