package uk.gov.hmcts.reform.fpl.model;

import java.util.List;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;
import uk.gov.hmcts.ccd.sdk.api.CCD;
import uk.gov.hmcts.ccd.sdk.api.ComplexType;
import uk.gov.hmcts.ccd.sdk.type.FieldType;
import uk.gov.hmcts.ccd.sdk.type.ListValue;

/**
 * Generated by ccd-definition-converter from CARE_SUPERVISION_EPO on migration; owned by this service team.
 */
@Data
@Builder
@NoArgsConstructor
@AllArgsConstructor
@ComplexType(
        generate = true
)
public class OrdersBundleForApproval {
    @CCD(
            label = "Order",
            showCondition = "orders=\"DO_NOT_SHOW\""
    )
    private String hearingId;

    @CCD(
            label = "Hearing"
    )
    private String hearingName;

    @CCD(
            label = "Judge"
    )
    private String judgeTitleAndName;

    @CCD(
            label = "This is a confidential draft order and restricted viewing applies",
            showCondition = "orders!=\"*\" AND ordersCTSC!=\"*\" AND ordersLA!=\"*\" AND ordersResp0!=\"*\" AND ordersResp1!=\"*\" AND ordersResp2!=\"*\" AND ordersResp3!=\"*\" AND ordersResp4!=\"*\" AND ordersResp5!=\"*\" AND ordersResp6!=\"*\" AND ordersResp7!=\"*\" AND ordersResp8!=\"*\" AND ordersResp9!=\"*\" AND ordersChild0!=\"*\" AND ordersChild1!=\"*\" AND ordersChild2!=\"*\" AND ordersChild3!=\"*\" AND ordersChild4!=\"*\" AND ordersChild5!=\"*\" AND ordersChild6!=\"*\" AND ordersChild7!=\"*\" AND ordersChild8!=\"*\" AND ordersChild9!=\"*\" AND ordersChild10!=\"*\" AND ordersChild11!=\"*\" AND ordersChild12!=\"*\" AND ordersChild13!=\"*\" AND ordersChild14!=\"*\"",
            searchable = false,
            typeOverride = FieldType.Label
    )
    private String confidentialDraftRestrictedLabel;

    @CCD(
            label = "Draft"
    )
    private List<ListValue<HearingOrderForApproval>> orders;

    @CCD(
            label = "Confidential Draft (Uploaded by CTSC)"
    )
    private List<ListValue<HearingOrderForApproval>> ordersCTSC;

    @CCD(
            label = "Confidential Draft (Uploaded by LA)"
    )
    private List<ListValue<HearingOrderForApproval>> ordersLA;

    @CCD(
            label = "Confidential Draft (Uploaded by Respondent 1)"
    )
    private List<ListValue<HearingOrderForApproval>> ordersResp0;

    @CCD(
            label = "Confidential Draft (Uploaded by Respondent 2)"
    )
    private List<ListValue<HearingOrderForApproval>> ordersResp1;

    @CCD(
            label = "Confidential Draft (Uploaded by Respondent 3)"
    )
    private List<ListValue<HearingOrderForApproval>> ordersResp2;

    @CCD(
            label = "Confidential Draft (Uploaded by Respondent 4)"
    )
    private List<ListValue<HearingOrderForApproval>> ordersResp3;

    @CCD(
            label = "Confidential Draft (Uploaded by Respondent 5)"
    )
    private List<ListValue<HearingOrderForApproval>> ordersResp4;

    @CCD(
            label = "Confidential Draft (Uploaded by Respondent 6)"
    )
    private List<ListValue<HearingOrderForApproval>> ordersResp5;

    @CCD(
            label = "Confidential Draft (Uploaded by Respondent 7)"
    )
    private List<ListValue<HearingOrderForApproval>> ordersResp6;

    @CCD(
            label = "Confidential Draft (Uploaded by Respondent 8)"
    )
    private List<ListValue<HearingOrderForApproval>> ordersResp7;

    @CCD(
            label = "Confidential Draft (Uploaded by Respondent 9)"
    )
    private List<ListValue<HearingOrderForApproval>> ordersResp8;

    @CCD(
            label = "Confidential Draft (Uploaded by Respondent 10)"
    )
    private List<ListValue<HearingOrderForApproval>> ordersResp9;

    @CCD(
            label = "Confidential Draft (Uploaded by Child 1)"
    )
    private List<ListValue<HearingOrderForApproval>> ordersChild0;

    @CCD(
            label = "Confidential Draft (Uploaded by Child 2)"
    )
    private List<ListValue<HearingOrderForApproval>> ordersChild1;

    @CCD(
            label = "Confidential Draft (Uploaded by Child 3)"
    )
    private List<ListValue<HearingOrderForApproval>> ordersChild2;

    @CCD(
            label = "Confidential Draft (Uploaded by Child 4)"
    )
    private List<ListValue<HearingOrderForApproval>> ordersChild3;

    @CCD(
            label = "Confidential Draft (Uploaded by Child 5)"
    )
    private List<ListValue<HearingOrderForApproval>> ordersChild4;

    @CCD(
            label = "Confidential Draft (Uploaded by Child 6)"
    )
    private List<ListValue<HearingOrderForApproval>> ordersChild5;

    @CCD(
            label = "Confidential Draft (Uploaded by Child 7)"
    )
    private List<ListValue<HearingOrderForApproval>> ordersChild6;

    @CCD(
            label = "Confidential Draft (Uploaded by Child 8)"
    )
    private List<ListValue<HearingOrderForApproval>> ordersChild7;

    @CCD(
            label = "Confidential Draft (Uploaded by Child 9)"
    )
    private List<ListValue<HearingOrderForApproval>> ordersChild8;

    @CCD(
            label = "Confidential Draft (Uploaded by Child 10)"
    )
    private List<ListValue<HearingOrderForApproval>> ordersChild9;

    @CCD(
            label = "Confidential Draft (Uploaded by Child 11)"
    )
    private List<ListValue<HearingOrderForApproval>> ordersChild10;

    @CCD(
            label = "Confidential Draft (Uploaded by Child 12)"
    )
    private List<ListValue<HearingOrderForApproval>> ordersChild11;

    @CCD(
            label = "Confidential Draft (Uploaded by Child 13)"
    )
    private List<ListValue<HearingOrderForApproval>> ordersChild12;

    @CCD(
            label = "Confidential Draft (Uploaded by Child 14)"
    )
    private List<ListValue<HearingOrderForApproval>> ordersChild13;

    @CCD(
            label = "Confidential Draft (Uploaded by Child 15)"
    )
    private List<ListValue<HearingOrderForApproval>> ordersChild14;
}
