package uk.gov.hmcts.reform.fpl.model;

import lombok.Getter;
import lombok.RequiredArgsConstructor;
import uk.gov.hmcts.ccd.sdk.api.HasLabel;

/**
 * Generated by ccd-definition-converter from CARE_SUPERVISION_EPO on migration; owned by this service team.
 */
@RequiredArgsConstructor
@Getter
public enum OrderTypeSolicitor implements HasLabel {
    OTHER("Variation of supervision order or discharge of care order"),

    CONTACT_WITH_CHILD_IN_CARE("Contact with child in care");

    private final String label;
}
