package uk.gov.hmcts.reform.fpl.model;

import java.time.LocalDateTime;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;
import uk.gov.hmcts.ccd.sdk.api.CCD;
import uk.gov.hmcts.ccd.sdk.api.ComplexType;
import uk.gov.hmcts.ccd.sdk.type.Document;

/**
 * Generated by ccd-definition-converter from CARE_SUPERVISION_EPO on migration; owned by this service team.
 */
@Data
@Builder
@NoArgsConstructor
@AllArgsConstructor
@ComplexType(
        generate = true
)
public class OtherDocument {
    @CCD(
            label = "Document name",
            hint = "Give the document a descriptive name. For example, 'Parenting assessment' or 'Paediatric report'"
    )
    private String documentTitle;

    @CCD(
            label = "Date and time uploaded"
    )
    private LocalDateTime dateTimeUploaded;

    @CCD(
            label = "Uploaded by"
    )
    private String uploadedBy;

    @CCD(
            label = "Upload a file",
            categoryID = "archivedDocuments"
    )
    private Document typeOfDocument;
}
