package uk.gov.hmcts.reform.fpl.model;

import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;
import uk.gov.hmcts.ccd.sdk.api.CCD;
import uk.gov.hmcts.ccd.sdk.api.ComplexType;
import uk.gov.hmcts.ccd.sdk.type.FieldType;
import uk.gov.hmcts.ccd.sdk.type.YesOrNo;

/**
 * Generated by ccd-definition-converter from CARE_SUPERVISION_EPO on migration; owned by this service team.
 */
@Data
@Builder
@NoArgsConstructor
@AllArgsConstructor
@ComplexType(
        name = "ProceedingType",
        generate = true
)
public class ProceedingType2 {
    @CCD(
            label = "Are these previous or ongoing proceedings?"
    )
    private ProceedingStatus proceedingStatus;

    @CCD(
            label = "Case number"
    )
    private String caseNumber;

    @CCD(
            label = "Date started"
    )
    private String started;

    @CCD(
            label = "Date ended"
    )
    private String ended;

    @CCD(
            label = "Orders made"
    )
    private String ordersMade;

    @CCD(
            label = "Judge",
            hint = "For example, District Judge Martin Brown"
    )
    private String judge;

    @CCD(
            label = "Names of children involved",
            typeOverride = FieldType.TextArea
    )
    private String children;

    @CCD(
            label = "Name of guardian"
    )
    private String guardian;

    @CCD(
            label = "Is the same guardian needed?"
    )
    private YesOrNo sameGuardianNeeded;

    @CCD(
            label = "Give reason",
            showCondition = "sameGuardianNeeded=\"No\"",
            typeOverride = FieldType.TextArea
    )
    private String sameGuardianDetails;
}
