package uk.gov.hmcts.reform.fpl.model;

import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;
import uk.gov.hmcts.ccd.sdk.api.CCD;
import uk.gov.hmcts.ccd.sdk.api.ComplexType;
import uk.gov.hmcts.ccd.sdk.type.FieldType;

/**
 * Generated by ccd-definition-converter from CARE_SUPERVISION_EPO on migration; owned by this service team.
 */
@Data
@Builder
@NoArgsConstructor
@AllArgsConstructor
@ComplexType(
        generate = true
)
public class RespondentsRefusedSelector {
    @CCD(
            label = "placeholder"
    )
    private String optionCount;

    @CCD(
            label = "Person 1",
            showCondition = "optionCount=\"1*\"",
            typeOverride = FieldType.MultiSelectList,
            typeParameterOverride = "RespondentsRefusedSelector"
    )
    private String option0;

    @CCD(
            label = "Person 2",
            showCondition = "optionCount=\"12*\"",
            typeOverride = FieldType.MultiSelectList,
            typeParameterOverride = "RespondentsRefusedSelector"
    )
    private String option1;

    @CCD(
            label = "Person 3",
            showCondition = "optionCount=\"123*\"",
            typeOverride = FieldType.MultiSelectList,
            typeParameterOverride = "RespondentsRefusedSelector"
    )
    private String option2;

    @CCD(
            label = "Person 4",
            showCondition = "optionCount=\"1234*\"",
            typeOverride = FieldType.MultiSelectList,
            typeParameterOverride = "RespondentsRefusedSelector"
    )
    private String option3;

    @CCD(
            label = "Person 5",
            showCondition = "optionCount=\"12345*\"",
            typeOverride = FieldType.MultiSelectList,
            typeParameterOverride = "RespondentsRefusedSelector"
    )
    private String option4;

    @CCD(
            label = "Person 6",
            showCondition = "optionCount=\"123456*\"",
            typeOverride = FieldType.MultiSelectList,
            typeParameterOverride = "RespondentsRefusedSelector"
    )
    private String option5;

    @CCD(
            label = "Person 7",
            showCondition = "optionCount=\"1234567*\"",
            typeOverride = FieldType.MultiSelectList,
            typeParameterOverride = "RespondentsRefusedSelector"
    )
    private String option6;

    @CCD(
            label = "Person 8",
            showCondition = "optionCount=\"12345678*\"",
            typeOverride = FieldType.MultiSelectList,
            typeParameterOverride = "RespondentsRefusedSelector"
    )
    private String option7;

    @CCD(
            label = "Person 9",
            showCondition = "optionCount=\"123456789*\"",
            typeOverride = FieldType.MultiSelectList,
            typeParameterOverride = "RespondentsRefusedSelector"
    )
    private String option8;

    @CCD(
            label = "Person 10",
            showCondition = "optionCount=\"12345678910*\"",
            typeOverride = FieldType.MultiSelectList,
            typeParameterOverride = "RespondentsRefusedSelector"
    )
    private String option9;

    @CCD(
            label = "Person 11",
            showCondition = "optionCount=\"1234567891011*\"",
            typeOverride = FieldType.MultiSelectList,
            typeParameterOverride = "RespondentsRefusedSelector"
    )
    private String option10;

    @CCD(
            label = "Person 12",
            showCondition = "optionCount=\"123456789101112*\"",
            typeOverride = FieldType.MultiSelectList,
            typeParameterOverride = "RespondentsRefusedSelector"
    )
    private String option11;

    @CCD(
            label = "Person 13",
            showCondition = "optionCount=\"12345678910111213*\"",
            typeOverride = FieldType.MultiSelectList,
            typeParameterOverride = "RespondentsRefusedSelector"
    )
    private String option12;

    @CCD(
            label = "Person 14",
            showCondition = "optionCount=\"1234567891011121314*\"",
            typeOverride = FieldType.MultiSelectList,
            typeParameterOverride = "RespondentsRefusedSelector"
    )
    private String option13;

    @CCD(
            label = "Person 15",
            showCondition = "optionCount=\"123456789101112131415\"",
            typeOverride = FieldType.MultiSelectList,
            typeParameterOverride = "RespondentsRefusedSelector"
    )
    private String option14;
}
