package uk.gov.hmcts.reform.fpl.model;

import java.util.List;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;
import uk.gov.hmcts.ccd.sdk.api.CCD;
import uk.gov.hmcts.ccd.sdk.api.ComplexType;
import uk.gov.hmcts.ccd.sdk.type.ListValue;

/**
 * Generated by ccd-definition-converter from CARE_SUPERVISION_EPO on migration; owned by this service team.
 */
@Data
@Builder
@NoArgsConstructor
@AllArgsConstructor
@ComplexType(
        generate = true
)
public class RespondentStatement {
    @CCD(
            label = "Respondent",
            searchable = false
    )
    private String respondentName;

    @CCD(
            label = "Id of the respondent for this respondent statement",
            showCondition = "respondentName=\"DO NOT SHOW\"",
            searchable = false
    )
    private String respondentId;

    @CCD(
            label = "Documents",
            searchable = false
    )
    private List<ListValue<SupportingEvidenceBundle>> supportingEvidenceBundle;

    @CCD(
            label = "Documents",
            searchable = false
    )
    private List<ListValue<SupportingEvidenceBundle>> supportingEvidenceLA;

    @CCD(
            label = "Documents",
            searchable = false
    )
    private List<ListValue<SupportingEvidenceBundle>> supportingEvidenceNC;
}
