package uk.gov.hmcts.reform.fpl.model;

import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;
import uk.gov.hmcts.ccd.sdk.api.CCD;
import uk.gov.hmcts.ccd.sdk.api.ComplexType;

/**
 * Generated by ccd-definition-converter from CARE_SUPERVISION_EPO on migration; owned by this service team.
 */
@Data
@Builder
@NoArgsConstructor
@AllArgsConstructor
@ComplexType(
        generate = true
)
public class SocialWorkerTelephone {
    @CCD(
            label = "Social worker's telephone number",
            hint = "For example, 020 2772 5772",
            max = 24
    )
    private String telephoneNumber;

    @CCD(
            label = "Name of person to contact"
    )
    private String contactDirection;
}
