package uk.gov.hmcts.reform.fpl.model;

import lombok.Getter;
import lombok.RequiredArgsConstructor;
import uk.gov.hmcts.ccd.sdk.api.HasLabel;

/**
 * Generated by ccd-definition-converter from CARE_SUPERVISION_EPO on migration; owned by this service team.
 */
@RequiredArgsConstructor
@Getter
public enum SouthEastDFJ implements HasLabel {
    BRIGHTON("Brighton"),

    ESSEX_AND_SUFFOLK("Essex & Suffolk"),

    GUILDFORD("Guildford"),

    LUTON("Luton"),

    MEDWAY("Medway"),

    MILTON_KEYNES("Milton Keynes"),

    NORWICH("Norwich"),

    PETERBOROUGH("Peterborough"),

    READING("Reading"),

    WATFORD("Watford");

    private final String label;
}
