package uk.gov.hmcts.reform.fpl.model;

import com.fasterxml.jackson.annotation.JsonValue;
import lombok.AllArgsConstructor;
import lombok.Getter;
import uk.gov.hmcts.ccd.sdk.api.HasLabel;

/**
 * Generated by ccd-definition-converter from CARE_SUPERVISION_EPO on migration; owned by this service team.
 */
@Getter
@AllArgsConstructor
public enum TimeFrameList implements HasLabel {
    WITHIN_18_DAYS("Within 18 days", "Within 18 days"),

    WITHIN_12_DAYS("Within 12 days", "Within 12 days"),

    WITHIN_7_DAYS("Within 7 days", "Within 7 days"),

    WITHIN_2_DAYS("Within 2 days", "Within 2 days"),

    SAME_DAY("Same day", "Same day"),

    OTHER("Other", "Other");

    private final String label;

    @JsonValue
    private final String code;
}
