package uk.gov.hmcts.reform.fpl.model;

import java.time.LocalDateTime;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;
import uk.gov.hmcts.ccd.sdk.api.CCD;
import uk.gov.hmcts.ccd.sdk.api.ComplexType;
import uk.gov.hmcts.ccd.sdk.type.Document;
import uk.gov.hmcts.ccd.sdk.type.FieldType;

/**
 * Generated by ccd-definition-converter from CARE_SUPERVISION_EPO on migration; owned by this service team.
 */
@Data
@Builder
@NoArgsConstructor
@AllArgsConstructor
@ComplexType(
        generate = true
)
public class UploadSwetDocument {
    @CCD(
            label = "Upload a file",
            showCondition = "documentStatus!=\"Not Required\""
    )
    private Document typeOfDocument;

    @CCD(
            label = "Date and time uploaded"
    )
    private LocalDateTime dateTimeUploaded;

    @CCD(
            label = "Uploaded by"
    )
    private String uploadedBy;

    @CCD(
            label = "Document status"
    )
    private SwetDocumentOptions documentStatus;

    @CCD(
            label = "Explain why the document isn't included and when you expect to provide it.",
            showCondition = "documentStatus=\"To follow\"",
            typeOverride = FieldType.TextArea
    )
    private String statusReason;
}
