package uk.gov.hmcts.reform.fpl.ccd.access;

import com.google.common.collect.HashMultimap;
import com.google.common.collect.SetMultimap;
import uk.gov.hmcts.ccd.sdk.api.HasAccessControl;
import uk.gov.hmcts.ccd.sdk.api.HasRole;
import uk.gov.hmcts.ccd.sdk.api.Permission;
import uk.gov.hmcts.reform.fpl.model.UserRole;

/**
 * Generated by ccd-definition-converter from CARE_SUPERVISION_EPO on migration; owned by this service team.
 */
public class BARRISTERUPlus40RolesUirdihAccess implements HasAccessControl {
    @Override
    public SetMultimap<HasRole, Permission> getGrants() {
        SetMultimap<HasRole, Permission> grants = HashMultimap.create();
        grants.put(UserRole.BARRISTER, Permission.U);
        grants.put(UserRole.CAFCASSSOLICITOR, Permission.U);
        grants.put(UserRole.CHILDSOLICITORA, Permission.U);
        grants.put(UserRole.CHILDSOLICITORB, Permission.U);
        grants.put(UserRole.CHILDSOLICITORC, Permission.U);
        grants.put(UserRole.CHILDSOLICITORD, Permission.U);
        grants.put(UserRole.CHILDSOLICITORE, Permission.U);
        grants.put(UserRole.CHILDSOLICITORF, Permission.U);
        grants.put(UserRole.CHILDSOLICITORG, Permission.U);
        grants.put(UserRole.CHILDSOLICITORH, Permission.U);
        grants.put(UserRole.CHILDSOLICITORI, Permission.U);
        grants.put(UserRole.CHILDSOLICITORJ, Permission.U);
        grants.put(UserRole.CHILDSOLICITORK, Permission.U);
        grants.put(UserRole.CHILDSOLICITORL, Permission.U);
        grants.put(UserRole.CHILDSOLICITORM, Permission.U);
        grants.put(UserRole.CHILDSOLICITORN, Permission.U);
        grants.put(UserRole.CHILDSOLICITORO, Permission.U);
        grants.put(UserRole.EPSMANAGING, Permission.U);
        grants.put(UserRole.LABARRISTER, Permission.U);
        grants.put(UserRole.LAMANAGING, Permission.U);
        grants.put(UserRole.LASHARED, Permission.U);
        grants.put(UserRole.LASOLICITOR, Permission.U);
        grants.put(UserRole.SOLICITORA, Permission.U);
        grants.put(UserRole.SOLICITORB, Permission.U);
        grants.put(UserRole.SOLICITORC, Permission.U);
        grants.put(UserRole.SOLICITORD, Permission.U);
        grants.put(UserRole.SOLICITORE, Permission.U);
        grants.put(UserRole.SOLICITORF, Permission.U);
        grants.put(UserRole.SOLICITORG, Permission.U);
        grants.put(UserRole.SOLICITORH, Permission.U);
        grants.put(UserRole.SOLICITORI, Permission.U);
        grants.put(UserRole.SOLICITORJ, Permission.U);
        grants.put(UserRole.SOLICITOR, Permission.U);
        grants.put(UserRole.CASEWORKER_PUBLICLAW_CAFCASS, Permission.U);
        grants.put(UserRole.CASEWORKER_PUBLICLAW_CAFCASSSYSTEMUPDATE, Permission.R);
        grants.put(UserRole.CASEWORKER_PUBLICLAW_COURTADMIN, Permission.U);
        grants.put(UserRole.CASEWORKER_PUBLICLAW_GATEKEEPER, Permission.C);
        grants.put(UserRole.CASEWORKER_PUBLICLAW_GATEKEEPER, Permission.U);
        grants.put(UserRole.CASEWORKER_PUBLICLAW_GATEKEEPER, Permission.D);
        grants.put(UserRole.CASEWORKER_PUBLICLAW_JUDICIARY, Permission.C);
        grants.put(UserRole.CASEWORKER_PUBLICLAW_JUDICIARY, Permission.U);
        grants.put(UserRole.CASEWORKER_PUBLICLAW_JUDICIARY, Permission.D);
        grants.put(UserRole.CASEWORKER_PUBLICLAW_MAGISTRATE, Permission.U);
        grants.put(UserRole.CASEWORKER_PUBLICLAW_SUPERUSER, Permission.C);
        grants.put(UserRole.CASEWORKER_PUBLICLAW_SUPERUSER, Permission.U);
        grants.put(UserRole.CASEWORKER_PUBLICLAW_SUPERUSER, Permission.D);
        grants.put(UserRole.CASEWORKER_PUBLICLAW_SYSTEMUPDATE, Permission.C);
        grants.put(UserRole.CASEWORKER_PUBLICLAW_SYSTEMUPDATE, Permission.U);
        grants.put(UserRole.CASEWORKER_PUBLICLAW_SYSTEMUPDATE, Permission.D);
        return grants;
    }
}
