package uk.gov.hmcts.reform.fpl.ccd.access;

import com.google.common.collect.HashMultimap;
import com.google.common.collect.SetMultimap;
import uk.gov.hmcts.ccd.sdk.api.HasAccessControl;
import uk.gov.hmcts.ccd.sdk.api.HasRole;
import uk.gov.hmcts.ccd.sdk.api.Permission;
import uk.gov.hmcts.reform.fpl.model.UserRole;

/**
 * Generated by ccd-definition-converter from CARE_SUPERVISION_EPO on migration; owned by this service team.
 */
public class CAFCASSSOLICITORRPlus10RolesOsrbexAccess implements HasAccessControl {
    @Override
    public SetMultimap<HasRole, Permission> getGrants() {
        SetMultimap<HasRole, Permission> grants = HashMultimap.create();
        grants.put(UserRole.CAFCASSSOLICITOR, Permission.R);
        grants.put(UserRole.LAMANAGING, Permission.R);
        grants.put(UserRole.LASHARED, Permission.R);
        grants.put(UserRole.LASOLICITOR, Permission.R);
        grants.put(UserRole.SOLICITOR, Permission.R);
        grants.put(UserRole.CASEWORKER_PUBLICLAW_CAFCASS, Permission.R);
        grants.put(UserRole.CASEWORKER_PUBLICLAW_CAFCASSSYSTEMUPDATE, Permission.C);
        grants.put(UserRole.CASEWORKER_PUBLICLAW_CAFCASSSYSTEMUPDATE, Permission.R);
        grants.put(UserRole.CASEWORKER_PUBLICLAW_CAFCASSSYSTEMUPDATE, Permission.U);
        grants.put(UserRole.CASEWORKER_PUBLICLAW_CAFCASSSYSTEMUPDATE, Permission.D);
        grants.put(UserRole.CASEWORKER_PUBLICLAW_COURTADMIN, Permission.R);
        grants.put(UserRole.CASEWORKER_PUBLICLAW_JUDICIARY, Permission.R);
        grants.put(UserRole.CASEWORKER_PUBLICLAW_SUPERUSER, Permission.C);
        grants.put(UserRole.CASEWORKER_PUBLICLAW_SUPERUSER, Permission.R);
        grants.put(UserRole.CASEWORKER_PUBLICLAW_SUPERUSER, Permission.U);
        grants.put(UserRole.CASEWORKER_PUBLICLAW_SUPERUSER, Permission.D);
        grants.put(UserRole.CASEWORKER_PUBLICLAW_SYSTEMUPDATE, Permission.C);
        grants.put(UserRole.CASEWORKER_PUBLICLAW_SYSTEMUPDATE, Permission.R);
        grants.put(UserRole.CASEWORKER_PUBLICLAW_SYSTEMUPDATE, Permission.U);
        grants.put(UserRole.CASEWORKER_PUBLICLAW_SYSTEMUPDATE, Permission.D);
        return grants;
    }
}
