package uk.gov.hmcts.reform.fpl.ccd.access;

import com.google.common.collect.HashMultimap;
import com.google.common.collect.SetMultimap;
import uk.gov.hmcts.ccd.sdk.api.HasAccessControl;
import uk.gov.hmcts.ccd.sdk.api.HasRole;
import uk.gov.hmcts.ccd.sdk.api.Permission;
import uk.gov.hmcts.reform.fpl.model.UserRole;

/**
 * Generated by ccd-definition-converter from CARE_SUPERVISION_EPO on migration; owned by this service team.
 */
public class CHILDSOLICITORBCuPlus23RolesLimnqvAccess implements HasAccessControl {
    @Override
    public SetMultimap<HasRole, Permission> getGrants() {
        SetMultimap<HasRole, Permission> grants = HashMultimap.create();
        grants.put(UserRole.CHILDSOLICITORB, Permission.C);
        grants.put(UserRole.CHILDSOLICITORB, Permission.U);
        grants.put(UserRole.CHILDSOLICITORC, Permission.C);
        grants.put(UserRole.CHILDSOLICITORC, Permission.U);
        grants.put(UserRole.CHILDSOLICITORD, Permission.C);
        grants.put(UserRole.CHILDSOLICITORD, Permission.U);
        grants.put(UserRole.CHILDSOLICITORE, Permission.C);
        grants.put(UserRole.CHILDSOLICITORE, Permission.U);
        grants.put(UserRole.CHILDSOLICITORF, Permission.C);
        grants.put(UserRole.CHILDSOLICITORF, Permission.U);
        grants.put(UserRole.CHILDSOLICITORG, Permission.C);
        grants.put(UserRole.CHILDSOLICITORG, Permission.U);
        grants.put(UserRole.CHILDSOLICITORH, Permission.C);
        grants.put(UserRole.CHILDSOLICITORH, Permission.U);
        grants.put(UserRole.CHILDSOLICITORI, Permission.C);
        grants.put(UserRole.CHILDSOLICITORI, Permission.U);
        grants.put(UserRole.CHILDSOLICITORJ, Permission.C);
        grants.put(UserRole.CHILDSOLICITORJ, Permission.U);
        grants.put(UserRole.CHILDSOLICITORK, Permission.C);
        grants.put(UserRole.CHILDSOLICITORK, Permission.U);
        grants.put(UserRole.CHILDSOLICITORL, Permission.C);
        grants.put(UserRole.CHILDSOLICITORL, Permission.U);
        grants.put(UserRole.CHILDSOLICITORM, Permission.C);
        grants.put(UserRole.CHILDSOLICITORM, Permission.U);
        grants.put(UserRole.CHILDSOLICITORN, Permission.C);
        grants.put(UserRole.CHILDSOLICITORN, Permission.U);
        grants.put(UserRole.CHILDSOLICITORO, Permission.C);
        grants.put(UserRole.CHILDSOLICITORO, Permission.U);
        grants.put(UserRole.SOLICITORB, Permission.C);
        grants.put(UserRole.SOLICITORB, Permission.U);
        grants.put(UserRole.SOLICITORC, Permission.C);
        grants.put(UserRole.SOLICITORC, Permission.U);
        grants.put(UserRole.SOLICITORD, Permission.C);
        grants.put(UserRole.SOLICITORD, Permission.U);
        grants.put(UserRole.SOLICITORE, Permission.C);
        grants.put(UserRole.SOLICITORE, Permission.U);
        grants.put(UserRole.SOLICITORF, Permission.C);
        grants.put(UserRole.SOLICITORF, Permission.U);
        grants.put(UserRole.SOLICITORG, Permission.C);
        grants.put(UserRole.SOLICITORG, Permission.U);
        grants.put(UserRole.SOLICITORH, Permission.C);
        grants.put(UserRole.SOLICITORH, Permission.U);
        grants.put(UserRole.SOLICITORI, Permission.C);
        grants.put(UserRole.SOLICITORI, Permission.U);
        grants.put(UserRole.SOLICITORJ, Permission.C);
        grants.put(UserRole.SOLICITORJ, Permission.U);
        grants.put(UserRole.SOLICITOR, Permission.C);
        grants.put(UserRole.SOLICITOR, Permission.U);
        return grants;
    }
}
