package uk.gov.hmcts.reform.fpl.ccd.access;

import com.google.common.collect.HashMultimap;
import com.google.common.collect.SetMultimap;
import uk.gov.hmcts.ccd.sdk.api.HasAccessControl;
import uk.gov.hmcts.ccd.sdk.api.HasRole;
import uk.gov.hmcts.ccd.sdk.api.Permission;
import uk.gov.hmcts.reform.fpl.model.UserRole;

/**
 * Generated by ccd-definition-converter from CARE_SUPERVISION_EPO on migration; owned by this service team.
 */
public class LABARRISTERCruPlus2RolesBskdreAccess implements HasAccessControl {
    @Override
    public SetMultimap<HasRole, Permission> getGrants() {
        SetMultimap<HasRole, Permission> grants = HashMultimap.create();
        grants.put(UserRole.LABARRISTER, Permission.C);
        grants.put(UserRole.LABARRISTER, Permission.R);
        grants.put(UserRole.LABARRISTER, Permission.U);
        grants.put(UserRole.CASEWORKER_PUBLICLAW_CAFCASS, Permission.R);
        grants.put(UserRole.CASEWORKER_PUBLICLAW_CAFCASSSYSTEMUPDATE, Permission.R);
        return grants;
    }
}
