test-conf:
  idam-url: https://idam-api.aat.platform.hmcts.net
  fpl-url:  https://fpl-case-service-pr-${CHANGE_ID}.service.core-compute-preview.internal
  xui-url:  https://xui-fpl-case-service-pr-${CHANGE_ID}.service.core-compute-preview.internal
  placeholders:
    SwanseaOrganisationID: W9V61CP
    WiltshireOrganisationID: 11VOC93
