spring:
  config:
    use-legacy-processing: true

test-conf:
  users:
    solicitor:
      name: james@swansea.gov.uk
    admin:
      name: hmcts-admin@example.com

contacts:
  passport_office:
    address: 'passport office, some address, somewhere'
    email: 'passport-office@example.com'
