test-conf:
  idam-url: https://idam-api.aat.platform.hmcts.net
  fpl-url:  http://fpl-case-service-pr-${CHANGE_ID}-java
  placeholders:
    SwanseaOrganisationID: W9V61CP
    WiltshireOrganisationID: 11VOC93
