test-conf:
  idam-url: https://idam-api.aat.platform.hmcts.net
  fpl-url:  http://fpl-case-service-pr-${CHANGE_ID}.service.core-compute-preview.internal
  placeholders:
    OrganisationID: W9V61CP
    OrganisationName: Swansea
  users:
    solicitor:
      name: james@swansea.gov.uk
    admin:
      name: hmcts-admin@example.com
