test-conf:
  idam-url: https://idam-api.aat.platform.hmcts.net
  fpl-url:  https://fpl-case-service-pr-${CHANGE_ID}.preview.platform.hmcts.net
  placeholders:
    SwanseaOrganisationID: W9V61CP
    WiltshireOrganisationID: 11VOC93
