test-conf:
  idam-url: http://localhost:5000
  fpl-url: http://localhost:4000
  placeholders:
    OrganisationID: 62LYJRF
  users:
    solicitor:
      name: james@swansea.gov.uk
    admin:
      name: hmcts-admin@example.com
