import { test, expect } from '@playwright/test';

test('test', async ({ page }) => {
  await page.goto('https://idam-web-public.aat.platform.hmcts.net/login?client_id=xuiwebapp&redirect_uri=https://manage-case.aat.platform.hmcts.net/oauth2/callback&state=3uzpJn_nSh5kP45I0RpIROyzLbRaMSbGAFLVYdNYDJ0&nonce=ZkR6REdDta7m5c6Y2e0Uu_ZRHmYGfFmsMUcDnoyCX3M&response_type=code&scope=profile%20openid%20roles%20manage-user%20create-user%20search-user&prompt=');
  await page.getByLabel('Email address').click();
  await page.getByLabel('Email address').fill('fpl-ctsc-team-leader@justice.gov.uk');
  await page.getByLabel('Password').click();
  await page.getByLabel('Password').press('CapsLock');
  await page.getByLabel('Password').fill('Password12');
  await page.getByRole('button', { name: 'Sign in' }).click();
  await page.goto('https://manage-case.aat.platform.hmcts.net/cases');
  await expect(page.getByLabel('Case type')).toBeVisible();
  await page.getByLabel('Case type').selectOption('4: Object');
  await page.getByLabel('Apply filter').click();
  await page.getByLabel('go to case with Case reference:1738-5952-1463-').click();
  await page.getByLabel('Next step').selectOption('16: Object');
  await page.getByRole('button', { name: 'Go' }).click();
  await page.getByLabel('Full name (Optional)').click();
  await page.getByLabel('Full name (Optional)').press('CapsLock');
  await page.getByLabel('Full name (Optional)').fill('James ');
  await page.getByLabel('Full name (Optional)').press('CapsLock');
  await page.getByLabel('Full name (Optional)').fill('James Gunn');
  await page.getByLabel('Day').click();
  await page.getByLabel('Day').fill('101');
  await page.getByLabel('Month').click();
  await page.getByLabel('Month').fill('1');
  await page.getByLabel('Year').click();
  await page.getByLabel('Year').fill('200');
  await page.getByLabel('Year').click();
  await page.getByLabel('Year').fill('2000');
  await page.getByLabel('Gender (Optional)').selectOption('1: Male');
  await page.getByLabel('Place of birth (Optional)').click();
  await page.getByLabel('Place of birth (Optional)').fill('london');
  await page.locator('#others_firstOther_addressKnowV2').getByText('No', { exact: true }).click();
  await page.getByLabel('*Reason the address is not').selectOption('1: No fixed abode');
  await page.getByLabel('Telephone number (Optional)').click();
  await page.getByLabel('Telephone number (Optional)').fill('00000000');
  await page.getByRole('group', { name: 'Do you need contact details' }).getByLabel('No').check();
  await page.getByLabel('What is this person\'s').click();
  await page.getByLabel('What is this person\'s').fill('test');
  await page.getByRole('group', { name: 'Do you believe this person' }).getByLabel('No', { exact: true }).check();
  await page.getByRole('heading', { name: 'Other person (Optional)' }).click();
  await page.getByRole('button', { name: 'Add new' }).click();
  await page.locator('#others_additionalOthers_0_name').click();
  await page.locator('#others_additionalOthers_0_name').press('CapsLock');
  await page.locator('#others_additionalOthers_0_name').fill('Jane ');
  await page.locator('#others_additionalOthers_0_name').press('CapsLock');
  await page.locator('#others_additionalOthers_0_name').fill('Jane Dow');
  await page.locator('#others_additionalOthers #DOB-day').click();
  await page.locator('#others_additionalOthers #DOB-day').fill('3');
  await page.locator('#others_additionalOthers #DOB-month').click();
  await page.locator('#others_additionalOthers #DOB-month').fill('6');
  await page.locator('#others_additionalOthers #DOB-year').click();
  await page.locator('#others_additionalOthers #DOB-year').fill('1999');
  await page.locator('#others_additionalOthers_0_gender').selectOption('2: Female');
  await page.locator('#others_additionalOthers_0_birthPlace').click();
  await page.locator('#others_additionalOthers_0_birthPlace').fill('london');
  await page.locator('#others_additionalOthers_0_addressKnowV2-No').check();
  await page.locator('#others_additionalOthers_0_addressNotKnowReason').selectOption('1: No fixed abode');
  await page.locator('#others_additionalOthers_0_telephone').click();
  await page.locator('#others_additionalOthers_0_telephone').fill('0000000');
  await page.locator('#others_additionalOthers_0_detailsHidden_No').check();
  await page.locator('#others_additionalOthers_0_childInformation').click();
  await page.locator('#others_additionalOthers_0_childInformation').fill('test');
  await page.locator('#others_additionalOthers_0_litigationIssues-NO').check();
  await page.getByRole('button', { name: 'Submit' }).click();
  await page.getByLabel('Day').click();
  await page.getByLabel('Day').fill('11');
  await page.getByRole('button', { name: 'Submit' }).click();
  await page.getByRole('button', { name: 'Save and continue' }).click();
  await page.getByRole('tab', { name: 'People in the case' }).locator('div').click();
  await page.getByText('Other person 1').click();
});