import { test, expect } from '@playwright/test';

test('test', async ({ page }) => {
  await page.goto('https://idam-web-public.aat.platform.hmcts.net/login?client_id=xuiwebapp&redirect_uri=https://manage-case.aat.platform.hmcts.net/oauth2/callback&state=hdS8eq0uJRZyJiqTg90-hDsuPXKW3tpArrOVTxro9bI&nonce=AUlYztS2TKw0iPeZQyZzhg0Yk9RFMbjVFvtax5IVY1o&response_type=code&scope=profile%20openid%20roles%20manage-user%20create-user%20search-user&prompt=');
  await page.getByLabel('Email address').click();
  await page.getByLabel('Email address').fill('fpl-ctsc-team-leader@justice.gov.uk');
  await page.getByLabel('Password').click();
  await page.getByLabel('Password').press('CapsLock');
  await page.getByLabel('Password').fill('Password12');
  await page.getByRole('button', { name: 'Sign in' }).click();
  await page.goto('https://manage-case.aat.platform.hmcts.net/cases');
  await page.getByLabel('Case type').selectOption('4: Object');
  await page.getByLabel('Apply filter').click();
  await page.getByLabel('go to case with Case reference:1738-6032-6229-').click();
  await page.goto('https://manage-case.aat.platform.hmcts.net/cases/case-details/1738603262297045#Summary');
  await page.getByLabel('Next step').selectOption('15: Object');
  await page.getByRole('button', { name: 'Go' }).click();
  await page.getByLabel('Next step').selectOption('16: Object');
  await page.getByRole('button', { name: 'Go' }).click();
  await page.getByLabel('Full name (Optional)').click();
  await page.getByLabel('Full name (Optional)').press('CapsLock');
  await page.getByLabel('Full name (Optional)').fill('Tom ');
  await page.getByLabel('Full name (Optional)').press('CapsLock');
  await page.getByLabel('Full name (Optional)').fill('Tom Cruise');
  await page.getByLabel('Day').click();
  await page.getByLabel('Day').fill('11');
  await page.getByLabel('Month').click();
  await page.getByLabel('Month').fill('04');
  await page.getByLabel('Year').click();
  await page.getByLabel('Year').fill('2000');
  await page.getByLabel('Gender (Optional)').selectOption('1: Male');
  await page.getByLabel('Place of birth (Optional)').click();
  await page.getByLabel('Place of birth (Optional)').fill('london');
  await page.getByRole('group', { name: '*Current address known? (' }).getByLabel('No').check();
  await page.getByLabel('*Reason the address is not').selectOption('1: No fixed abode');
  await page.getByLabel('Telephone number (Optional)').click();
  await page.getByLabel('Telephone number (Optional)').fill('000000000');
  await page.getByRole('group', { name: 'Do you need contact details' }).getByLabel('No').check();
  await page.getByLabel('What is this person\'s').click();
  await page.getByLabel('What is this person\'s').fill('uncle');
  await page.getByRole('group', { name: 'Do you believe this person' }).getByLabel('No', { exact: true }).check();
  await page.getByRole('button', { name: 'Submit' }).click();
  await page.getByRole('button', { name: 'Save and continue' }).click();
  await page.goto('https://manage-case.aat.platform.hmcts.net/cases/case-details/1738603262297045#Summary');
  //await page.getByLabel('Next step').selectOption('15: Object');
  await page.getByLabel('Next step').selectOption('Change other to respondent');
  await page.getByRole('button', { name: 'Go' }).click();
  await expect(page.getByRole('heading', { name: 'Change other to respondent' })).toBeVisible();
  await page.getByLabel('Select one of the others to').selectOption('1: b4ef35b4-3287-4d51-8a5d-b8e1fc6da18f');
  await page.getByRole('button', { name: 'Continue' }).click();
  await page.getByLabel('First name (Optional)', { exact: true }).click();
  await page.getByLabel('First name (Optional)', { exact: true }).fill('Tom ');
  await page.getByLabel('Last name (Optional)', { exact: true }).click();
  await page.getByLabel('Last name (Optional)', { exact: true }).press('CapsLock');
  await page.getByLabel('Last name (Optional)', { exact: true }).fill('Cruise');
  await page.getByText('Date of birth (Optional)').click();
  await page.getByLabel('Day').click();
  await page.getByLabel('Day').fill('11');
  await page.getByLabel('Month').click();
  await page.getByLabel('Month').fill('04');
  await page.getByLabel('Year').click();
  await page.getByLabel('Year').fill('1999');
  await page.getByText('First name (Optional)', { exact: true }).click();
  await page.getByText('Last name (Optional)', { exact: true }).click();
  await page.getByLabel('Last name (Optional)', { exact: true }).click();
  await page.getByText('Gender (Optional)').click();
  await page.getByText('*Current address known?').click();
  await page.getByRole('group', { name: '*Current address known?' }).getByLabel('No').check();
  await page.getByRole('group', { name: 'Telephone (Optional)' }).locator('#transformedRespondent_party_telephoneNumber_telephoneNumber').click();
  await page.getByRole('heading', { name: 'Telephone (Optional)' }).click();
  await page.getByRole('group', { name: 'Telephone (Optional)' }).locator('#transformedRespondent_party_telephoneNumber_telephoneNumber').click();
  await page.getByText('Do you need contact details').click();
  await page.getByRole('group', { name: 'Do you need contact details' }).getByLabel('No').check();
  await page.getByRole('heading', { name: 'Relationship to the child' }).click();
  await page.getByLabel('What is the respondent\'s').click();
  await page.getByRole('heading', { name: 'Ability to take part in' }).click();
  await page.getByRole('group', { name: 'Do you believe this person' }).getByLabel('No', { exact: true }).check();
  await page.getByRole('group', { name: 'Do they have legal' }).getByLabel('No').check();
  await page.getByRole('button', { name: 'Continue' }).click();
  await page.getByRole('button', { name: 'Continue' }).click();
});