import { test, expect } from '@playwright/test';

test('test', async ({ page }) => {
  await page.goto('https://idam-web-public.aat.platform.hmcts.net/login?client_id=xuiwebapp&redirect_uri=https://manage-case.aat.platform.hmcts.net/oauth2/callback&state=z8-W9IJcKWE5dN3Jb1rHm4AJTBqnwyK4LRgWyWWunV0&nonce=xSiwKsnKSXEynsn9g0DONzZ4hiv3iTeJ7dun4ZyMgkk&response_type=code&scope=profile%20openid%20roles%20manage-user%20create-user%20search-user&prompt=');
  await page.getByLabel('Email address').click();
  await page.getByLabel('Email address').fill('fpl-ctsc-admin@justice.gov.uk');
  await page.getByLabel('Password').click();
  await page.getByLabel('Password').press('CapsLock');
  await page.getByLabel('Password').fill('Password12');
  await page.locator('div').filter({ hasText: 'Forgotten password?' }).nth(3).click();
  await page.getByRole('button', { name: 'Sign in' }).click();
  await page.goto('https://manage-case.aat.platform.hmcts.net/cases');
  await page.getByLabel('go to case with Case reference:1730-7334-2785-').click();
  await page.getByText('Next step').click();
  await expect(page.getByText('Next step')).toBeVisible();
  await page.getByLabel('Next step').selectOption('20: Object');
  await page.getByRole('button', { name: 'Go' }).click();
  await page.getByRole('button', { name: 'Add new' }).click();
  await page.getByRole('heading', { name: 'Log expert report' }).click();
  await page.locator('h2').filter({ hasText: 'Report' }).click();
  await page.locator('h3').click();
  await page.getByText('What type of report have you requested? is required').click();
  await page.getByLabel('What type of report have you').selectOption('7: psychiatricOnChild');
  await page.getByRole('textbox', { name: 'Day' }).click();
  await page.getByRole('textbox', { name: 'Day' }).fill('02');
  await page.getByRole('textbox', { name: 'Month' }).click();
  await page.getByRole('textbox', { name: 'Month' }).fill('03');
  await page.getByRole('textbox', { name: 'Year' }).click();
  await page.getByRole('textbox', { name: 'Year' }).fill('2025');
  await page.getByRole('radio', { name: 'Yes' }).check();
  await page.getByRole('group', { name: 'Date approved' }).getByLabel('Day').click();
  await page.getByRole('radio', { name: 'No' }).check();
  await page.getByRole('button', { name: 'Submit' }).click();
  await page.getByRole('button', { name: 'Save and continue' }).click();
});