package uk.gov.hmcts.reform.fpl.service;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Service;
import uk.gov.hmcts.reform.fpl.config.LocalAuthorityLookupConfiguration;
import uk.gov.hmcts.reform.idam.client.IdamApi;
import uk.gov.hmcts.reform.idam.client.models.UserDetails;

import java.util.Map;

/**
 * Gets Users from Idam.
 */
@Service
public class UserService {

    private final IdamApi idamApi;
    private final LocalAuthorityLookupConfiguration localAuthorityLookupConfiguration;

    @Autowired
    public UserService(IdamApi idamApi, LocalAuthorityLookupConfiguration localAuthorityLookupConfiguration) {
        this.idamApi = idamApi;
        this.localAuthorityLookupConfiguration = localAuthorityLookupConfiguration;
    }

    /**
     * Makes a request to Idam and returns the user details for the user who is making the request.
     *
     * @param authorization the authorization token generated by the callback.
     * @return caseLocalAuthority gained from the extractEmailDomain function.
     */
    public String getLocalAuthorityCode(String authorization) {
        UserDetails userDetails = idamApi.retrieveUserDetails(authorization);
        String email = userDetails.getEmail();

        return extractEmailDomain(email);
    }

    private String extractEmailDomain(String email) {
        int start = email.indexOf("@");
        String tempState = email.toLowerCase().substring(start + 1);

        return lookUpCode(tempState);
    }

    private String lookUpCode(String emailDomain) {
        Map<String, String> lookupTable = localAuthorityLookupConfiguration.getLookupTable();

        return lookupTable.get(emailDomain);
    }
}
