package uk.gov.hmcts.reform.fpl.service;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Service;
import uk.gov.hmcts.reform.idam.client.IdamApi;
import uk.gov.hmcts.reform.idam.client.models.UserDetails;

/**
 * Gets Users from Idam.
 */
@Service
public class UserService {

    private final IdamApi idamApi;

    @Autowired
    public UserService(IdamApi idamApi) {
        this.idamApi = idamApi;
    }

    /**
     * Makes a request to Idam and returns the user details for the user who is making the request.
     *
     * @param authorization the authorization token generated by the callback.
     * @return caseLocalAuthority gained from the getEmailDomain function.
     */
    public String extractUserDomainName(String authorization) {
        UserDetails userDetails = idamApi.retrieveUserDetails(authorization);
        String email = userDetails.getEmail();
        return getEmailDomain(email);
    }

    private String getEmailDomain(String email) {
        int start = email.indexOf("@");
        String tempState = email.toLowerCase().substring(start + 1);

        int end = tempState.indexOf(".");

        return tempState.substring(0, end);
    }
}
