version: 1
update_configs:
  - package_manager: "java:gradle"
    directory: "/"
    update_schedule: "daily"
  - package_manager: "javascript"
    directory: "/"
    update_schedule: "daily"
  - package_manager: "docker"
    directory: "/"
    update_schedule: "daily"
  - package_manager: "submodules"
    directory: "/"
    update_schedule: "daily"
