package uk.gov.hmcts.reform.fpl.ccd.event;

import java.util.EnumSet;
import java.util.Set;
import org.springframework.stereotype.Component;
import uk.gov.hmcts.ccd.sdk.api.CCDConfig;
import uk.gov.hmcts.ccd.sdk.api.ConfigBuilder;
import uk.gov.hmcts.ccd.sdk.api.Permission;
import uk.gov.hmcts.reform.fpl.ccd.event.page.AddGatekeepingOrderAllocationDecisionPage;
import uk.gov.hmcts.reform.fpl.ccd.event.page.AddGatekeepingOrderConfirmStandardDirectionsPage;
import uk.gov.hmcts.reform.fpl.ccd.event.page.AddGatekeepingOrderCustomDirectionsPage;
import uk.gov.hmcts.reform.fpl.ccd.event.page.AddGatekeepingOrderIssuingJudgePage;
import uk.gov.hmcts.reform.fpl.ccd.event.page.AddGatekeepingOrderListHearingOrSendToAdminPage;
import uk.gov.hmcts.reform.fpl.ccd.event.page.AddGatekeepingOrderOrderUploadConfirmPage;
import uk.gov.hmcts.reform.fpl.ccd.event.page.AddGatekeepingOrderOrderUploadPage;
import uk.gov.hmcts.reform.fpl.ccd.event.page.AddGatekeepingOrderRouterPage;
import uk.gov.hmcts.reform.fpl.ccd.event.page.AddGatekeepingOrderSelectStandardDirectionsPage;
import uk.gov.hmcts.reform.fpl.ccd.event.page.AddGatekeepingOrderUrgentHearingAllocationPage;
import uk.gov.hmcts.reform.fpl.ccd.event.page.AddGatekeepingOrderUrgentHearingOrderPage;
import uk.gov.hmcts.reform.fpl.enums.State;
import uk.gov.hmcts.reform.fpl.model.Allocation;
import uk.gov.hmcts.reform.fpl.model.CaseData;
import uk.gov.hmcts.reform.fpl.model.CustomDirection;
import uk.gov.hmcts.reform.fpl.model.GatekeepingOrderSealDecision;
import uk.gov.hmcts.reform.fpl.model.NoticeOfProceedings;
import uk.gov.hmcts.reform.fpl.model.UserRole;
import uk.gov.hmcts.reform.fpl.model.common.JudgeAndLegalAdvisor;
import uk.gov.hmcts.reform.fpl.model.event.GatekeepingOrderEventData;

/**
 * Generated by ccd-definition-converter from CARE_SUPERVISION_EPO on migration; owned by this service team.
 *
 * <p>Event {@code addGatekeepingOrder} for case type {@code CARE_SUPERVISION_EPO}.
 */
@Component
public class AddGatekeepingOrder implements CCDConfig<CaseData, State, UserRole> {
    /**
     * The CCD event ID.
     */
    public static final String ADD_GATEKEEPING_ORDER = "addGatekeepingOrder";

    /**
     * Registers event {@code addGatekeepingOrder}.
     *
     * @param builder the config builder
     */
    @Override
    public void configure(ConfigBuilder<CaseData, State, UserRole> builder) {
        var fields = builder.event(ADD_GATEKEEPING_ORDER)
            .forStateTransition(EnumSet.of(State.GATEKEEPING, State.CASE_MANAGEMENT), State.GATEKEEPING_LISTING)
            .name("Judicial Gatekeeping")
            .displayOrder(1)
            .showSummary()
            .showEventNotes()
            .explicitGrants()
            .grant(Permission.CR, UserRole.CASEWORKER_PUBLICLAW_COURTADMIN, UserRole.CASEWORKER_PUBLICLAW_GATEKEEPER, UserRole.CASEWORKER_PUBLICLAW_JUDICIARY, UserRole.CASEWORKER_PUBLICLAW_SUPERUSER)
            .grant(Set.of(Permission.R), UserRole.CASEWORKER_PUBLICLAW_MAGISTRATE, UserRole.CASEWORKER_PUBLICLAW_SOLICITOR)
            .fields();
        AddGatekeepingOrderAllocationDecisionPage.apply(fields);
        AddGatekeepingOrderConfirmStandardDirectionsPage.apply(fields);
        AddGatekeepingOrderCustomDirectionsPage.apply(fields);
        AddGatekeepingOrderIssuingJudgePage.apply(fields);
        AddGatekeepingOrderListHearingOrSendToAdminPage.apply(fields);
        AddGatekeepingOrderOrderUploadPage.apply(fields);
        AddGatekeepingOrderOrderUploadConfirmPage.apply(fields);
        AddGatekeepingOrderRouterPage.apply(fields);
        AddGatekeepingOrderSelectStandardDirectionsPage.apply(fields);
        AddGatekeepingOrderUrgentHearingAllocationPage.apply(fields);
        AddGatekeepingOrderUrgentHearingOrderPage.apply(fields);
        fields.complex(CaseData::getGatekeepingOrderEventData)
                    .complex(GatekeepingOrderEventData::getCustomDirections, CustomDirection.class)
                    .mandatory(CustomDirection::getTitle)
                    .optional(CustomDirection::getDescription)
                    .mandatory(CustomDirection::getAssignee)
                    .mandatory(CustomDirection::getDueDateType)
                    .mandatory(CustomDirection::getDateToBeCompletedBy)
                    .fieldShowCondition("customDirections.dueDateType=\"DATE\"")
                    .mandatory(CustomDirection::getDaysBeforeHearing)
                    .fieldShowCondition("customDirections.dueDateType=\"DAYS\"").done().done();
        fields.complex(CaseData::getGatekeepingOrderEventData)
                    .complexScope(GatekeepingOrderEventData::getGatekeepingOrderSealDecision)
                    .readonly(GatekeepingOrderSealDecision::getDraftDocument)
                    .mandatory(GatekeepingOrderSealDecision::getOrderStatus)
                    .fieldShowCondition("nextSteps!=\"*\"")
                    .mandatory(GatekeepingOrderSealDecision::getDateOfIssue)
                    .readonly(GatekeepingOrderSealDecision::getNextSteps)
                    .fieldShowCondition("nextSteps=\"DO_NOT_SHOW\"").done().done();
        fields.complex(CaseData::getGatekeepingOrderEventData)
                    .complexScope(GatekeepingOrderEventData::getGatekeepingOrderIssuingJudge)
                    .readonly(JudgeAndLegalAdvisor::getAllocatedJudgeLabel)
                    .eventLabel(" ")
                    .optional(JudgeAndLegalAdvisor::getUseAllocatedJudge)
                    .eventLabel("Is this the judge issuing the order?")
                    .optional(JudgeAndLegalAdvisor::getJudgeTitle)
                    .eventLabel("Who is issuing the order?")
                    .mandatory(JudgeAndLegalAdvisor::getOtherTitle)
                    .eventLabel("Title")
                    .mandatory(JudgeAndLegalAdvisor::getJudgeLastName)
                    .eventLabel("Last name")
                    .mandatory(JudgeAndLegalAdvisor::getJudgeFullName)
                    .eventLabel("Full name")
                    .mandatory(JudgeAndLegalAdvisor::getJudgeEmailAddress)
                    .eventLabel("Email Address")
                    .optional(JudgeAndLegalAdvisor::getLegalAdvisorName)
                    .eventLabel("Justices' Legal Adviser's full name").done().done();
        fields.complexScope(CaseData::getNoticeOfProceedings)
                    .mandatory(NoticeOfProceedings::getProceedingTypes)
                    .eventLabel("Which notice of proceedings need to be sent with this order?").done();
        fields.complex(CaseData::getGatekeepingOrderEventData)
                    .complexScope(GatekeepingOrderEventData::getUrgentHearingAllocation)
                    .mandatory(Allocation::getJudgeLevelRadio)
                    .fieldShowCondition("urgentHearingAllocation.allocationProposalPresent=\"Yes\"")
                    .mandatory(Allocation::getProposalV2)
                    .fieldShowCondition("urgentHearingAllocation.allocationProposalPresent=\"No\" OR urgentHearingAllocation.judgeLevelRadio=\"No\"")
                    .mandatory(Allocation::getProposalReason)
                    .fieldShowCondition("urgentHearingAllocation.allocationProposalPresent=\"No\" OR urgentHearingAllocation.judgeLevelRadio=\"No\"")
                    .readonly(Allocation::getAllocationProposalPresent)
                    .fieldShowCondition("urgentHearingAllocation.allocationProposalPresent=\"DO_NOT_SHOW\"").done().done();
    }
}
