package uk.gov.hmcts.reform.fpl.ccd.event;

import java.util.Set;
import org.springframework.stereotype.Component;
import uk.gov.hmcts.ccd.sdk.api.CCDConfig;
import uk.gov.hmcts.ccd.sdk.api.ConfigBuilder;
import uk.gov.hmcts.ccd.sdk.api.Permission;
import uk.gov.hmcts.reform.fpl.enums.State;
import uk.gov.hmcts.reform.fpl.model.CaseData;
import uk.gov.hmcts.reform.fpl.model.UserRole;

/**
 * Generated by ccd-definition-converter from CARE_SUPERVISION_EPO on migration; owned by this service team.
 *
 * <p>Event {@code addStatementOfService} for case type {@code CARE_SUPERVISION_EPO}.
 */
@Component
public class AddStatementOfService implements CCDConfig<CaseData, State, UserRole> {
    /**
     * The CCD event ID.
     */
    public static final String ADD_STATEMENT_OF_SERVICE = "addStatementOfService";

    /**
     * Registers event {@code addStatementOfService}.
     *
     * @param builder the config builder
     */
    @Override
    public void configure(ConfigBuilder<CaseData, State, UserRole> builder) {
        var fields = builder.event(ADD_STATEMENT_OF_SERVICE)
            .forStates(State.SUBMITTED, State.GATEKEEPING_LISTING, State.GATEKEEPING, State.CASE_MANAGEMENT, State.FINAL_HEARING, State.CLOSED)
            .name("Add statement of service (c9)")
            .description("Add statement of service")
            .displayOrder(13)
            .showSummary()
            .showEventNotes()
            .explicitGrants()
            .grant(Permission.CR, UserRole.CHILDSOLICITORA, UserRole.EPSMANAGING, UserRole.LAMANAGING, UserRole.LASHARED, UserRole.LASOLICITOR, UserRole.SOLICITORA)
            .grant(Set.of(Permission.R), UserRole.CASEWORKER_PUBLICLAW_SOLICITOR)
            .fields();
        fields.page("1");
        fields.readonly(CaseData::getC9Declaration);
        fields.mandatory(CaseData::getStatementOfService);
        fields.readonly(CaseData::getServiceDeclarationLabel);
        fields.mandatory(CaseData::getServiceConsent);
    }
}
