package uk.gov.hmcts.reform.fpl.ccd.event;

import java.util.Set;
import org.springframework.stereotype.Component;
import uk.gov.hmcts.ccd.sdk.api.CCDConfig;
import uk.gov.hmcts.ccd.sdk.api.ConfigBuilder;
import uk.gov.hmcts.ccd.sdk.api.Permission;
import uk.gov.hmcts.reform.fpl.enums.State;
import uk.gov.hmcts.reform.fpl.model.CaseData;
import uk.gov.hmcts.reform.fpl.model.UserRole;

/**
 * Generated by ccd-definition-converter from CARE_SUPERVISION_EPO on migration; owned by this service team.
 *
 * <p>Event {@code addStatementOfService-PREPARE_FOR_HEARING} for case type {@code CARE_SUPERVISION_EPO}.
 */
@Component
public class AddStatementOfServicePREPAREFORHEARING implements CCDConfig<CaseData, State, UserRole> {
    /**
     * The CCD event ID.
     */
    public static final String ADD_STATEMENT_OF_SERVICE_PREPARE_FOR_HEARING = "addStatementOfService-PREPARE_FOR_HEARING";

    /**
     * Registers event {@code addStatementOfService-PREPARE_FOR_HEARING}.
     *
     * @param builder the config builder
     */
    @Override
    public void configure(ConfigBuilder<CaseData, State, UserRole> builder) {
        builder.event(ADD_STATEMENT_OF_SERVICE_PREPARE_FOR_HEARING)
            .forState(State.CASE_MANAGEMENT)
            .name("Add statement of service (c9)")
            .description("Add statement of service")
            .displayOrder(12)
            .showSummary()
            .explicitGrants()
            .grant(Set.of(Permission.R), UserRole.CASEWORKER_PUBLICLAW_SOLICITOR, UserRole.EPSMANAGING, UserRole.LAMANAGING, UserRole.LASHARED, UserRole.LASOLICITOR);
    }
}
