package uk.gov.hmcts.reform.fpl.ccd.event;

import java.util.Set;
import org.springframework.stereotype.Component;
import uk.gov.hmcts.ccd.sdk.api.CCDConfig;
import uk.gov.hmcts.ccd.sdk.api.ConfigBuilder;
import uk.gov.hmcts.ccd.sdk.api.Permission;
import uk.gov.hmcts.reform.fpl.enums.State;
import uk.gov.hmcts.reform.fpl.model.CaseData;
import uk.gov.hmcts.reform.fpl.model.UserRole;
import uk.gov.hmcts.reform.fpl.model.event.AllocateJudgeEventData;

/**
 * Generated by ccd-definition-converter from CARE_SUPERVISION_EPO on migration; owned by this service team.
 *
 * <p>Event {@code allocatedJudge} for case type {@code CARE_SUPERVISION_EPO}.
 */
@Component
public class AllocatedJudge implements CCDConfig<CaseData, State, UserRole> {
    /**
     * The CCD event ID.
     */
    public static final String ALLOCATED_JUDGE = "allocatedJudge";

    /**
     * Registers event {@code allocatedJudge}.
     *
     * @param builder the config builder
     */
    @Override
    public void configure(ConfigBuilder<CaseData, State, UserRole> builder) {
        var fields = builder.event(ALLOCATED_JUDGE)
            .forStates(State.GATEKEEPING, State.GATEKEEPING_LISTING, State.CASE_MANAGEMENT, State.FINAL_HEARING)
            .name("Allocated Judge")
            .description("Add allocated judge to a case")
            .displayOrder(4)
            .showSummary(false)
            .explicitGrants()
            .grant(Permission.CR, UserRole.CASEWORKER_PUBLICLAW_COURTADMIN, UserRole.CASEWORKER_PUBLICLAW_GATEKEEPER, UserRole.CASEWORKER_PUBLICLAW_JUDICIARY)
            .grant(Set.of(Permission.R), UserRole.CASEWORKER_PUBLICLAW_CAFCASS, UserRole.CASEWORKER_PUBLICLAW_MAGISTRATE, UserRole.CASEWORKER_PUBLICLAW_SOLICITOR)
            .fields();
        fields.page("AllocatedJudge");
        fields.complex(CaseData::getAllocateJudgeEventData)
                    .mandatory(AllocateJudgeEventData::getJudgeType)
                    .mandatory(AllocateJudgeEventData::getJudicialUser)
                    .fieldShowCondition("judgeType = \"SALARIED_JUDGE\" OR judgeType = \"FEE_PAID_JUDGE\"")
                    .mandatory(AllocateJudgeEventData::getFeePaidJudgeTitle)
                    .fieldShowCondition("judgeType = \"FEE_PAID_JUDGE\"").done();
        fields.readonly(CaseData::getManualJudgeAllocationWarning)
                    .fieldShowCondition("judgeType = \"LEGAL_ADVISOR\"");
        fields.complex(CaseData::getAllocateJudgeEventData)
                    .optional(AllocateJudgeEventData::getManualJudgeDetails)
                    .fieldShowCondition("judgeType = \"LEGAL_ADVISOR\"").done();
    }
}
