package uk.gov.hmcts.reform.fpl.ccd.event;

import java.util.Set;
import org.springframework.stereotype.Component;
import uk.gov.hmcts.ccd.sdk.api.CCDConfig;
import uk.gov.hmcts.ccd.sdk.api.ConfigBuilder;
import uk.gov.hmcts.ccd.sdk.api.Permission;
import uk.gov.hmcts.reform.fpl.ccd.event.page.AmendChildrenAdditionRepresentationPage;
import uk.gov.hmcts.reform.fpl.ccd.event.page.AmendChildrenChildrenDetailsPage;
import uk.gov.hmcts.reform.fpl.ccd.event.page.AmendChildrenMainRepresentativePage;
import uk.gov.hmcts.reform.fpl.enums.State;
import uk.gov.hmcts.reform.fpl.model.CaseData;
import uk.gov.hmcts.reform.fpl.model.UserRole;

/**
 * Generated by ccd-definition-converter from CARE_SUPERVISION_EPO on migration; owned by this service team.
 *
 * <p>Event {@code amendChildren} for case type {@code CARE_SUPERVISION_EPO}.
 */
@Component
public class AmendChildren implements CCDConfig<CaseData, State, UserRole> {
    /**
     * The CCD event ID.
     */
    public static final String AMEND_CHILDREN = "amendChildren";

    /**
     * Registers event {@code amendChildren}.
     *
     * @param builder the config builder
     */
    @Override
    public void configure(ConfigBuilder<CaseData, State, UserRole> builder) {
        var fields = builder.event(AMEND_CHILDREN)
            .forStates(State.SUBMITTED, State.GATEKEEPING_LISTING, State.GATEKEEPING, State.CASE_MANAGEMENT, State.FINAL_HEARING)
            .name("Children")
            .description("Amending the children for the case")
            .displayOrder(19)
            .showSummary()
            .showEventNotes()
            .explicitGrants()
            .grant(Permission.CR, UserRole.CASEWORKER_PUBLICLAW_COURTADMIN, UserRole.CASEWORKER_PUBLICLAW_JUDICIARY, UserRole.CHILDSOLICITORA, UserRole.EPSMANAGING, UserRole.LAMANAGING, UserRole.LASHARED, UserRole.LASOLICITOR, UserRole.SOLICITORA)
            .grant(Set.of(Permission.R), UserRole.CASEWORKER_PUBLICLAW_GATEKEEPER, UserRole.CASEWORKER_PUBLICLAW_MAGISTRATE)
            .fields();
        AmendChildrenChildrenDetailsPage.apply(fields);
        AmendChildrenMainRepresentativePage.apply(fields);
        AmendChildrenAdditionRepresentationPage.apply(fields);
    }
}
