package uk.gov.hmcts.reform.fpl.ccd.event;

import java.util.Set;
import org.springframework.stereotype.Component;
import uk.gov.hmcts.ccd.sdk.api.CCDConfig;
import uk.gov.hmcts.ccd.sdk.api.ConfigBuilder;
import uk.gov.hmcts.ccd.sdk.api.Permission;
import uk.gov.hmcts.reform.fpl.enums.State;
import uk.gov.hmcts.reform.fpl.model.CaseData;
import uk.gov.hmcts.reform.fpl.model.InternationalElement;
import uk.gov.hmcts.reform.fpl.model.UserRole;

/**
 * Generated by ccd-definition-converter from CARE_SUPERVISION_EPO on migration; owned by this service team.
 *
 * <p>Event {@code amendInternationalElement} for case type {@code CARE_SUPERVISION_EPO}.
 */
@Component
public class AmendInternationalElement implements CCDConfig<CaseData, State, UserRole> {
    /**
     * The CCD event ID.
     */
    public static final String AMEND_INTERNATIONAL_ELEMENT = "amendInternationalElement";

    /**
     * Registers event {@code amendInternationalElement}.
     *
     * @param builder the config builder
     */
    @Override
    public void configure(ConfigBuilder<CaseData, State, UserRole> builder) {
        var fields = builder.event(AMEND_INTERNATIONAL_ELEMENT)
            .forStates(State.SUBMITTED, State.CASE_MANAGEMENT, State.FINAL_HEARING)
            .name("International element")
            .description("Amending the international element")
            .displayOrder(24)
            .showSummary(false)
            .showEventNotes()
            .explicitGrants()
            .grant(Permission.CR, UserRole.CASEWORKER_PUBLICLAW_COURTADMIN)
            .grant(Set.of(Permission.R), UserRole.CASEWORKER_PUBLICLAW_GATEKEEPER, UserRole.CASEWORKER_PUBLICLAW_JUDICIARY, UserRole.CASEWORKER_PUBLICLAW_MAGISTRATE, UserRole.CASEWORKER_PUBLICLAW_SOLICITOR)
            .fields();
        fields.page("1");
        fields.mandatory(CaseData::getInternationalElement);
        fields.complexScope(CaseData::getInternationalElement)
                    .readonly(InternationalElement::getInternationalElementNotice)
                    .eventLabel("<div class='panel panel-border-wide govuk-!-font-size-16'>Only complete this section if there is an international element to this application.</div>")
                    .mandatory(InternationalElement::getWhichCountriesInvolved)
                    .eventLabel("Which other countries are involved?")
                    .mandatory(InternationalElement::getOutsideHagueConvention)
                    .eventLabel("Are any of these countries outside of the Hague Convention?")
                    .mandatory(InternationalElement::getImportantDetails)
                    .eventLabel("Provide all important details").done();
    }
}
