package uk.gov.hmcts.reform.fpl.ccd.event;

import java.util.Set;
import org.springframework.stereotype.Component;
import uk.gov.hmcts.ccd.sdk.api.CCDConfig;
import uk.gov.hmcts.ccd.sdk.api.ConfigBuilder;
import uk.gov.hmcts.ccd.sdk.api.Permission;
import uk.gov.hmcts.reform.fpl.enums.State;
import uk.gov.hmcts.reform.fpl.model.CaseData;
import uk.gov.hmcts.reform.fpl.model.HearingPreferences;
import uk.gov.hmcts.reform.fpl.model.UserRole;

/**
 * Generated by ccd-definition-converter from CARE_SUPERVISION_EPO on migration; owned by this service team.
 *
 * <p>Event {@code amendAttendingHearing} for case type {@code CARE_SUPERVISION_EPO}.
 */
@Component
public class AmendAttendingHearing implements CCDConfig<CaseData, State, UserRole> {
    /**
     * The CCD event ID.
     */
    public static final String AMEND_ATTENDING_HEARING = "amendAttendingHearing";

    /**
     * Registers event {@code amendAttendingHearing}.
     *
     * @param builder the config builder
     */
    @Override
    public void configure(ConfigBuilder<CaseData, State, UserRole> builder) {
        var fields = builder.event(AMEND_ATTENDING_HEARING)
            .forStates(State.SUBMITTED, State.GATEKEEPING, State.GATEKEEPING_LISTING, State.CASE_MANAGEMENT, State.FINAL_HEARING)
            .name("Court services")
            .description("Amend extra support needed for anyone to take part in hearing")
            .displayOrder(25)
            .showSummary(false)
            .showEventNotes()
            .explicitGrants()
            .grant(Permission.CR, UserRole.CASEWORKER_PUBLICLAW_COURTADMIN)
            .grant(Set.of(Permission.R), UserRole.CASEWORKER_PUBLICLAW_GATEKEEPER, UserRole.CASEWORKER_PUBLICLAW_JUDICIARY, UserRole.CASEWORKER_PUBLICLAW_MAGISTRATE, UserRole.CASEWORKER_PUBLICLAW_SOLICITOR)
            .fields();
        fields.page("1");
        fields.complex(CaseData::getHearingPreferences)
                    .optional(HearingPreferences::getWhichCourtServices)
                    .eventLabel("Choose which court services you need to be considered before first hearing")
                    .mandatory(HearingPreferences::getInterpreterDetails)
                    .eventLabel("Interpreter details")
                    .mandatory(HearingPreferences::getIntermediaryDetails)
                    .eventLabel("Intermediary details")
                    .mandatory(HearingPreferences::getDisabilityAssistanceDetails)
                    .eventLabel("Disability facilities and assistance details")
                    .mandatory(HearingPreferences::getExtraSecurityMeasuresDetails)
                    .eventLabel("Separate waiting rooms details")
                    .mandatory(HearingPreferences::getSomethingElseDetails)
                    .eventLabel("What else is needed?").done();
    }
}
