package uk.gov.hmcts.reform.fpl.ccd.event;

import java.util.Set;
import org.springframework.stereotype.Component;
import uk.gov.hmcts.ccd.sdk.api.CCDConfig;
import uk.gov.hmcts.ccd.sdk.api.ConfigBuilder;
import uk.gov.hmcts.ccd.sdk.api.Permission;
import uk.gov.hmcts.reform.fpl.ccd.event.page.CaseProgressionReportPage1;
import uk.gov.hmcts.reform.fpl.ccd.event.page.CaseProgressionReportPage2;
import uk.gov.hmcts.reform.fpl.enums.State;
import uk.gov.hmcts.reform.fpl.model.CaseData;
import uk.gov.hmcts.reform.fpl.model.UserRole;

/**
 * Generated by ccd-definition-converter from CARE_SUPERVISION_EPO on migration; owned by this service team.
 *
 * <p>Event {@code caseProgressionReport} for case type {@code CARE_SUPERVISION_EPO}.
 */
@Component
public class CaseProgressionReport implements CCDConfig<CaseData, State, UserRole> {
    /**
     * The CCD event ID.
     */
    public static final String CASE_PROGRESSION_REPORT = "caseProgressionReport";

    /**
     * Registers event {@code caseProgressionReport}.
     *
     * @param builder the config builder
     */
    @Override
    public void configure(ConfigBuilder<CaseData, State, UserRole> builder) {
        var fields = builder.event(CASE_PROGRESSION_REPORT)
            .forStates(State.OPEN, State.SUBMITTED, State.GATEKEEPING, State.GATEKEEPING_LISTING, State.CASE_MANAGEMENT, State.FINAL_HEARING, State.CLOSED, State.DELETED, State.RETURNED)
            .name("Case progression report")
            .description("Cases at risk and Cases not meeting timetable")
            .displayOrder(35)
            .showSummary(false)
            .endButtonLabel("Done")
            .explicitGrants()
            .grant(Permission.CRUD, UserRole.CASEWORKER_PUBLICLAW_COURTADMIN, UserRole.CASEWORKER_PUBLICLAW_JUDICIARY)
            .grant(Set.of(Permission.R), UserRole.CASEWORKER_PUBLICLAW_GATEKEEPER, UserRole.CASEWORKER_PUBLICLAW_MAGISTRATE)
            .fields();
        CaseProgressionReportPage1.apply(fields);
        CaseProgressionReportPage2.apply(fields);
    }
}
