package uk.gov.hmcts.reform.fpl.ccd.event;

import org.springframework.stereotype.Component;
import uk.gov.hmcts.ccd.sdk.api.CCDConfig;
import uk.gov.hmcts.ccd.sdk.api.ConfigBuilder;
import uk.gov.hmcts.ccd.sdk.api.Permission;
import uk.gov.hmcts.reform.fpl.enums.State;
import uk.gov.hmcts.reform.fpl.model.CaseData;
import uk.gov.hmcts.reform.fpl.model.UserRole;

/**
 * Generated by ccd-definition-converter from CARE_SUPERVISION_EPO on migration; owned by this service team.
 *
 * <p>Event {@code changeCaseName-superuser} for case type {@code CARE_SUPERVISION_EPO}.
 */
@Component
public class ChangeCaseNameSuperuser implements CCDConfig<CaseData, State, UserRole> {
    /**
     * The CCD event ID.
     */
    public static final String CHANGE_CASE_NAME_SUPERUSER = "changeCaseName-superuser";

    /**
     * Registers event {@code changeCaseName-superuser}.
     *
     * @param builder the config builder
     */
    @Override
    public void configure(ConfigBuilder<CaseData, State, UserRole> builder) {
        var fields = builder.event(CHANGE_CASE_NAME_SUPERUSER)
            .forStates(State.SUBMITTED, State.GATEKEEPING, State.CASE_MANAGEMENT, State.FINAL_HEARING, State.CLOSED)
            .name("Change case name")
            .displayOrder(20)
            .showSummary()
            .publishToCamunda()
            .explicitGrants()
            .grant(Permission.CR, UserRole.CASEWORKER_PUBLICLAW_SUPERUSER)
            .fields();
        fields.page("1");
        fields.mandatory(CaseData::getCaseName)
                    .caseEventFieldLabel("Case name")
                    .publish(false);
    }
}
