package uk.gov.hmcts.reform.fpl.ccd.event;

import java.util.EnumSet;
import org.springframework.stereotype.Component;
import uk.gov.hmcts.ccd.sdk.api.CCDConfig;
import uk.gov.hmcts.ccd.sdk.api.ConfigBuilder;
import uk.gov.hmcts.reform.fpl.enums.State;
import uk.gov.hmcts.reform.fpl.model.CaseData;
import uk.gov.hmcts.reform.fpl.model.UserRole;

/**
 * Generated by ccd-definition-converter from CARE_SUPERVISION_EPO on migration; owned by this service team.
 *
 * <p>Event {@code closeCase} for case type {@code CARE_SUPERVISION_EPO}.
 */
@Component
public class CloseCase implements CCDConfig<CaseData, State, UserRole> {
    /**
     * The CCD event ID.
     */
    public static final String CLOSE_CASE = "closeCase";

    /**
     * Registers event {@code closeCase}.
     *
     * @param builder the config builder
     */
    @Override
    public void configure(ConfigBuilder<CaseData, State, UserRole> builder) {
        builder.event(CLOSE_CASE)
            .forStateTransition(EnumSet.of(State.SUBMITTED, State.GATEKEEPING, State.CASE_MANAGEMENT, State.FINAL_HEARING), State.CLOSED)
            .name("Close the case")
            .displayOrder(22)
            .showSummary(false)
            .showEventNotes()
            .endButtonLabel("Submit")
            .explicitGrants();
    }
}
