package uk.gov.hmcts.reform.fpl.ccd.event;

import java.util.Set;
import org.springframework.stereotype.Component;
import uk.gov.hmcts.ccd.sdk.api.CCDConfig;
import uk.gov.hmcts.ccd.sdk.api.ConfigBuilder;
import uk.gov.hmcts.ccd.sdk.api.Permission;
import uk.gov.hmcts.reform.fpl.enums.State;
import uk.gov.hmcts.reform.fpl.model.CaseData;
import uk.gov.hmcts.reform.fpl.model.UserRole;

/**
 * Generated by ccd-definition-converter from CARE_SUPERVISION_EPO on migration; owned by this service team.
 *
 * <p>Event {@code createNoticeOfProceedings-PREPARE_FOR_HEARING} for case type {@code CARE_SUPERVISION_EPO}.
 */
@Component
public class CreateNoticeOfProceedingsPREPAREFORHEARING implements CCDConfig<CaseData, State, UserRole> {
    /**
     * The CCD event ID.
     */
    public static final String CREATE_NOTICE_OF_PROCEEDINGS_PREPARE_FOR_HEARING = "createNoticeOfProceedings-PREPARE_FOR_HEARING";

    /**
     * Registers event {@code createNoticeOfProceedings-PREPARE_FOR_HEARING}.
     *
     * @param builder the config builder
     */
    @Override
    public void configure(ConfigBuilder<CaseData, State, UserRole> builder) {
        builder.event(CREATE_NOTICE_OF_PROCEEDINGS_PREPARE_FOR_HEARING)
            .forState(State.CASE_MANAGEMENT)
            .name("Create notice of proceedings")
            .displayOrder(10)
            .showSummary()
            .explicitGrants()
            .grant(Set.of(Permission.R), UserRole.CASEWORKER_PUBLICLAW_COURTADMIN, UserRole.CASEWORKER_PUBLICLAW_SOLICITOR);
    }
}
