package uk.gov.hmcts.reform.fpl.ccd.event;

import java.util.Set;
import org.springframework.stereotype.Component;
import uk.gov.hmcts.ccd.sdk.api.CCDConfig;
import uk.gov.hmcts.ccd.sdk.api.ConfigBuilder;
import uk.gov.hmcts.ccd.sdk.api.Permission;
import uk.gov.hmcts.reform.fpl.ccd.event.page.DraftSDOAllPartiesDirectionsPage;
import uk.gov.hmcts.reform.fpl.ccd.event.page.DraftSDOCafcassDirectionsPage;
import uk.gov.hmcts.reform.fpl.ccd.event.page.DraftSDOCourtDirectionsPage;
import uk.gov.hmcts.reform.fpl.ccd.event.page.DraftSDODocumentReviewPage;
import uk.gov.hmcts.reform.fpl.ccd.event.page.DraftSDOJudgeAndLegalAdvisorPage;
import uk.gov.hmcts.reform.fpl.ccd.event.page.DraftSDOLocalAuthorityDirectionsPage;
import uk.gov.hmcts.reform.fpl.ccd.event.page.DraftSDONoticeOfProceedingsSDOPage;
import uk.gov.hmcts.reform.fpl.ccd.event.page.DraftSDOOrderUploadConfirmPage;
import uk.gov.hmcts.reform.fpl.ccd.event.page.DraftSDOOrderUploadPage;
import uk.gov.hmcts.reform.fpl.ccd.event.page.DraftSDOOtherPartiesDirectionsPage;
import uk.gov.hmcts.reform.fpl.ccd.event.page.DraftSDOParentsAndRespondentsDirectionsPage;
import uk.gov.hmcts.reform.fpl.ccd.event.page.DraftSDORoutingPage;
import uk.gov.hmcts.reform.fpl.ccd.event.page.DraftSDOSdoDateOfIssuePage;
import uk.gov.hmcts.reform.fpl.ccd.event.page.DraftSDOUrgentHearingAllocationPage;
import uk.gov.hmcts.reform.fpl.ccd.event.page.DraftSDOUrgentHearingOrderPage;
import uk.gov.hmcts.reform.fpl.enums.State;
import uk.gov.hmcts.reform.fpl.model.Allocation;
import uk.gov.hmcts.reform.fpl.model.CaseData;
import uk.gov.hmcts.reform.fpl.model.UserRole;
import uk.gov.hmcts.reform.fpl.model.event.GatekeepingOrderEventData;

/**
 * Generated by ccd-definition-converter from CARE_SUPERVISION_EPO on migration; owned by this service team.
 *
 * <p>Event {@code draftSDO} for case type {@code CARE_SUPERVISION_EPO}.
 */
@Component
public class DraftSDO implements CCDConfig<CaseData, State, UserRole> {
    /**
     * The CCD event ID.
     */
    public static final String DRAFT_SDO = "draftSDO";

    /**
     * Registers event {@code draftSDO}.
     *
     * @param builder the config builder
     */
    @Override
    public void configure(ConfigBuilder<CaseData, State, UserRole> builder) {
        var fields = builder.event(DRAFT_SDO)
            .forStates(State.GATEKEEPING, State.CASE_MANAGEMENT)
            .name("Add the gatekeeping order")
            .displayOrder(9)
            .showSummary()
            .showEventNotes()
            .explicitGrants()
            .grant(Set.of(Permission.R), UserRole.CASEWORKER_PUBLICLAW_COURTADMIN, UserRole.CASEWORKER_PUBLICLAW_GATEKEEPER, UserRole.CASEWORKER_PUBLICLAW_JUDICIARY, UserRole.CASEWORKER_PUBLICLAW_MAGISTRATE, UserRole.CASEWORKER_PUBLICLAW_SOLICITOR)
            .fields();
        DraftSDORoutingPage.apply(fields);
        DraftSDOSdoDateOfIssuePage.apply(fields);
        DraftSDOJudgeAndLegalAdvisorPage.apply(fields);
        DraftSDOAllPartiesDirectionsPage.apply(fields);
        DraftSDOLocalAuthorityDirectionsPage.apply(fields);
        DraftSDOParentsAndRespondentsDirectionsPage.apply(fields);
        DraftSDOCafcassDirectionsPage.apply(fields);
        DraftSDOOtherPartiesDirectionsPage.apply(fields);
        DraftSDOCourtDirectionsPage.apply(fields);
        DraftSDOOrderUploadPage.apply(fields);
        DraftSDOOrderUploadConfirmPage.apply(fields);
        DraftSDODocumentReviewPage.apply(fields);
        DraftSDONoticeOfProceedingsSDOPage.apply(fields);
        DraftSDOUrgentHearingAllocationPage.apply(fields);
        DraftSDOUrgentHearingOrderPage.apply(fields);
        fields.complex(CaseData::getGatekeepingOrderEventData)
                    .complexScope(GatekeepingOrderEventData::getUrgentHearingAllocation)
                    .mandatory(Allocation::getJudgeLevelRadio)
                    .fieldShowCondition("urgentHearingAllocation.allocationProposalPresent=\"Yes\"")
                    .mandatory(Allocation::getProposal)
                    .fieldShowCondition("urgentHearingAllocation.allocationProposalPresent=\"No\" OR urgentHearingAllocation.judgeLevelRadio=\"No\"")
                    .mandatory(Allocation::getProposalReason)
                    .fieldShowCondition("urgentHearingAllocation.allocationProposalPresent=\"No\" OR urgentHearingAllocation.judgeLevelRadio=\"No\"")
                    .readonly(Allocation::getAllocationProposalPresent)
                    .fieldShowCondition("urgentHearingAllocation.allocationProposalPresent=\"DO_NOT_SHOW\"").done().done();
    }
}
