package uk.gov.hmcts.reform.fpl.ccd.event;

import java.util.Set;
import org.springframework.stereotype.Component;
import uk.gov.hmcts.ccd.sdk.api.CCDConfig;
import uk.gov.hmcts.ccd.sdk.api.ConfigBuilder;
import uk.gov.hmcts.ccd.sdk.api.Permission;
import uk.gov.hmcts.reform.fpl.enums.State;
import uk.gov.hmcts.reform.fpl.model.Supplement;
import uk.gov.hmcts.reform.fpl.model.SupportingEvidenceBundle;
import uk.gov.hmcts.reform.fpl.model.CaseData;
import uk.gov.hmcts.reform.fpl.model.common.SubmittedC1WithSupplementBundle;
import uk.gov.hmcts.reform.fpl.model.UserRole;

/**
 * Generated by ccd-definition-converter from CARE_SUPERVISION_EPO on migration; owned by this service team.
 *
 * <p>Event {@code enterC1WithSupplement} for case type {@code CARE_SUPERVISION_EPO}.
 */
@Component
public class EnterC1WithSupplement implements CCDConfig<CaseData, State, UserRole> {
    /**
     * The CCD event ID.
     */
    public static final String ENTER_C1_WITH_SUPPLEMENT = "enterC1WithSupplement";

    /**
     * Registers event {@code enterC1WithSupplement}.
     *
     * @param builder the config builder
     */
    @Override
    public void configure(ConfigBuilder<CaseData, State, UserRole> builder) {
        var fields = builder.event(ENTER_C1_WITH_SUPPLEMENT)
            .forStates(State.OPEN, State.RETURNED)
            .name("C1 with supplement")
            .description("Entering C1 with supplement")
            .displayOrder(12)
            .showCondition("c1Application!=\"Yes\"")
            .showSummary()
            .explicitGrants()
            .grant(Permission.CR, UserRole.CHILDSOLICITORA, UserRole.EPSMANAGING, UserRole.LAMANAGING, UserRole.LASOLICITOR, UserRole.SOLICITORA)
            .grant(Set.of(Permission.R), UserRole.CASEWORKER_PUBLICLAW_SOLICITOR)
            .fields();
        fields.page("1");
        fields.complex(CaseData::getSubmittedC1WithSupplement)
                    .readonly(SubmittedC1WithSupplementBundle::getIsDocumentUploaded)
                    .fieldShowCondition("submittedC1WithSupplement.isDocumentUploaded=\"DO_NOT_SHOW\"")
                    .mandatory(SubmittedC1WithSupplementBundle::getClearSubmittedC1WithSupplement)
                    .fieldShowCondition("submittedC1WithSupplement.isDocumentUploaded=\"YES\"")
                    .mandatory(SubmittedC1WithSupplementBundle::getDocument)
                    .fieldShowCondition("submittedC1WithSupplement.clearSubmittedC1WithSupplement!=\"YES\"")
                    .eventLabel("Upload application")
                    .readonly(SubmittedC1WithSupplementBundle::getDocumentAcknowledgeLabel)
                    .fieldShowCondition("documentAcknowledge!=\"ACK_RELATED_TO_CASE\" AND submittedC1WithSupplement.clearSubmittedC1WithSupplement!=\"YES\"")
                    .eventLabel("<br /><div class='govuk-warning-text'><span class='govuk-warning-text__icon' aria-hidden='true'>!</span><strong class='govuk-warning-text__text'>Check if this document is related to ${caseName}</strong></div><br>")
                    .readonly(SubmittedC1WithSupplementBundle::getDocumentAcknowledgeLabelForCYA)
                    .fieldShowCondition("documentAcknowledge=\"ACK_RELATED_TO_CASE\" AND submittedC1WithSupplement.clearSubmittedC1WithSupplement!=\"YES\"")
                    .eventLabel("<br /><div class='govuk-warning-text'><span class='govuk-warning-text__icon' aria-hidden='true'>!</span><strong class='govuk-warning-text__text'>Check if this document is related to this case</strong></div><br>")
                    .mandatory(SubmittedC1WithSupplementBundle::getDocumentAcknowledge)
                    .fieldShowCondition("submittedC1WithSupplement.clearSubmittedC1WithSupplement!=\"YES\"")
                    .eventLabel("Tick to confirm this document is related to this case")
                    .optional(SubmittedC1WithSupplementBundle::getUrgencyTimeFrameType)
                    .fieldShowCondition("submittedC1WithSupplement.clearSubmittedC1WithSupplement!=\"YES\"")
                    .eventLabel("Please state how soon you want the judge to consider your application?")
                    .optional(SubmittedC1WithSupplementBundle::getSupplementsBundle)
                    .fieldShowCondition("submittedC1WithSupplement.clearSubmittedC1WithSupplement!=\"YES\"")
                    .eventLabel("Supplements")
                    .complex(SubmittedC1WithSupplementBundle::getSupplementsBundle, Supplement.class)
                    .mandatory(Supplement::getName)
                    .fieldShowCondition("submittedC1WithSupplement.clearSubmittedC1WithSupplement!=\"YES\"").done()
                    .complex(SubmittedC1WithSupplementBundle::getSupplementsBundle, Supplement.class)
                    .optional(Supplement::getNotes)
                    .fieldShowCondition("submittedC1WithSupplement.clearSubmittedC1WithSupplement!=\"YES\"").done()
                    .complex(SubmittedC1WithSupplementBundle::getSupplementsBundle, Supplement.class)
                    .mandatory(Supplement::getDocument)
                    .fieldShowCondition("submittedC1WithSupplement.clearSubmittedC1WithSupplement!=\"YES\"")
                    .eventLabel("Upload document").done()
                    .complex(SubmittedC1WithSupplementBundle::getSupplementsBundle, Supplement.class)
                    .readonly(Supplement::getDocumentAcknowledgeLabel)
                    .fieldShowCondition("documentAcknowledge!=\"ACK_RELATED_TO_CASE\" AND submittedC1WithSupplement.clearSubmittedC1WithSupplement!=\"YES\"")
                    .eventLabel("<br /><div class='govuk-warning-text'><span class='govuk-warning-text__icon' aria-hidden='true'>!</span><strong class='govuk-warning-text__text'>Check if this document is related to ${caseName}</strong></div><br>").done()
                    .complex(SubmittedC1WithSupplementBundle::getSupplementsBundle, Supplement.class)
                    .readonly(Supplement::getDocumentAcknowledgeLabelForCYA)
                    .fieldShowCondition("documentAcknowledge=\"ACK_RELATED_TO_CASE\" AND submittedC1WithSupplement.clearSubmittedC1WithSupplement!=\"YES\"")
                    .eventLabel("<br /><div class='govuk-warning-text'><span class='govuk-warning-text__icon' aria-hidden='true'>!</span><strong class='govuk-warning-text__text'>Check if this document is related to this case</strong></div><br>").done()
                    .complex(SubmittedC1WithSupplementBundle::getSupplementsBundle, Supplement.class)
                    .mandatory(Supplement::getDocumentAcknowledge)
                    .fieldShowCondition("submittedC1WithSupplement.clearSubmittedC1WithSupplement!=\"YES\"")
                    .eventLabel("Tick to confirm this document is related to this case").done()
                    .optional(SubmittedC1WithSupplementBundle::getSupportingEvidenceBundle)
                    .fieldShowCondition("submittedC1WithSupplement.clearSubmittedC1WithSupplement!=\"YES\"")
                    .eventLabel("Supporting Documents")
                    .complex(SubmittedC1WithSupplementBundle::getSupportingEvidenceBundle, SupportingEvidenceBundle.class)
                    .mandatory(SupportingEvidenceBundle::getName)
                    .fieldShowCondition("submittedC1WithSupplement.clearSubmittedC1WithSupplement!=\"YES\"")
                    .eventLabel("File name").done()
                    .complex(SubmittedC1WithSupplementBundle::getSupportingEvidenceBundle, SupportingEvidenceBundle.class)
                    .optional(SupportingEvidenceBundle::getNotes)
                    .fieldShowCondition("submittedC1WithSupplement.clearSubmittedC1WithSupplement!=\"YES\"").done()
                    .complex(SubmittedC1WithSupplementBundle::getSupportingEvidenceBundle, SupportingEvidenceBundle.class)
                    .optional(SupportingEvidenceBundle::getDateTimeReceived)
                    .fieldShowCondition("temporaryC2Document=\"DO NOT SHOW\" AND submittedC1WithSupplement.clearSubmittedC1WithSupplement!=\"YES\"")
                    .noHintText().done()
                    .complex(SubmittedC1WithSupplementBundle::getSupportingEvidenceBundle, SupportingEvidenceBundle.class)
                    .mandatory(SupportingEvidenceBundle::getDocument)
                    .fieldShowCondition("submittedC1WithSupplement.clearSubmittedC1WithSupplement!=\"YES\"")
                    .eventLabel("Upload document").done()
                    .complex(SubmittedC1WithSupplementBundle::getSupportingEvidenceBundle, SupportingEvidenceBundle.class)
                    .readonly(SupportingEvidenceBundle::getDocumentAcknowledgeLabel)
                    .fieldShowCondition("documentAcknowledge!=\"ACK_RELATED_TO_CASE\" AND submittedC1WithSupplement.clearSubmittedC1WithSupplement!=\"YES\"")
                    .eventLabel("<br /><div class='govuk-warning-text'><span class='govuk-warning-text__icon' aria-hidden='true'>!</span><strong class='govuk-warning-text__text'>Check if this document is related to ${caseName}</strong></div><br>").done()
                    .complex(SubmittedC1WithSupplementBundle::getSupportingEvidenceBundle, SupportingEvidenceBundle.class)
                    .readonly(SupportingEvidenceBundle::getDocumentAcknowledgeLabelForCYA)
                    .fieldShowCondition("documentAcknowledge=\"ACK_RELATED_TO_CASE\" AND submittedC1WithSupplement.clearSubmittedC1WithSupplement!=\"YES\"")
                    .eventLabel("<br /><div class='govuk-warning-text'><span class='govuk-warning-text__icon' aria-hidden='true'>!</span><strong class='govuk-warning-text__text'>Check if this document is related to this case</strong></div><br>").done()
                    .complex(SubmittedC1WithSupplementBundle::getSupportingEvidenceBundle, SupportingEvidenceBundle.class)
                    .mandatory(SupportingEvidenceBundle::getDocumentAcknowledge)
                    .fieldShowCondition("submittedC1WithSupplement.clearSubmittedC1WithSupplement!=\"YES\"")
                    .eventLabel("Tick to confirm this document is related to this case").done().done();
    }
}
