package uk.gov.hmcts.reform.fpl.ccd.event;

import java.util.Set;
import org.springframework.stereotype.Component;
import uk.gov.hmcts.ccd.sdk.api.CCDConfig;
import uk.gov.hmcts.ccd.sdk.api.ConfigBuilder;
import uk.gov.hmcts.ccd.sdk.api.Permission;
import uk.gov.hmcts.reform.fpl.ccd.event.page.EnterLocalAuthorityAfterSubmissionColleaguesPage;
import uk.gov.hmcts.reform.fpl.ccd.event.page.EnterLocalAuthorityAfterSubmissionDetailsPage;
import uk.gov.hmcts.reform.fpl.ccd.event.page.EnterLocalAuthorityAfterSubmissionMainContactPage;
import uk.gov.hmcts.reform.fpl.enums.State;
import uk.gov.hmcts.reform.fpl.model.Address;
import uk.gov.hmcts.reform.fpl.model.CaseData;
import uk.gov.hmcts.reform.fpl.model.LocalAuthority;
import uk.gov.hmcts.reform.fpl.model.UserRole;
import uk.gov.hmcts.reform.fpl.model.event.LocalAuthorityEventData;

/**
 * Generated by ccd-definition-converter from CARE_SUPERVISION_EPO on migration; owned by this service team.
 *
 * <p>Event {@code enterLocalAuthorityAfterSubmission} for case type {@code CARE_SUPERVISION_EPO}.
 */
@Component
public class EnterLocalAuthorityAfterSubmission implements CCDConfig<CaseData, State, UserRole> {
    /**
     * The CCD event ID.
     */
    public static final String ENTER_LOCAL_AUTHORITY_AFTER_SUBMISSION = "enterLocalAuthorityAfterSubmission";

    /**
     * Registers event {@code enterLocalAuthorityAfterSubmission}.
     *
     * @param builder the config builder
     */
    @Override
    public void configure(ConfigBuilder<CaseData, State, UserRole> builder) {
        var fields = builder.event(ENTER_LOCAL_AUTHORITY_AFTER_SUBMISSION)
            .forStates(State.CASE_MANAGEMENT, State.FINAL_HEARING, State.CLOSED)
            .name("Applicant's details")
            .displayOrder(6)
            .showSummary()
            .explicitGrants()
            .grant(Set.of(Permission.R), UserRole.CHILDSOLICITORA, UserRole.EPSMANAGING, UserRole.LAMANAGING, UserRole.LASHARED, UserRole.LASOLICITOR, UserRole.SOLICITORA)
            .fields();
        EnterLocalAuthorityAfterSubmissionDetailsPage.apply(fields);
        EnterLocalAuthorityAfterSubmissionColleaguesPage.apply(fields);
        EnterLocalAuthorityAfterSubmissionMainContactPage.apply(fields);
        fields.complex(CaseData::getLocalAuthorityEventData)
                    .complexScope(LocalAuthorityEventData::getLocalAuthority)
                    .mandatory(LocalAuthority::getName)
                    .eventLabel("Local authority's name")
                    .optional(LocalAuthority::getEmail)
                    .eventLabel("Group email address")
                    .optional(LocalAuthority::getLegalTeamManager)
                    .mandatory(LocalAuthority::getPbaNumber)
                    .eventLabel("PBA number")
                    .mandatory(LocalAuthority::getCustomerReference)
                    .eventLabel("Customer reference")
                    .optional(LocalAuthority::getClientCode)
                    .eventLabel("Client code")
                    .mandatory(LocalAuthority::getAddress)
                    .eventLabel("Address")
                    .complex(LocalAuthority::getAddress)
                    .mandatory(Address::getAddressLine1).done()
                    .complex(LocalAuthority::getAddress)
                    .optional(Address::getAddressLine2).done()
                    .complex(LocalAuthority::getAddress)
                    .optional(Address::getAddressLine3).done()
                    .complex(LocalAuthority::getAddress)
                    .optional(Address::getPostTown).done()
                    .complex(LocalAuthority::getAddress)
                    .optional(Address::getCounty).done()
                    .complex(LocalAuthority::getAddress)
                    .mandatory(Address::getPostcode).done()
                    .complex(LocalAuthority::getAddress)
                    .optional(Address::getCountry).done()
                    .mandatory(LocalAuthority::getPhone)
                    .eventLabel("Phone number").done().done();
    }
}
