package uk.gov.hmcts.reform.fpl.ccd.event;

import java.util.Set;
import org.springframework.stereotype.Component;
import uk.gov.hmcts.ccd.sdk.api.CCDConfig;
import uk.gov.hmcts.ccd.sdk.api.ConfigBuilder;
import uk.gov.hmcts.ccd.sdk.api.Permission;
import uk.gov.hmcts.reform.fpl.model.Address;
import uk.gov.hmcts.reform.ccd.model.Organisation;
import uk.gov.hmcts.reform.fpl.enums.State;
import uk.gov.hmcts.reform.fpl.model.CaseData;
import uk.gov.hmcts.reform.fpl.model.RespondentNew;
import uk.gov.hmcts.reform.fpl.model.RespondentParty;
import uk.gov.hmcts.reform.fpl.model.RespondentSolicitor;
import uk.gov.hmcts.reform.fpl.model.common.Telephone;
import uk.gov.hmcts.reform.fpl.model.UnregisteredOrganisation;
import uk.gov.hmcts.reform.fpl.model.UserRole;

/**
 * Generated by ccd-definition-converter from CARE_SUPERVISION_EPO on migration; owned by this service team.
 *
 * <p>Event {@code enterRespondents3rdParty} for case type {@code CARE_SUPERVISION_EPO}.
 */
@Component
public class EnterRespondents3rdParty implements CCDConfig<CaseData, State, UserRole> {
    /**
     * The CCD event ID.
     */
    public static final String ENTER_RESPONDENTS3RD_PARTY = "enterRespondents3rdParty";

    /**
     * Registers event {@code enterRespondents3rdParty}.
     *
     * @param builder the config builder
     */
    @Override
    public void configure(ConfigBuilder<CaseData, State, UserRole> builder) {
        var fields = builder.event(ENTER_RESPONDENTS3RD_PARTY)
            .forStates(State.OPEN, State.RETURNED)
            .name("Respondents' details")
            .description("Entering the respondents for the case")
            .displayOrder(5)
            .showCondition("hasRespondentLA = \"YES\"")
            .showSummary()
            .explicitGrants()
            .grant(Permission.CR, UserRole.CHILDSOLICITORA, UserRole.SOLICITORA)
            .grant(Set.of(Permission.R), UserRole.CASEWORKER_PUBLICLAW_SOLICITOR)
            .fields();
        fields.page("1");
        fields.mandatory(CaseData::getRepresentativeType)
                    .fieldShowCondition("respondentsConfirmPR = \"DO_NOT_SHOW\"");
        fields.complex(CaseData::getRespondentLocalAuthority).done();
        fields.mandatory(CaseData::getRespondentsConfirmPR);
        fields.complex(CaseData::getRespondents1).done()
                    .caseEventFieldLabel("Details of respondents with parental responsibility");
        fields.complex(CaseData::getRespondents1, RespondentNew.class)
                    .complex(RespondentNew::getParty)
                    .mandatory(RespondentParty::getFirstName)
                    .eventLabel("First name").done()
                    .complex(RespondentNew::getParty)
                    .mandatory(RespondentParty::getLastName)
                    .eventLabel("Last name").done()
                    .complex(RespondentNew::getParty)
                    .optional(RespondentParty::getDateOfBirth)
                    .noHintText().done()
                    .complex(RespondentNew::getParty)
                    .optional(RespondentParty::getGender).done()
                    .complex(RespondentNew::getParty)
                    .optional(RespondentParty::getGenderIdentification).done()
                    .complex(RespondentNew::getParty)
                    .mandatory(RespondentParty::getAddressKnow).done()
                    .complex(RespondentNew::getParty)
                    .mandatory(RespondentParty::getAddressNotKnowReason).done()
                    .complex(RespondentNew::getParty)
                    .mandatory(RespondentParty::getWhereaboutsUnknownDetails).done()
                    .complex(RespondentNew::getParty)
                    .optional(RespondentParty::getAddressAutoConfidentialLabel).done()
                    .complex(RespondentNew::getParty)
                    .mandatory(RespondentParty::getAddress).done()
                    .complex(RespondentNew::getParty)
                    .complex(RespondentParty::getAddress)
                    .mandatory(Address::getAddressLine1).done().done()
                    .complex(RespondentNew::getParty)
                    .complex(RespondentParty::getAddress)
                    .optional(Address::getAddressLine2).done().done()
                    .complex(RespondentNew::getParty)
                    .complex(RespondentParty::getAddress)
                    .optional(Address::getAddressLine3).done().done()
                    .complex(RespondentNew::getParty)
                    .complex(RespondentParty::getAddress)
                    .mandatory(Address::getPostTown).done().done()
                    .complex(RespondentNew::getParty)
                    .complex(RespondentParty::getAddress)
                    .optional(Address::getCounty).done().done()
                    .complex(RespondentNew::getParty)
                    .complex(RespondentParty::getAddress)
                    .mandatory(Address::getPostcode).done().done()
                    .complex(RespondentNew::getParty)
                    .complex(RespondentParty::getAddress)
                    .mandatory(Address::getCountry).done().done()
                    .complex(RespondentNew::getParty)
                    .mandatory(RespondentParty::getHideAddress).done()
                    .complex(RespondentNew::getParty)
                    .optional(RespondentParty::getTelephoneNumber).done()
                    .complex(RespondentNew::getParty)
                    .complex(RespondentParty::getTelephoneNumber)
                    .optional(Telephone::getTelephoneNumber)
                    .noHintText().done().done()
                    .complex(RespondentNew::getParty)
                    .complex(RespondentParty::getTelephoneNumber)
                    .optional(Telephone::getContactDirection)
                    .fieldShowCondition("party=\"DO_NOT_SHOW\"").done().done()
                    .complex(RespondentNew::getParty)
                    .optional(RespondentParty::getHideTelephone).done()
                    .complex(RespondentNew::getParty)
                    .optional(RespondentParty::getContactDetailsHidden)
                    .fieldShowCondition("party=\"DO_NOT_SHOW\"").done()
                    .complex(RespondentNew::getParty)
                    .optional(RespondentParty::getContactDetailsHiddenReason)
                    .fieldShowCondition("party=\"DO_NOT_SHOW\"").done()
                    .complex(RespondentNew::getParty)
                    .readonly(RespondentParty::getRelationshipLabel)
                    .fieldShowCondition("party=\"DO_NOT_SHOW\"").done()
                    .complex(RespondentNew::getParty)
                    .optional(RespondentParty::getRelationshipToChild)
                    .eventLabel("Which children does the respondent have parental responsibility for and what is their relationship?").done()
                    .complex(RespondentNew::getParty)
                    .readonly(RespondentParty::getProceedingsLabel)
                    .fieldShowCondition("party=\"DO_NOT_SHOW\"").done()
                    .complex(RespondentNew::getParty)
                    .optional(RespondentParty::getLitigationIssues).done()
                    .complex(RespondentNew::getParty)
                    .optional(RespondentParty::getLitigationIssuesDetails).done()
                    .readonly(RespondentNew::getLegalRepresentationLabel)
                    .mandatory(RespondentNew::getLegalRepresentation)
                    .eventLabel("Do they have legal representation?")
                    .complex(RespondentNew::getSolicitor)
                    .optional(RespondentSolicitor::getFirstName).done()
                    .complex(RespondentNew::getSolicitor)
                    .optional(RespondentSolicitor::getLastName).done()
                    .complex(RespondentNew::getSolicitor)
                    .optional(RespondentSolicitor::getEmail)
                    .eventLabel("*Email address").done()
                    .complex(RespondentNew::getSolicitor)
                    .optional(RespondentSolicitor::getOrganisation).done()
                    .complex(RespondentNew::getSolicitor)
                    .complex(RespondentSolicitor::getOrganisation)
                    .optional(Organisation::getOrganisationName).done().done()
                    .complex(RespondentNew::getSolicitor)
                    .optional(RespondentSolicitor::getUnregisteredOrganisation)
                    .fieldShowCondition("respondents1.solicitor.organisation.OrganisationName=\"\"")
                    .eventLabel(" ").done()
                    .complex(RespondentNew::getSolicitor)
                    .complex(RespondentSolicitor::getUnregisteredOrganisation)
                    .readonly(UnregisteredOrganisation::getSignUpRequestHeader)
                    .fieldShowCondition("party!=\"SHOW_LABEL\"").done().done()
                    .complex(RespondentNew::getSolicitor)
                    .complex(RespondentSolicitor::getUnregisteredOrganisation)
                    .readonly(UnregisteredOrganisation::getSignupRequestLabel)
                    .fieldShowCondition("party!=\"SHOW_LABEL\"").done().done()
                    .complex(RespondentNew::getSolicitor)
                    .complex(RespondentSolicitor::getUnregisteredOrganisation)
                    .optional(UnregisteredOrganisation::getName)
                    .eventLabel("*Organisation name").done().done()
                    .complex(RespondentNew::getSolicitor)
                    .complex(RespondentSolicitor::getUnregisteredOrganisation)
                    .optional(UnregisteredOrganisation::getAddress)
                    .eventLabel("*Address").done().done()
                    .complex(RespondentNew::getSolicitor)
                    .complex(RespondentSolicitor::getUnregisteredOrganisation)
                    .complex(UnregisteredOrganisation::getAddress)
                    .optional(Address::getAddressLine1).done().done().done()
                    .complex(RespondentNew::getSolicitor)
                    .complex(RespondentSolicitor::getUnregisteredOrganisation)
                    .complex(UnregisteredOrganisation::getAddress)
                    .optional(Address::getAddressLine2).done().done().done()
                    .complex(RespondentNew::getSolicitor)
                    .complex(RespondentSolicitor::getUnregisteredOrganisation)
                    .complex(UnregisteredOrganisation::getAddress)
                    .optional(Address::getAddressLine3).done().done().done()
                    .complex(RespondentNew::getSolicitor)
                    .complex(RespondentSolicitor::getUnregisteredOrganisation)
                    .complex(UnregisteredOrganisation::getAddress)
                    .optional(Address::getPostTown).done().done().done()
                    .complex(RespondentNew::getSolicitor)
                    .complex(RespondentSolicitor::getUnregisteredOrganisation)
                    .complex(UnregisteredOrganisation::getAddress)
                    .optional(Address::getCounty).done().done().done()
                    .complex(RespondentNew::getSolicitor)
                    .complex(RespondentSolicitor::getUnregisteredOrganisation)
                    .complex(UnregisteredOrganisation::getAddress)
                    .optional(Address::getPostcode).done().done().done()
                    .complex(RespondentNew::getSolicitor)
                    .complex(RespondentSolicitor::getUnregisteredOrganisation)
                    .complex(UnregisteredOrganisation::getAddress)
                    .optional(Address::getCountry).done().done().done()
                    .complex(RespondentNew::getSolicitor)
                    .optional(RespondentSolicitor::getRegionalOfficeAddress)
                    .eventLabel("Add the regional office managing this case").done()
                    .complex(RespondentNew::getSolicitor)
                    .complex(RespondentSolicitor::getRegionalOfficeAddress)
                    .optional(Address::getAddressLine1).done().done()
                    .complex(RespondentNew::getSolicitor)
                    .complex(RespondentSolicitor::getRegionalOfficeAddress)
                    .optional(Address::getAddressLine2).done().done()
                    .complex(RespondentNew::getSolicitor)
                    .complex(RespondentSolicitor::getRegionalOfficeAddress)
                    .optional(Address::getAddressLine3).done().done()
                    .complex(RespondentNew::getSolicitor)
                    .complex(RespondentSolicitor::getRegionalOfficeAddress)
                    .optional(Address::getPostTown).done().done()
                    .complex(RespondentNew::getSolicitor)
                    .complex(RespondentSolicitor::getRegionalOfficeAddress)
                    .optional(Address::getCounty).done().done()
                    .complex(RespondentNew::getSolicitor)
                    .complex(RespondentSolicitor::getRegionalOfficeAddress)
                    .optional(Address::getPostcode).done().done()
                    .complex(RespondentNew::getSolicitor)
                    .complex(RespondentSolicitor::getRegionalOfficeAddress)
                    .optional(Address::getCountry).done().done()
                    .readonly(RespondentNew::getLegalCounsellors)
                    .fieldShowCondition("party=\"DO_NOT_SHOW\"")
                    .complex(RespondentNew::getSolicitor)
                    .complex(RespondentSolicitor::getTelephoneNumber)
                    .optional(Telephone::getTelephoneNumber)
                    .eventLabel("*Telephone Number")
                    .noHintText().done().done().done();
    }
}
