package uk.gov.hmcts.reform.fpl.ccd.event;

import java.util.Set;
import org.springframework.stereotype.Component;
import uk.gov.hmcts.ccd.sdk.api.CCDConfig;
import uk.gov.hmcts.ccd.sdk.api.ConfigBuilder;
import uk.gov.hmcts.ccd.sdk.api.Permission;
import uk.gov.hmcts.reform.fpl.model.Address;
import uk.gov.hmcts.reform.fpl.enums.State;
import uk.gov.hmcts.reform.fpl.model.CaseData;
import uk.gov.hmcts.reform.fpl.model.ChildParty;
import uk.gov.hmcts.reform.fpl.model.ChildrenNew;
import uk.gov.hmcts.reform.fpl.model.common.Telephone;
import uk.gov.hmcts.reform.fpl.model.UserRole;

/**
 * Generated by ccd-definition-converter from CARE_SUPERVISION_EPO on migration; owned by this service team.
 *
 * <p>Event {@code enterChildren} for case type {@code CARE_SUPERVISION_EPO}.
 */
@Component
public class EnterChildren implements CCDConfig<CaseData, State, UserRole> {
    /**
     * The CCD event ID.
     */
    public static final String ENTER_CHILDREN = "enterChildren";

    /**
     * Registers event {@code enterChildren}.
     *
     * @param builder the config builder
     */
    @Override
    public void configure(ConfigBuilder<CaseData, State, UserRole> builder) {
        var fields = builder.event(ENTER_CHILDREN)
            .forStates(State.OPEN, State.RETURNED)
            .name("Child's details")
            .description("Entering the children for the case")
            .displayOrder(4)
            .showSummary()
            .explicitGrants()
            .grant(Permission.CR, UserRole.CHILDSOLICITORA, UserRole.EPSMANAGING, UserRole.LAMANAGING, UserRole.LASOLICITOR, UserRole.SOLICITORA)
            .grant(Set.of(Permission.R), UserRole.CASEWORKER_PUBLICLAW_SOLICITOR)
            .fields();
        fields.page("1");
        fields.complex(CaseData::getChildren1).done();
        fields.complex(CaseData::getChildren1, ChildrenNew.class)
                    .complex(ChildrenNew::getParty)
                    .mandatory(ChildParty::getFirstName)
                    .eventLabel("First name")
                    .noHintText().done()
                    .complex(ChildrenNew::getParty)
                    .mandatory(ChildParty::getLastName)
                    .eventLabel("Last name")
                    .noHintText().done()
                    .complex(ChildrenNew::getParty)
                    .mandatory(ChildParty::getDateOfBirth)
                    .eventLabel("Date of birth")
                    .noHintText().done()
                    .complex(ChildrenNew::getParty)
                    .mandatory(ChildParty::getGender)
                    .eventLabel("What was the child's sex at birth?").done()
                    .complex(ChildrenNew::getParty)
                    .optional(ChildParty::getGenderIdentification)
                    .eventLabel("What gender do they identify with?").done()
                    .complex(ChildrenNew::getParty)
                    .mandatory(ChildParty::getLivingSituation).done()
                    .complex(ChildrenNew::getParty)
                    .optional(ChildParty::getAddressAutoConfidentialLabel).done()
                    .complex(ChildrenNew::getParty)
                    .mandatory(ChildParty::getAddress).done()
                    .complex(ChildrenNew::getParty)
                    .complex(ChildParty::getAddress)
                    .optional(Address::getAddressLine1).done().done()
                    .complex(ChildrenNew::getParty)
                    .complex(ChildParty::getAddress)
                    .optional(Address::getAddressLine2).done().done()
                    .complex(ChildrenNew::getParty)
                    .complex(ChildParty::getAddress)
                    .optional(Address::getAddressLine3).done().done()
                    .complex(ChildrenNew::getParty)
                    .complex(ChildParty::getAddress)
                    .optional(Address::getPostTown).done().done()
                    .complex(ChildrenNew::getParty)
                    .complex(ChildParty::getAddress)
                    .optional(Address::getCounty).done().done()
                    .complex(ChildrenNew::getParty)
                    .complex(ChildParty::getAddress)
                    .optional(Address::getPostcode).done().done()
                    .complex(ChildrenNew::getParty)
                    .complex(ChildParty::getAddress)
                    .optional(Address::getCountry).done().done()
                    .complex(ChildrenNew::getParty)
                    .mandatory(ChildParty::getIsAddressConfidential).done()
                    .complex(ChildrenNew::getParty)
                    .optional(ChildParty::getLivingSituationDetails).done()
                    .complex(ChildrenNew::getParty)
                    .mandatory(ChildParty::getLivingWithDetails)
                    .noHintText().done()
                    .complex(ChildrenNew::getParty)
                    .optional(ChildParty::getAddressChangeDate)
                    .eventLabel(" ")
                    .noHintText().done()
                    .complex(ChildrenNew::getParty)
                    .optional(ChildParty::getDatePowersEnd)
                    .noHintText().done()
                    .complex(ChildrenNew::getParty)
                    .optional(ChildParty::getCareStartDate)
                    .noHintText().done()
                    .complex(ChildrenNew::getParty)
                    .optional(ChildParty::getDischargeDate)
                    .noHintText().done()
                    .complex(ChildrenNew::getParty)
                    .optional(ChildParty::getDetailsHidden)
                    .fieldShowCondition("party=\"DO_NOT_SHOW\"").done()
                    .complex(ChildrenNew::getParty)
                    .optional(ChildParty::getDetailsHiddenReason)
                    .fieldShowCondition("party=\"DO_NOT_SHOW\"").done()
                    .complex(ChildrenNew::getParty)
                    .optional(ChildParty::getCareAndContactPlan)
                    .noHintText().done()
                    .complex(ChildrenNew::getParty)
                    .optional(ChildParty::getKeyDates)
                    .noHintText().done()
                    .complex(ChildrenNew::getParty)
                    .optional(ChildParty::getAdditionalNeeds)
                    .noHintText().done()
                    .complex(ChildrenNew::getParty)
                    .optional(ChildParty::getAdditionalNeedsDetails).done()
                    .complex(ChildrenNew::getParty)
                    .optional(ChildParty::getMothersName).done()
                    .complex(ChildrenNew::getParty)
                    .optional(ChildParty::getFathersName).done()
                    .complex(ChildrenNew::getParty)
                    .optional(ChildParty::getAdoption).done()
                    .complex(ChildrenNew::getParty)
                    .optional(ChildParty::getPlacementOrderApplication).done()
                    .complex(ChildrenNew::getParty)
                    .optional(ChildParty::getPlacementCourt)
                    .eventLabel(" ").done()
                    .complex(ChildrenNew::getParty)
                    .optional(ChildParty::getSocialWorkerName).done()
                    .complex(ChildrenNew::getParty)
                    .optional(ChildParty::getSocialWorkerTelephoneNumber).done()
                    .complex(ChildrenNew::getParty)
                    .complex(ChildParty::getSocialWorkerTelephoneNumber)
                    .optional(Telephone::getTelephoneNumber)
                    .noHintText().done().done()
                    .complex(ChildrenNew::getParty)
                    .complex(ChildParty::getSocialWorkerTelephoneNumber)
                    .optional(Telephone::getContactDirection)
                    .fieldShowCondition("party=\"DO_NOT_SHOW\"").done().done()
                    .complex(ChildrenNew::getParty)
                    .optional(ChildParty::getSocialWorkerEmail).done()
                    .complex(ChildrenNew::getParty)
                    .optional(ChildParty::getSocialWorkerDetailsHidden).done()
                    .complex(ChildrenNew::getParty)
                    .optional(ChildParty::getSocialWorkerDetailsHiddenReason).done()
                    .complex(ChildrenNew::getParty)
                    .readonly(ChildParty::getProceedingsLabel)
                    .fieldShowCondition("party=\"DO_NOT_SHOW\"").done()
                    .complex(ChildrenNew::getParty)
                    .readonly(ChildParty::getLitigationIssues)
                    .fieldShowCondition("party=\"DO_NOT_SHOW\"").done()
                    .complex(ChildrenNew::getParty)
                    .readonly(ChildParty::getLitigationIssuesDetails)
                    .fieldShowCondition("party=\"DO_NOT_SHOW\"").done()
                    .readonly(ChildrenNew::getRepresentative)
                    .fieldShowCondition("party=\"DO_NOT_SHOW\"")
                    .readonly(ChildrenNew::getSolicitor)
                    .fieldShowCondition("party=\"DO_NOT_SHOW\"")
                    .readonly(ChildrenNew::getLegalCounsellors)
                    .fieldShowCondition("party=\"DO_NOT_SHOW\"").done();
    }
}
