package uk.gov.hmcts.reform.fpl.ccd.event;

import org.springframework.stereotype.Component;
import uk.gov.hmcts.ccd.sdk.api.CCDConfig;
import uk.gov.hmcts.ccd.sdk.api.ConfigBuilder;
import uk.gov.hmcts.ccd.sdk.api.Permission;
import uk.gov.hmcts.reform.fpl.ccd.event.page.EnterApplicantDetailsLAApplicantContactPage;
import uk.gov.hmcts.reform.fpl.ccd.event.page.EnterApplicantDetailsLAApplicantDetailsPage;
import uk.gov.hmcts.reform.fpl.enums.State;
import uk.gov.hmcts.reform.fpl.model.CaseData;
import uk.gov.hmcts.reform.fpl.model.UserRole;

/**
 * Generated by ccd-definition-converter from CARE_SUPERVISION_EPO on migration; owned by this service team.
 *
 * <p>Event {@code enterApplicantDetailsLA} for case type {@code CARE_SUPERVISION_EPO}.
 */
@Component
public class EnterApplicantDetailsLA implements CCDConfig<CaseData, State, UserRole> {
    /**
     * The CCD event ID.
     */
    public static final String ENTER_APPLICANT_DETAILS_LA = "enterApplicantDetailsLA";

    /**
     * Registers event {@code enterApplicantDetailsLA}.
     *
     * @param builder the config builder
     */
    @Override
    public void configure(ConfigBuilder<CaseData, State, UserRole> builder) {
        var fields = builder.event(ENTER_APPLICANT_DETAILS_LA)
            .forStates(State.OPEN, State.RETURNED, State.CASE_MANAGEMENT, State.FINAL_HEARING, State.CLOSED)
            .name("Applicant's details")
            .displayOrder(6)
            .showCondition("representativeType=\"LOCAL_AUTHORITY\"")
            .showSummary()
            .showEventNotes()
            .explicitGrants()
            .grant(Permission.CR, UserRole.CASEWORKER_PUBLICLAW_SUPERUSER, UserRole.EPSMANAGING, UserRole.LAMANAGING, UserRole.LASHARED, UserRole.LASOLICITOR)
            .fields();
        EnterApplicantDetailsLAApplicantDetailsPage.apply(fields);
        EnterApplicantDetailsLAApplicantContactPage.apply(fields);
    }
}
