package uk.gov.hmcts.reform.fpl.ccd.event;

import org.springframework.stereotype.Component;
import uk.gov.hmcts.ccd.sdk.api.CCDConfig;
import uk.gov.hmcts.ccd.sdk.api.ConfigBuilder;
import uk.gov.hmcts.ccd.sdk.api.Permission;
import uk.gov.hmcts.reform.fpl.ccd.event.page.EnterThirdPartyApplicantDetailsApplicantContactPage;
import uk.gov.hmcts.reform.fpl.ccd.event.page.EnterThirdPartyApplicantDetailsApplicantDetailsPage;
import uk.gov.hmcts.reform.fpl.enums.State;
import uk.gov.hmcts.reform.fpl.model.CaseData;
import uk.gov.hmcts.reform.fpl.model.UserRole;

/**
 * Generated by ccd-definition-converter from CARE_SUPERVISION_EPO on migration; owned by this service team.
 *
 * <p>Event {@code enterThirdPartyApplicantDetails} for case type {@code CARE_SUPERVISION_EPO}.
 */
@Component
public class EnterThirdPartyApplicantDetails implements CCDConfig<CaseData, State, UserRole> {
    /**
     * The CCD event ID.
     */
    public static final String ENTER_THIRD_PARTY_APPLICANT_DETAILS = "enterThirdPartyApplicantDetails";

    /**
     * Registers event {@code enterThirdPartyApplicantDetails}.
     *
     * @param builder the config builder
     */
    @Override
    public void configure(ConfigBuilder<CaseData, State, UserRole> builder) {
        var fields = builder.event(ENTER_THIRD_PARTY_APPLICANT_DETAILS)
            .forStates(State.OPEN, State.RETURNED, State.CASE_MANAGEMENT, State.FINAL_HEARING, State.CLOSED)
            .name("Applicant's details")
            .displayOrder(6)
            .showCondition("representativeType=\"RESPONDENT_SOLICITOR\" OR representativeType=\"CHILD_SOLICITOR\"")
            .showSummary()
            .showEventNotes()
            .explicitGrants()
            .grant(Permission.CR, UserRole.CASEWORKER_PUBLICLAW_SUPERUSER, UserRole.CHILDSOLICITORA, UserRole.SOLICITORA)
            .fields();
        EnterThirdPartyApplicantDetailsApplicantDetailsPage.apply(fields);
        EnterThirdPartyApplicantDetailsApplicantContactPage.apply(fields);
    }
}
