package uk.gov.hmcts.reform.fpl.ccd.event;

import org.springframework.stereotype.Component;
import uk.gov.hmcts.ccd.sdk.api.CCDConfig;
import uk.gov.hmcts.ccd.sdk.api.ConfigBuilder;
import uk.gov.hmcts.ccd.sdk.api.Permission;
import uk.gov.hmcts.reform.fpl.ccd.event.page.EnterThirdPartyApplicantDetailsApplicantContactPage;
import uk.gov.hmcts.reform.fpl.ccd.event.page.EnterThirdPartyApplicantDetailsApplicantDetailsPage;
import uk.gov.hmcts.reform.fpl.enums.State;
import uk.gov.hmcts.reform.fpl.model.Address;
import uk.gov.hmcts.reform.fpl.model.CaseData;
import uk.gov.hmcts.reform.fpl.model.Colleague;
import uk.gov.hmcts.reform.fpl.model.LocalAuthority;
import uk.gov.hmcts.reform.fpl.model.RepresentingDetails;
import uk.gov.hmcts.reform.fpl.model.UserRole;
import uk.gov.hmcts.reform.fpl.model.event.LocalAuthorityEventData;

/**
 * Generated by ccd-definition-converter from CARE_SUPERVISION_EPO on migration; owned by this service team.
 *
 * <p>Event {@code enterThirdPartyApplicantDetails} for case type {@code CARE_SUPERVISION_EPO}.
 */
@Component
public class EnterThirdPartyApplicantDetails implements CCDConfig<CaseData, State, UserRole> {
    /**
     * The CCD event ID.
     */
    public static final String ENTER_THIRD_PARTY_APPLICANT_DETAILS = "enterThirdPartyApplicantDetails";

    /**
     * Registers event {@code enterThirdPartyApplicantDetails}.
     *
     * @param builder the config builder
     */
    @Override
    public void configure(ConfigBuilder<CaseData, State, UserRole> builder) {
        var fields = builder.event(ENTER_THIRD_PARTY_APPLICANT_DETAILS)
            .forStates(State.OPEN, State.RETURNED, State.CASE_MANAGEMENT, State.FINAL_HEARING, State.CLOSED)
            .name("Applicant's details")
            .displayOrder(6)
            .showCondition("representativeType=\"RESPONDENT_SOLICITOR\" OR representativeType=\"CHILD_SOLICITOR\"")
            .showSummary()
            .showEventNotes()
            .explicitGrants()
            .grant(Permission.CR, UserRole.CASEWORKER_PUBLICLAW_SUPERUSER, UserRole.CHILDSOLICITORA, UserRole.SOLICITORA)
            .fields();
        EnterThirdPartyApplicantDetailsApplicantDetailsPage.apply(fields);
        EnterThirdPartyApplicantDetailsApplicantContactPage.apply(fields);
        fields.complex(CaseData::getLocalAuthorityEventData)
                    .complexScope(LocalAuthorityEventData::getApplicantContact)
                    .mandatory(Colleague::getFirstName)
                    .mandatory(Colleague::getLastName)
                    .mandatory(Colleague::getPhone)
                    .optional(Colleague::getAlternativePhone)
                    .optional(Colleague::getEmail)
                    .eventLabel("Direct email address").done().done();
        fields.complex(CaseData::getLocalAuthorityEventData)
                    .complex(LocalAuthorityEventData::getApplicantContactOthers, Colleague.class)
                    .mandatory(Colleague::getFirstName)
                    .mandatory(Colleague::getLastName)
                    .mandatory(Colleague::getEmail)
                    .mandatory(Colleague::getRole).done().done();
        fields.complex(CaseData::getLocalAuthorityEventData)
                    .complexScope(LocalAuthorityEventData::getLocalAuthority)
                    .complexMember(LocalAuthority::getRepresentingDetails)
                    .complex(LocalAuthority::getRepresentingDetails)
                    .mandatory(RepresentingDetails::getFirstName)
                    .eventLabel("First name").done()
                    .complex(LocalAuthority::getRepresentingDetails)
                    .mandatory(RepresentingDetails::getLastName)
                    .eventLabel("Last name").done()
                    .readonly(LocalAuthority::getSolicitorDetailsLabel)
                    .eventLabel("<h2>Solicitors details</h2>")
                    .mandatory(LocalAuthority::getName)
                    .eventLabel("Solicitor's name")
                    .optional(LocalAuthority::getEmail)
                    .eventLabel("Group email address")
                    .mandatory(LocalAuthority::getPbaNumberDynamicList)
                    .fieldShowCondition("isCTSCUser!=\"Yes\"")
                    .eventLabel("PBA number")
                    .eventHint("For example, PBA1234567")
                    .mandatory(LocalAuthority::getPbaNumber)
                    .fieldShowCondition("isCTSCUser=\"Yes\"")
                    .eventLabel("PBA number")
                    .eventHint("For example, PBA1234567")
                    .readonly(LocalAuthority::getApplicationDetailsLabel)
                    .eventLabel("<h2>Application details</h2>")
                    .mandatory(LocalAuthority::getCustomerReference)
                    .eventLabel("Customer reference")
                    .eventHint("Add a meaningful reference to help with your reconciliation of accounts")
                    .optional(LocalAuthority::getLegalTeamManager)
                    .eventLabel("Name of the person who will sign the statement of truth on the C110A")
                    .optional(LocalAuthority::getAddress)
                    .eventLabel("Solicitor address")
                    .complex(LocalAuthority::getAddress)
                    .optional(Address::getAddressLine1).done()
                    .complex(LocalAuthority::getAddress)
                    .optional(Address::getAddressLine2).done()
                    .complex(LocalAuthority::getAddress)
                    .optional(Address::getAddressLine3).done()
                    .complex(LocalAuthority::getAddress)
                    .optional(Address::getPostTown).done()
                    .complex(LocalAuthority::getAddress)
                    .optional(Address::getCounty).done()
                    .complex(LocalAuthority::getAddress)
                    .optional(Address::getPostcode).done()
                    .complex(LocalAuthority::getAddress)
                    .optional(Address::getCountry).done().done().done();
    }
}
