package uk.gov.hmcts.reform.fpl.ccd.event;

import org.springframework.stereotype.Component;
import uk.gov.hmcts.ccd.sdk.api.CCDConfig;
import uk.gov.hmcts.ccd.sdk.api.ConfigBuilder;
import uk.gov.hmcts.ccd.sdk.api.Permission;
import uk.gov.hmcts.reform.fpl.enums.State;
import uk.gov.hmcts.reform.fpl.model.CaseData;
import uk.gov.hmcts.reform.fpl.model.UserRole;

/**
 * Generated by ccd-definition-converter from CARE_SUPERVISION_EPO on migration; owned by this service team.
 *
 * <p>Event {@code internal-change-translations} for case type {@code CARE_SUPERVISION_EPO}.
 */
@Component
public class InternalChangeTranslations implements CCDConfig<CaseData, State, UserRole> {
    /**
     * The CCD event ID.
     */
    public static final String INTERNAL_CHANGE_TRANSLATIONS = "internal-change-translations";

    /**
     * Registers event {@code internal-change-translations}.
     *
     * @param builder the config builder
     */
    @Override
    public void configure(ConfigBuilder<CaseData, State, UserRole> builder) {
        builder.event(INTERNAL_CHANGE_TRANSLATIONS)
            .forAllStates()
            .name("Post-process translations")
            .explicitGrants()
            .grant(Permission.CRUD, UserRole.CASEWORKER_PUBLICLAW_SYSTEMUPDATE);
    }
}
