package uk.gov.hmcts.reform.fpl.ccd.event;

import java.util.Set;
import org.springframework.stereotype.Component;
import uk.gov.hmcts.ccd.sdk.api.CCDConfig;
import uk.gov.hmcts.ccd.sdk.api.ConfigBuilder;
import uk.gov.hmcts.ccd.sdk.api.Permission;
import uk.gov.hmcts.reform.fpl.ccd.event.page.ManageHearingsConfirmHearingDetailsPage;
import uk.gov.hmcts.reform.fpl.ccd.event.page.ManageHearingsEnterHearingDetailsPage;
import uk.gov.hmcts.reform.fpl.ccd.event.page.ManageHearingsJudgeInformationPage;
import uk.gov.hmcts.reform.fpl.ccd.event.page.ManageHearingsSelectAdjournmentReasonPage;
import uk.gov.hmcts.reform.fpl.ccd.event.page.ManageHearingsSelectHearingOptionPage;
import uk.gov.hmcts.reform.fpl.ccd.event.page.ManageHearingsSelectReListOptionPage;
import uk.gov.hmcts.reform.fpl.ccd.event.page.ManageHearingsSelectVacatedReasonPage;
import uk.gov.hmcts.reform.fpl.ccd.event.page.ManageHearingsSendNoticeOfHearingPage;
import uk.gov.hmcts.reform.fpl.enums.State;
import uk.gov.hmcts.reform.fpl.model.CaseData;
import uk.gov.hmcts.reform.fpl.model.UserRole;
import uk.gov.hmcts.reform.fpl.model.order.selector.Selector;

/**
 * Generated by ccd-definition-converter from CARE_SUPERVISION_EPO on migration; owned by this service team.
 *
 * <p>Event {@code manageHearings} for case type {@code CARE_SUPERVISION_EPO}.
 */
@Component
public class ManageHearings implements CCDConfig<CaseData, State, UserRole> {
    /**
     * The CCD event ID.
     */
    public static final String MANAGE_HEARINGS = "manageHearings";

    /**
     * Registers event {@code manageHearings}.
     *
     * @param builder the config builder
     */
    @Override
    public void configure(ConfigBuilder<CaseData, State, UserRole> builder) {
        var fields = builder.event(MANAGE_HEARINGS)
            .forStates(State.GATEKEEPING_LISTING, State.CASE_MANAGEMENT, State.FINAL_HEARING, State.CLOSED)
            .name("Manage hearings")
            .description("Manage hearing booking details on a case")
            .displayOrder(3)
            .showSummary()
            .showEventNotes()
            .publishToCamunda()
            .explicitGrants()
            .grant(Permission.CR, UserRole.CASEWORKER_PUBLICLAW_COURTADMIN, UserRole.CASEWORKER_PUBLICLAW_GATEKEEPER, UserRole.CASEWORKER_PUBLICLAW_JUDICIARY)
            .grant(Set.of(Permission.R), UserRole.CASEWORKER_PUBLICLAW_MAGISTRATE, UserRole.CASEWORKER_PUBLICLAW_SOLICITOR, UserRole.CASEWORKER_PUBLICLAW_SYSTEMUPDATE)
            .fields();
        ManageHearingsConfirmHearingDetailsPage.apply(fields);
        ManageHearingsEnterHearingDetailsPage.apply(fields);
        ManageHearingsJudgeInformationPage.apply(fields);
        ManageHearingsSelectAdjournmentReasonPage.apply(fields);
        ManageHearingsSelectHearingOptionPage.apply(fields);
        ManageHearingsSelectReListOptionPage.apply(fields);
        ManageHearingsSelectVacatedReasonPage.apply(fields);
        ManageHearingsSendNoticeOfHearingPage.apply(fields);
        fields.complexScope(CaseData::getOthersSelector)
                    .readonly(Selector::getOptionCount)
                    .fieldShowCondition("optionCount=\"DO_NOT_SHOW\"")
                    .eventLabel(" ")
                    .optional(Selector::getOption0)
                    .eventLabel(" ")
                    .optional(Selector::getOption1)
                    .eventLabel(" ")
                    .optional(Selector::getOption2)
                    .eventLabel(" ")
                    .optional(Selector::getOption3)
                    .eventLabel(" ")
                    .optional(Selector::getOption4)
                    .eventLabel(" ").done();
    }
}
