package uk.gov.hmcts.reform.fpl.ccd.event;

import org.springframework.stereotype.Component;
import uk.gov.hmcts.ccd.sdk.api.CCDConfig;
import uk.gov.hmcts.ccd.sdk.api.ConfigBuilder;
import uk.gov.hmcts.ccd.sdk.api.Permission;
import uk.gov.hmcts.reform.fpl.ccd.event.page.ManageLegalRepresentativesPage1;
import uk.gov.hmcts.reform.fpl.ccd.event.page.ManageLegalRepresentativesPage2;
import uk.gov.hmcts.reform.fpl.enums.State;
import uk.gov.hmcts.reform.fpl.model.CaseData;
import uk.gov.hmcts.reform.fpl.model.UserRole;

/**
 * Generated by ccd-definition-converter from CARE_SUPERVISION_EPO on migration; owned by this service team.
 *
 * <p>Event {@code manageLegalRepresentatives} for case type {@code CARE_SUPERVISION_EPO}.
 */
@Component
public class ManageLegalRepresentatives implements CCDConfig<CaseData, State, UserRole> {
    /**
     * The CCD event ID.
     */
    public static final String MANAGE_LEGAL_REPRESENTATIVES = "manageLegalRepresentatives";

    /**
     * Registers event {@code manageLegalRepresentatives}.
     *
     * @param builder the config builder
     */
    @Override
    public void configure(ConfigBuilder<CaseData, State, UserRole> builder) {
        var fields = builder.event(MANAGE_LEGAL_REPRESENTATIVES)
            .forStates(State.SUBMITTED, State.GATEKEEPING_LISTING, State.GATEKEEPING, State.CASE_MANAGEMENT, State.FINAL_HEARING)
            .name("Add counsel/external solicitor")
            .displayOrder(28)
            .showSummary()
            .explicitGrants()
            .grant(Permission.CR, UserRole.EPSMANAGING, UserRole.LABARRISTER, UserRole.LAMANAGING, UserRole.LASHARED, UserRole.LASOLICITOR)
            .fields();
        ManageLegalRepresentativesPage1.apply(fields);
        ManageLegalRepresentativesPage2.apply(fields);
    }
}
