package uk.gov.hmcts.reform.fpl.ccd.event;

import java.util.Set;
import org.springframework.stereotype.Component;
import uk.gov.hmcts.ccd.sdk.api.CCDConfig;
import uk.gov.hmcts.ccd.sdk.api.ConfigBuilder;
import uk.gov.hmcts.ccd.sdk.api.Permission;
import uk.gov.hmcts.reform.fpl.enums.State;
import uk.gov.hmcts.reform.fpl.model.CaseData;
import uk.gov.hmcts.reform.fpl.model.UserRole;

/**
 * Generated by ccd-definition-converter from CARE_SUPERVISION_EPO on migration; owned by this service team.
 *
 * <p>Event {@code manageRepresentatives} for case type {@code CARE_SUPERVISION_EPO}.
 */
@Component
public class ManageRepresentatives implements CCDConfig<CaseData, State, UserRole> {
    /**
     * The CCD event ID.
     */
    public static final String MANAGE_REPRESENTATIVES = "manageRepresentatives";

    /**
     * Registers event {@code manageRepresentatives}.
     *
     * @param builder the config builder
     */
    @Override
    public void configure(ConfigBuilder<CaseData, State, UserRole> builder) {
        var fields = builder.event(MANAGE_REPRESENTATIVES)
            .forStates(State.SUBMITTED, State.GATEKEEPING, State.GATEKEEPING_LISTING, State.CASE_MANAGEMENT, State.FINAL_HEARING)
            .name("Manage representatives")
            .displayOrder(15)
            .showSummary(false)
            .explicitGrants()
            .grant(Permission.CR, UserRole.CASEWORKER_PUBLICLAW_COURTADMIN, UserRole.CASEWORKER_PUBLICLAW_SYSTEMUPDATE)
            .grant(Set.of(Permission.R), UserRole.CASEWORKER_PUBLICLAW_GATEKEEPER, UserRole.CASEWORKER_PUBLICLAW_JUDICIARY, UserRole.CASEWORKER_PUBLICLAW_MAGISTRATE, UserRole.CASEWORKER_PUBLICLAW_SOLICITOR)
            .fields();
        fields.page("1");
        fields.readonly(CaseData::getWarning_label);
        fields.readonly(CaseData::getRespondents_label);
        fields.readonly(CaseData::getOthers_label);
        fields.optional(CaseData::getRepresentatives);
    }
}
