package uk.gov.hmcts.reform.fpl.ccd.event;

import org.springframework.stereotype.Component;
import uk.gov.hmcts.ccd.sdk.api.CCDConfig;
import uk.gov.hmcts.ccd.sdk.api.ConfigBuilder;
import uk.gov.hmcts.ccd.sdk.api.Permission;
import uk.gov.hmcts.reform.fpl.ccd.event.page.MessageJudgeOrLegalAdviserAttachmentSelectorPagePage;
import uk.gov.hmcts.reform.fpl.ccd.event.page.MessageJudgeOrLegalAdviserMessageDocumentSelectorPage;
import uk.gov.hmcts.reform.fpl.ccd.event.page.MessageJudgeOrLegalAdviserNewMessageMetaDataPage;
import uk.gov.hmcts.reform.fpl.enums.State;
import uk.gov.hmcts.reform.fpl.model.CaseData;
import uk.gov.hmcts.reform.fpl.model.UserRole;

/**
 * Generated by ccd-definition-converter from CARE_SUPERVISION_EPO on migration; owned by this service team.
 *
 * <p>Event {@code messageJudgeOrLegalAdviser} for case type {@code CARE_SUPERVISION_EPO}.
 */
@Component
public class MessageJudgeOrLegalAdviser implements CCDConfig<CaseData, State, UserRole> {
    /**
     * The CCD event ID.
     */
    public static final String MESSAGE_JUDGE_OR_LEGAL_ADVISER = "messageJudgeOrLegalAdviser";

    /**
     * Registers event {@code messageJudgeOrLegalAdviser}.
     *
     * @param builder the config builder
     */
    @Override
    public void configure(ConfigBuilder<CaseData, State, UserRole> builder) {
        var fields = builder.event(MESSAGE_JUDGE_OR_LEGAL_ADVISER)
            .forStates(State.SUBMITTED, State.GATEKEEPING, State.GATEKEEPING_LISTING, State.CASE_MANAGEMENT, State.FINAL_HEARING, State.CLOSED)
            .name("Send messages")
            .displayOrder(16)
            .showSummary()
            .publishToCamunda()
            .explicitGrants()
            .grant(Permission.CR, UserRole.CASEWORKER_PUBLICLAW_COURTADMIN, UserRole.CASEWORKER_PUBLICLAW_GATEKEEPER, UserRole.CASEWORKER_PUBLICLAW_JUDICIARY)
            .fields();
        MessageJudgeOrLegalAdviserAttachmentSelectorPagePage.apply(fields);
        MessageJudgeOrLegalAdviserMessageDocumentSelectorPage.apply(fields);
        MessageJudgeOrLegalAdviserNewMessageMetaDataPage.apply(fields);
    }
}
