package uk.gov.hmcts.reform.fpl.ccd.event;

import java.util.Set;
import org.springframework.stereotype.Component;
import uk.gov.hmcts.ccd.sdk.api.CCDConfig;
import uk.gov.hmcts.ccd.sdk.api.ConfigBuilder;
import uk.gov.hmcts.ccd.sdk.api.Permission;
import uk.gov.hmcts.reform.fpl.enums.State;
import uk.gov.hmcts.reform.fpl.model.Address;
import uk.gov.hmcts.reform.fpl.model.CaseData;
import uk.gov.hmcts.reform.fpl.model.Orders;
import uk.gov.hmcts.reform.fpl.model.UserRole;

/**
 * Generated by ccd-definition-converter from CARE_SUPERVISION_EPO on migration; owned by this service team.
 *
 * <p>Event {@code ordersNeeded} for case type {@code CARE_SUPERVISION_EPO}.
 */
@Component
public class OrdersNeeded implements CCDConfig<CaseData, State, UserRole> {
    /**
     * The CCD event ID.
     */
    public static final String ORDERS_NEEDED = "ordersNeeded";

    /**
     * Registers event {@code ordersNeeded}.
     *
     * @param builder the config builder
     */
    @Override
    public void configure(ConfigBuilder<CaseData, State, UserRole> builder) {
        var fields = builder.event(ORDERS_NEEDED)
            .forState(State.OPEN)
            .name("Orders and directions sought")
            .description("Selecting the orders needed for application")
            .displayOrder(2)
            .showSummary()
            .explicitGrants()
            .grant(Permission.CR, UserRole.CHILDSOLICITORA, UserRole.EPSMANAGING, UserRole.LAMANAGING, UserRole.LASOLICITOR, UserRole.SOLICITORA)
            .grant(Set.of(Permission.R), UserRole.CASEWORKER_PUBLICLAW_SOLICITOR)
            .fields();
        fields.page("1");
        fields.readonlyNoSummary(CaseData::getRepresentativeType)
                    .fieldShowCondition("orders = \"DO_NOT_SHOW\"");
        fields.complex(CaseData::getOrders)
                    .mandatory(Orders::getOrderType)
                    .eventLabel("Which orders are you asking for?")
                    .optional(Orders::getEmergencyProtectionOrderLabel)
                    .mandatory(Orders::getEpoType)
                    .eventLabel("What type of EPO are you requesting?")
                    .mandatory(Orders::getAddress)
                    .eventLabel("Address")
                    .complex(Orders::getAddress)
                    .mandatory(Address::getAddressLine1).done()
                    .complex(Orders::getAddress)
                    .optional(Address::getAddressLine2).done()
                    .complex(Orders::getAddress)
                    .optional(Address::getAddressLine3).done()
                    .complex(Orders::getAddress)
                    .mandatory(Address::getPostTown).done()
                    .complex(Orders::getAddress)
                    .mandatory(Address::getCounty).done()
                    .complex(Orders::getAddress)
                    .mandatory(Address::getPostcode).done()
                    .complex(Orders::getAddress)
                    .mandatory(Address::getCountry).done()
                    .optional(Orders::getEmergencyProtectionOrders)
                    .eventHint("Select all that apply")
                    .mandatory(Orders::getEmergencyProtectionOrderDetails)
                    .eventLabel("Give details")
                    .optional(Orders::getEmergencyProtectionOrderDirections)
                    .eventHint("Select all that apply")
                    .mandatory(Orders::getExcluded)
                    .eventLabel("Who is excluded?")
                    .mandatory(Orders::getEmergencyProtectionOrderDirectionDetails)
                    .eventLabel("Give details")
                    .optional(Orders::getOtherOrderLabel)
                    .eventLabel("## Variation of supervision order or discharge of care order")
                    .mandatory(Orders::getOtherOrder)
                    .eventLabel("Which order do you need?")
                    .optional(Orders::getChildAssessmentOrderLabel)
                    .eventLabel("## Child Assessment Order")
                    .optional(Orders::getChildAssessmentOrderAssessmentDirections)
                    .eventLabel("The directions sought in respect of the assessment")
                    .optional(Orders::getChildAssessmentOrderContactDirections)
                    .eventLabel("The directions sought in respect of contact")
                    .mandatory(Orders::getDirections)
                    .eventLabel("Do you need any other directions?")
                    .mandatory(Orders::getDirectionDetails)
                    .eventLabel("Please provide more details")
                    .optional(Orders::getSecureAccommodationOrderLabel)
                    .mandatory(Orders::getSecureAccommodationOrderSection)
                    .eventLabel("Under which section are you applying?")
                    .mandatory(Orders::getCourt)
                    .eventLabel("Which court are you issuing for?")
                    .readonly(Orders::getChildRecoveryOrderLabel)
                    .mandatory(Orders::getChildRecoveryOrderDirectionsAppliedFor)
                    .eventLabel("The orders and directions applied for")
                    .eventHint("State whether each child to be produced to an authorised person specified by the court (Section 50(7) Children Act 1989) AND whether you require the court to authorise a constable to enter specified premises (Section 50(3)(d) Children Act 1989).")
                    .mandatory(Orders::getParticularsOfChildren)
                    .eventLabel("State whether the child or children are")
                    .eventHint("Select all that apply")
                    .optional(Orders::getParticularsOfChildrenDetails)
                    .eventLabel("If a child's identity is not known, state details that will identify the child. You may enclose a recent photograph of the child in upload documents section, which should be dated")
                    .readonly(Orders::getEducationSupervisionOrderLabel)
                    .mandatory(Orders::getEducationSupervisionOrderDirectionsAppliedFor)
                    .eventLabel("The orders and directions applied for")
                    .optional(Orders::getEducationSupervisionOrderPriorConsultationOtherLA)
                    .eventLabel("State the name of any other local authority which has been consulted")
                    .mandatory(Orders::getEducationSupervisionOrderPriorConsultationType)
                    .eventLabel(" ").done()
                    .fieldShowCondition("representativeType = \"LOCAL_AUTHORITY\" OR representativeType = \"\"");
        fields.complex(CaseData::getOrdersSolicitor)
                    .mandatory(Orders::getOrderType)
                    .eventLabel("Which orders are you asking for?")
                    .optional(Orders::getEmergencyProtectionOrderLabel)
                    .mandatory(Orders::getEpoType)
                    .eventLabel("What type of EPO are you requesting?")
                    .mandatory(Orders::getAddress)
                    .eventLabel("Address")
                    .complex(Orders::getAddress)
                    .mandatory(Address::getAddressLine1).done()
                    .complex(Orders::getAddress)
                    .optional(Address::getAddressLine2).done()
                    .complex(Orders::getAddress)
                    .optional(Address::getAddressLine3).done()
                    .complex(Orders::getAddress)
                    .mandatory(Address::getPostTown).done()
                    .complex(Orders::getAddress)
                    .mandatory(Address::getCounty).done()
                    .complex(Orders::getAddress)
                    .mandatory(Address::getPostcode).done()
                    .complex(Orders::getAddress)
                    .mandatory(Address::getCountry).done()
                    .optional(Orders::getEmergencyProtectionOrders)
                    .eventHint("Select all that apply")
                    .mandatory(Orders::getEmergencyProtectionOrderDetails)
                    .eventLabel("Give details")
                    .optional(Orders::getEmergencyProtectionOrderDirections)
                    .eventHint("Select all that apply")
                    .mandatory(Orders::getExcluded)
                    .eventLabel("Who is excluded?")
                    .mandatory(Orders::getEmergencyProtectionOrderDirectionDetails)
                    .eventLabel("Give details")
                    .optional(Orders::getOtherOrderLabel)
                    .eventLabel("## Variation of supervision order or discharge of care order")
                    .mandatory(Orders::getOtherOrder)
                    .eventLabel("Which order do you need?")
                    .mandatory(Orders::getDirections)
                    .eventLabel("Do you need any other directions?")
                    .mandatory(Orders::getDirectionDetails)
                    .eventLabel("Please provide more details")
                    .mandatory(Orders::getCourt)
                    .eventLabel("Which court are you issuing for?").done()
                    .fieldShowCondition("representativeType = \"CHILD_SOLICITOR\" OR representativeType = \"RESPONDENT_SOLICITOR\"");
    }
}
