package uk.gov.hmcts.reform.fpl.ccd.event;

import java.util.Set;
import org.springframework.stereotype.Component;
import uk.gov.hmcts.ccd.sdk.api.CCDConfig;
import uk.gov.hmcts.ccd.sdk.api.ConfigBuilder;
import uk.gov.hmcts.ccd.sdk.api.Permission;
import uk.gov.hmcts.reform.fpl.enums.State;
import uk.gov.hmcts.reform.fpl.model.Allocation;
import uk.gov.hmcts.reform.fpl.model.CaseData;
import uk.gov.hmcts.reform.fpl.model.UserRole;

/**
 * Generated by ccd-definition-converter from CARE_SUPERVISION_EPO on migration; owned by this service team.
 *
 * <p>Event {@code otherProposal} for case type {@code CARE_SUPERVISION_EPO}.
 */
@Component
public class OtherProposal implements CCDConfig<CaseData, State, UserRole> {
    /**
     * The CCD event ID.
     */
    public static final String OTHER_PROPOSAL = "otherProposal";

    /**
     * Registers event {@code otherProposal}.
     *
     * @param builder the config builder
     */
    @Override
    public void configure(ConfigBuilder<CaseData, State, UserRole> builder) {
        var fields = builder.event(OTHER_PROPOSAL)
            .forStates(State.OPEN, State.RETURNED)
            .name("Allocation proposal")
            .description("Entering other proceedings and allocation proposals")
            .displayOrder(14)
            .showSummary()
            .explicitGrants()
            .grant(Permission.CR, UserRole.CHILDSOLICITORA, UserRole.EPSMANAGING, UserRole.LAMANAGING, UserRole.LASOLICITOR, UserRole.SOLICITORA)
            .grant(Set.of(Permission.R), UserRole.CASEWORKER_PUBLICLAW_SOLICITOR)
            .fields();
        fields.page("1");
        fields.complex(CaseData::getAllocationProposal)
                    .mandatory(Allocation::getProposalV2)
                    .eventLabel("Which level of judge do you recommend for this case?")
                    .mandatory(Allocation::getProposalReason).done();
    }
}
