package uk.gov.hmcts.reform.fpl.ccd.event;

import java.util.Set;
import org.springframework.stereotype.Component;
import uk.gov.hmcts.ccd.sdk.api.CCDConfig;
import uk.gov.hmcts.ccd.sdk.api.ConfigBuilder;
import uk.gov.hmcts.ccd.sdk.api.Permission;
import uk.gov.hmcts.reform.fpl.ccd.event.page.PlacementChildrenListPage;
import uk.gov.hmcts.reform.fpl.ccd.event.page.PlacementNoticesPage;
import uk.gov.hmcts.reform.fpl.ccd.event.page.PlacementPaymentNotRequiredPage;
import uk.gov.hmcts.reform.fpl.ccd.event.page.PlacementPaymentPage;
import uk.gov.hmcts.reform.fpl.ccd.event.page.PlacementPlacementPage;
import uk.gov.hmcts.reform.fpl.enums.State;
import uk.gov.hmcts.reform.fpl.model.CaseData;
import uk.gov.hmcts.reform.fpl.model.UserRole;

/**
 * Generated by ccd-definition-converter from CARE_SUPERVISION_EPO on migration; owned by this service team.
 *
 * <p>Event {@code placement} for case type {@code CARE_SUPERVISION_EPO}.
 */
@Component
public class Placement implements CCDConfig<CaseData, State, UserRole> {
    /**
     * The CCD event ID.
     */
    public static final String PLACEMENT = "placement";

    /**
     * Registers event {@code placement}.
     *
     * @param builder the config builder
     */
    @Override
    public void configure(ConfigBuilder<CaseData, State, UserRole> builder) {
        var fields = builder.event(PLACEMENT)
            .forStates(State.CASE_MANAGEMENT, State.FINAL_HEARING)
            .name("Placement")
            .displayOrder(28)
            .showSummary()
            .publishToCamunda()
            .explicitGrants()
            .grant(Permission.CR, UserRole.CASEWORKER_PUBLICLAW_COURTADMIN, UserRole.EPSMANAGING, UserRole.LABARRISTER, UserRole.LAMANAGING, UserRole.LASHARED, UserRole.LASOLICITOR)
            .grant(Set.of(Permission.R), UserRole.CASEWORKER_PUBLICLAW_CAFCASS, UserRole.CASEWORKER_PUBLICLAW_GATEKEEPER, UserRole.CASEWORKER_PUBLICLAW_JUDICIARY, UserRole.CASEWORKER_PUBLICLAW_MAGISTRATE, UserRole.CASEWORKER_PUBLICLAW_SOLICITOR)
            .fields();
        PlacementNoticesPage.apply(fields);
        PlacementChildrenListPage.apply(fields);
        PlacementPlacementPage.apply(fields);
        PlacementPaymentPage.apply(fields);
        PlacementPaymentNotRequiredPage.apply(fields);
    }
}
