package uk.gov.hmcts.reform.fpl.ccd.event;

import java.util.Set;
import org.springframework.stereotype.Component;
import uk.gov.hmcts.ccd.sdk.api.CCDConfig;
import uk.gov.hmcts.ccd.sdk.api.ConfigBuilder;
import uk.gov.hmcts.ccd.sdk.api.Permission;
import uk.gov.hmcts.reform.fpl.ccd.event.page.PlacementChildrenListPage;
import uk.gov.hmcts.reform.fpl.ccd.event.page.PlacementNoticesPage;
import uk.gov.hmcts.reform.fpl.ccd.event.page.PlacementPaymentNotRequiredPage;
import uk.gov.hmcts.reform.fpl.ccd.event.page.PlacementPaymentPage;
import uk.gov.hmcts.reform.fpl.ccd.event.page.PlacementPlacementPage;
import uk.gov.hmcts.reform.fpl.enums.State;
import uk.gov.hmcts.reform.fpl.model.CaseData;
import uk.gov.hmcts.reform.fpl.model.PBAPayment;
import uk.gov.hmcts.reform.fpl.model.PlacementConfidentialDocument;
import uk.gov.hmcts.reform.fpl.model.PlacementSupportingDocument;
import uk.gov.hmcts.reform.fpl.model.UserRole;
import uk.gov.hmcts.reform.fpl.model.event.PlacementEventData;

/**
 * Generated by ccd-definition-converter from CARE_SUPERVISION_EPO on migration; owned by this service team.
 *
 * <p>Event {@code placement} for case type {@code CARE_SUPERVISION_EPO}.
 */
@Component
public class Placement implements CCDConfig<CaseData, State, UserRole> {
    /**
     * The CCD event ID.
     */
    public static final String PLACEMENT = "placement";

    /**
     * Registers event {@code placement}.
     *
     * @param builder the config builder
     */
    @Override
    public void configure(ConfigBuilder<CaseData, State, UserRole> builder) {
        var fields = builder.event(PLACEMENT)
            .forStates(State.CASE_MANAGEMENT, State.FINAL_HEARING)
            .name("Placement")
            .displayOrder(28)
            .showSummary()
            .publishToCamunda()
            .explicitGrants()
            .grant(Permission.CR, UserRole.CASEWORKER_PUBLICLAW_COURTADMIN, UserRole.EPSMANAGING, UserRole.LABARRISTER, UserRole.LAMANAGING, UserRole.LASHARED, UserRole.LASOLICITOR)
            .grant(Set.of(Permission.R), UserRole.CASEWORKER_PUBLICLAW_CAFCASS, UserRole.CASEWORKER_PUBLICLAW_GATEKEEPER, UserRole.CASEWORKER_PUBLICLAW_JUDICIARY, UserRole.CASEWORKER_PUBLICLAW_MAGISTRATE, UserRole.CASEWORKER_PUBLICLAW_SOLICITOR)
            .fields();
        PlacementNoticesPage.apply(fields);
        PlacementChildrenListPage.apply(fields);
        PlacementPlacementPage.apply(fields);
        PlacementPaymentPage.apply(fields);
        PlacementPaymentNotRequiredPage.apply(fields);
        fields.complex(CaseData::getPlacementEventData)
                    .complexScope(PlacementEventData::getPlacement)
                    .readonly(uk.gov.hmcts.reform.fpl.model.Placement::getChildId)
                    .fieldShowCondition("placementChildName = \"DO NOT SHOW\"")
                    .retainHiddenValue()
                    .readonly(uk.gov.hmcts.reform.fpl.model.Placement::getChildName)
                    .fieldShowCondition("placementChildId = \"DO NOT SHOW\"")
                    .retainHiddenValue()
                    .readonly(uk.gov.hmcts.reform.fpl.model.Placement::getIsSubmitted)
                    .readonly(uk.gov.hmcts.reform.fpl.model.Placement::getPlacementUploadDateTime)
                    .eventLabel("Date and time of submission")
                    .mandatory(uk.gov.hmcts.reform.fpl.model.Placement::getApplication)
                    .eventLabel("Application document")
                    .readonly(uk.gov.hmcts.reform.fpl.model.Placement::getPlacementApplicationCopy)
                    .eventLabel("Application document")
                    .optional(uk.gov.hmcts.reform.fpl.model.Placement::getSupportingDocuments)
                    .optional(uk.gov.hmcts.reform.fpl.model.Placement::getConfidentialDocuments)
                    .optional(uk.gov.hmcts.reform.fpl.model.Placement::getPlacementNotice)
                    .fieldShowCondition("placementChildId = \"DO NOT SHOW\"")
                    .complex(uk.gov.hmcts.reform.fpl.model.Placement::getConfidentialDocuments, PlacementConfidentialDocument.class)
                    .mandatory(PlacementConfidentialDocument::getType)
                    .eventLabel("Document type").done()
                    .complex(uk.gov.hmcts.reform.fpl.model.Placement::getConfidentialDocuments, PlacementConfidentialDocument.class)
                    .mandatory(PlacementConfidentialDocument::getOtherDocTypeName)
                    .fieldShowCondition("placement.placementConfidentialDocuments.type=\"OTHER_CONFIDENTIAL_DOCUMENTS\"")
                    .eventLabel("Custom document type").done()
                    .complex(uk.gov.hmcts.reform.fpl.model.Placement::getConfidentialDocuments, PlacementConfidentialDocument.class)
                    .mandatory(PlacementConfidentialDocument::getDocument)
                    .eventLabel("Document").done()
                    .complex(uk.gov.hmcts.reform.fpl.model.Placement::getConfidentialDocuments, PlacementConfidentialDocument.class)
                    .optional(PlacementConfidentialDocument::getDescription)
                    .eventLabel("Description").done()
                    .complex(uk.gov.hmcts.reform.fpl.model.Placement::getSupportingDocuments, PlacementSupportingDocument.class)
                    .mandatory(PlacementSupportingDocument::getType)
                    .eventLabel("Document type").done()
                    .complex(uk.gov.hmcts.reform.fpl.model.Placement::getSupportingDocuments, PlacementSupportingDocument.class)
                    .mandatory(PlacementSupportingDocument::getOtherDocTypeName)
                    .fieldShowCondition("placement.placementSupportingDocuments.type=\"OTHER_DOCUMENT_TYPE\"")
                    .eventLabel("Custom document type").done()
                    .complex(uk.gov.hmcts.reform.fpl.model.Placement::getSupportingDocuments, PlacementSupportingDocument.class)
                    .mandatory(PlacementSupportingDocument::getDocument)
                    .eventLabel("Document").done()
                    .complex(uk.gov.hmcts.reform.fpl.model.Placement::getSupportingDocuments, PlacementSupportingDocument.class)
                    .optional(PlacementSupportingDocument::getDescription)
                    .eventLabel("Description").done().done().done();
        fields.complex(CaseData::getPlacementEventData)
                    .complexScope(PlacementEventData::getPlacementPayment)
                    .mandatory(PBAPayment::getPbaNumber)
                    .fieldShowCondition("isCTSCUser=\"Yes\"")
                    .mandatory(PBAPayment::getPbaNumberDynamicList)
                    .fieldShowCondition("isCTSCUser!=\"Yes\"")
                    .optional(PBAPayment::getClientCode)
                    .mandatory(PBAPayment::getFileReference).done().done();
    }
}
