package uk.gov.hmcts.reform.fpl.ccd.event;

import java.util.Set;
import org.springframework.stereotype.Component;
import uk.gov.hmcts.ccd.sdk.api.CCDConfig;
import uk.gov.hmcts.ccd.sdk.api.ConfigBuilder;
import uk.gov.hmcts.ccd.sdk.api.Permission;
import uk.gov.hmcts.reform.fpl.ccd.event.page.RemoveDraftOrdersPage1;
import uk.gov.hmcts.reform.fpl.ccd.event.page.RemoveDraftOrdersPage2;
import uk.gov.hmcts.reform.fpl.enums.State;
import uk.gov.hmcts.reform.fpl.model.CaseData;
import uk.gov.hmcts.reform.fpl.model.UserRole;

/**
 * Generated by ccd-definition-converter from CARE_SUPERVISION_EPO on migration; owned by this service team.
 *
 * <p>Event {@code removeDraftOrders} for case type {@code CARE_SUPERVISION_EPO}.
 */
@Component
public class RemoveDraftOrders implements CCDConfig<CaseData, State, UserRole> {
    /**
     * The CCD event ID.
     */
    public static final String REMOVE_DRAFT_ORDERS = "removeDraftOrders";

    /**
     * Registers event {@code removeDraftOrders}.
     *
     * @param builder the config builder
     */
    @Override
    public void configure(ConfigBuilder<CaseData, State, UserRole> builder) {
        var fields = builder.event(REMOVE_DRAFT_ORDERS)
            .forStates(State.CASE_MANAGEMENT, State.FINAL_HEARING)
            .name("Remove draft orders")
            .displayOrder(29)
            .showSummary()
            .showEventNotes()
            .explicitGrants()
            .grant(Permission.CR, UserRole.EPSMANAGING, UserRole.LAMANAGING, UserRole.LASHARED, UserRole.LASOLICITOR)
            .grant(Set.of(Permission.R), UserRole.CASEWORKER_PUBLICLAW_SOLICITOR)
            .fields();
        RemoveDraftOrdersPage1.apply(fields);
        RemoveDraftOrdersPage2.apply(fields);
    }
}
