package uk.gov.hmcts.reform.fpl.ccd.event;

import org.springframework.stereotype.Component;
import uk.gov.hmcts.ccd.sdk.api.CCDConfig;
import uk.gov.hmcts.ccd.sdk.api.ConfigBuilder;
import uk.gov.hmcts.ccd.sdk.api.Permission;
import uk.gov.hmcts.reform.fpl.ccd.event.page.ReplyToMessageJudgeOrLegalAdviserReplyToMessagePage;
import uk.gov.hmcts.reform.fpl.ccd.event.page.ReplyToMessageJudgeOrLegalAdviserSelectMessagePage;
import uk.gov.hmcts.reform.fpl.enums.State;
import uk.gov.hmcts.reform.fpl.model.CaseData;
import uk.gov.hmcts.reform.fpl.model.UserRole;

/**
 * Generated by ccd-definition-converter from CARE_SUPERVISION_EPO on migration; owned by this service team.
 *
 * <p>Event {@code replyToMessageJudgeOrLegalAdviser} for case type {@code CARE_SUPERVISION_EPO}.
 */
@Component
public class ReplyToMessageJudgeOrLegalAdviser implements CCDConfig<CaseData, State, UserRole> {
    /**
     * The CCD event ID.
     */
    public static final String REPLY_TO_MESSAGE_JUDGE_OR_LEGAL_ADVISER = "replyToMessageJudgeOrLegalAdviser";

    /**
     * Registers event {@code replyToMessageJudgeOrLegalAdviser}.
     *
     * @param builder the config builder
     */
    @Override
    public void configure(ConfigBuilder<CaseData, State, UserRole> builder) {
        var fields = builder.event(REPLY_TO_MESSAGE_JUDGE_OR_LEGAL_ADVISER)
            .forStates(State.SUBMITTED, State.GATEKEEPING, State.GATEKEEPING_LISTING, State.CASE_MANAGEMENT, State.FINAL_HEARING, State.CLOSED)
            .name("Reply to messages")
            .displayOrder(17)
            .showCondition("judicialMessages!=\"\" AND judicialMessages!=\"[]\"")
            .showSummary()
            .publishToCamunda()
            .explicitGrants()
            .grant(Permission.CR, UserRole.CASEWORKER_PUBLICLAW_COURTADMIN, UserRole.CASEWORKER_PUBLICLAW_GATEKEEPER, UserRole.CASEWORKER_PUBLICLAW_JUDICIARY)
            .fields();
        ReplyToMessageJudgeOrLegalAdviserSelectMessagePage.apply(fields);
        ReplyToMessageJudgeOrLegalAdviserReplyToMessagePage.apply(fields);
    }
}
