package uk.gov.hmcts.reform.fpl.ccd.event;

import java.util.Set;
import org.springframework.stereotype.Component;
import uk.gov.hmcts.ccd.sdk.api.CCDConfig;
import uk.gov.hmcts.ccd.sdk.api.ConfigBuilder;
import uk.gov.hmcts.ccd.sdk.api.Permission;
import uk.gov.hmcts.reform.fpl.enums.State;
import uk.gov.hmcts.reform.fpl.model.CaseData;
import uk.gov.hmcts.reform.fpl.model.UserRole;

/**
 * Generated by ccd-definition-converter from CARE_SUPERVISION_EPO on migration; owned by this service team.
 *
 * <p>Event {@code requestListingAction} for case type {@code CARE_SUPERVISION_EPO}.
 */
@Component
public class RequestListingAction implements CCDConfig<CaseData, State, UserRole> {
    /**
     * The CCD event ID.
     */
    public static final String REQUEST_LISTING_ACTION = "requestListingAction";

    /**
     * Registers event {@code requestListingAction}.
     *
     * @param builder the config builder
     */
    @Override
    public void configure(ConfigBuilder<CaseData, State, UserRole> builder) {
        var fields = builder.event(REQUEST_LISTING_ACTION)
            .forStates(State.SUBMITTED, State.GATEKEEPING_LISTING, State.GATEKEEPING, State.CASE_MANAGEMENT, State.FINAL_HEARING, State.CLOSED)
            .name("Request listing action")
            .displayOrder(999)
            .showSummary()
            .endButtonLabel("Make request")
            .publishToCamunda()
            .explicitGrants()
            .grant(Permission.CR, UserRole.CTSC)
            .grant(Set.of(Permission.R), UserRole.CASEWORKER_PUBLICLAW_JUDICIARY, UserRole.HEARING_CENTRE_ADMIN)
            .fields();
        fields.page("ListingActions");
        fields.mandatory(CaseData::getSelectListingActions)
                    .publish(false);
        fields.mandatory(CaseData::getListingDetails)
                    .fieldShowCondition("selectListingActions=\"*\"")
                    .publish(false);
        fields.mandatory(CaseData::getLastListingRequestType)
                    .fieldShowCondition("selectListingActions=\"DO_NOT_SHOW\"");
    }
}
