package uk.gov.hmcts.reform.fpl.ccd.event;

import java.util.EnumSet;
import java.util.Set;
import org.springframework.stereotype.Component;
import uk.gov.hmcts.ccd.sdk.api.CCDConfig;
import uk.gov.hmcts.ccd.sdk.api.ConfigBuilder;
import uk.gov.hmcts.ccd.sdk.api.Permission;
import uk.gov.hmcts.reform.fpl.enums.State;
import uk.gov.hmcts.reform.fpl.model.CaseData;
import uk.gov.hmcts.reform.fpl.model.UserRole;

/**
 * Generated by ccd-definition-converter from CARE_SUPERVISION_EPO on migration; owned by this service team.
 *
 * <p>Event {@code returnApplication} for case type {@code CARE_SUPERVISION_EPO}.
 */
@Component
public class ReturnApplication implements CCDConfig<CaseData, State, UserRole> {
    /**
     * The CCD event ID.
     */
    public static final String RETURN_APPLICATION = "returnApplication";

    /**
     * Registers event {@code returnApplication}.
     *
     * @param builder the config builder
     */
    @Override
    public void configure(ConfigBuilder<CaseData, State, UserRole> builder) {
        var fields = builder.event(RETURN_APPLICATION)
            .forStateTransition(EnumSet.of(State.SUBMITTED, State.GATEKEEPING, State.GATEKEEPING_LISTING), State.RETURNED)
            .name("Return application")
            .description("Return an application to the LA")
            .displayOrder(50)
            .showSummary(false)
            .showEventNotes()
            .explicitGrants()
            .grant(Permission.CR, UserRole.CASEWORKER_PUBLICLAW_COURTADMIN, UserRole.CASEWORKER_PUBLICLAW_GATEKEEPER, UserRole.CASEWORKER_PUBLICLAW_JUDICIARY)
            .grant(Set.of(Permission.R), UserRole.CASEWORKER_PUBLICLAW_MAGISTRATE, UserRole.CHILDSOLICITORA, UserRole.EPSMANAGING, UserRole.LAMANAGING, UserRole.LASHARED, UserRole.LASOLICITOR, UserRole.SOLICITORA)
            .fields();
        fields.page("1");
        fields.complex(CaseData::getReturnApplication)
                    .mandatory(uk.gov.hmcts.reform.fpl.model.ReturnApplication::getReason)
                    .mandatory(uk.gov.hmcts.reform.fpl.model.ReturnApplication::getNote)
                    .readonly(uk.gov.hmcts.reform.fpl.model.ReturnApplication::getSubmittedDate)
                    .fieldShowCondition("note = \"DO NOT SHOW\"")
                    .readonly(uk.gov.hmcts.reform.fpl.model.ReturnApplication::getReturnedDate)
                    .fieldShowCondition("note = \"DO NOT SHOW\"")
                    .readonly(uk.gov.hmcts.reform.fpl.model.ReturnApplication::getDocument)
                    .fieldShowCondition("note = \"DO NOT SHOW\"").done();
    }
}
