package uk.gov.hmcts.reform.fpl.ccd.event;

import java.util.Set;
import org.springframework.stereotype.Component;
import uk.gov.hmcts.ccd.sdk.api.CCDConfig;
import uk.gov.hmcts.ccd.sdk.api.ConfigBuilder;
import uk.gov.hmcts.ccd.sdk.api.Permission;
import uk.gov.hmcts.reform.fpl.ccd.event.page.ReviewAdditionalApplicationPage1;
import uk.gov.hmcts.reform.fpl.ccd.event.page.ReviewAdditionalApplicationPage2;
import uk.gov.hmcts.reform.fpl.enums.State;
import uk.gov.hmcts.reform.fpl.model.CaseData;
import uk.gov.hmcts.reform.fpl.model.UserRole;

/**
 * Generated by ccd-definition-converter from CARE_SUPERVISION_EPO on migration; owned by this service team.
 *
 * <p>Event {@code reviewAdditionalApplication} for case type {@code CARE_SUPERVISION_EPO}.
 */
@Component
public class ReviewAdditionalApplication implements CCDConfig<CaseData, State, UserRole> {
    /**
     * The CCD event ID.
     */
    public static final String REVIEW_ADDITIONAL_APPLICATION = "reviewAdditionalApplication";

    /**
     * Registers event {@code reviewAdditionalApplication}.
     *
     * @param builder the config builder
     */
    @Override
    public void configure(ConfigBuilder<CaseData, State, UserRole> builder) {
        var fields = builder.event(REVIEW_ADDITIONAL_APPLICATION)
            .forStates(State.SUBMITTED, State.GATEKEEPING, State.CASE_MANAGEMENT, State.FINAL_HEARING, State.CLOSED)
            .name("Review additional application")
            .description("Judges to review uploaded additional application")
            .showSummary()
            .showEventNotes()
            .explicitGrants()
            .grant(Permission.CR, UserRole.CASEWORKER_PUBLICLAW_JUDICIARY)
            .grant(Set.of(Permission.R), UserRole.CASEWORKER_PUBLICLAW_COURTADMIN)
            .fields();
        ReviewAdditionalApplicationPage1.apply(fields);
        ReviewAdditionalApplicationPage2.apply(fields);
    }
}
