package uk.gov.hmcts.reform.fpl.ccd.event;

import java.util.Set;
import org.springframework.stereotype.Component;
import uk.gov.hmcts.ccd.sdk.api.CCDConfig;
import uk.gov.hmcts.ccd.sdk.api.ConfigBuilder;
import uk.gov.hmcts.ccd.sdk.api.Permission;
import uk.gov.hmcts.reform.fpl.enums.State;
import uk.gov.hmcts.reform.fpl.model.CaseData;
import uk.gov.hmcts.reform.fpl.model.UserRole;

/**
 * Generated by ccd-definition-converter from CARE_SUPERVISION_EPO on migration; owned by this service team.
 *
 * <p>Event {@code sendToGatekeeper} for case type {@code CARE_SUPERVISION_EPO}.
 */
@Component
public class SendToGatekeeper implements CCDConfig<CaseData, State, UserRole> {
    /**
     * The CCD event ID.
     */
    public static final String SEND_TO_GATEKEEPER = "sendToGatekeeper";

    /**
     * Registers event {@code sendToGatekeeper}.
     *
     * @param builder the config builder
     */
    @Override
    public void configure(ConfigBuilder<CaseData, State, UserRole> builder) {
        var fields = builder.event(SEND_TO_GATEKEEPER)
            .forStateTransition(State.SUBMITTED, State.GATEKEEPING)
            .name("Send to gatekeeper")
            .description("Send email to gatekeeper")
            .displayOrder(2)
            .showEventNotes()
            .explicitGrants()
            .grant(Permission.CR, UserRole.CASEWORKER_PUBLICLAW_COURTADMIN)
            .grant(Set.of(Permission.R), UserRole.CASEWORKER_PUBLICLAW_GATEKEEPER, UserRole.CASEWORKER_PUBLICLAW_JUDICIARY, UserRole.CASEWORKER_PUBLICLAW_MAGISTRATE, UserRole.CASEWORKER_PUBLICLAW_SOLICITOR)
            .fields();
        fields.page("1");
        fields.readonly(CaseData::getGateKeeperLabel);
        fields.readonly(CaseData::getGatekeeperHintLabel);
        fields.mandatory(CaseData::getGatekeeperEmails);
    }
}
