package uk.gov.hmcts.reform.fpl.ccd.event;

import org.springframework.stereotype.Component;
import uk.gov.hmcts.ccd.sdk.api.CCDConfig;
import uk.gov.hmcts.ccd.sdk.api.ConfigBuilder;
import uk.gov.hmcts.ccd.sdk.api.Permission;
import uk.gov.hmcts.reform.fpl.enums.State;
import uk.gov.hmcts.reform.fpl.model.CaseData;
import uk.gov.hmcts.reform.fpl.model.UserRole;

/**
 * Generated by ccd-definition-converter from CARE_SUPERVISION_EPO on migration; owned by this service team.
 *
 * <p>Event {@code updateCaseName} for case type {@code CARE_SUPERVISION_EPO}.
 */
@Component
public class UpdateCaseName implements CCDConfig<CaseData, State, UserRole> {
    /**
     * The CCD event ID.
     */
    public static final String UPDATE_CASE_NAME = "updateCaseName";

    /**
     * Registers event {@code updateCaseName}.
     *
     * @param builder the config builder
     */
    @Override
    public void configure(ConfigBuilder<CaseData, State, UserRole> builder) {
        var fields = builder.event(UPDATE_CASE_NAME)
            .forAllStates()
            .name("Update case name")
            .displayOrder(21)
            .showSummary(false)
            .publishToCamunda()
            .explicitGrants()
            .grant(Permission.CR, UserRole.CASEWORKER_PUBLICLAW_SOLICITOR, UserRole.CHILDSOLICITORA, UserRole.CTSC, UserRole.EPSMANAGING, UserRole.LAMANAGING, UserRole.LASHARED, UserRole.LASOLICITOR, UserRole.SOLICITORA)
            .fields();
        fields.page("1");
        fields.readonly(CaseData::getCaseName)
                    .fieldShowCondition("updatedCaseNameLabel=\"DO_NOT_SHOW\"")
                    .publish(false);
        fields.readonly(CaseData::getUpdatedCaseNameLabel)
                    .publish(false);
    }
}
