package uk.gov.hmcts.reform.fpl.ccd.event;

import java.util.Set;
import org.springframework.stereotype.Component;
import uk.gov.hmcts.ccd.sdk.api.CCDConfig;
import uk.gov.hmcts.ccd.sdk.api.ConfigBuilder;
import uk.gov.hmcts.ccd.sdk.api.Permission;
import uk.gov.hmcts.reform.fpl.enums.State;
import uk.gov.hmcts.reform.fpl.model.CaseData;
import uk.gov.hmcts.reform.fpl.model.UserRole;

/**
 * Generated by ccd-definition-converter from CARE_SUPERVISION_EPO on migration; owned by this service team.
 *
 * <p>Event {@code uploadStandardDirections} for case type {@code CARE_SUPERVISION_EPO}.
 */
@Component
public class UploadStandardDirections implements CCDConfig<CaseData, State, UserRole> {
    /**
     * The CCD event ID.
     */
    public static final String UPLOAD_STANDARD_DIRECTIONS = "uploadStandardDirections";

    /**
     * Registers event {@code uploadStandardDirections}.
     *
     * @param builder the config builder
     */
    @Override
    public void configure(ConfigBuilder<CaseData, State, UserRole> builder) {
        var fields = builder.event(UPLOAD_STANDARD_DIRECTIONS)
            .forStates(State.SUBMITTED, State.GATEKEEPING)
            .name("Upload documents")
            .description("Upload standard directions")
            .displayOrder(13)
            .showSummary(false)
            .showEventNotes()
            .explicitGrants()
            .grant(Set.of(Permission.R), UserRole.CASEWORKER_PUBLICLAW_COURTADMIN, UserRole.CASEWORKER_PUBLICLAW_GATEKEEPER, UserRole.CASEWORKER_PUBLICLAW_JUDICIARY, UserRole.CASEWORKER_PUBLICLAW_MAGISTRATE, UserRole.CASEWORKER_PUBLICLAW_SOLICITOR)
            .fields();
        fields.page("1");
        fields.readonly(CaseData::getStandardDirectionsLabel);
        fields.readonly(CaseData::getStandardDirectionsTitle);
        fields.optional(CaseData::getStandardDirectionsDocument);
        fields.optional(CaseData::getOtherCourtAdminDocuments);
    }
}
