package uk.gov.hmcts.reform.fpl.ccd.event;

import java.util.Set;
import org.springframework.stereotype.Component;
import uk.gov.hmcts.ccd.sdk.api.CCDConfig;
import uk.gov.hmcts.ccd.sdk.api.ConfigBuilder;
import uk.gov.hmcts.ccd.sdk.api.Permission;
import uk.gov.hmcts.reform.fpl.enums.State;
import uk.gov.hmcts.reform.fpl.model.CaseData;
import uk.gov.hmcts.reform.fpl.model.UserRole;

/**
 * Generated by ccd-definition-converter from CARE_SUPERVISION_EPO on migration; owned by this service team.
 *
 * <p>Event {@code uploadC2} for case type {@code CARE_SUPERVISION_EPO}.
 */
@Component
public class UploadC2 implements CCDConfig<CaseData, State, UserRole> {
    /**
     * The CCD event ID.
     */
    public static final String UPLOAD_C2 = "uploadC2";

    /**
     * Registers event {@code uploadC2}.
     *
     * @param builder the config builder
     */
    @Override
    public void configure(ConfigBuilder<CaseData, State, UserRole> builder) {
        builder.event(UPLOAD_C2)
            .forStates(State.SUBMITTED, State.GATEKEEPING, State.CASE_MANAGEMENT, State.FINAL_HEARING, State.CLOSED)
            .name("Upload a C2")
            .description("Upload a c2 to the case")
            .displayOrder(11)
            .showSummary()
            .showEventNotes()
            .explicitGrants()
            .grant(Set.of(Permission.R), UserRole.CAFCASSSOLICITOR, UserRole.CASEWORKER_PUBLICLAW_CAFCASS, UserRole.CASEWORKER_PUBLICLAW_COURTADMIN, UserRole.CASEWORKER_PUBLICLAW_GATEKEEPER, UserRole.CASEWORKER_PUBLICLAW_JUDICIARY, UserRole.CASEWORKER_PUBLICLAW_MAGISTRATE, UserRole.CASEWORKER_PUBLICLAW_SOLICITOR, UserRole.EPSMANAGING, UserRole.LABARRISTER, UserRole.LAMANAGING, UserRole.LASHARED, UserRole.LASOLICITOR, UserRole.SOLICITOR);
    }
}
