package uk.gov.hmcts.reform.fpl.model.order;

import lombok.Getter;
import lombok.RequiredArgsConstructor;

import java.util.Collections;
import java.util.List;

@Getter
@RequiredArgsConstructor
public enum OrderQuestionBlock {

    CHILD_ASSESSMENT_ORDER("manageOrdersChildAssessment", OrderSection.ORDER_DETAILS,
        List.of("manageOrdersChildAssessmentType", "manageOrdersAssessmentStartDate",
            "manageOrdersDurationOfAssessment",
            "manageOrdersPlaceOfAssessment",
            "manageOrdersAssessingBody",
            "manageOrdersChildKeepAwayFromHome",
            "manageOrdersFullAddressToStayIfKeepAwayFromHome",
            "manageOrdersStartDateOfStayIfKeepAwayFromHome",
            "manageOrdersEndDateOfStayIfKeepAwayFromHome",
            "manageOrdersChildFirstContactIfKeepAwayFromHome",
            "manageOrdersChildSecondContactIfKeepAwayFromHome",
            "manageOrdersChildThirdContactIfKeepAwayFromHome",
            "manageOrdersDoesCostOrderExist",
            "manageOrdersCostOrderDetails")),
    LINKED_TO_HEARING("hearingDetails", OrderSection.HEARING_DETAILS,
        List.of("manageOrdersApprovedAtHearing", "manageOrdersApprovedAtHearingList",
            "manageOrdersApprovalDate", "manageOrdersApprovalDateTime", "judgeAndLegalAdvisor")),
    LINK_APPLICATION("linkApplication", OrderSection.HEARING_DETAILS,
        List.of("manageOrdersShouldLinkApplication", "manageOrdersLinkedApplication")),
    CHILD_PLACEMENT_APPLICATIONS("childPlacementApplications", OrderSection.ISSUING_DETAILS,
        List.of("manageOrdersChildPlacementApplication")),
    APPROVER("approver", OrderSection.ISSUING_DETAILS,
        List.of("judgeAndLegalAdvisor")),
    APPROVAL_DATE("approvalDate", OrderSection.ISSUING_DETAILS,
        List.of("manageOrdersApprovalDate")),
    APPROVAL_DATE_TIME("approvalDateTime", OrderSection.ISSUING_DETAILS,
        List.of("manageOrdersApprovalDateTime")),
    WHICH_CHILDREN("whichChildren", OrderSection.CHILDREN_DETAILS,
        List.of("orderAppliesToAllChildren", "children_label", "childSelector")),
    SELECT_SINGLE_CHILD("selectSingleChild", OrderSection.CHILDREN_DETAILS, List.of("whichChildIsTheOrderFor")),
    EPO_INCLUDE_PHRASE("epoIncludePhrase", OrderSection.ORDER_DETAILS,
        List.of("manageOrdersIncludePhrase")),
    EPO_CHILDREN_DESCRIPTION("epoChildrenDescription", OrderSection.ORDER_DETAILS,
        List.of("manageOrdersChildrenDescription")),
    EPO_EXPIRY_DATE("epoExpiryDate", OrderSection.ORDER_DETAILS,
        List.of("manageOrdersEndDateTime")),
    EPO_TYPE_AND_PREVENT_REMOVAL("epoTypeAndPreventRemoval", OrderSection.ORDER_DETAILS,
        List.of("manageOrdersEpoType", "manageOrdersEpoRemovalAddress", "manageOrdersExclusionRequirement",
            "manageOrdersWhoIsExcluded", "manageOrdersExclusionStartDate", "manageOrdersPowerOfArrest")),
    CHILD_PLACEMENT("childPlacementQuestions", OrderSection.ORDER_DETAILS, List.of("manageOrdersSerialNumber",
        "manageOrdersBirthCertificateNumber", "manageOrdersBirthCertificateDate",
        "manageOrdersBirthCertificateRegistrationDistrict", "manageOrdersBirthCertificateRegistrationSubDistrict",
        "manageOrdersBirthCertificateRegistrationCounty", "manageOrdersPlacementOrderOtherDetails")),
    CHILD_PLACEMENT_FOR_BLANK_ORDER("childPlacementQuestionsForBlankOrder", OrderSection.ORDER_DETAILS, List.of(
        "manageOrdersPreamblesText", "manageOrdersParagraphs", "manageOrdersCostOrders")),
    TITLE("orderTitle", OrderSection.ORDER_DETAILS,
        List.of("manageOrdersTitle")),
    FURTHER_DIRECTIONS("furtherDirections", OrderSection.ORDER_DETAILS,
        List.of("manageOrdersFurtherDirections")),
    REASON_FOR_SECURE_ACCOMMODATION("reasonForSecureAccommodation", OrderSection.ORDER_DETAILS,
        List.of("manageOrdersReasonForSecureAccommodation")),
    IS_CHILD_REPRESENTED("childLegalRepresentation", OrderSection.ORDER_DETAILS,
        List.of("manageOrdersIsChildRepresented")),
    SECURE_ACCOMMODATION_ORDER_JURISDICTION("orderJurisdiction",
        OrderSection.ORDER_DETAILS, List.of("manageOrdersOrderJurisdiction")),
    CAFCASS_JURISDICTIONS("cafcassJurisdictions", OrderSection.ORDER_DETAILS,
        List.of("manageOrdersCafcassRegion", "manageOrdersCafcassOfficesEngland", "manageOrdersCafcassOfficesWales")),
    DETAILS("orderDetails", OrderSection.ORDER_DETAILS,
        List.of("manageOrdersDirections")),
    CHILD_ARRANGEMENT_SPECIFIC_ISSUE_PROHIBITED_STEPS("childArrangementSpecificIssueProhibitedSteps",
        OrderSection.ORDER_DETAILS,
        List.of("manageOrdersMultiSelectListForC43", "manageOrdersRecitalsAndPreambles")),
    DISCHARGE_DETAILS("dischargeOfCareDetails", OrderSection.ORDER_DETAILS,
        List.of("manageOrdersCareOrderIssuedDate", "manageOrdersCareOrderIssuedCourt")),
    REVIEW_DRAFT_ORDER("previewOrder", OrderSection.REVIEW,
        List.of("orderPreview")),
    APPOINTED_GUARDIAN("appointedGuardian", OrderSection.ORDER_DETAILS,
        List.of("appointedGuardians_label", "appointedGuardianSelector", "additionalAppointedSpecialGuardians")),
    ORDER_BY_CONSENT("orderIsByConsent", OrderSection.ORDER_DETAILS,
        List.of("manageOrdersIsByConsent")),
    PARENTAL_RESPONSIBILITY("parentResponsible", OrderSection.ORDER_DETAILS,
        List.of("manageOrdersParentResponsible", "manageOrdersRelationshipWithChild")),
    MANAGE_ORDER_END_DATE_WITH_MONTH(
        "manageOrdersExpiryDateWithMonth", OrderSection.ORDER_DETAILS,
        List.of("manageOrdersEndDateTypeWithMonth", "manageOrdersSetDateEndDate", "manageOrdersSetDateAndTimeEndDate",
            "manageOrdersSetMonthsEndDate")),
    MANAGE_ORDER_END_DATE_WITH_END_OF_PROCEEDINGS(
        "manageOrdersExpiryDateWithEndOfProceedings", OrderSection.ORDER_DETAILS,
        List.of("manageOrdersEndDateTypeWithEndOfProceedings", "manageOrdersSetDateEndDate",
            "manageOrdersSetDateAndTimeEndDate")),
    NEED_SEALING("needSealing", OrderSection.ORDER_DETAILS,
        List.of("manageOrdersNeedSealing")),
    UPLOAD_ORDER_FILE("uploadOrderFile", OrderSection.ORDER_DETAILS,
        List.of("manageOrdersUploadOrderFile")),
    ICO_EXCLUSION(
        "manageOrdersExclusionRequirementDetails", OrderSection.ORDER_DETAILS,
        List.of("manageOrdersHasExclusionRequirement", "manageOrdersExclusionDetails")),
    CLOSE_CASE("closeCase", OrderSection.REVIEW,
        List.of("manageOrdersCloseCase", "manageOrdersCloseCaseWarning")),
    WHICH_OTHERS("whichOthers", OrderSection.OTHER_DETAILS,
        List.of("sendOrderToAllOthers", "others_label", "othersSelector")),
    TRANSLATION_REQUIREMENTS("translationRequirements", OrderSection.ORDER_DETAILS,
        List.of("manageOrdersTranslationNeeded")),
    ORDER_TO_AMEND("orderToAmend", OrderSection.AMEND_DOWNLOAD,
        List.of("manageOrdersOrderToAmend")),
    UPLOAD_AMENDED_ORDER("uploadAmendedOrder", OrderSection.AMEND_DOWNLOAD,
        List.of("manageOrdersAmendedOrder")),
    EDUCATION_SUPERVISION("manageOrdersEducationSupervision", OrderSection.ORDER_DETAILS,
        List.of("manageOrdersLeaName","manageOrdersEndDateWithEducationAge")),
    VARY_OR_EXTEND_SUPERVISION_ORDER("manageOrdersVaryOrExtendSupervisionOrder", OrderSection.ORDER_DETAILS,
        List.of("manageOrdersSupervisionOrderType", "manageOrdersC35aOrderExists",
            "manageOrdersC35aOrderDoesntExistMessage", "manageOrdersSupervisionOrderVariationHeading",
            "manageOrdersSupervisionOrderExtensionHeading", "manageOrdersSupervisionOrderCourtDirection",
            "manageOrdersSupervisionOrderApprovalDate", "manageOrdersSupervisionOrderEndDate")),
    REFUSE_CONTACT_ORDER("refuseContactQuestions", OrderSection.ORDER_DETAILS, Collections.emptyList()),
    RESPONDENTS_REFUSED("respondentsRefused", OrderSection.ORDER_DETAILS,
                       List.of("respondentsRefused_label", "respondentsRefusedSelector")),
    DECLARATION_OF_PARENTAGE("declarationOfParentage", OrderSection.ORDER_DETAILS,
        List.of("manageOrdersParentageApplicant", "manageOrdersHearingParty1",
            "manageOrdersHearingParty2", "manageOrdersPersonWhoseParenthoodIs", "manageOrdersParentageAction")),
    ORDER_PLACED_CHILD_IN_CUSTODY("orderPlacedChildInCustody", OrderSection.ORDER_DETAILS,
        List.of("manageOrdersPlacedUnderOrder", "manageOrdersOrderCreatedDate", "manageOrdersActionsPermitted",
            "manageOrdersIsExParte")),
    LEAVE_TO_CHANGE_CHILD_SURNAME("leaveToChangeChildSurname", OrderSection.ORDER_DETAILS,
        List.of("manageOrdersPartyGrantedLeave", "manageOrdersChildNewSurname")),
    PARTY_ALLOWED_CONTACTS_AND_CONDITIONS("partyAllowedContactsAndConditions", OrderSection.ORDER_DETAILS,
        List.of("manageOrdersAllowedContact1", "manageOrdersAllowedContact2", "manageOrdersAllowedContact3",
            "manageOrdersConditionsOfContact")),
    FAMILY_ASSISTANCE_ORDER("familyAssistanceOrder", OrderSection.ORDER_DETAILS,
        List.of("manageOrdersPartyToBeBefriended1", "manageOrdersPartyToBeBefriended2",
            "manageOrdersPartyToBeBefriended3", "manageOrdersFamilyAssistanceEndDate")),
    TRANSPARENCY_ORDER_BLOCK("manageOrdersTransparencyOrder", OrderSection.ORDER_DETAILS,
        List.of("manageOrdersTransparencyOrderExpiration", "manageOrdersTransparencyOrderEndDate",
            "manageOrdersTransparencyOrderPublishInformationLabel",
            "manageOrdersTransparencyOrderPublishInformationDetails",
            "manageOrdersTransparencyOrderPublishIdentityLabel", "manageOrdersTransparencyOrderPublishIdentityDetails",
            "manageOrdersTransparencyOrderPublishDocumentsLabel",
            "manageOrdersTransparencyOrderPublishDocumentsDetails",
            "manageOrdersTransparencyOrderPermissionToReportEffectiveDate"));

    private final String showHideField;
    private final OrderSection section;
    private final List<String> transientDataFields;
}
