apiVersion: apps/v1
kind: Deployment
metadata:
  name: fpl-prd-mock-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fpl-prd-mock
  template:
    metadata:
      labels:
        app: fpl-prd-mock
    spec:
      containers:
        - name: fpl-prd-mock
          image: rodolpheche/wiremock
          ports:
            - containerPort: 8080
          volumeMounts:
            - name: fpl-prd-mock-mappings-volume
              mountPath: /home/wiremock/mappings
      volumes:
        - name: fpl-prd-mock-mappings-volume
          configMap:
            name: fpl-prd-mock-mappings
