package uk.gov.hmcts.reform.fpl.ccd;

import java.util.Set;
import uk.gov.hmcts.ccd.sdk.api.ConfigBuilder;
import uk.gov.hmcts.ccd.sdk.api.Permission;
import uk.gov.hmcts.reform.fpl.enums.State;
import uk.gov.hmcts.reform.fpl.model.CaseData;
import uk.gov.hmcts.reform.fpl.model.UserRole;

/**
 * Generated by ccd-definition-converter from CARE_SUPERVISION_EPO on migration; owned by this service team.
 *
 * <p>AuthorisationComplexType grants for {@code CARE_SUPERVISION_EPO} (part 36).
 */
public final class CARESUPERVISIONEPOComplexTypeGrants36 {
    private CARESUPERVISIONEPOComplexTypeGrants36() {
    }

    /**
     * @param builder the config builder
     */
    static void apply(ConfigBuilder<CaseData, State, UserRole> builder) {
        builder.grantComplexType(CaseData::getHearingOrdersBundlesDrafts, "ordersChild12", Set.of(Permission.C), UserRole.SOLICITORC);
        builder.grantComplexType(CaseData::getHearingOrdersBundlesDrafts, "ordersChild12", Set.of(Permission.C), UserRole.SOLICITORD);
        builder.grantComplexType(CaseData::getHearingOrdersBundlesDrafts, "ordersChild12", Set.of(Permission.C), UserRole.SOLICITORE);
        builder.grantComplexType(CaseData::getHearingOrdersBundlesDrafts, "ordersChild12", Set.of(Permission.C), UserRole.SOLICITORF);
        builder.grantComplexType(CaseData::getHearingOrdersBundlesDrafts, "ordersChild12", Set.of(Permission.C), UserRole.SOLICITORG);
        builder.grantComplexType(CaseData::getHearingOrdersBundlesDrafts, "ordersChild12", Set.of(Permission.C), UserRole.SOLICITORH);
        builder.grantComplexType(CaseData::getHearingOrdersBundlesDrafts, "ordersChild12", Set.of(Permission.C), UserRole.SOLICITORI);
        builder.grantComplexType(CaseData::getHearingOrdersBundlesDrafts, "ordersChild12", Set.of(Permission.C), UserRole.SOLICITORJ);
        builder.grantComplexType(CaseData::getHearingOrdersBundlesDrafts, "ordersChild12", Set.of(Permission.C), UserRole.CHILDSOLICITORA);
        builder.grantComplexType(CaseData::getHearingOrdersBundlesDrafts, "ordersChild12", Set.of(Permission.C), UserRole.CHILDSOLICITORB);
        builder.grantComplexType(CaseData::getHearingOrdersBundlesDrafts, "ordersChild12", Set.of(Permission.C), UserRole.CHILDSOLICITORC);
        builder.grantComplexType(CaseData::getHearingOrdersBundlesDrafts, "ordersChild12", Set.of(Permission.C), UserRole.CHILDSOLICITORD);
        builder.grantComplexType(CaseData::getHearingOrdersBundlesDrafts, "ordersChild12", Set.of(Permission.C), UserRole.CHILDSOLICITORE);
        builder.grantComplexType(CaseData::getHearingOrdersBundlesDrafts, "ordersChild12", Set.of(Permission.C), UserRole.CHILDSOLICITORF);
        builder.grantComplexType(CaseData::getHearingOrdersBundlesDrafts, "ordersChild12", Set.of(Permission.C), UserRole.CHILDSOLICITORG);
        builder.grantComplexType(CaseData::getHearingOrdersBundlesDrafts, "ordersChild12", Set.of(Permission.C), UserRole.CHILDSOLICITORH);
        builder.grantComplexType(CaseData::getHearingOrdersBundlesDrafts, "ordersChild12", Set.of(Permission.C), UserRole.CHILDSOLICITORI);
        builder.grantComplexType(CaseData::getHearingOrdersBundlesDrafts, "ordersChild12", Set.of(Permission.C), UserRole.CHILDSOLICITORJ);
        builder.grantComplexType(CaseData::getHearingOrdersBundlesDrafts, "ordersChild12", Set.of(Permission.C), UserRole.CHILDSOLICITORK);
        builder.grantComplexType(CaseData::getHearingOrdersBundlesDrafts, "ordersChild12", Set.of(Permission.C), UserRole.CHILDSOLICITORL);
        builder.grantComplexType(CaseData::getHearingOrdersBundlesDrafts, "ordersChild12", Set.of(Permission.C), UserRole.CHILDSOLICITORN);
        builder.grantComplexType(CaseData::getHearingOrdersBundlesDrafts, "ordersChild12", Set.of(Permission.C), UserRole.CHILDSOLICITORO);
        builder.grantComplexType(CaseData::getHearingOrdersBundlesDrafts, "ordersChild12", Set.of(Permission.C), UserRole.EPSMANAGING);
        builder.grantComplexType(CaseData::getHearingOrdersBundlesDrafts, "ordersChild12", Set.of(Permission.C), UserRole.LABARRISTER);
        builder.grantComplexType(CaseData::getHearingOrdersBundlesDrafts, "ordersChild12", Set.of(Permission.C), UserRole.LASOLICITOR);
        builder.grantComplexType(CaseData::getHearingOrdersBundlesDrafts, "ordersChild12", Set.of(Permission.C), UserRole.LAMANAGING);
        builder.grantComplexType(CaseData::getHearingOrdersBundlesDrafts, "ordersChild12", Set.of(Permission.C), UserRole.LASHARED);
        builder.grantComplexType(CaseData::getHearingOrdersBundlesDrafts, "ordersChild12", Set.of(Permission.C), UserRole.CAFCASSSOLICITOR);
        builder.grantComplexType(CaseData::getHearingOrdersBundlesDrafts, "ordersChild13", Permission.CRU, UserRole.CASEWORKER_PUBLICLAW_JUDICIARY);
        builder.grantComplexType(CaseData::getHearingOrdersBundlesDrafts, "ordersChild13", Permission.CRU, UserRole.CASEWORKER_PUBLICLAW_SYSTEMUPDATE);
        builder.grantComplexType(CaseData::getHearingOrdersBundlesDrafts, "ordersChild13", Permission.CRU, UserRole.CASEWORKER_PUBLICLAW_SUPERUSER);
        builder.grantComplexType(CaseData::getHearingOrdersBundlesDrafts, "ordersChild13", Permission.CRU, UserRole.CHILDSOLICITORN);
        builder.grantComplexType(CaseData::getHearingOrdersBundlesDrafts, "ordersChild13", Set.of(Permission.R), UserRole.CASEWORKER_PUBLICLAW_COURTADMIN);
        builder.grantComplexType(CaseData::getHearingOrdersBundlesDrafts, "ordersChild13", Set.of(Permission.R), UserRole.CASEWORKER_PUBLICLAW_GATEKEEPER);
        builder.grantComplexType(CaseData::getHearingOrdersBundlesDrafts, "ordersChild13", Set.of(Permission.R), UserRole.CASEWORKER_PUBLICLAW_CAFCASS);
        builder.grantComplexType(CaseData::getHearingOrdersBundlesDrafts, "ordersChild13", Set.of(Permission.R), UserRole.CASEWORKER_PUBLICLAW_CAFCASSSYSTEMUPDATE);
        builder.grantComplexType(CaseData::getHearingOrdersBundlesDrafts, "ordersChild13", Set.of(Permission.R), UserRole.CASEWORKER_PUBLICLAW_MAGISTRATE);
        builder.grantComplexType(CaseData::getHearingOrdersBundlesDrafts, "ordersChild13", Set.of(Permission.C), UserRole.BARRISTER);
        builder.grantComplexType(CaseData::getHearingOrdersBundlesDrafts, "ordersChild13", Set.of(Permission.C), UserRole.SOLICITOR);
        builder.grantComplexType(CaseData::getHearingOrdersBundlesDrafts, "ordersChild13", Set.of(Permission.C), UserRole.SOLICITORA);
        builder.grantComplexType(CaseData::getHearingOrdersBundlesDrafts, "ordersChild13", Set.of(Permission.C), UserRole.SOLICITORB);
        builder.grantComplexType(CaseData::getHearingOrdersBundlesDrafts, "ordersChild13", Set.of(Permission.C), UserRole.SOLICITORC);
        builder.grantComplexType(CaseData::getHearingOrdersBundlesDrafts, "ordersChild13", Set.of(Permission.C), UserRole.SOLICITORD);
        builder.grantComplexType(CaseData::getHearingOrdersBundlesDrafts, "ordersChild13", Set.of(Permission.C), UserRole.SOLICITORE);
        builder.grantComplexType(CaseData::getHearingOrdersBundlesDrafts, "ordersChild13", Set.of(Permission.C), UserRole.SOLICITORF);
        builder.grantComplexType(CaseData::getHearingOrdersBundlesDrafts, "ordersChild13", Set.of(Permission.C), UserRole.SOLICITORG);
        builder.grantComplexType(CaseData::getHearingOrdersBundlesDrafts, "ordersChild13", Set.of(Permission.C), UserRole.SOLICITORH);
        builder.grantComplexType(CaseData::getHearingOrdersBundlesDrafts, "ordersChild13", Set.of(Permission.C), UserRole.SOLICITORI);
        builder.grantComplexType(CaseData::getHearingOrdersBundlesDrafts, "ordersChild13", Set.of(Permission.C), UserRole.SOLICITORJ);
        builder.grantComplexType(CaseData::getHearingOrdersBundlesDrafts, "ordersChild13", Set.of(Permission.C), UserRole.CHILDSOLICITORA);
        builder.grantComplexType(CaseData::getHearingOrdersBundlesDrafts, "ordersChild13", Set.of(Permission.C), UserRole.CHILDSOLICITORB);
        builder.grantComplexType(CaseData::getHearingOrdersBundlesDrafts, "ordersChild13", Set.of(Permission.C), UserRole.CHILDSOLICITORC);
        builder.grantComplexType(CaseData::getHearingOrdersBundlesDrafts, "ordersChild13", Set.of(Permission.C), UserRole.CHILDSOLICITORD);
        builder.grantComplexType(CaseData::getHearingOrdersBundlesDrafts, "ordersChild13", Set.of(Permission.C), UserRole.CHILDSOLICITORE);
        builder.grantComplexType(CaseData::getHearingOrdersBundlesDrafts, "ordersChild13", Set.of(Permission.C), UserRole.CHILDSOLICITORF);
        builder.grantComplexType(CaseData::getHearingOrdersBundlesDrafts, "ordersChild13", Set.of(Permission.C), UserRole.CHILDSOLICITORG);
        builder.grantComplexType(CaseData::getHearingOrdersBundlesDrafts, "ordersChild13", Set.of(Permission.C), UserRole.CHILDSOLICITORH);
        builder.grantComplexType(CaseData::getHearingOrdersBundlesDrafts, "ordersChild13", Set.of(Permission.C), UserRole.CHILDSOLICITORI);
        builder.grantComplexType(CaseData::getHearingOrdersBundlesDrafts, "ordersChild13", Set.of(Permission.C), UserRole.CHILDSOLICITORJ);
        builder.grantComplexType(CaseData::getHearingOrdersBundlesDrafts, "ordersChild13", Set.of(Permission.C), UserRole.CHILDSOLICITORK);
        builder.grantComplexType(CaseData::getHearingOrdersBundlesDrafts, "ordersChild13", Set.of(Permission.C), UserRole.CHILDSOLICITORL);
        builder.grantComplexType(CaseData::getHearingOrdersBundlesDrafts, "ordersChild13", Set.of(Permission.C), UserRole.CHILDSOLICITORM);
        builder.grantComplexType(CaseData::getHearingOrdersBundlesDrafts, "ordersChild13", Set.of(Permission.C), UserRole.CHILDSOLICITORO);
        builder.grantComplexType(CaseData::getHearingOrdersBundlesDrafts, "ordersChild13", Set.of(Permission.C), UserRole.EPSMANAGING);
        builder.grantComplexType(CaseData::getHearingOrdersBundlesDrafts, "ordersChild13", Set.of(Permission.C), UserRole.LABARRISTER);
        builder.grantComplexType(CaseData::getHearingOrdersBundlesDrafts, "ordersChild13", Set.of(Permission.C), UserRole.LASOLICITOR);
        builder.grantComplexType(CaseData::getHearingOrdersBundlesDrafts, "ordersChild13", Set.of(Permission.C), UserRole.LAMANAGING);
        builder.grantComplexType(CaseData::getHearingOrdersBundlesDrafts, "ordersChild13", Set.of(Permission.C), UserRole.LASHARED);
        builder.grantComplexType(CaseData::getHearingOrdersBundlesDrafts, "ordersChild13", Set.of(Permission.C), UserRole.CAFCASSSOLICITOR);
        builder.grantComplexType(CaseData::getHearingOrdersBundlesDrafts, "ordersChild14", Permission.CRU, UserRole.CASEWORKER_PUBLICLAW_JUDICIARY);
        builder.grantComplexType(CaseData::getHearingOrdersBundlesDrafts, "ordersChild14", Permission.CRU, UserRole.CASEWORKER_PUBLICLAW_SYSTEMUPDATE);
        builder.grantComplexType(CaseData::getHearingOrdersBundlesDrafts, "ordersChild14", Permission.CRU, UserRole.CASEWORKER_PUBLICLAW_SUPERUSER);
        builder.grantComplexType(CaseData::getHearingOrdersBundlesDrafts, "ordersChild14", Permission.CRU, UserRole.CHILDSOLICITORO);
        builder.grantComplexType(CaseData::getHearingOrdersBundlesDrafts, "ordersChild14", Set.of(Permission.R), UserRole.CASEWORKER_PUBLICLAW_COURTADMIN);
        builder.grantComplexType(CaseData::getHearingOrdersBundlesDrafts, "ordersChild14", Set.of(Permission.R), UserRole.CASEWORKER_PUBLICLAW_GATEKEEPER);
        builder.grantComplexType(CaseData::getHearingOrdersBundlesDrafts, "ordersChild14", Set.of(Permission.R), UserRole.CASEWORKER_PUBLICLAW_CAFCASS);
        builder.grantComplexType(CaseData::getHearingOrdersBundlesDrafts, "ordersChild14", Set.of(Permission.R), UserRole.CASEWORKER_PUBLICLAW_CAFCASSSYSTEMUPDATE);
        builder.grantComplexType(CaseData::getHearingOrdersBundlesDrafts, "ordersChild14", Set.of(Permission.R), UserRole.CASEWORKER_PUBLICLAW_MAGISTRATE);
        builder.grantComplexType(CaseData::getHearingOrdersBundlesDrafts, "ordersChild14", Set.of(Permission.C), UserRole.BARRISTER);
        builder.grantComplexType(CaseData::getHearingOrdersBundlesDrafts, "ordersChild14", Set.of(Permission.C), UserRole.SOLICITOR);
        builder.grantComplexType(CaseData::getHearingOrdersBundlesDrafts, "ordersChild14", Set.of(Permission.C), UserRole.SOLICITORA);
        builder.grantComplexType(CaseData::getHearingOrdersBundlesDrafts, "ordersChild14", Set.of(Permission.C), UserRole.SOLICITORB);
        builder.grantComplexType(CaseData::getHearingOrdersBundlesDrafts, "ordersChild14", Set.of(Permission.C), UserRole.SOLICITORC);
        builder.grantComplexType(CaseData::getHearingOrdersBundlesDrafts, "ordersChild14", Set.of(Permission.C), UserRole.SOLICITORD);
        builder.grantComplexType(CaseData::getHearingOrdersBundlesDrafts, "ordersChild14", Set.of(Permission.C), UserRole.SOLICITORE);
        builder.grantComplexType(CaseData::getHearingOrdersBundlesDrafts, "ordersChild14", Set.of(Permission.C), UserRole.SOLICITORF);
        builder.grantComplexType(CaseData::getHearingOrdersBundlesDrafts, "ordersChild14", Set.of(Permission.C), UserRole.SOLICITORG);
        builder.grantComplexType(CaseData::getHearingOrdersBundlesDrafts, "ordersChild14", Set.of(Permission.C), UserRole.SOLICITORH);
        builder.grantComplexType(CaseData::getHearingOrdersBundlesDrafts, "ordersChild14", Set.of(Permission.C), UserRole.SOLICITORI);
        builder.grantComplexType(CaseData::getHearingOrdersBundlesDrafts, "ordersChild14", Set.of(Permission.C), UserRole.SOLICITORJ);
        builder.grantComplexType(CaseData::getHearingOrdersBundlesDrafts, "ordersChild14", Set.of(Permission.C), UserRole.CHILDSOLICITORA);
        builder.grantComplexType(CaseData::getHearingOrdersBundlesDrafts, "ordersChild14", Set.of(Permission.C), UserRole.CHILDSOLICITORB);
        builder.grantComplexType(CaseData::getHearingOrdersBundlesDrafts, "ordersChild14", Set.of(Permission.C), UserRole.CHILDSOLICITORC);
        builder.grantComplexType(CaseData::getHearingOrdersBundlesDrafts, "ordersChild14", Set.of(Permission.C), UserRole.CHILDSOLICITORD);
        builder.grantComplexType(CaseData::getHearingOrdersBundlesDrafts, "ordersChild14", Set.of(Permission.C), UserRole.CHILDSOLICITORE);
        builder.grantComplexType(CaseData::getHearingOrdersBundlesDrafts, "ordersChild14", Set.of(Permission.C), UserRole.CHILDSOLICITORF);
        builder.grantComplexType(CaseData::getHearingOrdersBundlesDrafts, "ordersChild14", Set.of(Permission.C), UserRole.CHILDSOLICITORG);
        builder.grantComplexType(CaseData::getHearingOrdersBundlesDrafts, "ordersChild14", Set.of(Permission.C), UserRole.CHILDSOLICITORH);
        builder.grantComplexType(CaseData::getHearingOrdersBundlesDrafts, "ordersChild14", Set.of(Permission.C), UserRole.CHILDSOLICITORI);
        builder.grantComplexType(CaseData::getHearingOrdersBundlesDrafts, "ordersChild14", Set.of(Permission.C), UserRole.CHILDSOLICITORJ);
        builder.grantComplexType(CaseData::getHearingOrdersBundlesDrafts, "ordersChild14", Set.of(Permission.C), UserRole.CHILDSOLICITORK);
        builder.grantComplexType(CaseData::getHearingOrdersBundlesDrafts, "ordersChild14", Set.of(Permission.C), UserRole.CHILDSOLICITORL);
        builder.grantComplexType(CaseData::getHearingOrdersBundlesDrafts, "ordersChild14", Set.of(Permission.C), UserRole.CHILDSOLICITORM);
        builder.grantComplexType(CaseData::getHearingOrdersBundlesDrafts, "ordersChild14", Set.of(Permission.C), UserRole.CHILDSOLICITORN);
        builder.grantComplexType(CaseData::getHearingOrdersBundlesDrafts, "ordersChild14", Set.of(Permission.C), UserRole.EPSMANAGING);
        builder.grantComplexType(CaseData::getHearingOrdersBundlesDrafts, "ordersChild14", Set.of(Permission.C), UserRole.LABARRISTER);
        builder.grantComplexType(CaseData::getHearingOrdersBundlesDrafts, "ordersChild14", Set.of(Permission.C), UserRole.LASOLICITOR);
        builder.grantComplexType(CaseData::getHearingOrdersBundlesDrafts, "ordersChild14", Set.of(Permission.C), UserRole.LAMANAGING);
        builder.grantComplexType(CaseData::getHearingOrdersBundlesDrafts, "ordersChild14", Set.of(Permission.C), UserRole.LASHARED);
        builder.grantComplexType(CaseData::getHearingOrdersBundlesDrafts, "ordersChild14", Set.of(Permission.C), UserRole.CAFCASSSOLICITOR);
        builder.grantComplexType(CaseData::getOrderCollection, "type", Permission.CRU, UserRole.CASEWORKER_PUBLICLAW_COURTADMIN);
        builder.grantComplexType(CaseData::getOrderCollection, "type", Permission.CRU, UserRole.CASEWORKER_PUBLICLAW_GATEKEEPER);
        builder.grantComplexType(CaseData::getOrderCollection, "type", Permission.CRU, UserRole.CASEWORKER_PUBLICLAW_JUDICIARY);
        builder.grantComplexType(CaseData::getOrderCollection, "type", Permission.CRU, UserRole.CASEWORKER_PUBLICLAW_SYSTEMUPDATE);
        builder.grantComplexType(CaseData::getOrderCollection, "type", Set.of(Permission.R), UserRole.BARRISTER);
        builder.grantComplexType(CaseData::getOrderCollection, "type", Set.of(Permission.R), UserRole.CAFCASSSOLICITOR);
        builder.grantComplexType(CaseData::getOrderCollection, "type", Set.of(Permission.R), UserRole.EPSMANAGING);
        builder.grantComplexType(CaseData::getOrderCollection, "type", Set.of(Permission.R), UserRole.LABARRISTER);
        builder.grantComplexType(CaseData::getOrderCollection, "type", Set.of(Permission.R), UserRole.LAMANAGING);
        builder.grantComplexType(CaseData::getOrderCollection, "type", Set.of(Permission.R), UserRole.LASHARED);
    }
}
