package uk.gov.hmcts.reform.fpl.ccd;

import java.util.Set;
import uk.gov.hmcts.ccd.sdk.api.ConfigBuilder;
import uk.gov.hmcts.ccd.sdk.api.Permission;
import uk.gov.hmcts.reform.fpl.enums.State;
import uk.gov.hmcts.reform.fpl.model.CaseData;
import uk.gov.hmcts.reform.fpl.model.UserRole;

/**
 * Generated by ccd-definition-converter from CARE_SUPERVISION_EPO on migration; owned by this service team.
 *
 * <p>AuthorisationComplexType grants for {@code CARE_SUPERVISION_EPO} (part 79).
 */
public final class CARESUPERVISIONEPOComplexTypeGrants79 {
    private CARESUPERVISIONEPOComplexTypeGrants79() {
    }

    /**
     * @param builder the config builder
     */
    static void apply(ConfigBuilder<CaseData, State, UserRole> builder) {
        builder.grantComplexType(CaseData::getUrgentHearingOrder, "translationUploadDateTime", Set.of(Permission.R), UserRole.EPSMANAGING);
        builder.grantComplexType(CaseData::getUrgentHearingOrder, "translationUploadDateTime", Set.of(Permission.R), UserRole.LABARRISTER);
        builder.grantComplexType(CaseData::getUrgentHearingOrder, "translationUploadDateTime", Set.of(Permission.R), UserRole.LAMANAGING);
        builder.grantComplexType(CaseData::getUrgentHearingOrder, "translationUploadDateTime", Set.of(Permission.R), UserRole.LASHARED);
        builder.grantComplexType(CaseData::getUrgentHearingOrder, "translationUploadDateTime", Set.of(Permission.R), UserRole.LASOLICITOR);
        builder.grantComplexType(CaseData::getUrgentHearingOrder, "translationUploadDateTime", Set.of(Permission.R), UserRole.CASEWORKER_PUBLICLAW_MAGISTRATE);
        builder.grantComplexType(CaseData::getUrgentHearingOrder, "unsealedOrder", Set.of(Permission.C, Permission.U), UserRole.CASEWORKER_PUBLICLAW_GATEKEEPER);
        builder.grantComplexType(CaseData::getUrgentHearingOrder, "unsealedOrder", Set.of(Permission.C, Permission.U), UserRole.CASEWORKER_PUBLICLAW_JUDICIARY);
        builder.grantComplexType(CaseData::getUrgentHearingOrder, "unsealedOrder", Set.of(Permission.C, Permission.U), UserRole.SOLICITOR);
        builder.grantComplexType(CaseData::getUrgentHearingOrder, "unsealedOrder", Set.of(Permission.C, Permission.U), UserRole.SOLICITORA);
        builder.grantComplexType(CaseData::getUrgentHearingOrder, "unsealedOrder", Set.of(Permission.C, Permission.U), UserRole.SOLICITORB);
        builder.grantComplexType(CaseData::getUrgentHearingOrder, "unsealedOrder", Set.of(Permission.C, Permission.U), UserRole.SOLICITORC);
        builder.grantComplexType(CaseData::getUrgentHearingOrder, "unsealedOrder", Set.of(Permission.C, Permission.U), UserRole.SOLICITORD);
        builder.grantComplexType(CaseData::getUrgentHearingOrder, "unsealedOrder", Set.of(Permission.C, Permission.U), UserRole.SOLICITORE);
        builder.grantComplexType(CaseData::getUrgentHearingOrder, "unsealedOrder", Set.of(Permission.C, Permission.U), UserRole.SOLICITORF);
        builder.grantComplexType(CaseData::getUrgentHearingOrder, "unsealedOrder", Set.of(Permission.C, Permission.U), UserRole.SOLICITORG);
        builder.grantComplexType(CaseData::getUrgentHearingOrder, "unsealedOrder", Set.of(Permission.C, Permission.U), UserRole.SOLICITORH);
        builder.grantComplexType(CaseData::getUrgentHearingOrder, "unsealedOrder", Set.of(Permission.C, Permission.U), UserRole.SOLICITORI);
        builder.grantComplexType(CaseData::getUrgentHearingOrder, "unsealedOrder", Set.of(Permission.C, Permission.U), UserRole.SOLICITORJ);
        builder.grantComplexType(CaseData::getUrgentHearingOrder, "unsealedOrder", Set.of(Permission.C, Permission.U), UserRole.CHILDSOLICITORA);
        builder.grantComplexType(CaseData::getUrgentHearingOrder, "unsealedOrder", Set.of(Permission.C, Permission.U), UserRole.CHILDSOLICITORB);
        builder.grantComplexType(CaseData::getUrgentHearingOrder, "unsealedOrder", Set.of(Permission.C, Permission.U), UserRole.CHILDSOLICITORC);
        builder.grantComplexType(CaseData::getUrgentHearingOrder, "unsealedOrder", Set.of(Permission.C, Permission.U), UserRole.CHILDSOLICITORD);
        builder.grantComplexType(CaseData::getUrgentHearingOrder, "unsealedOrder", Set.of(Permission.C, Permission.U), UserRole.CHILDSOLICITORE);
        builder.grantComplexType(CaseData::getUrgentHearingOrder, "unsealedOrder", Set.of(Permission.C, Permission.U), UserRole.CHILDSOLICITORF);
        builder.grantComplexType(CaseData::getUrgentHearingOrder, "unsealedOrder", Set.of(Permission.C, Permission.U), UserRole.CHILDSOLICITORG);
        builder.grantComplexType(CaseData::getUrgentHearingOrder, "unsealedOrder", Set.of(Permission.C, Permission.U), UserRole.CHILDSOLICITORH);
        builder.grantComplexType(CaseData::getUrgentHearingOrder, "unsealedOrder", Set.of(Permission.C, Permission.U), UserRole.CHILDSOLICITORI);
        builder.grantComplexType(CaseData::getUrgentHearingOrder, "unsealedOrder", Set.of(Permission.C, Permission.U), UserRole.CHILDSOLICITORJ);
        builder.grantComplexType(CaseData::getUrgentHearingOrder, "unsealedOrder", Set.of(Permission.C, Permission.U), UserRole.CHILDSOLICITORK);
        builder.grantComplexType(CaseData::getUrgentHearingOrder, "unsealedOrder", Set.of(Permission.C, Permission.U), UserRole.CHILDSOLICITORL);
        builder.grantComplexType(CaseData::getUrgentHearingOrder, "unsealedOrder", Set.of(Permission.C, Permission.U), UserRole.CHILDSOLICITORM);
        builder.grantComplexType(CaseData::getUrgentHearingOrder, "unsealedOrder", Set.of(Permission.C, Permission.U), UserRole.CHILDSOLICITORN);
        builder.grantComplexType(CaseData::getUrgentHearingOrder, "unsealedOrder", Set.of(Permission.C, Permission.U), UserRole.CHILDSOLICITORO);
        builder.grantComplexType(CaseData::getUrgentHearingOrder, "unsealedOrder", Set.of(Permission.C, Permission.U), UserRole.CASEWORKER_PUBLICLAW_SUPERUSER);
        builder.grantComplexType(CaseData::getUrgentHearingOrder, "unsealedOrder", Set.of(Permission.C, Permission.U, Permission.D), UserRole.CASEWORKER_PUBLICLAW_SYSTEMUPDATE);
        builder.grantComplexType(CaseData::getUrgentHearingOrder, "unsealedOrder", Set.of(Permission.U), UserRole.CASEWORKER_PUBLICLAW_COURTADMIN);
        builder.grantComplexType(CaseData::getUrgentHearingOrder, "unsealedOrder", Set.of(Permission.U), UserRole.CASEWORKER_PUBLICLAW_CAFCASS);
        builder.grantComplexType(CaseData::getUrgentHearingOrder, "amendedDate", Permission.CRU, UserRole.CASEWORKER_PUBLICLAW_GATEKEEPER);
        builder.grantComplexType(CaseData::getUrgentHearingOrder, "amendedDate", Permission.CRU, UserRole.CASEWORKER_PUBLICLAW_JUDICIARY);
        builder.grantComplexType(CaseData::getUrgentHearingOrder, "amendedDate", Permission.CRU, UserRole.SOLICITOR);
        builder.grantComplexType(CaseData::getUrgentHearingOrder, "amendedDate", Permission.CRU, UserRole.SOLICITORA);
        builder.grantComplexType(CaseData::getUrgentHearingOrder, "amendedDate", Permission.CRU, UserRole.SOLICITORB);
        builder.grantComplexType(CaseData::getUrgentHearingOrder, "amendedDate", Permission.CRU, UserRole.SOLICITORC);
        builder.grantComplexType(CaseData::getUrgentHearingOrder, "amendedDate", Permission.CRU, UserRole.SOLICITORD);
        builder.grantComplexType(CaseData::getUrgentHearingOrder, "amendedDate", Permission.CRU, UserRole.SOLICITORE);
        builder.grantComplexType(CaseData::getUrgentHearingOrder, "amendedDate", Permission.CRU, UserRole.SOLICITORF);
        builder.grantComplexType(CaseData::getUrgentHearingOrder, "amendedDate", Permission.CRU, UserRole.SOLICITORG);
        builder.grantComplexType(CaseData::getUrgentHearingOrder, "amendedDate", Permission.CRU, UserRole.SOLICITORH);
        builder.grantComplexType(CaseData::getUrgentHearingOrder, "amendedDate", Permission.CRU, UserRole.SOLICITORI);
        builder.grantComplexType(CaseData::getUrgentHearingOrder, "amendedDate", Permission.CRU, UserRole.SOLICITORJ);
        builder.grantComplexType(CaseData::getUrgentHearingOrder, "amendedDate", Permission.CRU, UserRole.CHILDSOLICITORA);
        builder.grantComplexType(CaseData::getUrgentHearingOrder, "amendedDate", Permission.CRU, UserRole.CHILDSOLICITORB);
        builder.grantComplexType(CaseData::getUrgentHearingOrder, "amendedDate", Permission.CRU, UserRole.CHILDSOLICITORC);
        builder.grantComplexType(CaseData::getUrgentHearingOrder, "amendedDate", Permission.CRU, UserRole.CHILDSOLICITORD);
        builder.grantComplexType(CaseData::getUrgentHearingOrder, "amendedDate", Permission.CRU, UserRole.CHILDSOLICITORE);
        builder.grantComplexType(CaseData::getUrgentHearingOrder, "amendedDate", Permission.CRU, UserRole.CHILDSOLICITORF);
        builder.grantComplexType(CaseData::getUrgentHearingOrder, "amendedDate", Permission.CRU, UserRole.CHILDSOLICITORG);
        builder.grantComplexType(CaseData::getUrgentHearingOrder, "amendedDate", Permission.CRU, UserRole.CHILDSOLICITORH);
        builder.grantComplexType(CaseData::getUrgentHearingOrder, "amendedDate", Permission.CRU, UserRole.CHILDSOLICITORI);
        builder.grantComplexType(CaseData::getUrgentHearingOrder, "amendedDate", Permission.CRU, UserRole.CHILDSOLICITORJ);
        builder.grantComplexType(CaseData::getUrgentHearingOrder, "amendedDate", Permission.CRU, UserRole.CHILDSOLICITORK);
        builder.grantComplexType(CaseData::getUrgentHearingOrder, "amendedDate", Permission.CRU, UserRole.CHILDSOLICITORL);
        builder.grantComplexType(CaseData::getUrgentHearingOrder, "amendedDate", Permission.CRU, UserRole.CHILDSOLICITORM);
        builder.grantComplexType(CaseData::getUrgentHearingOrder, "amendedDate", Permission.CRU, UserRole.CHILDSOLICITORN);
        builder.grantComplexType(CaseData::getUrgentHearingOrder, "amendedDate", Permission.CRU, UserRole.CHILDSOLICITORO);
        builder.grantComplexType(CaseData::getUrgentHearingOrder, "amendedDate", Permission.CRU, UserRole.CASEWORKER_PUBLICLAW_SUPERUSER);
        builder.grantComplexType(CaseData::getUrgentHearingOrder, "amendedDate", Permission.CRUD, UserRole.CASEWORKER_PUBLICLAW_SYSTEMUPDATE);
        builder.grantComplexType(CaseData::getUrgentHearingOrder, "amendedDate", Set.of(Permission.R, Permission.U), UserRole.CASEWORKER_PUBLICLAW_COURTADMIN);
        builder.grantComplexType(CaseData::getUrgentHearingOrder, "amendedDate", Set.of(Permission.R, Permission.U), UserRole.CASEWORKER_PUBLICLAW_CAFCASS);
        builder.grantComplexType(CaseData::getUrgentHearingOrder, "amendedDate", Set.of(Permission.R), UserRole.BARRISTER);
        builder.grantComplexType(CaseData::getUrgentHearingOrder, "amendedDate", Set.of(Permission.R), UserRole.CAFCASSSOLICITOR);
        builder.grantComplexType(CaseData::getUrgentHearingOrder, "amendedDate", Set.of(Permission.R), UserRole.EPSMANAGING);
        builder.grantComplexType(CaseData::getUrgentHearingOrder, "amendedDate", Set.of(Permission.R), UserRole.LABARRISTER);
        builder.grantComplexType(CaseData::getUrgentHearingOrder, "amendedDate", Set.of(Permission.R), UserRole.LAMANAGING);
        builder.grantComplexType(CaseData::getUrgentHearingOrder, "amendedDate", Set.of(Permission.R), UserRole.LASHARED);
        builder.grantComplexType(CaseData::getUrgentHearingOrder, "amendedDate", Set.of(Permission.R), UserRole.LASOLICITOR);
        builder.grantComplexType(CaseData::getUrgentHearingOrder, "amendedDate", Set.of(Permission.R), UserRole.CASEWORKER_PUBLICLAW_MAGISTRATE);
        builder.grantComplexType(CaseData::getUrgentHearingOrder, "dateAdded", Permission.CRU, UserRole.CASEWORKER_PUBLICLAW_GATEKEEPER);
        builder.grantComplexType(CaseData::getUrgentHearingOrder, "dateAdded", Permission.CRU, UserRole.CASEWORKER_PUBLICLAW_JUDICIARY);
        builder.grantComplexType(CaseData::getUrgentHearingOrder, "dateAdded", Permission.CRU, UserRole.SOLICITOR);
        builder.grantComplexType(CaseData::getUrgentHearingOrder, "dateAdded", Permission.CRU, UserRole.SOLICITORA);
        builder.grantComplexType(CaseData::getUrgentHearingOrder, "dateAdded", Permission.CRU, UserRole.SOLICITORB);
        builder.grantComplexType(CaseData::getUrgentHearingOrder, "dateAdded", Permission.CRU, UserRole.SOLICITORC);
        builder.grantComplexType(CaseData::getUrgentHearingOrder, "dateAdded", Permission.CRU, UserRole.SOLICITORD);
        builder.grantComplexType(CaseData::getUrgentHearingOrder, "dateAdded", Permission.CRU, UserRole.SOLICITORE);
        builder.grantComplexType(CaseData::getUrgentHearingOrder, "dateAdded", Permission.CRU, UserRole.SOLICITORF);
        builder.grantComplexType(CaseData::getUrgentHearingOrder, "dateAdded", Permission.CRU, UserRole.SOLICITORG);
        builder.grantComplexType(CaseData::getUrgentHearingOrder, "dateAdded", Permission.CRU, UserRole.SOLICITORH);
        builder.grantComplexType(CaseData::getUrgentHearingOrder, "dateAdded", Permission.CRU, UserRole.SOLICITORI);
        builder.grantComplexType(CaseData::getUrgentHearingOrder, "dateAdded", Permission.CRU, UserRole.SOLICITORJ);
        builder.grantComplexType(CaseData::getUrgentHearingOrder, "dateAdded", Permission.CRU, UserRole.CHILDSOLICITORA);
        builder.grantComplexType(CaseData::getUrgentHearingOrder, "dateAdded", Permission.CRU, UserRole.CHILDSOLICITORB);
        builder.grantComplexType(CaseData::getUrgentHearingOrder, "dateAdded", Permission.CRU, UserRole.CHILDSOLICITORC);
        builder.grantComplexType(CaseData::getUrgentHearingOrder, "dateAdded", Permission.CRU, UserRole.CHILDSOLICITORD);
        builder.grantComplexType(CaseData::getUrgentHearingOrder, "dateAdded", Permission.CRU, UserRole.CHILDSOLICITORE);
        builder.grantComplexType(CaseData::getUrgentHearingOrder, "dateAdded", Permission.CRU, UserRole.CHILDSOLICITORF);
        builder.grantComplexType(CaseData::getUrgentHearingOrder, "dateAdded", Permission.CRU, UserRole.CHILDSOLICITORG);
        builder.grantComplexType(CaseData::getUrgentHearingOrder, "dateAdded", Permission.CRU, UserRole.CHILDSOLICITORH);
        builder.grantComplexType(CaseData::getUrgentHearingOrder, "dateAdded", Permission.CRU, UserRole.CHILDSOLICITORI);
        builder.grantComplexType(CaseData::getUrgentHearingOrder, "dateAdded", Permission.CRU, UserRole.CHILDSOLICITORJ);
        builder.grantComplexType(CaseData::getUrgentHearingOrder, "dateAdded", Permission.CRU, UserRole.CHILDSOLICITORK);
        builder.grantComplexType(CaseData::getUrgentHearingOrder, "dateAdded", Permission.CRU, UserRole.CHILDSOLICITORL);
        builder.grantComplexType(CaseData::getUrgentHearingOrder, "dateAdded", Permission.CRU, UserRole.CHILDSOLICITORM);
        builder.grantComplexType(CaseData::getUrgentHearingOrder, "dateAdded", Permission.CRU, UserRole.CHILDSOLICITORN);
        builder.grantComplexType(CaseData::getUrgentHearingOrder, "dateAdded", Permission.CRU, UserRole.CHILDSOLICITORO);
        builder.grantComplexType(CaseData::getUrgentHearingOrder, "dateAdded", Permission.CRU, UserRole.CASEWORKER_PUBLICLAW_SUPERUSER);
        builder.grantComplexType(CaseData::getUrgentHearingOrder, "dateAdded", Permission.CRUD, UserRole.CASEWORKER_PUBLICLAW_SYSTEMUPDATE);
        builder.grantComplexType(CaseData::getUrgentHearingOrder, "dateAdded", Set.of(Permission.R, Permission.U), UserRole.CASEWORKER_PUBLICLAW_COURTADMIN);
        builder.grantComplexType(CaseData::getUrgentHearingOrder, "dateAdded", Set.of(Permission.R, Permission.U), UserRole.CASEWORKER_PUBLICLAW_CAFCASS);
        builder.grantComplexType(CaseData::getUrgentHearingOrder, "dateAdded", Set.of(Permission.R), UserRole.BARRISTER);
        builder.grantComplexType(CaseData::getUrgentHearingOrder, "dateAdded", Set.of(Permission.R), UserRole.CAFCASSSOLICITOR);
        builder.grantComplexType(CaseData::getUrgentHearingOrder, "dateAdded", Set.of(Permission.R), UserRole.EPSMANAGING);
        builder.grantComplexType(CaseData::getUrgentHearingOrder, "dateAdded", Set.of(Permission.R), UserRole.LABARRISTER);
        builder.grantComplexType(CaseData::getUrgentHearingOrder, "dateAdded", Set.of(Permission.R), UserRole.LAMANAGING);
        builder.grantComplexType(CaseData::getUrgentHearingOrder, "dateAdded", Set.of(Permission.R), UserRole.LASHARED);
        builder.grantComplexType(CaseData::getUrgentHearingOrder, "dateAdded", Set.of(Permission.R), UserRole.LASOLICITOR);
        builder.grantComplexType(CaseData::getUrgentHearingOrder, "dateAdded", Set.of(Permission.R), UserRole.CASEWORKER_PUBLICLAW_MAGISTRATE);
        builder.grantComplexType(CaseData::getUrgentHearingOrder, "translationRequirements", Permission.CRU, UserRole.CASEWORKER_PUBLICLAW_GATEKEEPER);
        builder.grantComplexType(CaseData::getUrgentHearingOrder, "translationRequirements", Permission.CRU, UserRole.CASEWORKER_PUBLICLAW_JUDICIARY);
    }
}
