package uk.gov.hmcts.reform.fpl.ccd;

import java.util.Set;
import uk.gov.hmcts.ccd.sdk.api.ConfigBuilder;
import uk.gov.hmcts.ccd.sdk.api.Permission;
import uk.gov.hmcts.reform.fpl.enums.State;
import uk.gov.hmcts.reform.fpl.model.CaseData;
import uk.gov.hmcts.reform.fpl.model.UserRole;

/**
 * Generated by ccd-definition-converter from CARE_SUPERVISION_EPO on migration; owned by this service team.
 *
 * <p>AuthorisationComplexType grants for {@code CARE_SUPERVISION_EPO} (part 21).
 */
public final class CARESUPERVISIONEPOComplexTypeGrants21 {
    private CARESUPERVISIONEPOComplexTypeGrants21() {
    }

    /**
     * @param builder the config builder
     */
    static void apply(ConfigBuilder<CaseData, State, UserRole> builder) {
        builder.grantComplexType(CaseData::getAdditionalApplicationsBundle, "c2DocumentBundleChild9", Set.of(Permission.U), UserRole.CHILDSOLICITORK);
        builder.grantComplexType(CaseData::getAdditionalApplicationsBundle, "c2DocumentBundleChild9", Set.of(Permission.U), UserRole.CHILDSOLICITORL);
        builder.grantComplexType(CaseData::getAdditionalApplicationsBundle, "c2DocumentBundleChild9", Set.of(Permission.U), UserRole.CHILDSOLICITORM);
        builder.grantComplexType(CaseData::getAdditionalApplicationsBundle, "c2DocumentBundleChild9", Set.of(Permission.U), UserRole.CHILDSOLICITORN);
        builder.grantComplexType(CaseData::getAdditionalApplicationsBundle, "c2DocumentBundleChild9", Set.of(Permission.U), UserRole.CHILDSOLICITORO);
        builder.grantComplexType(CaseData::getAdditionalApplicationsBundle, "c2DocumentBundleChild9", Set.of(Permission.U), UserRole.CAFCASSSOLICITOR);
        builder.grantComplexType(CaseData::getAdditionalApplicationsBundle, "c2DocumentBundleChild9", Set.of(Permission.U), UserRole.CASEWORKER_PUBLICLAW_COURTADMIN);
        builder.grantComplexType(CaseData::getAdditionalApplicationsBundle, "c2DocumentBundleChild9", Set.of(Permission.U), UserRole.BARRISTER);
        builder.grantComplexType(CaseData::getAdditionalApplicationsBundle, "c2DocumentBundleChild9", Set.of(Permission.U), UserRole.CASEWORKER_PUBLICLAW_GATEKEEPER);
        builder.grantComplexType(CaseData::getAdditionalApplicationsBundle, "c2DocumentBundleChild9", Set.of(Permission.U), UserRole.CASEWORKER_PUBLICLAW_JUDICIARY);
        builder.grantComplexType(CaseData::getAdditionalApplicationsBundle, "c2DocumentBundleChild9", Set.of(Permission.U), UserRole.CASEWORKER_PUBLICLAW_MAGISTRATE);
        builder.grantComplexType(CaseData::getAdditionalApplicationsBundle, "c2DocumentBundleChild9", Set.of(Permission.U), UserRole.EPSMANAGING);
        builder.grantComplexType(CaseData::getAdditionalApplicationsBundle, "c2DocumentBundleChild9", Set.of(Permission.U), UserRole.LABARRISTER);
        builder.grantComplexType(CaseData::getAdditionalApplicationsBundle, "c2DocumentBundleChild9", Set.of(Permission.U), UserRole.LAMANAGING);
        builder.grantComplexType(CaseData::getAdditionalApplicationsBundle, "c2DocumentBundleChild9", Set.of(Permission.U), UserRole.LASOLICITOR);
        builder.grantComplexType(CaseData::getAdditionalApplicationsBundle, "c2DocumentBundleChild9", Set.of(Permission.U), UserRole.LASHARED);
        builder.grantComplexType(CaseData::getAdditionalApplicationsBundle, "c2DocumentBundleChild10", Set.of(Permission.R), UserRole.CASEWORKER_PUBLICLAW_CAFCASSSYSTEMUPDATE);
        builder.grantComplexType(CaseData::getAdditionalApplicationsBundle, "c2DocumentBundleChild10", Permission.CRU, UserRole.CASEWORKER_PUBLICLAW_CAFCASS);
        builder.grantComplexType(CaseData::getAdditionalApplicationsBundle, "c2DocumentBundleChild10", Permission.CRU, UserRole.CASEWORKER_PUBLICLAW_SYSTEMUPDATE);
        builder.grantComplexType(CaseData::getAdditionalApplicationsBundle, "c2DocumentBundleChild10", Permission.CRU, UserRole.CHILDSOLICITORK);
        builder.grantComplexType(CaseData::getAdditionalApplicationsBundle, "c2DocumentBundleChild10", Set.of(Permission.U), UserRole.SOLICITORA);
        builder.grantComplexType(CaseData::getAdditionalApplicationsBundle, "c2DocumentBundleChild10", Set.of(Permission.U), UserRole.SOLICITORB);
        builder.grantComplexType(CaseData::getAdditionalApplicationsBundle, "c2DocumentBundleChild10", Set.of(Permission.U), UserRole.SOLICITORC);
        builder.grantComplexType(CaseData::getAdditionalApplicationsBundle, "c2DocumentBundleChild10", Set.of(Permission.U), UserRole.SOLICITORD);
        builder.grantComplexType(CaseData::getAdditionalApplicationsBundle, "c2DocumentBundleChild10", Set.of(Permission.U), UserRole.SOLICITORE);
        builder.grantComplexType(CaseData::getAdditionalApplicationsBundle, "c2DocumentBundleChild10", Set.of(Permission.U), UserRole.SOLICITORF);
        builder.grantComplexType(CaseData::getAdditionalApplicationsBundle, "c2DocumentBundleChild10", Set.of(Permission.U), UserRole.SOLICITORG);
        builder.grantComplexType(CaseData::getAdditionalApplicationsBundle, "c2DocumentBundleChild10", Set.of(Permission.U), UserRole.SOLICITORH);
        builder.grantComplexType(CaseData::getAdditionalApplicationsBundle, "c2DocumentBundleChild10", Set.of(Permission.U), UserRole.SOLICITORI);
        builder.grantComplexType(CaseData::getAdditionalApplicationsBundle, "c2DocumentBundleChild10", Set.of(Permission.U), UserRole.SOLICITORJ);
        builder.grantComplexType(CaseData::getAdditionalApplicationsBundle, "c2DocumentBundleChild10", Set.of(Permission.U), UserRole.CHILDSOLICITORA);
        builder.grantComplexType(CaseData::getAdditionalApplicationsBundle, "c2DocumentBundleChild10", Set.of(Permission.U), UserRole.CHILDSOLICITORB);
        builder.grantComplexType(CaseData::getAdditionalApplicationsBundle, "c2DocumentBundleChild10", Set.of(Permission.U), UserRole.CHILDSOLICITORC);
        builder.grantComplexType(CaseData::getAdditionalApplicationsBundle, "c2DocumentBundleChild10", Set.of(Permission.U), UserRole.CHILDSOLICITORD);
        builder.grantComplexType(CaseData::getAdditionalApplicationsBundle, "c2DocumentBundleChild10", Set.of(Permission.U), UserRole.CHILDSOLICITORE);
        builder.grantComplexType(CaseData::getAdditionalApplicationsBundle, "c2DocumentBundleChild10", Set.of(Permission.U), UserRole.CHILDSOLICITORF);
        builder.grantComplexType(CaseData::getAdditionalApplicationsBundle, "c2DocumentBundleChild10", Set.of(Permission.U), UserRole.CHILDSOLICITORG);
        builder.grantComplexType(CaseData::getAdditionalApplicationsBundle, "c2DocumentBundleChild10", Set.of(Permission.U), UserRole.CHILDSOLICITORH);
        builder.grantComplexType(CaseData::getAdditionalApplicationsBundle, "c2DocumentBundleChild10", Set.of(Permission.U), UserRole.CHILDSOLICITORI);
        builder.grantComplexType(CaseData::getAdditionalApplicationsBundle, "c2DocumentBundleChild10", Set.of(Permission.U), UserRole.CHILDSOLICITORJ);
        builder.grantComplexType(CaseData::getAdditionalApplicationsBundle, "c2DocumentBundleChild10", Set.of(Permission.U), UserRole.CHILDSOLICITORL);
        builder.grantComplexType(CaseData::getAdditionalApplicationsBundle, "c2DocumentBundleChild10", Set.of(Permission.U), UserRole.CHILDSOLICITORM);
        builder.grantComplexType(CaseData::getAdditionalApplicationsBundle, "c2DocumentBundleChild10", Set.of(Permission.U), UserRole.CHILDSOLICITORN);
        builder.grantComplexType(CaseData::getAdditionalApplicationsBundle, "c2DocumentBundleChild10", Set.of(Permission.U), UserRole.CHILDSOLICITORO);
        builder.grantComplexType(CaseData::getAdditionalApplicationsBundle, "c2DocumentBundleChild10", Set.of(Permission.U), UserRole.CAFCASSSOLICITOR);
        builder.grantComplexType(CaseData::getAdditionalApplicationsBundle, "c2DocumentBundleChild10", Set.of(Permission.U), UserRole.CASEWORKER_PUBLICLAW_COURTADMIN);
        builder.grantComplexType(CaseData::getAdditionalApplicationsBundle, "c2DocumentBundleChild10", Set.of(Permission.U), UserRole.BARRISTER);
        builder.grantComplexType(CaseData::getAdditionalApplicationsBundle, "c2DocumentBundleChild10", Set.of(Permission.U), UserRole.CASEWORKER_PUBLICLAW_GATEKEEPER);
        builder.grantComplexType(CaseData::getAdditionalApplicationsBundle, "c2DocumentBundleChild10", Set.of(Permission.U), UserRole.CASEWORKER_PUBLICLAW_JUDICIARY);
        builder.grantComplexType(CaseData::getAdditionalApplicationsBundle, "c2DocumentBundleChild10", Set.of(Permission.U), UserRole.CASEWORKER_PUBLICLAW_MAGISTRATE);
        builder.grantComplexType(CaseData::getAdditionalApplicationsBundle, "c2DocumentBundleChild10", Set.of(Permission.U), UserRole.EPSMANAGING);
        builder.grantComplexType(CaseData::getAdditionalApplicationsBundle, "c2DocumentBundleChild10", Set.of(Permission.U), UserRole.LABARRISTER);
        builder.grantComplexType(CaseData::getAdditionalApplicationsBundle, "c2DocumentBundleChild10", Set.of(Permission.U), UserRole.LAMANAGING);
        builder.grantComplexType(CaseData::getAdditionalApplicationsBundle, "c2DocumentBundleChild10", Set.of(Permission.U), UserRole.LASOLICITOR);
        builder.grantComplexType(CaseData::getAdditionalApplicationsBundle, "c2DocumentBundleChild10", Set.of(Permission.U), UserRole.LASHARED);
        builder.grantComplexType(CaseData::getAdditionalApplicationsBundle, "c2DocumentBundleChild11", Set.of(Permission.R), UserRole.CASEWORKER_PUBLICLAW_CAFCASSSYSTEMUPDATE);
        builder.grantComplexType(CaseData::getAdditionalApplicationsBundle, "c2DocumentBundleChild11", Permission.CRU, UserRole.CASEWORKER_PUBLICLAW_CAFCASS);
        builder.grantComplexType(CaseData::getAdditionalApplicationsBundle, "c2DocumentBundleChild11", Permission.CRU, UserRole.CASEWORKER_PUBLICLAW_SYSTEMUPDATE);
        builder.grantComplexType(CaseData::getAdditionalApplicationsBundle, "c2DocumentBundleChild11", Permission.CRU, UserRole.CHILDSOLICITORL);
        builder.grantComplexType(CaseData::getAdditionalApplicationsBundle, "c2DocumentBundleChild11", Set.of(Permission.U), UserRole.SOLICITORA);
        builder.grantComplexType(CaseData::getAdditionalApplicationsBundle, "c2DocumentBundleChild11", Set.of(Permission.U), UserRole.SOLICITORB);
        builder.grantComplexType(CaseData::getAdditionalApplicationsBundle, "c2DocumentBundleChild11", Set.of(Permission.U), UserRole.SOLICITORC);
        builder.grantComplexType(CaseData::getAdditionalApplicationsBundle, "c2DocumentBundleChild11", Set.of(Permission.U), UserRole.SOLICITORD);
        builder.grantComplexType(CaseData::getAdditionalApplicationsBundle, "c2DocumentBundleChild11", Set.of(Permission.U), UserRole.SOLICITORE);
        builder.grantComplexType(CaseData::getAdditionalApplicationsBundle, "c2DocumentBundleChild11", Set.of(Permission.U), UserRole.SOLICITORF);
        builder.grantComplexType(CaseData::getAdditionalApplicationsBundle, "c2DocumentBundleChild11", Set.of(Permission.U), UserRole.SOLICITORG);
        builder.grantComplexType(CaseData::getAdditionalApplicationsBundle, "c2DocumentBundleChild11", Set.of(Permission.U), UserRole.SOLICITORH);
        builder.grantComplexType(CaseData::getAdditionalApplicationsBundle, "c2DocumentBundleChild11", Set.of(Permission.U), UserRole.SOLICITORI);
        builder.grantComplexType(CaseData::getAdditionalApplicationsBundle, "c2DocumentBundleChild11", Set.of(Permission.U), UserRole.SOLICITORJ);
        builder.grantComplexType(CaseData::getAdditionalApplicationsBundle, "c2DocumentBundleChild11", Set.of(Permission.U), UserRole.CHILDSOLICITORA);
        builder.grantComplexType(CaseData::getAdditionalApplicationsBundle, "c2DocumentBundleChild11", Set.of(Permission.U), UserRole.CHILDSOLICITORB);
        builder.grantComplexType(CaseData::getAdditionalApplicationsBundle, "c2DocumentBundleChild11", Set.of(Permission.U), UserRole.CHILDSOLICITORC);
        builder.grantComplexType(CaseData::getAdditionalApplicationsBundle, "c2DocumentBundleChild11", Set.of(Permission.U), UserRole.CHILDSOLICITORD);
        builder.grantComplexType(CaseData::getAdditionalApplicationsBundle, "c2DocumentBundleChild11", Set.of(Permission.U), UserRole.CHILDSOLICITORE);
        builder.grantComplexType(CaseData::getAdditionalApplicationsBundle, "c2DocumentBundleChild11", Set.of(Permission.U), UserRole.CHILDSOLICITORF);
        builder.grantComplexType(CaseData::getAdditionalApplicationsBundle, "c2DocumentBundleChild11", Set.of(Permission.U), UserRole.CHILDSOLICITORG);
        builder.grantComplexType(CaseData::getAdditionalApplicationsBundle, "c2DocumentBundleChild11", Set.of(Permission.U), UserRole.CHILDSOLICITORH);
        builder.grantComplexType(CaseData::getAdditionalApplicationsBundle, "c2DocumentBundleChild11", Set.of(Permission.U), UserRole.CHILDSOLICITORI);
        builder.grantComplexType(CaseData::getAdditionalApplicationsBundle, "c2DocumentBundleChild11", Set.of(Permission.U), UserRole.CHILDSOLICITORJ);
        builder.grantComplexType(CaseData::getAdditionalApplicationsBundle, "c2DocumentBundleChild11", Set.of(Permission.U), UserRole.CHILDSOLICITORK);
        builder.grantComplexType(CaseData::getAdditionalApplicationsBundle, "c2DocumentBundleChild11", Set.of(Permission.U), UserRole.CHILDSOLICITORM);
        builder.grantComplexType(CaseData::getAdditionalApplicationsBundle, "c2DocumentBundleChild11", Set.of(Permission.U), UserRole.CHILDSOLICITORN);
        builder.grantComplexType(CaseData::getAdditionalApplicationsBundle, "c2DocumentBundleChild11", Set.of(Permission.U), UserRole.CHILDSOLICITORO);
        builder.grantComplexType(CaseData::getAdditionalApplicationsBundle, "c2DocumentBundleChild11", Set.of(Permission.U), UserRole.CAFCASSSOLICITOR);
        builder.grantComplexType(CaseData::getAdditionalApplicationsBundle, "c2DocumentBundleChild11", Set.of(Permission.U), UserRole.CASEWORKER_PUBLICLAW_COURTADMIN);
        builder.grantComplexType(CaseData::getAdditionalApplicationsBundle, "c2DocumentBundleChild11", Set.of(Permission.U), UserRole.BARRISTER);
        builder.grantComplexType(CaseData::getAdditionalApplicationsBundle, "c2DocumentBundleChild11", Set.of(Permission.U), UserRole.CASEWORKER_PUBLICLAW_GATEKEEPER);
        builder.grantComplexType(CaseData::getAdditionalApplicationsBundle, "c2DocumentBundleChild11", Set.of(Permission.U), UserRole.CASEWORKER_PUBLICLAW_JUDICIARY);
        builder.grantComplexType(CaseData::getAdditionalApplicationsBundle, "c2DocumentBundleChild11", Set.of(Permission.U), UserRole.CASEWORKER_PUBLICLAW_MAGISTRATE);
        builder.grantComplexType(CaseData::getAdditionalApplicationsBundle, "c2DocumentBundleChild11", Set.of(Permission.U), UserRole.EPSMANAGING);
        builder.grantComplexType(CaseData::getAdditionalApplicationsBundle, "c2DocumentBundleChild11", Set.of(Permission.U), UserRole.LABARRISTER);
        builder.grantComplexType(CaseData::getAdditionalApplicationsBundle, "c2DocumentBundleChild11", Set.of(Permission.U), UserRole.LAMANAGING);
        builder.grantComplexType(CaseData::getAdditionalApplicationsBundle, "c2DocumentBundleChild11", Set.of(Permission.U), UserRole.LASOLICITOR);
        builder.grantComplexType(CaseData::getAdditionalApplicationsBundle, "c2DocumentBundleChild11", Set.of(Permission.U), UserRole.LASHARED);
        builder.grantComplexType(CaseData::getAdditionalApplicationsBundle, "c2DocumentBundleChild12", Set.of(Permission.R), UserRole.CASEWORKER_PUBLICLAW_CAFCASSSYSTEMUPDATE);
        builder.grantComplexType(CaseData::getAdditionalApplicationsBundle, "c2DocumentBundleChild12", Permission.CRU, UserRole.CASEWORKER_PUBLICLAW_CAFCASS);
        builder.grantComplexType(CaseData::getAdditionalApplicationsBundle, "c2DocumentBundleChild12", Permission.CRU, UserRole.CASEWORKER_PUBLICLAW_SYSTEMUPDATE);
        builder.grantComplexType(CaseData::getAdditionalApplicationsBundle, "c2DocumentBundleChild12", Permission.CRU, UserRole.CHILDSOLICITORM);
        builder.grantComplexType(CaseData::getAdditionalApplicationsBundle, "c2DocumentBundleChild12", Set.of(Permission.U), UserRole.SOLICITORA);
        builder.grantComplexType(CaseData::getAdditionalApplicationsBundle, "c2DocumentBundleChild12", Set.of(Permission.U), UserRole.SOLICITORB);
        builder.grantComplexType(CaseData::getAdditionalApplicationsBundle, "c2DocumentBundleChild12", Set.of(Permission.U), UserRole.SOLICITORC);
        builder.grantComplexType(CaseData::getAdditionalApplicationsBundle, "c2DocumentBundleChild12", Set.of(Permission.U), UserRole.SOLICITORD);
        builder.grantComplexType(CaseData::getAdditionalApplicationsBundle, "c2DocumentBundleChild12", Set.of(Permission.U), UserRole.SOLICITORE);
        builder.grantComplexType(CaseData::getAdditionalApplicationsBundle, "c2DocumentBundleChild12", Set.of(Permission.U), UserRole.SOLICITORF);
        builder.grantComplexType(CaseData::getAdditionalApplicationsBundle, "c2DocumentBundleChild12", Set.of(Permission.U), UserRole.SOLICITORG);
        builder.grantComplexType(CaseData::getAdditionalApplicationsBundle, "c2DocumentBundleChild12", Set.of(Permission.U), UserRole.SOLICITORH);
        builder.grantComplexType(CaseData::getAdditionalApplicationsBundle, "c2DocumentBundleChild12", Set.of(Permission.U), UserRole.SOLICITORI);
        builder.grantComplexType(CaseData::getAdditionalApplicationsBundle, "c2DocumentBundleChild12", Set.of(Permission.U), UserRole.SOLICITORJ);
        builder.grantComplexType(CaseData::getAdditionalApplicationsBundle, "c2DocumentBundleChild12", Set.of(Permission.U), UserRole.CHILDSOLICITORA);
        builder.grantComplexType(CaseData::getAdditionalApplicationsBundle, "c2DocumentBundleChild12", Set.of(Permission.U), UserRole.CHILDSOLICITORB);
        builder.grantComplexType(CaseData::getAdditionalApplicationsBundle, "c2DocumentBundleChild12", Set.of(Permission.U), UserRole.CHILDSOLICITORC);
        builder.grantComplexType(CaseData::getAdditionalApplicationsBundle, "c2DocumentBundleChild12", Set.of(Permission.U), UserRole.CHILDSOLICITORD);
        builder.grantComplexType(CaseData::getAdditionalApplicationsBundle, "c2DocumentBundleChild12", Set.of(Permission.U), UserRole.CHILDSOLICITORE);
        builder.grantComplexType(CaseData::getAdditionalApplicationsBundle, "c2DocumentBundleChild12", Set.of(Permission.U), UserRole.CHILDSOLICITORF);
        builder.grantComplexType(CaseData::getAdditionalApplicationsBundle, "c2DocumentBundleChild12", Set.of(Permission.U), UserRole.CHILDSOLICITORG);
        builder.grantComplexType(CaseData::getAdditionalApplicationsBundle, "c2DocumentBundleChild12", Set.of(Permission.U), UserRole.CHILDSOLICITORH);
        builder.grantComplexType(CaseData::getAdditionalApplicationsBundle, "c2DocumentBundleChild12", Set.of(Permission.U), UserRole.CHILDSOLICITORI);
        builder.grantComplexType(CaseData::getAdditionalApplicationsBundle, "c2DocumentBundleChild12", Set.of(Permission.U), UserRole.CHILDSOLICITORJ);
        builder.grantComplexType(CaseData::getAdditionalApplicationsBundle, "c2DocumentBundleChild12", Set.of(Permission.U), UserRole.CHILDSOLICITORK);
        builder.grantComplexType(CaseData::getAdditionalApplicationsBundle, "c2DocumentBundleChild12", Set.of(Permission.U), UserRole.CHILDSOLICITORL);
    }
}
