package uk.gov.hmcts.reform.fpl.ccd;

import java.util.Set;
import uk.gov.hmcts.ccd.sdk.api.ConfigBuilder;
import uk.gov.hmcts.ccd.sdk.api.Permission;
import uk.gov.hmcts.reform.fpl.enums.State;
import uk.gov.hmcts.reform.fpl.model.CaseData;
import uk.gov.hmcts.reform.fpl.model.UserRole;

/**
 * Generated by ccd-definition-converter from CARE_SUPERVISION_EPO on migration; owned by this service team.
 *
 * <p>AuthorisationComplexType grants for {@code CARE_SUPERVISION_EPO} (part 51).
 */
public final class CARESUPERVISIONEPOComplexTypeGrants51 {
    private CARESUPERVISIONEPOComplexTypeGrants51() {
    }

    /**
     * @param builder the config builder
     */
    static void apply(ConfigBuilder<CaseData, State, UserRole> builder) {
        builder.grantComplexType(CaseData::getPlacements, "placementConfidentialDocuments", Set.of(Permission.U), UserRole.SOLICITORH);
        builder.grantComplexType(CaseData::getPlacements, "placementConfidentialDocuments", Set.of(Permission.U), UserRole.SOLICITORI);
        builder.grantComplexType(CaseData::getPlacements, "placementConfidentialDocuments", Set.of(Permission.U), UserRole.SOLICITORJ);
        builder.grantComplexType(CaseData::getPlacements, "placementNoticeDocuments", Set.of(Permission.R), UserRole.CAFCASSSOLICITOR);
        builder.grantComplexType(CaseData::getPlacements, "placementNoticeDocuments", Set.of(Permission.R), UserRole.CASEWORKER_PUBLICLAW_GATEKEEPER);
        builder.grantComplexType(CaseData::getPlacements, "placementNoticeDocuments", Set.of(Permission.R), UserRole.CASEWORKER_PUBLICLAW_JUDICIARY);
        builder.grantComplexType(CaseData::getPlacements, "placementNoticeDocuments", Set.of(Permission.R), UserRole.CASEWORKER_PUBLICLAW_MAGISTRATE);
        builder.grantComplexType(CaseData::getPlacements, "placementNoticeDocuments", Permission.CRUD, UserRole.CASEWORKER_PUBLICLAW_CAFCASS);
        builder.grantComplexType(CaseData::getPlacements, "placementNoticeDocuments", Permission.CRUD, UserRole.CASEWORKER_PUBLICLAW_COURTADMIN);
        builder.grantComplexType(CaseData::getPlacements, "placementNoticeDocuments", Permission.CRUD, UserRole.EPSMANAGING);
        builder.grantComplexType(CaseData::getPlacements, "placementNoticeDocuments", Permission.CRUD, UserRole.LABARRISTER);
        builder.grantComplexType(CaseData::getPlacements, "placementNoticeDocuments", Permission.CRUD, UserRole.LAMANAGING);
        builder.grantComplexType(CaseData::getPlacements, "placementNoticeDocuments", Permission.CRUD, UserRole.LASHARED);
        builder.grantComplexType(CaseData::getPlacements, "placementNoticeDocuments", Permission.CRUD, UserRole.LASOLICITOR);
        builder.grantComplexType(CaseData::getPlacements, "placementNoticeDocuments", Permission.CRUD, UserRole.CASEWORKER_PUBLICLAW_SUPERUSER);
        builder.grantComplexType(CaseData::getPlacements, "placementNoticeDocuments", Permission.CRUD, UserRole.CASEWORKER_PUBLICLAW_SYSTEMUPDATE);
        builder.grantComplexType(CaseData::getPlacements, "placementNoticeDocuments", Set.of(Permission.U), UserRole.SOLICITOR);
        builder.grantComplexType(CaseData::getPlacements, "placementNoticeDocuments", Set.of(Permission.U), UserRole.SOLICITORA);
        builder.grantComplexType(CaseData::getPlacements, "placementNoticeDocuments", Set.of(Permission.U), UserRole.SOLICITORB);
        builder.grantComplexType(CaseData::getPlacements, "placementNoticeDocuments", Set.of(Permission.U), UserRole.SOLICITORC);
        builder.grantComplexType(CaseData::getPlacements, "placementNoticeDocuments", Set.of(Permission.U), UserRole.SOLICITORD);
        builder.grantComplexType(CaseData::getPlacements, "placementNoticeDocuments", Set.of(Permission.U), UserRole.SOLICITORE);
        builder.grantComplexType(CaseData::getPlacements, "placementNoticeDocuments", Set.of(Permission.U), UserRole.SOLICITORF);
        builder.grantComplexType(CaseData::getPlacements, "placementNoticeDocuments", Set.of(Permission.U), UserRole.SOLICITORG);
        builder.grantComplexType(CaseData::getPlacements, "placementNoticeDocuments", Set.of(Permission.U), UserRole.SOLICITORH);
        builder.grantComplexType(CaseData::getPlacements, "placementNoticeDocuments", Set.of(Permission.U), UserRole.SOLICITORI);
        builder.grantComplexType(CaseData::getPlacements, "placementNoticeDocuments", Set.of(Permission.U), UserRole.SOLICITORJ);
        builder.grantComplexType(CaseData::getPlacements, "placementNoticeDocumentsRemoved", Set.of(Permission.R), UserRole.CAFCASSSOLICITOR);
        builder.grantComplexType(CaseData::getPlacements, "placementNoticeDocumentsRemoved", Set.of(Permission.R), UserRole.CASEWORKER_PUBLICLAW_GATEKEEPER);
        builder.grantComplexType(CaseData::getPlacements, "placementNoticeDocumentsRemoved", Set.of(Permission.R), UserRole.CASEWORKER_PUBLICLAW_JUDICIARY);
        builder.grantComplexType(CaseData::getPlacements, "placementNoticeDocumentsRemoved", Set.of(Permission.R), UserRole.CASEWORKER_PUBLICLAW_MAGISTRATE);
        builder.grantComplexType(CaseData::getPlacements, "placementNoticeDocumentsRemoved", Set.of(Permission.C, Permission.U, Permission.D), UserRole.CASEWORKER_PUBLICLAW_CAFCASS);
        builder.grantComplexType(CaseData::getPlacements, "placementNoticeDocumentsRemoved", Set.of(Permission.C, Permission.U, Permission.D), UserRole.CASEWORKER_PUBLICLAW_COURTADMIN);
        builder.grantComplexType(CaseData::getPlacements, "placementNoticeDocumentsRemoved", Set.of(Permission.C, Permission.U, Permission.D), UserRole.EPSMANAGING);
        builder.grantComplexType(CaseData::getPlacements, "placementNoticeDocumentsRemoved", Set.of(Permission.C, Permission.U, Permission.D), UserRole.LABARRISTER);
        builder.grantComplexType(CaseData::getPlacements, "placementNoticeDocumentsRemoved", Set.of(Permission.C, Permission.U, Permission.D), UserRole.LAMANAGING);
        builder.grantComplexType(CaseData::getPlacements, "placementNoticeDocumentsRemoved", Set.of(Permission.C, Permission.U, Permission.D), UserRole.LASHARED);
        builder.grantComplexType(CaseData::getPlacements, "placementNoticeDocumentsRemoved", Set.of(Permission.C, Permission.U, Permission.D), UserRole.LASOLICITOR);
        builder.grantComplexType(CaseData::getPlacements, "placementNoticeDocumentsRemoved", Set.of(Permission.C, Permission.U, Permission.D), UserRole.CASEWORKER_PUBLICLAW_SUPERUSER);
        builder.grantComplexType(CaseData::getPlacements, "placementNoticeDocumentsRemoved", Set.of(Permission.C, Permission.U, Permission.D), UserRole.CASEWORKER_PUBLICLAW_SYSTEMUPDATE);
        builder.grantComplexType(CaseData::getPlacements, "placementNoticeDocumentsRemoved", Set.of(Permission.U), UserRole.SOLICITOR);
        builder.grantComplexType(CaseData::getPlacements, "placementNoticeDocumentsRemoved", Set.of(Permission.U), UserRole.SOLICITORA);
        builder.grantComplexType(CaseData::getPlacements, "placementNoticeDocumentsRemoved", Set.of(Permission.U), UserRole.SOLICITORB);
        builder.grantComplexType(CaseData::getPlacements, "placementNoticeDocumentsRemoved", Set.of(Permission.U), UserRole.SOLICITORC);
        builder.grantComplexType(CaseData::getPlacements, "placementNoticeDocumentsRemoved", Set.of(Permission.U), UserRole.SOLICITORD);
        builder.grantComplexType(CaseData::getPlacements, "placementNoticeDocumentsRemoved", Set.of(Permission.U), UserRole.SOLICITORE);
        builder.grantComplexType(CaseData::getPlacements, "placementNoticeDocumentsRemoved", Set.of(Permission.U), UserRole.SOLICITORF);
        builder.grantComplexType(CaseData::getPlacements, "placementNoticeDocumentsRemoved", Set.of(Permission.U), UserRole.SOLICITORG);
        builder.grantComplexType(CaseData::getPlacements, "placementNoticeDocumentsRemoved", Set.of(Permission.U), UserRole.SOLICITORH);
        builder.grantComplexType(CaseData::getPlacements, "placementNoticeDocumentsRemoved", Set.of(Permission.U), UserRole.SOLICITORI);
        builder.grantComplexType(CaseData::getPlacements, "placementNoticeDocumentsRemoved", Set.of(Permission.U), UserRole.SOLICITORJ);
        builder.grantComplexType(CaseData::getPlacements, "placementRespondentsToNotify", Set.of(Permission.R), UserRole.CAFCASSSOLICITOR);
        builder.grantComplexType(CaseData::getPlacements, "placementRespondentsToNotify", Set.of(Permission.R), UserRole.CASEWORKER_PUBLICLAW_GATEKEEPER);
        builder.grantComplexType(CaseData::getPlacements, "placementRespondentsToNotify", Set.of(Permission.R), UserRole.CASEWORKER_PUBLICLAW_JUDICIARY);
        builder.grantComplexType(CaseData::getPlacements, "placementRespondentsToNotify", Set.of(Permission.R), UserRole.CASEWORKER_PUBLICLAW_MAGISTRATE);
        builder.grantComplexType(CaseData::getPlacements, "placementRespondentsToNotify", Permission.CRUD, UserRole.CASEWORKER_PUBLICLAW_CAFCASS);
        builder.grantComplexType(CaseData::getPlacements, "placementRespondentsToNotify", Permission.CRUD, UserRole.CASEWORKER_PUBLICLAW_COURTADMIN);
        builder.grantComplexType(CaseData::getPlacements, "placementRespondentsToNotify", Permission.CRUD, UserRole.EPSMANAGING);
        builder.grantComplexType(CaseData::getPlacements, "placementRespondentsToNotify", Permission.CRUD, UserRole.LABARRISTER);
        builder.grantComplexType(CaseData::getPlacements, "placementRespondentsToNotify", Permission.CRUD, UserRole.LAMANAGING);
        builder.grantComplexType(CaseData::getPlacements, "placementRespondentsToNotify", Permission.CRUD, UserRole.LASHARED);
        builder.grantComplexType(CaseData::getPlacements, "placementRespondentsToNotify", Permission.CRUD, UserRole.LASOLICITOR);
        builder.grantComplexType(CaseData::getPlacements, "placementRespondentsToNotify", Permission.CRUD, UserRole.CASEWORKER_PUBLICLAW_SUPERUSER);
        builder.grantComplexType(CaseData::getPlacements, "placementRespondentsToNotify", Permission.CRUD, UserRole.CASEWORKER_PUBLICLAW_SYSTEMUPDATE);
        builder.grantComplexType(CaseData::getPlacements, "placementRespondentsToNotify", Set.of(Permission.U), UserRole.SOLICITOR);
        builder.grantComplexType(CaseData::getPlacements, "placementRespondentsToNotify", Set.of(Permission.U), UserRole.SOLICITORA);
        builder.grantComplexType(CaseData::getPlacements, "placementRespondentsToNotify", Set.of(Permission.U), UserRole.SOLICITORB);
        builder.grantComplexType(CaseData::getPlacements, "placementRespondentsToNotify", Set.of(Permission.U), UserRole.SOLICITORC);
        builder.grantComplexType(CaseData::getPlacements, "placementRespondentsToNotify", Set.of(Permission.U), UserRole.SOLICITORD);
        builder.grantComplexType(CaseData::getPlacements, "placementRespondentsToNotify", Set.of(Permission.U), UserRole.SOLICITORE);
        builder.grantComplexType(CaseData::getPlacements, "placementRespondentsToNotify", Set.of(Permission.U), UserRole.SOLICITORF);
        builder.grantComplexType(CaseData::getPlacements, "placementRespondentsToNotify", Set.of(Permission.U), UserRole.SOLICITORG);
        builder.grantComplexType(CaseData::getPlacements, "placementRespondentsToNotify", Set.of(Permission.U), UserRole.SOLICITORH);
        builder.grantComplexType(CaseData::getPlacements, "placementRespondentsToNotify", Set.of(Permission.U), UserRole.SOLICITORI);
        builder.grantComplexType(CaseData::getPlacements, "placementRespondentsToNotify", Set.of(Permission.U), UserRole.SOLICITORJ);
        builder.grantComplexType(CaseData::getPlacements, "placementNotice", Set.of(Permission.R), UserRole.CAFCASSSOLICITOR);
        builder.grantComplexType(CaseData::getPlacements, "placementNotice", Set.of(Permission.R), UserRole.CASEWORKER_PUBLICLAW_GATEKEEPER);
        builder.grantComplexType(CaseData::getPlacements, "placementNotice", Set.of(Permission.R), UserRole.CASEWORKER_PUBLICLAW_JUDICIARY);
        builder.grantComplexType(CaseData::getPlacements, "placementNotice", Set.of(Permission.R), UserRole.CASEWORKER_PUBLICLAW_MAGISTRATE);
        builder.grantComplexType(CaseData::getPlacements, "placementNotice", Permission.CRUD, UserRole.CASEWORKER_PUBLICLAW_CAFCASS);
        builder.grantComplexType(CaseData::getPlacements, "placementNotice", Permission.CRUD, UserRole.CASEWORKER_PUBLICLAW_COURTADMIN);
        builder.grantComplexType(CaseData::getPlacements, "placementNotice", Permission.CRUD, UserRole.EPSMANAGING);
        builder.grantComplexType(CaseData::getPlacements, "placementNotice", Permission.CRUD, UserRole.LABARRISTER);
        builder.grantComplexType(CaseData::getPlacements, "placementNotice", Permission.CRUD, UserRole.LAMANAGING);
        builder.grantComplexType(CaseData::getPlacements, "placementNotice", Permission.CRUD, UserRole.LASHARED);
        builder.grantComplexType(CaseData::getPlacements, "placementNotice", Permission.CRUD, UserRole.LASOLICITOR);
        builder.grantComplexType(CaseData::getPlacements, "placementNotice", Permission.CRUD, UserRole.CASEWORKER_PUBLICLAW_SUPERUSER);
        builder.grantComplexType(CaseData::getPlacements, "placementNotice", Permission.CRUD, UserRole.CASEWORKER_PUBLICLAW_SYSTEMUPDATE);
        builder.grantComplexType(CaseData::getPlacements, "placementNotice", Set.of(Permission.U), UserRole.SOLICITOR);
        builder.grantComplexType(CaseData::getPlacements, "placementNotice", Set.of(Permission.U), UserRole.SOLICITORA);
        builder.grantComplexType(CaseData::getPlacements, "placementNotice", Set.of(Permission.U), UserRole.SOLICITORB);
        builder.grantComplexType(CaseData::getPlacements, "placementNotice", Set.of(Permission.U), UserRole.SOLICITORC);
        builder.grantComplexType(CaseData::getPlacements, "placementNotice", Set.of(Permission.U), UserRole.SOLICITORD);
        builder.grantComplexType(CaseData::getPlacements, "placementNotice", Set.of(Permission.U), UserRole.SOLICITORE);
        builder.grantComplexType(CaseData::getPlacements, "placementNotice", Set.of(Permission.U), UserRole.SOLICITORF);
        builder.grantComplexType(CaseData::getPlacements, "placementNotice", Set.of(Permission.U), UserRole.SOLICITORG);
        builder.grantComplexType(CaseData::getPlacements, "placementNotice", Set.of(Permission.U), UserRole.SOLICITORH);
        builder.grantComplexType(CaseData::getPlacements, "placementNotice", Set.of(Permission.U), UserRole.SOLICITORI);
        builder.grantComplexType(CaseData::getPlacements, "placementNotice", Set.of(Permission.U), UserRole.SOLICITORJ);
        builder.grantComplexType(CaseData::getPlacementsNonConfidential, "placementChildId", Set.of(Permission.R, Permission.U), UserRole.BARRISTER);
        builder.grantComplexType(CaseData::getPlacementsNonConfidential, "placementChildId", Set.of(Permission.R, Permission.U), UserRole.SOLICITOR);
        builder.grantComplexType(CaseData::getPlacementsNonConfidential, "placementChildId", Set.of(Permission.R, Permission.U), UserRole.SOLICITORA);
        builder.grantComplexType(CaseData::getPlacementsNonConfidential, "placementChildId", Set.of(Permission.R, Permission.U), UserRole.SOLICITORB);
        builder.grantComplexType(CaseData::getPlacementsNonConfidential, "placementChildId", Set.of(Permission.R, Permission.U), UserRole.SOLICITORC);
        builder.grantComplexType(CaseData::getPlacementsNonConfidential, "placementChildId", Set.of(Permission.R, Permission.U), UserRole.SOLICITORD);
        builder.grantComplexType(CaseData::getPlacementsNonConfidential, "placementChildId", Set.of(Permission.R, Permission.U), UserRole.SOLICITORE);
        builder.grantComplexType(CaseData::getPlacementsNonConfidential, "placementChildId", Set.of(Permission.R, Permission.U), UserRole.SOLICITORF);
        builder.grantComplexType(CaseData::getPlacementsNonConfidential, "placementChildId", Set.of(Permission.R, Permission.U), UserRole.SOLICITORG);
        builder.grantComplexType(CaseData::getPlacementsNonConfidential, "placementChildId", Set.of(Permission.R, Permission.U), UserRole.SOLICITORH);
        builder.grantComplexType(CaseData::getPlacementsNonConfidential, "placementChildId", Set.of(Permission.R, Permission.U), UserRole.SOLICITORI);
        builder.grantComplexType(CaseData::getPlacementsNonConfidential, "placementChildId", Set.of(Permission.R, Permission.U), UserRole.SOLICITORJ);
        builder.grantComplexType(CaseData::getPlacementsNonConfidential, "placementChildId", Set.of(Permission.C, Permission.U, Permission.D), UserRole.CASEWORKER_PUBLICLAW_CAFCASS);
        builder.grantComplexType(CaseData::getPlacementsNonConfidential, "placementChildId", Set.of(Permission.C, Permission.U, Permission.D), UserRole.CASEWORKER_PUBLICLAW_COURTADMIN);
        builder.grantComplexType(CaseData::getPlacementsNonConfidential, "placementChildId", Set.of(Permission.C, Permission.U, Permission.D), UserRole.EPSMANAGING);
        builder.grantComplexType(CaseData::getPlacementsNonConfidential, "placementChildId", Set.of(Permission.C, Permission.U, Permission.D), UserRole.LABARRISTER);
        builder.grantComplexType(CaseData::getPlacementsNonConfidential, "placementChildId", Set.of(Permission.C, Permission.U, Permission.D), UserRole.LAMANAGING);
        builder.grantComplexType(CaseData::getPlacementsNonConfidential, "placementChildId", Set.of(Permission.C, Permission.U, Permission.D), UserRole.LASHARED);
        builder.grantComplexType(CaseData::getPlacementsNonConfidential, "placementChildId", Set.of(Permission.C, Permission.U, Permission.D), UserRole.LASOLICITOR);
        builder.grantComplexType(CaseData::getPlacementsNonConfidential, "placementChildId", Set.of(Permission.C, Permission.U, Permission.D), UserRole.CASEWORKER_PUBLICLAW_SUPERUSER);
        builder.grantComplexType(CaseData::getPlacementsNonConfidential, "placementChildId", Set.of(Permission.C, Permission.U, Permission.D), UserRole.CASEWORKER_PUBLICLAW_SYSTEMUPDATE);
    }
}
