package uk.gov.hmcts.reform.fpl.ccd;

import java.util.Set;
import uk.gov.hmcts.ccd.sdk.api.ConfigBuilder;
import uk.gov.hmcts.ccd.sdk.api.Permission;
import uk.gov.hmcts.reform.fpl.enums.State;
import uk.gov.hmcts.reform.fpl.model.CaseData;
import uk.gov.hmcts.reform.fpl.model.UserRole;

/**
 * Generated by ccd-definition-converter from CARE_SUPERVISION_EPO on migration; owned by this service team.
 *
 * <p>AuthorisationComplexType grants for {@code CARE_SUPERVISION_EPO} (part 25).
 */
public final class CARESUPERVISIONEPOComplexTypeGrants25 {
    private CARESUPERVISIONEPOComplexTypeGrants25() {
    }

    /**
     * @param builder the config builder
     */
    static void apply(ConfigBuilder<CaseData, State, UserRole> builder) {
        builder.grantComplexType(CaseData::getC2DocumentBundle, "pbaNumber", Permission.CRU, UserRole.SOLICITORJ);
        builder.grantComplexType(CaseData::getC2DocumentBundle, "pbaNumber", Permission.CRU, UserRole.CHILDSOLICITORA);
        builder.grantComplexType(CaseData::getC2DocumentBundle, "pbaNumber", Permission.CRU, UserRole.CHILDSOLICITORB);
        builder.grantComplexType(CaseData::getC2DocumentBundle, "pbaNumber", Permission.CRU, UserRole.CHILDSOLICITORC);
        builder.grantComplexType(CaseData::getC2DocumentBundle, "pbaNumber", Permission.CRU, UserRole.CHILDSOLICITORD);
        builder.grantComplexType(CaseData::getC2DocumentBundle, "pbaNumber", Permission.CRU, UserRole.CHILDSOLICITORE);
        builder.grantComplexType(CaseData::getC2DocumentBundle, "pbaNumber", Permission.CRU, UserRole.CHILDSOLICITORF);
        builder.grantComplexType(CaseData::getC2DocumentBundle, "pbaNumber", Permission.CRU, UserRole.CHILDSOLICITORG);
        builder.grantComplexType(CaseData::getC2DocumentBundle, "pbaNumber", Permission.CRU, UserRole.CHILDSOLICITORH);
        builder.grantComplexType(CaseData::getC2DocumentBundle, "pbaNumber", Permission.CRU, UserRole.CHILDSOLICITORI);
        builder.grantComplexType(CaseData::getC2DocumentBundle, "pbaNumber", Permission.CRU, UserRole.CHILDSOLICITORJ);
        builder.grantComplexType(CaseData::getC2DocumentBundle, "pbaNumber", Permission.CRU, UserRole.CHILDSOLICITORK);
        builder.grantComplexType(CaseData::getC2DocumentBundle, "pbaNumber", Permission.CRU, UserRole.CHILDSOLICITORL);
        builder.grantComplexType(CaseData::getC2DocumentBundle, "pbaNumber", Permission.CRU, UserRole.CHILDSOLICITORM);
        builder.grantComplexType(CaseData::getC2DocumentBundle, "pbaNumber", Permission.CRU, UserRole.CHILDSOLICITORN);
        builder.grantComplexType(CaseData::getC2DocumentBundle, "pbaNumber", Permission.CRU, UserRole.CHILDSOLICITORO);
        builder.grantComplexType(CaseData::getC2DocumentBundle, "pbaNumber", Permission.CRU, UserRole.LASOLICITOR);
        builder.grantComplexType(CaseData::getC2DocumentBundle, "pbaNumber", Permission.CRU, UserRole.LASHARED);
        builder.grantComplexType(CaseData::getC2DocumentBundle, "pbaNumber", Permission.CRU, UserRole.CAFCASSSOLICITOR);
        builder.grantComplexType(CaseData::getC2DocumentBundle, "pbaNumber", Permission.CRU, UserRole.CASEWORKER_PUBLICLAW_COURTADMIN);
        builder.grantComplexType(CaseData::getC2DocumentBundle, "pbaNumber", Permission.CRU, UserRole.CASEWORKER_PUBLICLAW_SYSTEMUPDATE);
        builder.grantComplexType(CaseData::getC2DocumentBundle, "pbaNumber", Permission.CRU, UserRole.CASEWORKER_PUBLICLAW_CAFCASS);
        builder.grantComplexType(CaseData::getC2DocumentBundle, "pbaNumber", Permission.CRU, UserRole.BARRISTER);
        builder.grantComplexType(CaseData::getC2DocumentBundle, "pbaNumber", Set.of(Permission.R), UserRole.CASEWORKER_PUBLICLAW_GATEKEEPER);
        builder.grantComplexType(CaseData::getC2DocumentBundle, "pbaNumber", Set.of(Permission.R), UserRole.CASEWORKER_PUBLICLAW_JUDICIARY);
        builder.grantComplexType(CaseData::getC2DocumentBundle, "pbaNumber", Set.of(Permission.R), UserRole.CASEWORKER_PUBLICLAW_MAGISTRATE);
        builder.grantComplexType(CaseData::getC2DocumentBundle, "clientCode", Permission.CRU, UserRole.LABARRISTER);
        builder.grantComplexType(CaseData::getC2DocumentBundle, "clientCode", Permission.CRU, UserRole.SOLICITOR);
        builder.grantComplexType(CaseData::getC2DocumentBundle, "clientCode", Permission.CRU, UserRole.SOLICITORA);
        builder.grantComplexType(CaseData::getC2DocumentBundle, "clientCode", Permission.CRU, UserRole.SOLICITORB);
        builder.grantComplexType(CaseData::getC2DocumentBundle, "clientCode", Permission.CRU, UserRole.SOLICITORC);
        builder.grantComplexType(CaseData::getC2DocumentBundle, "clientCode", Permission.CRU, UserRole.SOLICITORD);
        builder.grantComplexType(CaseData::getC2DocumentBundle, "clientCode", Permission.CRU, UserRole.SOLICITORE);
        builder.grantComplexType(CaseData::getC2DocumentBundle, "clientCode", Permission.CRU, UserRole.SOLICITORF);
        builder.grantComplexType(CaseData::getC2DocumentBundle, "clientCode", Permission.CRU, UserRole.SOLICITORG);
        builder.grantComplexType(CaseData::getC2DocumentBundle, "clientCode", Permission.CRU, UserRole.SOLICITORH);
        builder.grantComplexType(CaseData::getC2DocumentBundle, "clientCode", Permission.CRU, UserRole.SOLICITORI);
        builder.grantComplexType(CaseData::getC2DocumentBundle, "clientCode", Permission.CRU, UserRole.SOLICITORJ);
        builder.grantComplexType(CaseData::getC2DocumentBundle, "clientCode", Permission.CRU, UserRole.CHILDSOLICITORA);
        builder.grantComplexType(CaseData::getC2DocumentBundle, "clientCode", Permission.CRU, UserRole.CHILDSOLICITORB);
        builder.grantComplexType(CaseData::getC2DocumentBundle, "clientCode", Permission.CRU, UserRole.CHILDSOLICITORC);
        builder.grantComplexType(CaseData::getC2DocumentBundle, "clientCode", Permission.CRU, UserRole.CHILDSOLICITORD);
        builder.grantComplexType(CaseData::getC2DocumentBundle, "clientCode", Permission.CRU, UserRole.CHILDSOLICITORE);
        builder.grantComplexType(CaseData::getC2DocumentBundle, "clientCode", Permission.CRU, UserRole.CHILDSOLICITORF);
        builder.grantComplexType(CaseData::getC2DocumentBundle, "clientCode", Permission.CRU, UserRole.CHILDSOLICITORG);
        builder.grantComplexType(CaseData::getC2DocumentBundle, "clientCode", Permission.CRU, UserRole.CHILDSOLICITORH);
        builder.grantComplexType(CaseData::getC2DocumentBundle, "clientCode", Permission.CRU, UserRole.CHILDSOLICITORI);
        builder.grantComplexType(CaseData::getC2DocumentBundle, "clientCode", Permission.CRU, UserRole.CHILDSOLICITORJ);
        builder.grantComplexType(CaseData::getC2DocumentBundle, "clientCode", Permission.CRU, UserRole.CHILDSOLICITORK);
        builder.grantComplexType(CaseData::getC2DocumentBundle, "clientCode", Permission.CRU, UserRole.CHILDSOLICITORL);
        builder.grantComplexType(CaseData::getC2DocumentBundle, "clientCode", Permission.CRU, UserRole.CHILDSOLICITORM);
        builder.grantComplexType(CaseData::getC2DocumentBundle, "clientCode", Permission.CRU, UserRole.CHILDSOLICITORN);
        builder.grantComplexType(CaseData::getC2DocumentBundle, "clientCode", Permission.CRU, UserRole.CHILDSOLICITORO);
        builder.grantComplexType(CaseData::getC2DocumentBundle, "clientCode", Permission.CRU, UserRole.LASOLICITOR);
        builder.grantComplexType(CaseData::getC2DocumentBundle, "clientCode", Permission.CRU, UserRole.LASHARED);
        builder.grantComplexType(CaseData::getC2DocumentBundle, "clientCode", Permission.CRU, UserRole.CAFCASSSOLICITOR);
        builder.grantComplexType(CaseData::getC2DocumentBundle, "clientCode", Permission.CRU, UserRole.CASEWORKER_PUBLICLAW_COURTADMIN);
        builder.grantComplexType(CaseData::getC2DocumentBundle, "clientCode", Permission.CRU, UserRole.CASEWORKER_PUBLICLAW_SYSTEMUPDATE);
        builder.grantComplexType(CaseData::getC2DocumentBundle, "clientCode", Permission.CRU, UserRole.CASEWORKER_PUBLICLAW_CAFCASS);
        builder.grantComplexType(CaseData::getC2DocumentBundle, "clientCode", Permission.CRU, UserRole.BARRISTER);
        builder.grantComplexType(CaseData::getC2DocumentBundle, "clientCode", Set.of(Permission.R), UserRole.CASEWORKER_PUBLICLAW_GATEKEEPER);
        builder.grantComplexType(CaseData::getC2DocumentBundle, "clientCode", Set.of(Permission.R), UserRole.CASEWORKER_PUBLICLAW_JUDICIARY);
        builder.grantComplexType(CaseData::getC2DocumentBundle, "clientCode", Set.of(Permission.R), UserRole.CASEWORKER_PUBLICLAW_MAGISTRATE);
        builder.grantComplexType(CaseData::getC2DocumentBundle, "fileReference", Permission.CRU, UserRole.LABARRISTER);
        builder.grantComplexType(CaseData::getC2DocumentBundle, "fileReference", Permission.CRU, UserRole.SOLICITOR);
        builder.grantComplexType(CaseData::getC2DocumentBundle, "fileReference", Permission.CRU, UserRole.SOLICITORA);
        builder.grantComplexType(CaseData::getC2DocumentBundle, "fileReference", Permission.CRU, UserRole.SOLICITORB);
        builder.grantComplexType(CaseData::getC2DocumentBundle, "fileReference", Permission.CRU, UserRole.SOLICITORC);
        builder.grantComplexType(CaseData::getC2DocumentBundle, "fileReference", Permission.CRU, UserRole.SOLICITORD);
        builder.grantComplexType(CaseData::getC2DocumentBundle, "fileReference", Permission.CRU, UserRole.SOLICITORE);
        builder.grantComplexType(CaseData::getC2DocumentBundle, "fileReference", Permission.CRU, UserRole.SOLICITORF);
        builder.grantComplexType(CaseData::getC2DocumentBundle, "fileReference", Permission.CRU, UserRole.SOLICITORG);
        builder.grantComplexType(CaseData::getC2DocumentBundle, "fileReference", Permission.CRU, UserRole.SOLICITORH);
        builder.grantComplexType(CaseData::getC2DocumentBundle, "fileReference", Permission.CRU, UserRole.SOLICITORI);
        builder.grantComplexType(CaseData::getC2DocumentBundle, "fileReference", Permission.CRU, UserRole.SOLICITORJ);
        builder.grantComplexType(CaseData::getC2DocumentBundle, "fileReference", Permission.CRU, UserRole.CHILDSOLICITORA);
        builder.grantComplexType(CaseData::getC2DocumentBundle, "fileReference", Permission.CRU, UserRole.CHILDSOLICITORB);
        builder.grantComplexType(CaseData::getC2DocumentBundle, "fileReference", Permission.CRU, UserRole.CHILDSOLICITORC);
        builder.grantComplexType(CaseData::getC2DocumentBundle, "fileReference", Permission.CRU, UserRole.CHILDSOLICITORD);
        builder.grantComplexType(CaseData::getC2DocumentBundle, "fileReference", Permission.CRU, UserRole.CHILDSOLICITORE);
        builder.grantComplexType(CaseData::getC2DocumentBundle, "fileReference", Permission.CRU, UserRole.CHILDSOLICITORF);
        builder.grantComplexType(CaseData::getC2DocumentBundle, "fileReference", Permission.CRU, UserRole.CHILDSOLICITORG);
        builder.grantComplexType(CaseData::getC2DocumentBundle, "fileReference", Permission.CRU, UserRole.CHILDSOLICITORH);
        builder.grantComplexType(CaseData::getC2DocumentBundle, "fileReference", Permission.CRU, UserRole.CHILDSOLICITORI);
        builder.grantComplexType(CaseData::getC2DocumentBundle, "fileReference", Permission.CRU, UserRole.CHILDSOLICITORJ);
        builder.grantComplexType(CaseData::getC2DocumentBundle, "fileReference", Permission.CRU, UserRole.CHILDSOLICITORK);
        builder.grantComplexType(CaseData::getC2DocumentBundle, "fileReference", Permission.CRU, UserRole.CHILDSOLICITORL);
        builder.grantComplexType(CaseData::getC2DocumentBundle, "fileReference", Permission.CRU, UserRole.CHILDSOLICITORM);
        builder.grantComplexType(CaseData::getC2DocumentBundle, "fileReference", Permission.CRU, UserRole.CHILDSOLICITORN);
        builder.grantComplexType(CaseData::getC2DocumentBundle, "fileReference", Permission.CRU, UserRole.CHILDSOLICITORO);
        builder.grantComplexType(CaseData::getC2DocumentBundle, "fileReference", Permission.CRU, UserRole.LASOLICITOR);
        builder.grantComplexType(CaseData::getC2DocumentBundle, "fileReference", Permission.CRU, UserRole.LASHARED);
        builder.grantComplexType(CaseData::getC2DocumentBundle, "fileReference", Permission.CRU, UserRole.CAFCASSSOLICITOR);
        builder.grantComplexType(CaseData::getC2DocumentBundle, "fileReference", Permission.CRU, UserRole.CASEWORKER_PUBLICLAW_COURTADMIN);
        builder.grantComplexType(CaseData::getC2DocumentBundle, "fileReference", Permission.CRU, UserRole.CASEWORKER_PUBLICLAW_SYSTEMUPDATE);
        builder.grantComplexType(CaseData::getC2DocumentBundle, "fileReference", Permission.CRU, UserRole.CASEWORKER_PUBLICLAW_CAFCASS);
        builder.grantComplexType(CaseData::getC2DocumentBundle, "fileReference", Permission.CRU, UserRole.BARRISTER);
        builder.grantComplexType(CaseData::getC2DocumentBundle, "fileReference", Set.of(Permission.R), UserRole.CASEWORKER_PUBLICLAW_GATEKEEPER);
        builder.grantComplexType(CaseData::getC2DocumentBundle, "fileReference", Set.of(Permission.R), UserRole.CASEWORKER_PUBLICLAW_JUDICIARY);
        builder.grantComplexType(CaseData::getC2DocumentBundle, "fileReference", Set.of(Permission.R), UserRole.CASEWORKER_PUBLICLAW_MAGISTRATE);
        builder.grantComplexType(CaseData::getC2DocumentBundle, "supportingEvidenceBundle", Permission.CRU, UserRole.CASEWORKER_PUBLICLAW_COURTADMIN);
        builder.grantComplexType(CaseData::getC2DocumentBundle, "supportingEvidenceBundle", Permission.CRU, UserRole.CASEWORKER_PUBLICLAW_SYSTEMUPDATE);
        builder.grantComplexType(CaseData::getC2DocumentBundle, "supportingEvidenceBundle", Set.of(Permission.C, Permission.U), UserRole.LASOLICITOR);
        builder.grantComplexType(CaseData::getC2DocumentBundle, "supportingEvidenceBundle", Set.of(Permission.C, Permission.U), UserRole.LASHARED);
        builder.grantComplexType(CaseData::getC2DocumentBundle, "supportingEvidenceBundle", Set.of(Permission.C, Permission.U), UserRole.LABARRISTER);
        builder.grantComplexType(CaseData::getC2DocumentBundle, "supportingEvidenceBundle", Set.of(Permission.C, Permission.U), UserRole.CAFCASSSOLICITOR);
        builder.grantComplexType(CaseData::getC2DocumentBundle, "supportingEvidenceBundle", Set.of(Permission.C, Permission.U), UserRole.SOLICITOR);
        builder.grantComplexType(CaseData::getC2DocumentBundle, "supportingEvidenceBundle", Set.of(Permission.C, Permission.U), UserRole.SOLICITORA);
        builder.grantComplexType(CaseData::getC2DocumentBundle, "supportingEvidenceBundle", Set.of(Permission.C, Permission.U), UserRole.SOLICITORB);
        builder.grantComplexType(CaseData::getC2DocumentBundle, "supportingEvidenceBundle", Set.of(Permission.C, Permission.U), UserRole.SOLICITORC);
        builder.grantComplexType(CaseData::getC2DocumentBundle, "supportingEvidenceBundle", Set.of(Permission.C, Permission.U), UserRole.SOLICITORD);
        builder.grantComplexType(CaseData::getC2DocumentBundle, "supportingEvidenceBundle", Set.of(Permission.C, Permission.U), UserRole.SOLICITORE);
        builder.grantComplexType(CaseData::getC2DocumentBundle, "supportingEvidenceBundle", Set.of(Permission.C, Permission.U), UserRole.SOLICITORF);
        builder.grantComplexType(CaseData::getC2DocumentBundle, "supportingEvidenceBundle", Set.of(Permission.C, Permission.U), UserRole.SOLICITORG);
        builder.grantComplexType(CaseData::getC2DocumentBundle, "supportingEvidenceBundle", Set.of(Permission.C, Permission.U), UserRole.SOLICITORH);
        builder.grantComplexType(CaseData::getC2DocumentBundle, "supportingEvidenceBundle", Set.of(Permission.C, Permission.U), UserRole.SOLICITORI);
        builder.grantComplexType(CaseData::getC2DocumentBundle, "supportingEvidenceBundle", Set.of(Permission.C, Permission.U), UserRole.SOLICITORJ);
        builder.grantComplexType(CaseData::getC2DocumentBundle, "supportingEvidenceBundle", Set.of(Permission.C, Permission.U), UserRole.CHILDSOLICITORA);
        builder.grantComplexType(CaseData::getC2DocumentBundle, "supportingEvidenceBundle", Set.of(Permission.C, Permission.U), UserRole.CHILDSOLICITORB);
        builder.grantComplexType(CaseData::getC2DocumentBundle, "supportingEvidenceBundle", Set.of(Permission.C, Permission.U), UserRole.CHILDSOLICITORC);
    }
}
