package uk.gov.hmcts.reform.fpl.ccd;

import java.util.Set;
import uk.gov.hmcts.ccd.sdk.api.ConfigBuilder;
import uk.gov.hmcts.ccd.sdk.api.Permission;
import uk.gov.hmcts.reform.fpl.enums.State;
import uk.gov.hmcts.reform.fpl.model.CaseData;
import uk.gov.hmcts.reform.fpl.model.UserRole;

/**
 * Generated by ccd-definition-converter from CARE_SUPERVISION_EPO on migration; owned by this service team.
 *
 * <p>AuthorisationComplexType grants for {@code CARE_SUPERVISION_EPO} (part 8).
 */
public final class CARESUPERVISIONEPOComplexTypeGrants08 {
    private CARESUPERVISIONEPOComplexTypeGrants08() {
    }

    /**
     * @param builder the config builder
     */
    static void apply(ConfigBuilder<CaseData, State, UserRole> builder) {
        builder.grantComplexType(CaseData::getAdditionalApplicationsBundle, "c2DocumentBundle.supportingEvidenceBundle", Permission.CRU, UserRole.SOLICITORI);
        builder.grantComplexType(CaseData::getAdditionalApplicationsBundle, "c2DocumentBundle.supportingEvidenceBundle", Permission.CRU, UserRole.SOLICITORJ);
        builder.grantComplexType(CaseData::getAdditionalApplicationsBundle, "c2DocumentBundle.supportingEvidenceBundle", Permission.CRU, UserRole.CHILDSOLICITORA);
        builder.grantComplexType(CaseData::getAdditionalApplicationsBundle, "c2DocumentBundle.supportingEvidenceBundle", Permission.CRU, UserRole.CHILDSOLICITORB);
        builder.grantComplexType(CaseData::getAdditionalApplicationsBundle, "c2DocumentBundle.supportingEvidenceBundle", Permission.CRU, UserRole.CHILDSOLICITORC);
        builder.grantComplexType(CaseData::getAdditionalApplicationsBundle, "c2DocumentBundle.supportingEvidenceBundle", Permission.CRU, UserRole.CHILDSOLICITORD);
        builder.grantComplexType(CaseData::getAdditionalApplicationsBundle, "c2DocumentBundle.supportingEvidenceBundle", Permission.CRU, UserRole.CHILDSOLICITORE);
        builder.grantComplexType(CaseData::getAdditionalApplicationsBundle, "c2DocumentBundle.supportingEvidenceBundle", Permission.CRU, UserRole.CHILDSOLICITORF);
        builder.grantComplexType(CaseData::getAdditionalApplicationsBundle, "c2DocumentBundle.supportingEvidenceBundle", Permission.CRU, UserRole.CHILDSOLICITORG);
        builder.grantComplexType(CaseData::getAdditionalApplicationsBundle, "c2DocumentBundle.supportingEvidenceBundle", Permission.CRU, UserRole.CHILDSOLICITORH);
        builder.grantComplexType(CaseData::getAdditionalApplicationsBundle, "c2DocumentBundle.supportingEvidenceBundle", Permission.CRU, UserRole.CHILDSOLICITORI);
        builder.grantComplexType(CaseData::getAdditionalApplicationsBundle, "c2DocumentBundle.supportingEvidenceBundle", Permission.CRU, UserRole.CHILDSOLICITORJ);
        builder.grantComplexType(CaseData::getAdditionalApplicationsBundle, "c2DocumentBundle.supportingEvidenceBundle", Permission.CRU, UserRole.CHILDSOLICITORK);
        builder.grantComplexType(CaseData::getAdditionalApplicationsBundle, "c2DocumentBundle.supportingEvidenceBundle", Permission.CRU, UserRole.CHILDSOLICITORL);
        builder.grantComplexType(CaseData::getAdditionalApplicationsBundle, "c2DocumentBundle.supportingEvidenceBundle", Permission.CRU, UserRole.CHILDSOLICITORM);
        builder.grantComplexType(CaseData::getAdditionalApplicationsBundle, "c2DocumentBundle.supportingEvidenceBundle", Permission.CRU, UserRole.CHILDSOLICITORN);
        builder.grantComplexType(CaseData::getAdditionalApplicationsBundle, "c2DocumentBundle.supportingEvidenceBundle", Permission.CRU, UserRole.CHILDSOLICITORO);
        builder.grantComplexType(CaseData::getAdditionalApplicationsBundle, "c2DocumentBundle.supportingEvidenceBundle", Permission.CRU, UserRole.BARRISTER);
        builder.grantComplexType(CaseData::getAdditionalApplicationsBundle, "c2DocumentBundle.supportingEvidenceBundle", Set.of(Permission.R), UserRole.CASEWORKER_PUBLICLAW_GATEKEEPER);
        builder.grantComplexType(CaseData::getAdditionalApplicationsBundle, "c2DocumentBundle.supportingEvidenceBundle", Set.of(Permission.R), UserRole.CASEWORKER_PUBLICLAW_JUDICIARY);
        builder.grantComplexType(CaseData::getAdditionalApplicationsBundle, "c2DocumentBundle.supportingEvidenceBundle", Set.of(Permission.R), UserRole.CASEWORKER_PUBLICLAW_MAGISTRATE);
        builder.grantComplexType(CaseData::getAdditionalApplicationsBundle, "c2DocumentBundle.supportingEvidenceBundle", Set.of(Permission.R), UserRole.CASEWORKER_PUBLICLAW_CAFCASSSYSTEMUPDATE);
        builder.grantComplexType(CaseData::getAdditionalApplicationsBundle, "c2DocumentBundle.supportingEvidenceBundle", Set.of(Permission.R, Permission.U), UserRole.CASEWORKER_PUBLICLAW_CAFCASS);
        builder.grantComplexType(CaseData::getAdditionalApplicationsBundle, "pbaPayment.usePbaPayment", Permission.CRU, UserRole.LABARRISTER);
        builder.grantComplexType(CaseData::getAdditionalApplicationsBundle, "pbaPayment.usePbaPayment", Permission.CRU, UserRole.SOLICITOR);
        builder.grantComplexType(CaseData::getAdditionalApplicationsBundle, "pbaPayment.usePbaPayment", Permission.CRU, UserRole.LASOLICITOR);
        builder.grantComplexType(CaseData::getAdditionalApplicationsBundle, "pbaPayment.usePbaPayment", Permission.CRU, UserRole.LASHARED);
        builder.grantComplexType(CaseData::getAdditionalApplicationsBundle, "pbaPayment.usePbaPayment", Permission.CRU, UserRole.LAMANAGING);
        builder.grantComplexType(CaseData::getAdditionalApplicationsBundle, "pbaPayment.usePbaPayment", Permission.CRU, UserRole.EPSMANAGING);
        builder.grantComplexType(CaseData::getAdditionalApplicationsBundle, "pbaPayment.usePbaPayment", Permission.CRU, UserRole.CAFCASSSOLICITOR);
        builder.grantComplexType(CaseData::getAdditionalApplicationsBundle, "pbaPayment.usePbaPayment", Permission.CRU, UserRole.CASEWORKER_PUBLICLAW_COURTADMIN);
        builder.grantComplexType(CaseData::getAdditionalApplicationsBundle, "pbaPayment.usePbaPayment", Permission.CRU, UserRole.CASEWORKER_PUBLICLAW_SYSTEMUPDATE);
        builder.grantComplexType(CaseData::getAdditionalApplicationsBundle, "pbaPayment.usePbaPayment", Permission.CRU, UserRole.CASEWORKER_PUBLICLAW_CAFCASS);
        builder.grantComplexType(CaseData::getAdditionalApplicationsBundle, "pbaPayment.usePbaPayment", Permission.CRU, UserRole.BARRISTER);
        builder.grantComplexType(CaseData::getAdditionalApplicationsBundle, "pbaPayment.usePbaPayment", Set.of(Permission.R), UserRole.CASEWORKER_PUBLICLAW_GATEKEEPER);
        builder.grantComplexType(CaseData::getAdditionalApplicationsBundle, "pbaPayment.usePbaPayment", Set.of(Permission.R), UserRole.CASEWORKER_PUBLICLAW_JUDICIARY);
        builder.grantComplexType(CaseData::getAdditionalApplicationsBundle, "pbaPayment.usePbaPayment", Set.of(Permission.R), UserRole.CASEWORKER_PUBLICLAW_MAGISTRATE);
        builder.grantComplexType(CaseData::getAdditionalApplicationsBundle, "pbaPayment.pbaNumber", Permission.CRU, UserRole.LABARRISTER);
        builder.grantComplexType(CaseData::getAdditionalApplicationsBundle, "pbaPayment.pbaNumber", Permission.CRU, UserRole.SOLICITOR);
        builder.grantComplexType(CaseData::getAdditionalApplicationsBundle, "pbaPayment.pbaNumber", Permission.CRU, UserRole.LASOLICITOR);
        builder.grantComplexType(CaseData::getAdditionalApplicationsBundle, "pbaPayment.pbaNumber", Permission.CRU, UserRole.LASHARED);
        builder.grantComplexType(CaseData::getAdditionalApplicationsBundle, "pbaPayment.pbaNumber", Permission.CRU, UserRole.LAMANAGING);
        builder.grantComplexType(CaseData::getAdditionalApplicationsBundle, "pbaPayment.pbaNumber", Permission.CRU, UserRole.EPSMANAGING);
        builder.grantComplexType(CaseData::getAdditionalApplicationsBundle, "pbaPayment.pbaNumber", Permission.CRU, UserRole.CAFCASSSOLICITOR);
        builder.grantComplexType(CaseData::getAdditionalApplicationsBundle, "pbaPayment.pbaNumber", Permission.CRU, UserRole.BARRISTER);
        builder.grantComplexType(CaseData::getAdditionalApplicationsBundle, "pbaPayment.pbaNumber", Permission.CRU, UserRole.CASEWORKER_PUBLICLAW_COURTADMIN);
        builder.grantComplexType(CaseData::getAdditionalApplicationsBundle, "pbaPayment.pbaNumber", Permission.CRU, UserRole.CASEWORKER_PUBLICLAW_SYSTEMUPDATE);
        builder.grantComplexType(CaseData::getAdditionalApplicationsBundle, "pbaPayment.pbaNumber", Permission.CRU, UserRole.CASEWORKER_PUBLICLAW_CAFCASS);
        builder.grantComplexType(CaseData::getAdditionalApplicationsBundle, "pbaPayment.pbaNumber", Set.of(Permission.R), UserRole.CASEWORKER_PUBLICLAW_GATEKEEPER);
        builder.grantComplexType(CaseData::getAdditionalApplicationsBundle, "pbaPayment.pbaNumber", Set.of(Permission.R), UserRole.CASEWORKER_PUBLICLAW_JUDICIARY);
        builder.grantComplexType(CaseData::getAdditionalApplicationsBundle, "pbaPayment.pbaNumber", Set.of(Permission.R), UserRole.CASEWORKER_PUBLICLAW_MAGISTRATE);
        builder.grantComplexType(CaseData::getAdditionalApplicationsBundle, "pbaPayment.clientCode", Permission.CRU, UserRole.LABARRISTER);
        builder.grantComplexType(CaseData::getAdditionalApplicationsBundle, "pbaPayment.clientCode", Permission.CRU, UserRole.SOLICITOR);
        builder.grantComplexType(CaseData::getAdditionalApplicationsBundle, "pbaPayment.clientCode", Permission.CRU, UserRole.LASOLICITOR);
        builder.grantComplexType(CaseData::getAdditionalApplicationsBundle, "pbaPayment.clientCode", Permission.CRU, UserRole.LASHARED);
        builder.grantComplexType(CaseData::getAdditionalApplicationsBundle, "pbaPayment.clientCode", Permission.CRU, UserRole.LAMANAGING);
        builder.grantComplexType(CaseData::getAdditionalApplicationsBundle, "pbaPayment.clientCode", Permission.CRU, UserRole.EPSMANAGING);
        builder.grantComplexType(CaseData::getAdditionalApplicationsBundle, "pbaPayment.clientCode", Permission.CRU, UserRole.CAFCASSSOLICITOR);
        builder.grantComplexType(CaseData::getAdditionalApplicationsBundle, "pbaPayment.clientCode", Permission.CRU, UserRole.CASEWORKER_PUBLICLAW_COURTADMIN);
        builder.grantComplexType(CaseData::getAdditionalApplicationsBundle, "pbaPayment.clientCode", Permission.CRU, UserRole.CASEWORKER_PUBLICLAW_SYSTEMUPDATE);
        builder.grantComplexType(CaseData::getAdditionalApplicationsBundle, "pbaPayment.clientCode", Permission.CRU, UserRole.CASEWORKER_PUBLICLAW_CAFCASS);
        builder.grantComplexType(CaseData::getAdditionalApplicationsBundle, "pbaPayment.clientCode", Permission.CRU, UserRole.BARRISTER);
        builder.grantComplexType(CaseData::getAdditionalApplicationsBundle, "pbaPayment.clientCode", Set.of(Permission.R), UserRole.CASEWORKER_PUBLICLAW_GATEKEEPER);
        builder.grantComplexType(CaseData::getAdditionalApplicationsBundle, "pbaPayment.clientCode", Set.of(Permission.R), UserRole.CASEWORKER_PUBLICLAW_JUDICIARY);
        builder.grantComplexType(CaseData::getAdditionalApplicationsBundle, "pbaPayment.clientCode", Set.of(Permission.R), UserRole.CASEWORKER_PUBLICLAW_MAGISTRATE);
        builder.grantComplexType(CaseData::getAdditionalApplicationsBundle, "pbaPayment.fileReference", Permission.CRU, UserRole.LABARRISTER);
        builder.grantComplexType(CaseData::getAdditionalApplicationsBundle, "pbaPayment.fileReference", Permission.CRU, UserRole.SOLICITOR);
        builder.grantComplexType(CaseData::getAdditionalApplicationsBundle, "pbaPayment.fileReference", Permission.CRU, UserRole.LASOLICITOR);
        builder.grantComplexType(CaseData::getAdditionalApplicationsBundle, "pbaPayment.fileReference", Permission.CRU, UserRole.LASHARED);
        builder.grantComplexType(CaseData::getAdditionalApplicationsBundle, "pbaPayment.fileReference", Permission.CRU, UserRole.LAMANAGING);
        builder.grantComplexType(CaseData::getAdditionalApplicationsBundle, "pbaPayment.fileReference", Permission.CRU, UserRole.EPSMANAGING);
        builder.grantComplexType(CaseData::getAdditionalApplicationsBundle, "pbaPayment.fileReference", Permission.CRU, UserRole.CAFCASSSOLICITOR);
        builder.grantComplexType(CaseData::getAdditionalApplicationsBundle, "pbaPayment.fileReference", Permission.CRU, UserRole.CASEWORKER_PUBLICLAW_COURTADMIN);
        builder.grantComplexType(CaseData::getAdditionalApplicationsBundle, "pbaPayment.fileReference", Permission.CRU, UserRole.CASEWORKER_PUBLICLAW_SYSTEMUPDATE);
        builder.grantComplexType(CaseData::getAdditionalApplicationsBundle, "pbaPayment.fileReference", Permission.CRU, UserRole.CASEWORKER_PUBLICLAW_CAFCASS);
        builder.grantComplexType(CaseData::getAdditionalApplicationsBundle, "pbaPayment.fileReference", Permission.CRU, UserRole.BARRISTER);
        builder.grantComplexType(CaseData::getAdditionalApplicationsBundle, "pbaPayment.fileReference", Set.of(Permission.R), UserRole.CASEWORKER_PUBLICLAW_GATEKEEPER);
        builder.grantComplexType(CaseData::getAdditionalApplicationsBundle, "pbaPayment.fileReference", Set.of(Permission.R), UserRole.CASEWORKER_PUBLICLAW_JUDICIARY);
        builder.grantComplexType(CaseData::getAdditionalApplicationsBundle, "pbaPayment.fileReference", Set.of(Permission.R), UserRole.CASEWORKER_PUBLICLAW_MAGISTRATE);
        builder.grantComplexType(CaseData::getAdditionalApplicationsBundle, "otherApplicationsBundle.applicantName", Permission.CRU, UserRole.LABARRISTER);
        builder.grantComplexType(CaseData::getAdditionalApplicationsBundle, "otherApplicationsBundle.applicantName", Permission.CRU, UserRole.SOLICITOR);
        builder.grantComplexType(CaseData::getAdditionalApplicationsBundle, "otherApplicationsBundle.applicantName", Permission.CRU, UserRole.SOLICITORA);
        builder.grantComplexType(CaseData::getAdditionalApplicationsBundle, "otherApplicationsBundle.applicantName", Permission.CRU, UserRole.SOLICITORB);
        builder.grantComplexType(CaseData::getAdditionalApplicationsBundle, "otherApplicationsBundle.applicantName", Permission.CRU, UserRole.SOLICITORC);
        builder.grantComplexType(CaseData::getAdditionalApplicationsBundle, "otherApplicationsBundle.applicantName", Permission.CRU, UserRole.SOLICITORD);
        builder.grantComplexType(CaseData::getAdditionalApplicationsBundle, "otherApplicationsBundle.applicantName", Permission.CRU, UserRole.SOLICITORE);
        builder.grantComplexType(CaseData::getAdditionalApplicationsBundle, "otherApplicationsBundle.applicantName", Permission.CRU, UserRole.SOLICITORF);
        builder.grantComplexType(CaseData::getAdditionalApplicationsBundle, "otherApplicationsBundle.applicantName", Permission.CRU, UserRole.SOLICITORG);
        builder.grantComplexType(CaseData::getAdditionalApplicationsBundle, "otherApplicationsBundle.applicantName", Permission.CRU, UserRole.SOLICITORH);
        builder.grantComplexType(CaseData::getAdditionalApplicationsBundle, "otherApplicationsBundle.applicantName", Permission.CRU, UserRole.SOLICITORI);
        builder.grantComplexType(CaseData::getAdditionalApplicationsBundle, "otherApplicationsBundle.applicantName", Permission.CRU, UserRole.SOLICITORJ);
        builder.grantComplexType(CaseData::getAdditionalApplicationsBundle, "otherApplicationsBundle.applicantName", Permission.CRU, UserRole.CHILDSOLICITORA);
        builder.grantComplexType(CaseData::getAdditionalApplicationsBundle, "otherApplicationsBundle.applicantName", Permission.CRU, UserRole.CHILDSOLICITORB);
        builder.grantComplexType(CaseData::getAdditionalApplicationsBundle, "otherApplicationsBundle.applicantName", Permission.CRU, UserRole.CHILDSOLICITORC);
        builder.grantComplexType(CaseData::getAdditionalApplicationsBundle, "otherApplicationsBundle.applicantName", Permission.CRU, UserRole.CHILDSOLICITORD);
        builder.grantComplexType(CaseData::getAdditionalApplicationsBundle, "otherApplicationsBundle.applicantName", Permission.CRU, UserRole.CHILDSOLICITORE);
        builder.grantComplexType(CaseData::getAdditionalApplicationsBundle, "otherApplicationsBundle.applicantName", Permission.CRU, UserRole.CHILDSOLICITORF);
        builder.grantComplexType(CaseData::getAdditionalApplicationsBundle, "otherApplicationsBundle.applicantName", Permission.CRU, UserRole.CHILDSOLICITORG);
        builder.grantComplexType(CaseData::getAdditionalApplicationsBundle, "otherApplicationsBundle.applicantName", Permission.CRU, UserRole.CHILDSOLICITORH);
        builder.grantComplexType(CaseData::getAdditionalApplicationsBundle, "otherApplicationsBundle.applicantName", Permission.CRU, UserRole.CHILDSOLICITORI);
        builder.grantComplexType(CaseData::getAdditionalApplicationsBundle, "otherApplicationsBundle.applicantName", Permission.CRU, UserRole.CHILDSOLICITORJ);
        builder.grantComplexType(CaseData::getAdditionalApplicationsBundle, "otherApplicationsBundle.applicantName", Permission.CRU, UserRole.CHILDSOLICITORK);
        builder.grantComplexType(CaseData::getAdditionalApplicationsBundle, "otherApplicationsBundle.applicantName", Permission.CRU, UserRole.CHILDSOLICITORL);
        builder.grantComplexType(CaseData::getAdditionalApplicationsBundle, "otherApplicationsBundle.applicantName", Permission.CRU, UserRole.CHILDSOLICITORM);
        builder.grantComplexType(CaseData::getAdditionalApplicationsBundle, "otherApplicationsBundle.applicantName", Permission.CRU, UserRole.CHILDSOLICITORN);
        builder.grantComplexType(CaseData::getAdditionalApplicationsBundle, "otherApplicationsBundle.applicantName", Permission.CRU, UserRole.CHILDSOLICITORO);
        builder.grantComplexType(CaseData::getAdditionalApplicationsBundle, "otherApplicationsBundle.applicantName", Permission.CRU, UserRole.LASOLICITOR);
        builder.grantComplexType(CaseData::getAdditionalApplicationsBundle, "otherApplicationsBundle.applicantName", Permission.CRU, UserRole.LASHARED);
        builder.grantComplexType(CaseData::getAdditionalApplicationsBundle, "otherApplicationsBundle.applicantName", Permission.CRU, UserRole.LAMANAGING);
        builder.grantComplexType(CaseData::getAdditionalApplicationsBundle, "otherApplicationsBundle.applicantName", Permission.CRU, UserRole.EPSMANAGING);
        builder.grantComplexType(CaseData::getAdditionalApplicationsBundle, "otherApplicationsBundle.applicantName", Permission.CRU, UserRole.CAFCASSSOLICITOR);
        builder.grantComplexType(CaseData::getAdditionalApplicationsBundle, "otherApplicationsBundle.applicantName", Permission.CRU, UserRole.BARRISTER);
        builder.grantComplexType(CaseData::getAdditionalApplicationsBundle, "otherApplicationsBundle.applicantName", Permission.CRU, UserRole.CASEWORKER_PUBLICLAW_COURTADMIN);
        builder.grantComplexType(CaseData::getAdditionalApplicationsBundle, "otherApplicationsBundle.applicantName", Permission.CRU, UserRole.CASEWORKER_PUBLICLAW_SYSTEMUPDATE);
        builder.grantComplexType(CaseData::getAdditionalApplicationsBundle, "otherApplicationsBundle.applicantName", Permission.CRU, UserRole.CASEWORKER_PUBLICLAW_CAFCASS);
        builder.grantComplexType(CaseData::getAdditionalApplicationsBundle, "otherApplicationsBundle.applicantName", Set.of(Permission.R), UserRole.CASEWORKER_PUBLICLAW_GATEKEEPER);
        builder.grantComplexType(CaseData::getAdditionalApplicationsBundle, "otherApplicationsBundle.applicantName", Set.of(Permission.R), UserRole.CASEWORKER_PUBLICLAW_JUDICIARY);
        builder.grantComplexType(CaseData::getAdditionalApplicationsBundle, "otherApplicationsBundle.applicantName", Set.of(Permission.R), UserRole.CASEWORKER_PUBLICLAW_MAGISTRATE);
        builder.grantComplexType(CaseData::getAdditionalApplicationsBundle, "otherApplicationsBundle.urgencyTimeFrameType", Permission.CRU, UserRole.LABARRISTER);
        builder.grantComplexType(CaseData::getAdditionalApplicationsBundle, "otherApplicationsBundle.urgencyTimeFrameType", Permission.CRU, UserRole.SOLICITOR);
    }
}
